using System.Net;
using System.Security.Claims;
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.Data.Sqlite;

namespace CltPlusPlus.Employee;

public static class AnimalCareShelter
{
    public static void Map(WebApplication app)
    {
        var dbPath = app.Configuration["CLTPP_GENERAL_CITY_DB"] ?? Path.Combine(AppContext.BaseDirectory, "data", "city-services.db");
        Directory.CreateDirectory(Path.GetDirectoryName(dbPath)!);
        Ensure(dbPath);

        app.MapGet("/animal-care", async (HttpContext ctx, IAntiforgery anti) =>
        {
            if (!CanAnimalCare(ctx.User)) return Results.Forbid();
            var token = anti.GetAndStoreTokens(ctx).RequestToken!;
            await using var cn = Open(dbPath); await cn.OpenAsync();
            var animalCount = await Scalar(cn, "SELECT COUNT(1) FROM ShelterAnimals WHERE CustodyStatus NOT IN ('Adopted','Released','Transferred','Deceased')");
            var availableCount = await Scalar(cn, "SELECT COUNT(1) FROM ShelterAnimals WHERE PublishToPublic=1 AND AdoptionStatus='Available'");
            var pendingApps = await Scalar(cn, "SELECT COUNT(1) FROM AdoptionRequests WHERE Status IN ('Submitted','In review')");
            var spaces = await Scalar(cn, "SELECT COUNT(1) FROM ShelterSpaces WHERE Active=1");
            return Html(Page("Animal Care & Control", $"""
            <main class='wrap'><section class='page-head'><div><span class='eyebrow'>ANIMAL CARE & CONTROL</span><h1>Shelter operations</h1><p>Manage shelter space, animals in custody, public adoption listings, and citizen adoption requests.</p></div><a class='button' href='/'>Employee home</a></section>
            <div class='detail-grid'><section><div class='card'><h2>Current shelter</h2><dl><dt>Animals in custody</dt><dd>{animalCount}</dd><dt>Published / adoptable</dt><dd>{availableCount}</dd><dt>Pending adoption requests</dt><dd>{pendingApps}</dd><dt>Active spaces</dt><dd>{spaces}</dd></dl></div></section><aside><section class='card'><h2>Actions</h2><a class='button' href='/animal-care/spaces'>Manage shelter spaces</a><a class='button' href='/animal-care/animals'>Animals in custody</a><a class='button' href='/animal-care/adoptions'>Adoption requests</a><a class='button' href='/animal-care/animals/new'>Add animal</a></section></aside></div></main>"""));
        }).RequireAuthorization();

        app.MapGet("/animal-care/spaces", async (HttpContext ctx, IAntiforgery anti) =>
        {
            if (!CanAnimalCare(ctx.User)) return Results.Forbid(); var t=anti.GetAndStoreTokens(ctx).RequestToken!;
            await using var cn=Open(dbPath); await cn.OpenAsync(); var c=cn.CreateCommand(); c.CommandText="SELECT Id,Name,SpaceType,Capacity,Active,COALESCE(Notes,'') FROM ShelterSpaces ORDER BY Name";
            var rows=new List<string>(); await using var r=await c.ExecuteReaderAsync(); while(await r.ReadAsync()) rows.Add($"<tr><td>{H(r.GetString(1))}</td><td>{H(r.GetString(2))}</td><td>{r.GetInt32(3)}</td><td>{(r.GetInt32(4)==1?"Active":"Inactive")}</td><td>{H(r.GetString(5))}</td></tr>");
            return Html(Page("Shelter spaces",$"<main class='wrap'><a href='/animal-care'>← Animal Care</a><section class='page-head'><div><h1>Shelter spaces</h1><p>Configure kennels, rooms, wards, cages, runs, and other capacity areas.</p></div></section><section class='card'><form method='post' action='/animal-care/spaces'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><label>Name<input name='name' required/></label><label>Type<input name='type' required placeholder='Kennel, cat room, isolation, medical, quarantine'/></label><label>Capacity<input type='number' min='1' name='capacity' value='1' required/></label><label>Notes<textarea name='notes'></textarea></label><button>Add space</button></form></section><section class='table-card'><table><thead><tr><th>Name</th><th>Type</th><th>Capacity</th><th>Status</th><th>Notes</th></tr></thead><tbody>{string.Join("",rows)}</tbody></table></section></main>"));
        }).RequireAuthorization();

        app.MapPost("/animal-care/spaces", async (HttpContext ctx, IAntiforgery anti) =>
        { if(!CanAnimalCare(ctx.User))return Results.Forbid(); await anti.ValidateRequestAsync(ctx); var f=await ctx.Request.ReadFormAsync(); var cap=int.TryParse(f["capacity"],out var n)?Math.Max(1,n):1; await Exec(dbPath,"INSERT INTO ShelterSpaces(Id,Name,SpaceType,Capacity,Active,Notes,CreatedAt,CreatedBy) VALUES($i,$n,$t,$c,1,$o,$d,$b)",("$i",Guid.NewGuid()),("$n",f["name"]),("$t",f["type"]),("$c",cap),("$o",f["notes"]),("$d",Now()),("$b",ctx.User.Identity?.Name)); return Results.Redirect("/animal-care/spaces"); }).RequireAuthorization();

        app.MapGet("/animal-care/animals", async (HttpContext ctx) =>
        {
            if(!CanAnimalCare(ctx.User))return Results.Forbid(); await using var cn=Open(dbPath);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Id,AnimalNumber,Name,Species,Breed,CustodyStatus,AdoptionStatus,PublishToPublic,COALESCE(SpaceId,'') FROM ShelterAnimals ORDER BY IntakeAt DESC";var rows=new List<string>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<tr><td><a href='/animal-care/animals/{r.GetString(0)}'><b>{H(r.GetString(1))}</b></a></td><td>{H(r.GetString(2))}</td><td>{H(r.GetString(3))}</td><td>{H(r.GetString(4))}</td><td>{H(r.GetString(5))}</td><td>{H(r.GetString(6))}</td><td>{(r.GetInt32(7)==1?"Yes":"No")}</td></tr>");return Html(Page("Animals",$"<main class='wrap'><section class='page-head'><div><h1>Animals in custody</h1></div><a class='button' href='/animal-care/animals/new'>Add animal</a></section><section class='table-card'><table><thead><tr><th>Animal</th><th>Name</th><th>Species</th><th>Breed</th><th>Custody</th><th>Adoption</th><th>Published</th></tr></thead><tbody>{string.Join("",rows)}</tbody></table></section></main>"));
        }).RequireAuthorization();

        app.MapGet("/animal-care/animals/new", async (HttpContext ctx, IAntiforgery anti) =>
        { if(!CanAnimalCare(ctx.User))return Results.Forbid(); var t=anti.GetAndStoreTokens(ctx).RequestToken!; var opts=await SpaceOptions(dbPath,null); return Html(Page("Add animal",$"""<main class='wrap'><a href='/animal-care/animals'>← Animals</a><section class='card'><h1>Add animal to custody</h1><form method='post' action='/animal-care/animals'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><label>Name<input name='name'/></label><label>Species<input name='species' required/></label><label>Breed<input name='breed'/></label><label>Sex<input name='sex'/></label><label>Approximate age<input name='age'/></label><label>Color / markings<input name='color'/></label><label>Microchip<input name='microchip'/></label><label>Custody status<select name='custody'><option>In custody</option><option>Stray hold</option><option>Medical hold</option><option>Owner surrender</option><option>Protective custody</option></select></label><label>Shelter space<select name='spaceId'><option value=''>Unassigned</option>{opts}</select></label><label>Public description<textarea name='publicDescription'></textarea></label><label>Internal notes<textarea name='notes'></textarea></label><button>Add animal</button></form></section></main>""")); }).RequireAuthorization();

        app.MapPost("/animal-care/animals", async (HttpContext ctx, IAntiforgery anti) =>
        { if(!CanAnimalCare(ctx.User))return Results.Forbid(); await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();var id=Guid.NewGuid();var num=$"AC-{DateTime.UtcNow:yyMMdd}-{Random.Shared.Next(10000,99999)}";await Exec(dbPath,"INSERT INTO ShelterAnimals(Id,AnimalNumber,Name,Species,Breed,Sex,ApproxAge,ColorMarkings,Microchip,CustodyStatus,AdoptionStatus,PublishToPublic,SpaceId,PublicDescription,InternalNotes,IntakeAt,CreatedBy,UpdatedAt) VALUES($i,$n,$nm,$s,$b,$sx,$a,$c,$m,$cs,'Not available',0,NULLIF($sp,''),$pd,$no,$d,$by,$d)",("$i",id),("$n",num),("$nm",f["name"]),("$s",f["species"]),("$b",f["breed"]),("$sx",f["sex"]),("$a",f["age"]),("$c",f["color"]),("$m",f["microchip"]),("$cs",f["custody"]),("$sp",f["spaceId"]),("$pd",f["publicDescription"]),("$no",f["notes"]),("$d",Now()),("$by",ctx.User.Identity?.Name));return Results.Redirect($"/animal-care/animals/{id}"); }).RequireAuthorization();

        app.MapGet("/animal-care/animals/{id:guid}", async (Guid id,HttpContext ctx,IAntiforgery anti) =>
        { if(!CanAnimalCare(ctx.User))return Results.Forbid();var a=await LoadAnimal(dbPath,id);if(a is null)return Results.NotFound();var t=anti.GetAndStoreTokens(ctx).RequestToken!;var opts=await SpaceOptions(dbPath,a.Value.SpaceId);return Html(Page(a.Value.Number,$"""<main class='wrap'><a href='/animal-care/animals'>← Animals</a><section class='page-head'><div><span class='eyebrow'>{H(a.Value.Number)}</span><h1>{H(a.Value.Name)}</h1><p>{H(a.Value.Species)} · {H(a.Value.Breed)}</p></div></section><section class='card'><form method='post' action='/animal-care/animals/{id}'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><label>Custody status<input name='custody' value='{H(a.Value.Custody)}'/></label><label>Adoption status<select name='adoption'><option>{H(a.Value.Adoption)}</option><option>Not available</option><option>Available</option><option>Application pending</option><option>Adopted</option></select></label><label>Shelter space<select name='spaceId'><option value=''>Unassigned</option>{opts}</select></label><label>Publish on citizen site<select name='publish'><option value='false'>No</option><option value='true' {(a.Value.Publish?"selected":"")}>Yes</option></select></label><label>Public description<textarea name='publicDescription'>{H(a.Value.PublicDescription)}</textarea></label><label>Internal notes<textarea name='notes'>{H(a.Value.InternalNotes)}</textarea></label><button>Save animal</button></form></section></main>""")); }).RequireAuthorization();

        app.MapPost("/animal-care/animals/{id:guid}", async(Guid id,HttpContext ctx,IAntiforgery anti)=>{if(!CanAnimalCare(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();await Exec(dbPath,"UPDATE ShelterAnimals SET CustodyStatus=$c,AdoptionStatus=$a,SpaceId=NULLIF($s,''),PublishToPublic=$p,PublicDescription=$d,InternalNotes=$n,UpdatedAt=$u WHERE Id=$i",("$c",f["custody"]),("$a",f["adoption"]),("$s",f["spaceId"]),("$p",f["publish"].ToString()=="true"?1:0),("$d",f["publicDescription"]),("$n",f["notes"]),("$u",Now()),("$i",id));return Results.Redirect($"/animal-care/animals/{id}");}).RequireAuthorization();

        app.MapGet("/animal-care/adoptions", async(HttpContext ctx,IAntiforgery anti)=>{if(!CanAnimalCare(ctx.User))return Results.Forbid();var t=anti.GetAndStoreTokens(ctx).RequestToken!;await using var cn=Open(dbPath);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT r.Id,r.RequestNumber,a.AnimalNumber,a.Name,r.ApplicantName,r.Email,r.Phone,r.Status,r.SubmittedAt FROM AdoptionRequests r JOIN ShelterAnimals a ON a.Id=r.AnimalId ORDER BY r.SubmittedAt DESC";var rows=new List<string>();await using var rd=await c.ExecuteReaderAsync();while(await rd.ReadAsync())rows.Add($"<tr><td>{H(rd.GetString(1))}</td><td>{H(rd.GetString(2))} · {H(rd.GetString(3))}</td><td>{H(rd.GetString(4))}<small>{H(rd.GetString(5))} · {H(rd.GetString(6))}</small></td><td>{H(rd.GetString(7))}</td><td><form method='post' action='/animal-care/adoptions/{rd.GetString(0)}/status'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><select name='status'><option>In review</option><option>Approved</option><option>Denied</option><option>Withdrawn</option><option>Completed</option></select><button>Update</button></form></td></tr>");return Html(Page("Adoption requests",$"<main class='wrap'><section class='page-head'><div><h1>Citizen adoption requests</h1></div></section><section class='table-card'><table><thead><tr><th>Request</th><th>Animal</th><th>Applicant</th><th>Status</th><th>Action</th></tr></thead><tbody>{string.Join("",rows)}</tbody></table></section></main>"));}).RequireAuthorization();

        app.MapPost("/animal-care/adoptions/{id:guid}/status",async(Guid id,HttpContext ctx,IAntiforgery anti)=>{if(!CanAnimalCare(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();var s=f["status"].ToString();await Exec(dbPath,"UPDATE AdoptionRequests SET Status=$s,UpdatedAt=$u,UpdatedBy=$b WHERE Id=$i",("$s",s),("$u",Now()),("$b",ctx.User.Identity?.Name),("$i",id));return Results.Redirect("/animal-care/adoptions");}).RequireAuthorization();

        app.MapGet("/api/adoptable-animals", async()=>{await using var cn=Open(dbPath);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Id,AnimalNumber,Name,Species,Breed,Sex,ApproxAge,ColorMarkings,PublicDescription FROM ShelterAnimals WHERE PublishToPublic=1 AND AdoptionStatus='Available' ORDER BY UpdatedAt DESC";var list=new List<object>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync())list.Add(new{id=r.GetString(0),animalNumber=r.GetString(1),name=N(r,2),species=r.GetString(3),breed=N(r,4),sex=N(r,5),age=N(r,6),color=N(r,7),description=N(r,8)});return Results.Ok(list);});

        app.MapPost("/api/adoptable-animals/{animalId:guid}/requests", async(Guid animalId, AdoptionInput input)=>{await using var cn=Open(dbPath);await cn.OpenAsync();var check=cn.CreateCommand();check.CommandText="SELECT COUNT(1) FROM ShelterAnimals WHERE Id=$i AND PublishToPublic=1 AND AdoptionStatus='Available'";check.Parameters.AddWithValue("$i",animalId.ToString());if(Convert.ToInt32(await check.ExecuteScalarAsync())!=1)return Results.BadRequest(new{error="Animal is not currently available for adoption."});var id=Guid.NewGuid();var num=$"ADOPT-{DateTime.UtcNow:yyMMdd}-{Random.Shared.Next(10000,99999)}";await Exec(dbPath,"INSERT INTO AdoptionRequests(Id,RequestNumber,AnimalId,ApplicantName,Email,Phone,Address,HouseholdNotes,PetExperience,Status,SubmittedAt,UpdatedAt) VALUES($i,$n,$a,$nm,$e,$p,$ad,$h,$x,'Submitted',$d,$d)",("$i",id),("$n",num),("$a",animalId),("$nm",input.Name),("$e",input.Email),("$p",input.Phone),("$ad",input.Address),("$h",input.HouseholdNotes),("$x",input.PetExperience),("$d",Now()));return Results.Created($"/api/adoption-requests/{id}",new{requestNumber=num,status="Submitted"});});
    }

    public sealed record AdoptionInput(string Name,string Email,string Phone,string? Address,string? HouseholdNotes,string? PetExperience);
    static void Ensure(string p){using var cn=Open(p);cn.Open();var c=cn.CreateCommand();c.CommandText="CREATE TABLE IF NOT EXISTS ShelterSpaces(Id TEXT PRIMARY KEY,Name TEXT NOT NULL,SpaceType TEXT NOT NULL,Capacity INTEGER NOT NULL,Active INTEGER NOT NULL,Notes TEXT,CreatedAt TEXT NOT NULL,CreatedBy TEXT);CREATE TABLE IF NOT EXISTS ShelterAnimals(Id TEXT PRIMARY KEY,AnimalNumber TEXT NOT NULL UNIQUE,Name TEXT,Species TEXT NOT NULL,Breed TEXT,Sex TEXT,ApproxAge TEXT,ColorMarkings TEXT,Microchip TEXT,CustodyStatus TEXT NOT NULL,AdoptionStatus TEXT NOT NULL,PublishToPublic INTEGER NOT NULL,SpaceId TEXT,PublicDescription TEXT,InternalNotes TEXT,IntakeAt TEXT NOT NULL,CreatedBy TEXT,UpdatedAt TEXT NOT NULL);CREATE TABLE IF NOT EXISTS AdoptionRequests(Id TEXT PRIMARY KEY,RequestNumber TEXT NOT NULL UNIQUE,AnimalId TEXT NOT NULL,ApplicantName TEXT NOT NULL,Email TEXT NOT NULL,Phone TEXT NOT NULL,Address TEXT,HouseholdNotes TEXT,PetExperience TEXT,Status TEXT NOT NULL,SubmittedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL,UpdatedBy TEXT);CREATE INDEX IF NOT EXISTS IX_ShelterAnimals_Public ON ShelterAnimals(PublishToPublic,AdoptionStatus);CREATE INDEX IF NOT EXISTS IX_AdoptionRequests_Status ON AdoptionRequests(Status,SubmittedAt);";c.ExecuteNonQuery();}
    static bool CanAnimalCare(ClaimsPrincipal u)=>u.IsInRole("Administrator")||u.IsInRole("Supervisor")||u.Claims.Any(c=>c.Type==DepartmentAccess.ClaimType&&c.Value.Equals("Animal Care & Control",StringComparison.OrdinalIgnoreCase));
    static SqliteConnection Open(string p)=>new($"Data Source={p}"); static async Task Exec(string p,string sql,params(string,object?)[] ps){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText=sql;foreach(var x in ps)c.Parameters.AddWithValue(x.Item1,x.Item2??DBNull.Value);await c.ExecuteNonQueryAsync();} static async Task<int> Scalar(SqliteConnection cn,string sql){var c=cn.CreateCommand();c.CommandText=sql;return Convert.ToInt32(await c.ExecuteScalarAsync());}
    static async Task<string> SpaceOptions(string p,string? selected){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Id,Name,SpaceType,Capacity FROM ShelterSpaces WHERE Active=1 ORDER BY Name";var rows=new List<string>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync()){var id=r.GetString(0);rows.Add($"<option value='{H(id)}' {(id==selected?"selected":"")}>{H(r.GetString(1))} · {H(r.GetString(2))} · cap {r.GetInt32(3)}</option>");}return string.Join("",rows);} 
    static async Task<(string Number,string Name,string Species,string Breed,string Custody,string Adoption,bool Publish,string? SpaceId,string PublicDescription,string InternalNotes)?> LoadAnimal(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT AnimalNumber,COALESCE(Name,''),Species,COALESCE(Breed,''),CustodyStatus,AdoptionStatus,PublishToPublic,SpaceId,COALESCE(PublicDescription,''),COALESCE(InternalNotes,'') FROM ShelterAnimals WHERE Id=$i";c.Parameters.AddWithValue("$i",id.ToString());await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?(r.GetString(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5),r.GetInt32(6)==1,r.IsDBNull(7)?null:r.GetString(7),r.GetString(8),r.GetString(9)):null;}
    static string? N(SqliteDataReader r,int i)=>r.IsDBNull(i)?null:r.GetString(i); static string Now()=>DateTimeOffset.UtcNow.ToString("O");static string H(object? x)=>WebUtility.HtmlEncode(x?.ToString()??"");static IResult Html(string x)=>Results.Content(x,"text/html; charset=utf-8");static string Page(string t,string b)=>$"<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width'><title>{H(t)} · CLT++ Employee</title><link rel='stylesheet' href='/app.css'></head><body>{b}</body></html>";
}
