using System.Net;
using System.Security.Claims;
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.Data.Sqlite;

namespace CltPlusPlus.Employee;

public static class ArrestRecords
{
    public static void Map(WebApplication app)
    {
        EnsureSchema(app.Configuration);

        app.MapGet("/arrests", async (HttpContext ctx) =>
        {
            if(!CanPolice(ctx.User)) return Results.Forbid();
            await using var cn=Open(app.Configuration);await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="SELECT Id,ArrestNumber,PersonName,IncidentNumber,Status,ArrestingOfficer,ArrestedAt FROM ArrestRecords ORDER BY ArrestedAt DESC LIMIT 200";var rows=new List<string>();await using var r=await cmd.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<tr><td><a href='/arrests/{r.GetString(0)}'><b>{H(r.GetString(1))}</b></a></td><td>{H(r.GetString(2))}</td><td>{H(N(r,3))}</td><td><span class='status'>{H(r.GetString(4))}</span></td><td>{H(r.GetString(5))}</td><td>{H(r.GetString(6))}</td></tr>");return Html(Page("Arrest records",$"""<main class='wrap'><a class='back' href='/'>← Work queue</a><section class='page-head'><div><span class='eyebrow'>POLICE · ARREST RECORDS</span><h1>Arrest records</h1><p>Document arrests already made by an authorized officer. CLT++ does not determine probable cause or recommend arrest.</p></div><a class='button' href='/arrests/new'>New arrest record</a></section><section class='table-card'><table><thead><tr><th>Arrest</th><th>Person</th><th>Incident</th><th>Status</th><th>Officer</th><th>Arrested</th></tr></thead><tbody>{(rows.Count>0?string.Join("",rows):"<tr><td colspan='6' class='empty'>No arrest records.</td></tr>")}</tbody></table></section></main>"""));
        }).RequireAuthorization();

        app.MapGet("/arrests/new", async (HttpContext ctx, IAntiforgery anti, Guid? expressReportId) =>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();var token=anti.GetAndStoreTokens(ctx).RequestToken!;var reports=await ExpressOptions(app.Configuration,expressReportId);return Html(Page("New arrest record",$"""<main class='wrap'><a class='back' href='/arrests'>← Arrest records</a><section class='card'><span class='eyebrow'>POLICE · ARREST</span><h1>Document an arrest</h1><div class='notice'><b>Officer decision</b><p>This form records an arrest the officer has already made. It does not make a probable-cause determination or recommend arrest.</p></div><form method='post' action='/arrests'><input type='hidden' name='__RequestVerificationToken' value='{H(token)}'/><label>Linked Express Report (optional)<select name='expressReportId'><option value=''>None</option>{reports}</select></label><h2>Person</h2><label>Full name<input name='personName' required/></label><div class='two'><label>Date of birth<input name='dateOfBirth'/></label><label>Driver license / ID<input name='licenseId'/></label></div><label>Address<input name='address'/></label><h2>Arrest details</h2><label>Incident / case number<input name='incidentNumber' required/></label><label>Arrest date/time<input name='arrestedAt' type='datetime-local' required/></label><label>Arrest location<input name='arrestLocation' required/></label><label>Legal basis<select name='legalBasis'><option>Warrant</option><option>Probable cause without warrant</option><option>Other lawful authority</option></select></label><label>Warrant / process reference<input name='warrantReference'/></label><label>Charges / statutes<textarea name='charges' rows='5' required></textarea></label><label>Facts supporting officer's stated legal basis<textarea name='basisNarrative' rows='6' required></textarea></label><h2>Custody</h2><label>Transport / booking destination<input name='bookingDestination'/></label><label>Property / evidence references<textarea name='propertyEvidence' rows='3'></textarea></label><label>Custody disposition<textarea name='custodyDisposition' rows='3'></textarea></label><button>Create arrest record</button></form></section></main>"""));
        }).RequireAuthorization();

        app.MapPost("/arrests", async (HttpContext ctx, IAntiforgery anti)=>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();var name=f["personName"].ToString().Trim();var incident=f["incidentNumber"].ToString().Trim();var location=f["arrestLocation"].ToString().Trim();var charges=f["charges"].ToString().Trim();var basis=f["basisNarrative"].ToString().Trim();if(new[]{name,incident,location,charges,basis}.Any(string.IsNullOrWhiteSpace))return Results.BadRequest("Person, incident number, arrest location, charges, and legal-basis narrative are required.");var id=Guid.NewGuid();var now=DateTimeOffset.UtcNow.ToString("O");var arrestedAt=DateTimeOffset.TryParse(f["arrestedAt"],out var at)?at.ToString("O"):now;await using var cn=Open(app.Configuration);await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="""INSERT INTO ArrestRecords(Id,ArrestNumber,ExpressReportId,IncidentNumber,PersonName,DateOfBirth,LicenseId,Address,ArrestedAt,ArrestLocation,LegalBasis,WarrantReference,Charges,BasisNarrative,BookingDestination,PropertyEvidence,CustodyDisposition,ArrestingOfficer,Status,CreatedAt,UpdatedAt) VALUES($id,$num,$rid,$incident,$name,$dob,$dl,$addr,$at,$loc,$legal,$warrant,$charges,$basis,$book,$prop,$disp,$officer,'Recorded',$now,$now)""";void P(string k,string v)=>cmd.Parameters.AddWithValue(k,v);P("$id",id.ToString());P("$num",$"ARR-{DateTime.UtcNow:yyMMdd}-{Random.Shared.Next(100000,999999)}");P("$rid",Guid.TryParse(f["expressReportId"],out var rid)?rid.ToString():"");P("$incident",incident);P("$name",name);P("$dob",f["dateOfBirth"].ToString().Trim());P("$dl",f["licenseId"].ToString().Trim());P("$addr",f["address"].ToString().Trim());P("$at",arrestedAt);P("$loc",location);P("$legal",f["legalBasis"].ToString());P("$warrant",f["warrantReference"].ToString().Trim());P("$charges",charges);P("$basis",basis);P("$book",f["bookingDestination"].ToString().Trim());P("$prop",f["propertyEvidence"].ToString());P("$disp",f["custodyDisposition"].ToString());P("$officer",ctx.User.Identity?.Name??"officer");P("$now",now);await cmd.ExecuteNonQueryAsync();await AddHistory(cn,id,ctx.User.Identity?.Name??"officer","Created","Arrest record created",now);return Results.Redirect($"/arrests/{id}");
        }).RequireAuthorization();

        app.MapGet("/arrests/{id:guid}",async(Guid id,HttpContext ctx)=>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();await using var cn=Open(app.Configuration);await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="SELECT ArrestNumber,ExpressReportId,IncidentNumber,PersonName,DateOfBirth,LicenseId,Address,ArrestedAt,ArrestLocation,LegalBasis,WarrantReference,Charges,BasisNarrative,BookingDestination,PropertyEvidence,CustodyDisposition,ArrestingOfficer,Status,CreatedAt FROM ArrestRecords WHERE Id=$id";cmd.Parameters.AddWithValue("$id",id.ToString());await using var r=await cmd.ExecuteReaderAsync();if(!await r.ReadAsync())return Results.NotFound();var history=await History(app.Configuration,id);return Html(Page(r.GetString(0),$"""<main class='wrap'><a class='back' href='/arrests'>← Arrest records</a><section class='page-head'><div><span class='eyebrow'>ARREST · {H(r.GetString(17))}</span><h1>{H(r.GetString(0))}</h1><p>{H(r.GetString(3))}</p></div></section><div class='detail-grid'><section class='card'><dl><dt>Incident</dt><dd>{H(r.GetString(2))}</dd><dt>Express report</dt><dd>{H(N(r,1))}</dd><dt>DOB</dt><dd>{H(N(r,4))}</dd><dt>License / ID</dt><dd>{H(N(r,5))}</dd><dt>Address</dt><dd>{H(N(r,6))}</dd><dt>Arrested at</dt><dd>{H(r.GetString(7))}</dd><dt>Location</dt><dd>{H(r.GetString(8))}</dd><dt>Legal basis</dt><dd>{H(r.GetString(9))}</dd><dt>Warrant/process</dt><dd>{H(N(r,10))}</dd><dt>Arresting officer</dt><dd>{H(r.GetString(16))}</dd><dt>Booking destination</dt><dd>{H(N(r,13))}</dd></dl><h2>Charges / statutes</h2><p style='white-space:pre-wrap'>{H(r.GetString(11))}</p><h2>Officer-stated legal basis</h2><p style='white-space:pre-wrap'>{H(r.GetString(12))}</p><h2>Property / evidence</h2><p style='white-space:pre-wrap'>{H(N(r,14))}</p><h2>Custody disposition</h2><p style='white-space:pre-wrap'>{H(N(r,15))}</p></section><aside><section class='card'><h2>Audit history</h2>{history}</section></aside></div></main>"""));
        }).RequireAuthorization();
    }

    private static async Task<string> ExpressOptions(IConfiguration c,Guid? selected){await using var cn=Open(c);await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="SELECT Id,ReportNumber,COALESCE(Title,'') FROM ExpressReports ORDER BY UpdatedAt DESC LIMIT 100";var list=new List<string>();await using var r=await cmd.ExecuteReaderAsync();while(await r.ReadAsync()){var id=r.GetString(0);list.Add($"<option value='{H(id)}' {(selected?.ToString()==id?"selected":"")}>{H(r.GetString(1))} · {H(r.GetString(2))}</option>");}return string.Join("",list);}
    private static async Task AddHistory(SqliteConnection cn,Guid id,string actor,string action,string detail,string at){var cmd=cn.CreateCommand();cmd.CommandText="INSERT INTO ArrestHistory(Id,ArrestId,Actor,Action,Detail,OccurredAt) VALUES($i,$a,$u,$x,$d,$t)";cmd.Parameters.AddWithValue("$i",Guid.NewGuid().ToString());cmd.Parameters.AddWithValue("$a",id.ToString());cmd.Parameters.AddWithValue("$u",actor);cmd.Parameters.AddWithValue("$x",action);cmd.Parameters.AddWithValue("$d",detail);cmd.Parameters.AddWithValue("$t",at);await cmd.ExecuteNonQueryAsync();}
    private static async Task<string> History(IConfiguration c,Guid id){await using var cn=Open(c);await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="SELECT Actor,Action,Detail,OccurredAt FROM ArrestHistory WHERE ArrestId=$id ORDER BY OccurredAt DESC";cmd.Parameters.AddWithValue("$id",id.ToString());var rows=new List<string>();await using var r=await cmd.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<article><b>{H(r.GetString(1))}</b><small>{H(r.GetString(0))} · {H(r.GetString(3))}</small><p>{H(r.GetString(2))}</p></article>");return rows.Count==0?"<p class='muted'>No history.</p>":string.Join("",rows);}
    private static void EnsureSchema(IConfiguration c){using var cn=Open(c);cn.Open();using var cmd=cn.CreateCommand();cmd.CommandText="""CREATE TABLE IF NOT EXISTS ArrestRecords(Id TEXT PRIMARY KEY,ArrestNumber TEXT NOT NULL UNIQUE,ExpressReportId TEXT NULL,IncidentNumber TEXT NOT NULL,PersonName TEXT NOT NULL,DateOfBirth TEXT NULL,LicenseId TEXT NULL,Address TEXT NULL,ArrestedAt TEXT NOT NULL,ArrestLocation TEXT NOT NULL,LegalBasis TEXT NOT NULL,WarrantReference TEXT NULL,Charges TEXT NOT NULL,BasisNarrative TEXT NOT NULL,BookingDestination TEXT NULL,PropertyEvidence TEXT NULL,CustodyDisposition TEXT NULL,ArrestingOfficer TEXT NOT NULL,Status TEXT NOT NULL,CreatedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL);CREATE TABLE IF NOT EXISTS ArrestHistory(Id TEXT PRIMARY KEY,ArrestId TEXT NOT NULL,Actor TEXT NOT NULL,Action TEXT NOT NULL,Detail TEXT NOT NULL,OccurredAt TEXT NOT NULL);CREATE INDEX IF NOT EXISTS IX_Arrests_Incident ON ArrestRecords(IncidentNumber);CREATE INDEX IF NOT EXISTS IX_Arrests_Express ON ArrestRecords(ExpressReportId);""";cmd.ExecuteNonQuery();}
    private static SqliteConnection Open(IConfiguration c){var p=c["CLTPP_PUBLIC_SAFETY_DB"]??Path.Combine(AppContext.BaseDirectory,"data","public-safety.db");Directory.CreateDirectory(Path.GetDirectoryName(p)!);return new SqliteConnection($"Data Source={p}");}
    private static bool CanPolice(ClaimsPrincipal u)=>u.IsInRole("Administrator")||u.IsInRole("Supervisor")||u.FindAll(DepartmentAccess.ClaimType).Any(c=>string.Equals(c.Value,"Police",StringComparison.OrdinalIgnoreCase));
    private static string? N(SqliteDataReader r,int i)=>r.IsDBNull(i)?null:r.GetString(i);private static string H(string? s)=>WebUtility.HtmlEncode(s??"");private static IResult Html(string s)=>Results.Content(s,"text/html; charset=utf-8");private static string Page(string t,string b)=>$"<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>{H(t)} · CLT++ Employee</title><link rel='stylesheet' href='/app.css'></head><body><header class='top'><a href='/' class='brand'>CLT<span>++</span> <small>EMPLOYEE</small></a><div>Police arrest records</div></header>{b}</body></html>";
}
