using System.Net;
using System.Security.Claims;
using System.Text;
using System.Text.Json;
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.Data.Sqlite;

namespace CltPlusPlus.Employee;

public static class AwsSupplementalNarrativeCalls
{
    public static void Map(WebApplication app)
    {
        var dbPath=app.Configuration["CLTPP_PUBLIC_SAFETY_DB"]??Path.Combine(AppContext.BaseDirectory,"data","public-safety.db");
        Directory.CreateDirectory(Path.GetDirectoryName(dbPath)!);EnsureSchema(dbPath);

        app.MapGet("/supplemental-calls",async(HttpContext ctx)=>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();await using var cn=Open(dbPath);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT x.Id,r.ReportNumber,x.ContactName,x.ContactRole,x.Phone,x.Status,x.StartedAt,x.DurationSeconds,x.OfficerUsername FROM AwsSupplementalCalls x JOIN ExpressReports r ON r.Id=x.ExpressReportId ORDER BY x.CreatedAt DESC LIMIT 300";var rows=new List<string>();await using var rd=await c.ExecuteReaderAsync();while(await rd.ReadAsync())rows.Add($"<tr><td><a href='/supplemental-calls/{rd.GetString(0)}'><b>{H(rd.GetString(1))}</b></a></td><td>{H(rd.GetString(2))}<small>{H(rd.GetString(3))}</small></td><td>{H(rd.GetString(4))}</td><td>{H(rd.GetString(5))}</td><td>{H(N(rd,6))}</td><td>{H(N(rd,7))}</td><td>{H(rd.GetString(8))}</td></tr>");return Html(Page("Supplemental calls",$"<main class='wrap'><a class='back' href='/'>← Work queue</a><section class='page-head'><div><span class='eyebrow'>POLICE · AWS VOICE</span><h1>Recorded supplemental calls</h1><p>Recorded outbound calls tied to Express Reports.</p></div><a class='button' href='/supplemental-calls/new'>New call</a></section><section class='table-card'><table><thead><tr><th>Report</th><th>Contact</th><th>Phone</th><th>Status</th><th>Started</th><th>Seconds</th><th>Officer</th></tr></thead><tbody>{(rows.Count>0?string.Join("",rows):"<tr><td colspan='7'>No supplemental calls.</td></tr>")}</tbody></table></section></main>"));
        }).RequireAuthorization();

        app.MapGet("/supplemental-calls/new",async(HttpContext ctx,IAntiforgery anti,Guid? expressReportId)=>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();var t=anti.GetAndStoreTokens(ctx).RequestToken!;var reports=await ReportOptions(dbPath,expressReportId);return Html(Page("New supplemental call",$"""<main class='wrap'><a class='back' href='/supplemental-calls'>← Supplemental calls</a><section class='card'><span class='eyebrow'>POLICE · AWS VOICE</span><h1>Place recorded supplemental call</h1><div class='notice'><b>Recording disclosure required</b><p>The AWS call request instructs the voice service to play a recording notice before recording begins. Do not use this workflow for covert recording.</p></div><form method='post' action='/supplemental-calls'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><label>Express Report<select name='expressReportId' required><option value=''>Select report</option>{reports}</select></label><label>Contact role<select name='contactRole'><option>Victim</option><option>Suspect</option><option>Witness</option><option>Reporting Person</option><option>Other</option></select></label><label>Contact name<input name='contactName' required/></label><label>Phone<input name='phone' type='tel' required placeholder='+17045551212'/></label><label>Purpose<textarea name='purpose' rows='4' required></textarea></label><button>Place recorded AWS call</button></form></section></main>"""));
        }).RequireAuthorization();

        app.MapPost("/supplemental-calls",async(HttpContext ctx,IAntiforgery anti,IHttpClientFactory factory)=>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();if(!Guid.TryParse(f["expressReportId"],out var reportId)||!await ReportExists(dbPath,reportId))return Results.BadRequest("Valid Express Report required.");var name=f["contactName"].ToString().Trim();var phone=f["phone"].ToString().Trim();var purpose=f["purpose"].ToString().Trim();if(name.Length==0||phone.Length==0||purpose.Length==0)return Results.BadRequest("Contact, phone, and purpose are required.");var endpoint=app.Configuration["CLTPP_AWS_CALL_API_URL"];if(string.IsNullOrWhiteSpace(endpoint))return Results.BadRequest("AWS call API is not configured (CLTPP_AWS_CALL_API_URL).");var id=Guid.NewGuid();var callbackSecret=Guid.NewGuid().ToString("N")+Guid.NewGuid().ToString("N");var callbackUrl=$"{ctx.Request.Scheme}://{ctx.Request.Host}/integrations/aws-call/{id}/status?secret={Uri.EscapeDataString(callbackSecret)}";var body=new{destinationPhone=phone,callerId=app.Configuration["CLTPP_AWS_CALLER_ID"],record=true,recordingDisclosure=true,disclosureText="This call may be recorded for law enforcement report documentation.",officer=ctx.User.Identity?.Name??"officer",referenceId=id.ToString(),expressReportId=reportId.ToString(),purpose,callbackUrl};var client=factory.CreateClient();using var req=new HttpRequestMessage(HttpMethod.Post,endpoint);var key=app.Configuration["CLTPP_AWS_CALL_API_KEY"];if(!string.IsNullOrWhiteSpace(key))req.Headers.TryAddWithoutValidation("X-Api-Key",key);req.Content=new StringContent(JsonSerializer.Serialize(body),Encoding.UTF8,"application/json");using var resp=await client.SendAsync(req);var responseText=await resp.Content.ReadAsStringAsync();if(!resp.IsSuccessStatusCode)return Results.BadRequest($"AWS call API rejected the call request: {(int)resp.StatusCode} {resp.StatusCode}.");string? callId=null,recording=null;try{using var doc=JsonDocument.Parse(responseText);var root=doc.RootElement;if(root.TryGetProperty("callId",out var cid))callId=cid.GetString();if(root.TryGetProperty("recordingReference",out var rr))recording=rr.GetString();}catch{}var now=Now();await Exec(dbPath,"""INSERT INTO AwsSupplementalCalls(Id,ExpressReportId,ContactRole,ContactName,Phone,Purpose,OfficerUsername,Status,AwsCallId,RecordingStatus,RecordingReference,CallbackSecret,CreatedAt,UpdatedAt) VALUES($i,$r,$role,$n,$p,$purpose,$o,'Requested',$call,'Requested',$recording,$secret,$t,$t)""",("$i",id),("$r",reportId),("$role",f["contactRole"]),("$n",name),("$p",phone),("$purpose",purpose),("$o",ctx.User.Identity?.Name??"officer"),("$call",callId),("$recording",recording),("$secret",callbackSecret),("$t",now));await Hist(dbPath,id,ctx.User.Identity?.Name??"officer","Call requested",$"AWS call ID: {callId??"pending"}");return Results.Redirect($"/supplemental-calls/{id}");
        }).RequireAuthorization();

        app.MapPost("/integrations/aws-call/{id:guid}/status",async(Guid id,HttpContext ctx,string secret)=>
        {
            var call=await Load(dbPath,id);if(call is null||!string.Equals(secret,call.Value.CallbackSecret,StringComparison.Ordinal))return Results.Unauthorized();AwsCallback? payload;try{payload=await JsonSerializer.DeserializeAsync<AwsCallback>(ctx.Request.Body,new JsonSerializerOptions{PropertyNameCaseInsensitive=true});}catch{return Results.BadRequest();}if(payload is null)return Results.BadRequest();var now=Now();await Exec(dbPath,"""UPDATE AwsSupplementalCalls SET Status=$s,AwsCallId=COALESCE(NULLIF($call,''),AwsCallId),RecordingStatus=$rs,RecordingReference=COALESCE(NULLIF($rr,''),RecordingReference),StartedAt=COALESCE(NULLIF($start,''),StartedAt),EndedAt=COALESCE(NULLIF($end,''),EndedAt),DurationSeconds=CASE WHEN $dur='' THEN DurationSeconds ELSE $dur END,UpdatedAt=$t WHERE Id=$id""",("$s",payload.Status??"Updated"),("$call",payload.CallId),("$rs",payload.RecordingStatus??"Updated"),("$rr",payload.RecordingReference),("$start",payload.StartedAt),("$end",payload.EndedAt),("$dur",payload.DurationSeconds?.ToString()),("$t",now),("$id",id));await Hist(dbPath,id,"AWS Call API","Status callback",$"{payload.Status}; recording {payload.RecordingStatus}; duration {payload.DurationSeconds}");return Results.Ok();
        });

        app.MapGet("/supplemental-calls/{id:guid}",async(Guid id,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();var x=await Load(dbPath,id);if(x is null)return Results.NotFound();var t=anti.GetAndStoreTokens(ctx).RequestToken!;var hist=await History(dbPath,id);var supplements=await Supplements(dbPath,x.Value.ExpressReportId,id);return Html(Page("Supplemental call",$"""<main class='wrap'><a class='back' href='/supplemental-calls'>← Supplemental calls</a><section class='page-head'><div><span class='eyebrow'>AWS RECORDED CALL · {H(x.Value.Status)}</span><h1>{H(x.Value.ReportNumber)}</h1><p>{H(x.Value.ContactRole)} · {H(x.Value.ContactName)}</p></div></section><div class='detail-grid'><section><section class='card'><dl><dt>Phone</dt><dd>{H(x.Value.Phone)}</dd><dt>Officer</dt><dd>{H(x.Value.Officer)}</dd><dt>AWS call ID</dt><dd>{H(x.Value.AwsCallId)}</dd><dt>Recording status</dt><dd>{H(x.Value.RecordingStatus)}</dd><dt>Recording reference</dt><dd>{H(x.Value.RecordingReference)}</dd><dt>Started</dt><dd>{H(x.Value.StartedAt)}</dd><dt>Ended</dt><dd>{H(x.Value.EndedAt)}</dd><dt>Duration</dt><dd>{H(x.Value.DurationSeconds)} seconds</dd></dl><h2>Purpose</h2><p>{H(x.Value.Purpose)}</p></section><section class='card'><h2>Express Report supplements</h2>{supplements}</section></section><aside><section class='card'><h2>Append supplemental narrative</h2><form method='post' action='/supplemental-calls/{id}/narrative'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><label>Officer narrative<textarea name='narrative' rows='10' required></textarea></label><label>Call outcome<textarea name='outcome' rows='4'></textarea></label><button>Append to Express Report</button></form></section><section class='card'><h2>Call history</h2>{hist}</section></aside></div></main>"""));
        }).RequireAuthorization();

        app.MapPost("/supplemental-calls/{id:guid}/narrative",async(Guid id,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var x=await Load(dbPath,id);if(x is null)return Results.NotFound();var f=await ctx.Request.ReadFormAsync();var narrative=f["narrative"].ToString().Trim();if(narrative.Length==0)return Results.BadRequest("Narrative required.");var now=Now();await Exec(dbPath,"INSERT INTO ExpressReportSupplements(Id,ExpressReportId,SourceType,SourceId,ParticipantRole,Title,Narrative,AuthoredBy,AuthoredAt) VALUES($i,$r,'AWS Supplemental Call',$source,$role,$title,$n,$by,$t)",("$i",Guid.NewGuid()),("$r",x.Value.ExpressReportId),("$source",id),("$role",x.Value.ContactRole),("$title",$"Recorded supplemental call with {x.Value.ContactName}"),("$n",narrative),("$by",ctx.User.Identity?.Name??"officer"),("$t",now));await Exec(dbPath,"UPDATE AwsSupplementalCalls SET Outcome=$o,UpdatedAt=$t WHERE Id=$id",("$o",f["outcome"]),("$t",now),("$id",id));await Hist(dbPath,id,ctx.User.Identity?.Name??"officer","Narrative appended","Express Report supplement created.");return Results.Redirect($"/supplemental-calls/{id}");
        }).RequireAuthorization();
    }

    private sealed record Call(Guid Id,Guid ExpressReportId,string ReportNumber,string ContactRole,string ContactName,string Phone,string Purpose,string Officer,string Status,string? AwsCallId,string RecordingStatus,string? RecordingReference,string CallbackSecret,string? StartedAt,string? EndedAt,string? DurationSeconds);
    private sealed record AwsCallback(string? CallId,string? Status,string? RecordingStatus,string? RecordingReference,string? StartedAt,string? EndedAt,int? DurationSeconds);
    private static async Task<Call?> Load(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT x.Id,x.ExpressReportId,r.ReportNumber,x.ContactRole,x.ContactName,x.Phone,x.Purpose,x.OfficerUsername,x.Status,x.AwsCallId,x.RecordingStatus,x.RecordingReference,x.CallbackSecret,x.StartedAt,x.EndedAt,x.DurationSeconds FROM AwsSupplementalCalls x JOIN ExpressReports r ON r.Id=x.ExpressReportId WHERE x.Id=$id";P(c,"$id",id);await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?new(Guid.Parse(r.GetString(0)),Guid.Parse(r.GetString(1)),r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5),r.GetString(6),r.GetString(7),r.GetString(8),N(r,9),r.GetString(10),N(r,11),r.GetString(12),N(r,13),N(r,14),r.IsDBNull(15)?null:r.GetValue(15).ToString()):null;}
    private static async Task<string> ReportOptions(string p,Guid? selected){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Id,ReportNumber,COALESCE(Title,''),Status FROM ExpressReports ORDER BY UpdatedAt DESC LIMIT 200";var rows=new List<string>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync()){var id=r.GetString(0);rows.Add($"<option value='{H(id)}' {(selected?.ToString()==id?"selected":"")}>{H(r.GetString(1))} · {H(r.GetString(2))} · {H(r.GetString(3))}</option>");}return string.Join("",rows);}
    private static async Task<bool> ReportExists(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT 1 FROM ExpressReports WHERE Id=$id";P(c,"$id",id);return await c.ExecuteScalarAsync()!=null;}
    private static async Task<string> Supplements(string p,Guid reportId,Guid callId){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Title,Narrative,AuthoredBy,AuthoredAt FROM ExpressReportSupplements WHERE ExpressReportId=$r AND SourceId=$s ORDER BY AuthoredAt DESC";P(c,"$r",reportId);P(c,"$s",callId);var rows=new List<string>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<article><b>{H(r.GetString(0))}</b><small>{H(r.GetString(2))} · {H(r.GetString(3))}</small><p style='white-space:pre-wrap'>{H(r.GetString(1))}</p></article>");return rows.Count==0?"<p class='muted'>No call narrative appended yet.</p>":string.Join("",rows);}
    private static async Task<string> History(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Actor,Action,Detail,OccurredAt FROM AwsSupplementalCallHistory WHERE CallId=$id ORDER BY OccurredAt DESC";P(c,"$id",id);var rows=new List<string>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<article><b>{H(r.GetString(1))}</b><small>{H(r.GetString(0))} · {H(r.GetString(3))}</small><p>{H(r.GetString(2))}</p></article>");return rows.Count==0?"<p class='muted'>No history.</p>":string.Join("",rows);}
    private static async Task Hist(string p,Guid id,string actor,string action,string detail)=>await Exec(p,"INSERT INTO AwsSupplementalCallHistory(Id,CallId,Actor,Action,Detail,OccurredAt) VALUES($i,$c,$a,$x,$d,$t)",("$i",Guid.NewGuid()),("$c",id),("$a",actor),("$x",action),("$d",detail),("$t",Now()));
    private static async Task Exec(string p,string sql,params(string Key,object? Value)[] ps){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText=sql;foreach(var x in ps)P(c,x.Key,x.Value);await c.ExecuteNonQueryAsync();}
    private static void EnsureSchema(string p){using var cn=Open(p);cn.Open();using var c=cn.CreateCommand();c.CommandText="""CREATE TABLE IF NOT EXISTS AwsSupplementalCalls(Id TEXT PRIMARY KEY,ExpressReportId TEXT NOT NULL,ContactRole TEXT NOT NULL,ContactName TEXT NOT NULL,Phone TEXT NOT NULL,Purpose TEXT NOT NULL,OfficerUsername TEXT NOT NULL,Status TEXT NOT NULL,AwsCallId TEXT NULL,RecordingStatus TEXT NOT NULL,RecordingReference TEXT NULL,CallbackSecret TEXT NOT NULL,StartedAt TEXT NULL,EndedAt TEXT NULL,DurationSeconds INTEGER NULL,Outcome TEXT NULL,CreatedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL);CREATE TABLE IF NOT EXISTS AwsSupplementalCallHistory(Id TEXT PRIMARY KEY,CallId TEXT NOT NULL,Actor TEXT NOT NULL,Action TEXT NOT NULL,Detail TEXT NOT NULL,OccurredAt TEXT NOT NULL);CREATE TABLE IF NOT EXISTS ExpressReportSupplements(Id TEXT PRIMARY KEY,ExpressReportId TEXT NOT NULL,SourceType TEXT NOT NULL,SourceId TEXT NOT NULL,ParticipantRole TEXT NULL,Title TEXT NOT NULL,Narrative TEXT NOT NULL,AuthoredBy TEXT NOT NULL,AuthoredAt TEXT NOT NULL);CREATE INDEX IF NOT EXISTS IX_AwsCalls_Report ON AwsSupplementalCalls(ExpressReportId);CREATE INDEX IF NOT EXISTS IX_AwsCalls_AwsId ON AwsSupplementalCalls(AwsCallId);""";c.ExecuteNonQuery();}
    private static SqliteConnection Open(string p)=>new($"Data Source={p}");private static string Now()=>DateTimeOffset.UtcNow.ToString("O");private static void P(SqliteCommand c,string k,object? v)=>c.Parameters.AddWithValue(k,v?.ToString()??"");private static string? N(SqliteDataReader r,int i)=>r.IsDBNull(i)?null:r.GetString(i);private static bool CanPolice(ClaimsPrincipal u)=>u.IsInRole("Administrator")||u.IsInRole("Supervisor")||u.FindAll(DepartmentAccess.ClaimType).Any(c=>c.Value.Equals("Police",StringComparison.OrdinalIgnoreCase));private static string H(string? s)=>WebUtility.HtmlEncode(s??"");private static IResult Html(string s)=>Results.Content(s,"text/html; charset=utf-8");private static string Page(string t,string b)=>$"<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>{H(t)} · CLT++ Employee</title><link rel='stylesheet' href='/app.css'></head><body><header class='top'><a href='/' class='brand'>CLT<span>++</span> <small>EMPLOYEE</small></a><div>AWS supplemental calls</div></header>{b}</body></html>";
}
