using System.Net;
using System.Security.Claims;
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.Data.Sqlite;

namespace CltPlusPlus.Employee;

public static class DaComplaints
{
    public static void Map(WebApplication app)
    {
        var dbPath=app.Configuration["CLTPP_PUBLIC_SAFETY_DB"]??Path.Combine(AppContext.BaseDirectory,"data","public-safety.db");
        Directory.CreateDirectory(Path.GetDirectoryName(dbPath)!);EnsureSchema(dbPath);

        app.MapGet("/express-reports/{id:guid}/da-complaint/new",async(Guid id,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();var report=await LoadReport(dbPath,id);if(report is null)return Results.NotFound();if(!IsApproved(report.Value.Status))return Results.BadRequest("Only approved or submitted Express Reports may be filed as a DA complaint.");var t=anti.GetAndStoreTokens(ctx).RequestToken!;return Html(Page("File DA complaint",$"""<main class='wrap'><a class='back' href='/express-reports/{id}'>← Express report</a><section class='page-head'><div><span class='eyebrow'>POLICE · DISTRICT ATTORNEY</span><h1>File DA complaint</h1><p>{H(report.Value.Number)} · {H(report.Value.Title)}</p></div></section><div class='detail-grid'><section class='card'><h2>Approved Express Report</h2><dl><dt>Status</dt><dd>{H(report.Value.Status)}</dd><dt>Location</dt><dd>{H(report.Value.Location)}</dd><dt>Officer</dt><dd>{H(report.Value.CreatedBy)}</dd></dl><h3>Narrative / transcript</h3><p style='white-space:pre-wrap'>{H(report.Value.Transcript)}</p></section><aside><section class='card'><h2>Complaint intake</h2><form method='post' action='/da-complaints'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><input type='hidden' name='expressReportId' value='{id}'/><label>Defendant / suspect name<input name='subjectName' required/></label><label>Date of birth<input name='dateOfBirth'/></label><label>Incident / case number<input name='incidentNumber' value='{H(report.Value.Number)}' required/></label><label>Officer complaint narrative<textarea name='complaintNarrative' rows='7' required></textarea></label><label>Requested prosecutorial review<textarea name='reviewRequest' rows='4' required></textarea></label><label>Supporting references<textarea name='supportingReferences' rows='4' placeholder='Warrants, evidence items, witness references, etc.'></textarea></label><button>File complaint with DA</button></form></section></aside></div></main>"""));
        }).RequireAuthorization();

        app.MapPost("/da-complaints",async(HttpContext ctx,IAntiforgery anti)=>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();if(!Guid.TryParse(f["expressReportId"],out var rid))return Results.BadRequest("Express Report is required.");var report=await LoadReport(dbPath,rid);if(report is null||!IsApproved(report.Value.Status))return Results.BadRequest("Only approved or submitted Express Reports may be filed as a DA complaint.");var subject=f["subjectName"].ToString().Trim();var narrative=f["complaintNarrative"].ToString().Trim();var review=f["reviewRequest"].ToString().Trim();if(new[]{subject,narrative,review}.Any(string.IsNullOrWhiteSpace))return Results.BadRequest("Subject, complaint narrative, and review request are required.");var id=Guid.NewGuid();var now=DateTimeOffset.UtcNow.ToString("O");await using var cn=Open(dbPath);await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="""INSERT INTO DaComplaints(Id,ComplaintNumber,ExpressReportId,IncidentNumber,SubjectName,DateOfBirth,ComplaintNarrative,ReviewRequest,SupportingReferences,Status,FiledBy,FiledAt,UpdatedAt) VALUES($id,$num,$rid,$incident,$subject,$dob,$n,$r,$s,'Filed',$by,$at,$at)""";void P(string k,string v)=>cmd.Parameters.AddWithValue(k,v);P("$id",id.ToString());P("$num",$"DAC-{DateTime.UtcNow:yyMMdd}-{Random.Shared.Next(100000,999999)}");P("$rid",rid.ToString());P("$incident",f["incidentNumber"].ToString().Trim());P("$subject",subject);P("$dob",f["dateOfBirth"].ToString().Trim());P("$n",narrative);P("$r",review);P("$s",f["supportingReferences"].ToString());P("$by",ctx.User.Identity?.Name??"officer");P("$at",now);await cmd.ExecuteNonQueryAsync();return Results.Redirect($"/da-complaints/{id}");
        }).RequireAuthorization();

        app.MapGet("/da-complaints/{id:guid}",async(Guid id,HttpContext ctx)=>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();await using var cn=Open(dbPath);await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="SELECT ComplaintNumber,ExpressReportId,IncidentNumber,SubjectName,DateOfBirth,ComplaintNarrative,ReviewRequest,SupportingReferences,Status,FiledBy,FiledAt FROM DaComplaints WHERE Id=$id";cmd.Parameters.AddWithValue("$id",id.ToString());await using var r=await cmd.ExecuteReaderAsync();if(!await r.ReadAsync())return Results.NotFound();return Html(Page(r.GetString(0),$"""<main class='wrap'><a class='back' href='/express-reports/{r.GetString(1)}'>← Express report</a><section class='page-head'><div><span class='eyebrow'>DA COMPLAINT · {H(r.GetString(8))}</span><h1>{H(r.GetString(0))}</h1><p>{H(r.GetString(3))}</p></div></section><section class='card'><dl><dt>Incident</dt><dd>{H(r.GetString(2))}</dd><dt>Express Report</dt><dd>{H(r.GetString(1))}</dd><dt>DOB</dt><dd>{H(N(r,4))}</dd><dt>Filed by</dt><dd>{H(r.GetString(9))}</dd><dt>Filed</dt><dd>{H(r.GetString(10))}</dd></dl><h2>Complaint narrative</h2><p style='white-space:pre-wrap'>{H(r.GetString(5))}</p><h2>Requested review</h2><p style='white-space:pre-wrap'>{H(r.GetString(6))}</p><h2>Supporting references</h2><p style='white-space:pre-wrap'>{H(N(r,7))}</p></section></main>"""));
        }).RequireAuthorization();
    }

    private static bool IsApproved(string s)=>s.Equals("Approved",StringComparison.OrdinalIgnoreCase)||s.Equals("Submitted",StringComparison.OrdinalIgnoreCase);
    private static async Task<(Guid Id,string Number,string Status,string Title,string Transcript,string Location,string CreatedBy)?> LoadReport(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="SELECT Id,ReportNumber,Status,COALESCE(Title,''),COALESCE(Transcript,''),COALESCE(Location,''),CreatedBy FROM ExpressReports WHERE Id=$id";cmd.Parameters.AddWithValue("$id",id.ToString());await using var r=await cmd.ExecuteReaderAsync();return await r.ReadAsync()?(Guid.Parse(r.GetString(0)),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5),r.GetString(6)):null;}
    private static void EnsureSchema(string p){using var cn=Open(p);cn.Open();using var cmd=cn.CreateCommand();cmd.CommandText="""CREATE TABLE IF NOT EXISTS DaComplaints(Id TEXT PRIMARY KEY,ComplaintNumber TEXT NOT NULL UNIQUE,ExpressReportId TEXT NOT NULL,IncidentNumber TEXT NOT NULL,SubjectName TEXT NOT NULL,DateOfBirth TEXT NULL,ComplaintNarrative TEXT NOT NULL,ReviewRequest TEXT NOT NULL,SupportingReferences TEXT NULL,Status TEXT NOT NULL,FiledBy TEXT NOT NULL,FiledAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL);CREATE INDEX IF NOT EXISTS IX_DaComplaints_Report ON DaComplaints(ExpressReportId);CREATE INDEX IF NOT EXISTS IX_DaComplaints_Status ON DaComplaints(Status);""";cmd.ExecuteNonQuery();}
    private static SqliteConnection Open(string p)=>new($"Data Source={p}");private static bool CanPolice(ClaimsPrincipal u)=>u.IsInRole("Administrator")||u.IsInRole("Supervisor")||u.FindAll(DepartmentAccess.ClaimType).Any(c=>string.Equals(c.Value,"Police",StringComparison.OrdinalIgnoreCase));private static string? N(SqliteDataReader r,int i)=>r.IsDBNull(i)?null:r.GetString(i);private static string H(string? s)=>WebUtility.HtmlEncode(s??"");private static IResult Html(string s)=>Results.Content(s,"text/html; charset=utf-8");private static string Page(string t,string b)=>$"<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>{H(t)} · CLT++ Employee</title><link rel='stylesheet' href='/app.css'></head><body><header class='top'><a href='/' class='brand'>CLT<span>++</span> <small>EMPLOYEE</small></a><div>DA complaint filing</div></header>{b}</body></html>";
}
