using System.Net;
using System.Security.Claims;
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.Data.Sqlite;

namespace CltPlusPlus.Employee;

public static class JailBookings
{
    public static void Map(WebApplication app)
    {
        var dbPath=app.Configuration["CLTPP_PUBLIC_SAFETY_DB"]??Path.Combine(AppContext.BaseDirectory,"data","public-safety.db");
        Directory.CreateDirectory(Path.GetDirectoryName(dbPath)!);EnsureSchema(dbPath);

        app.MapGet("/jail-bookings",async(HttpContext ctx)=>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();await using var cn=Open(dbPath);await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="SELECT b.Id,b.BookingNumber,a.ArrestNumber,b.PersonName,b.FacilityName,b.Status,b.RequestedBy,b.RequestedAt,b.ConfirmedAt FROM JailBookings b LEFT JOIN ArrestRecords a ON a.Id=b.ArrestId ORDER BY b.RequestedAt DESC LIMIT 300";var rows=new List<string>();await using var r=await cmd.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<tr><td><a href='/jail-bookings/{r.GetString(0)}'><b>{H(r.GetString(1))}</b></a></td><td>{H(N(r,2))}</td><td>{H(r.GetString(3))}</td><td>{H(r.GetString(4))}</td><td><span class='status'>{H(r.GetString(5))}</span></td><td>{H(r.GetString(6))}<small>{H(r.GetString(7))}</small></td><td>{H(N(r,8))}</td></tr>");return Html(Page("Jail bookings",$"<main class='wrap'><a class='back' href='/'>← Work queue</a><section class='page-head'><div><span class='eyebrow'>POLICE · JAIL BOOKING</span><h1>Jail bookings</h1><p>Send arrest booking packets to configured county-jail facilities and track intake confirmation.</p></div><a class='button' href='/jail-bookings/new'>New booking</a></section><section class='table-card'><table><thead><tr><th>Booking</th><th>Arrest</th><th>Person</th><th>Facility</th><th>Status</th><th>Requested</th><th>Confirmed</th></tr></thead><tbody>{(rows.Count>0?string.Join("",rows):"<tr><td colspan='7'>No bookings.</td></tr>")}</tbody></table></section></main>"));
        }).RequireAuthorization();

        app.MapGet("/jail-bookings/new",async(HttpContext ctx,IAntiforgery anti,Guid? arrestId)=>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();var t=anti.GetAndStoreTokens(ctx).RequestToken!;var arrests=await ArrestOptions(dbPath,arrestId);var facilities=await FacilityOptions(dbPath);return Html(Page("New jail booking",$"""<main class='wrap'><a class='back' href='/jail-bookings'>← Jail bookings</a><section class='card'><span class='eyebrow'>POLICE · BOOK INTO JAIL</span><h1>Create booking packet</h1><div class='notice'><b>Custody record</b><p>This records a booking request for an arrest already made. Jail acceptance is completed by an authorized county-jail partner.</p></div><form method='post' action='/jail-bookings'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><label>Arrest record<select name='arrestId' required><option value=''>Select arrest</option>{arrests}</select></label><label>Receiving jail facility<select name='facilityId' required><option value=''>Select facility</option>{facilities}</select></label><h2>Transport & intake</h2><label>Transporting officer / unit<input name='transportUnit'/></label><label>Estimated arrival<input type='datetime-local' name='estimatedArrival'/></label><label>Property inventory<textarea name='propertyInventory' rows='4'></textarea></label><label>Cash / valuables<textarea name='valuables' rows='3'></textarea></label><label>Required booking documents / process references<textarea name='documents' rows='4' placeholder='Warrant, commitment order, charging documents, citation/process references'></textarea></label><label>Officer intake notes<textarea name='officerNotes' rows='4'></textarea></label><button>Send booking request</button></form></section></main>"""));
        }).RequireAuthorization();

        app.MapPost("/jail-bookings",async(HttpContext ctx,IAntiforgery anti)=>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();if(!Guid.TryParse(f["arrestId"],out var arrestId)||!Guid.TryParse(f["facilityId"],out var facilityId))return Results.BadRequest("Arrest and facility are required.");var arrest=await LoadArrest(dbPath,arrestId);var facility=await LoadFacility(dbPath,facilityId);if(arrest is null||facility is null||!facility.Value.Active)return Results.BadRequest("Valid arrest and active facility are required.");var id=Guid.NewGuid();var now=Now();await Exec(dbPath,"""INSERT INTO JailBookings(Id,BookingNumber,ArrestId,IncidentNumber,PersonName,DateOfBirth,LicenseId,Address,Charges,LegalBasis,WarrantReference,ArrestingOfficer,ArrestedAt,ArrestLocation,FacilityId,FacilityName,FacilityAddress,Status,TransportUnit,EstimatedArrival,PropertyInventory,Valuables,Documents,OfficerNotes,RequestedBy,RequestedAt,UpdatedAt) VALUES($i,$n,$a,$inc,$p,$dob,$dl,$addr,$ch,$legal,$w,$ao,$at,$loc,$fid,$fn,$fa,'Requested',$unit,$eta,$prop,$val,$docs,$notes,$by,$t,$t)""",("$i",id),("$n",$"JBK-{DateTime.UtcNow:yyMMdd}-{Random.Shared.Next(100000,999999)}"),("$a",arrestId),("$inc",arrest.Value.Incident),("$p",arrest.Value.Name),("$dob",arrest.Value.Dob),("$dl",arrest.Value.License),("$addr",arrest.Value.Address),("$ch",arrest.Value.Charges),("$legal",arrest.Value.LegalBasis),("$w",arrest.Value.Warrant),("$ao",arrest.Value.Officer),("$at",arrest.Value.ArrestedAt),("$loc",arrest.Value.Location),("$fid",facilityId),("$fn",facility.Value.Name),("$fa",facility.Value.Address),("$unit",f["transportUnit"]),("$eta",f["estimatedArrival"]),("$prop",f["propertyInventory"]),("$val",f["valuables"]),("$docs",f["documents"]),("$notes",f["officerNotes"]),("$by",ctx.User.Identity?.Name??"officer"),("$t",now));await Exec(dbPath,"UPDATE ArrestRecords SET BookingDestination=$d,CustodyDisposition='Booking requested',UpdatedAt=$t WHERE Id=$id",("$d",facility.Value.Name),("$t",now),("$id",arrestId));await Hist(dbPath,id,ctx.User.Identity?.Name??"officer","Requested",$"Booking sent to {facility.Value.Name}");return Results.Redirect($"/jail-bookings/{id}");
        }).RequireAuthorization();

        app.MapGet("/jail-bookings/{id:guid}",async(Guid id,HttpContext ctx)=>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();var b=await LoadBooking(dbPath,id);if(b is null)return Results.NotFound();var hist=await History(dbPath,id);return Html(Page(b.Value.Number,$"<main class='wrap'><a class='back' href='/jail-bookings'>← Jail bookings</a><section class='page-head'><div><span class='eyebrow'>JAIL BOOKING · {H(b.Value.Status)}</span><h1>{H(b.Value.Number)}</h1><p>{H(b.Value.Person)} · {H(b.Value.Facility)}</p></div></section><div class='detail-grid'><section class='card'><dl><dt>Incident</dt><dd>{H(b.Value.Incident)}</dd><dt>DOB</dt><dd>{H(b.Value.Dob)}</dd><dt>License / ID</dt><dd>{H(b.Value.License)}</dd><dt>Arresting officer</dt><dd>{H(b.Value.ArrestingOfficer)}</dd><dt>Arrested</dt><dd>{H(b.Value.ArrestedAt)}</dd><dt>Arrest location</dt><dd>{H(b.Value.ArrestLocation)}</dd><dt>Facility</dt><dd>{H(b.Value.Facility)} · {H(b.Value.FacilityAddress)}</dd><dt>County booking #</dt><dd>{H(b.Value.JailBookingNumber)}</dd><dt>Confirmed by</dt><dd>{H(b.Value.ConfirmedBy)}</dd><dt>Confirmed at</dt><dd>{H(b.Value.ConfirmedAt)}</dd></dl><h2>Charges</h2><p style='white-space:pre-wrap'>{H(b.Value.Charges)}</p><h2>Property inventory</h2><p>{H(b.Value.Property)}</p><h2>Documents</h2><p>{H(b.Value.Documents)}</p><h2>Jail intake disposition</h2><p>{H(b.Value.JailNotes)}</p></section><aside><section class='card'><h2>History</h2>{hist}</section></aside></div></main>"));
        }).RequireAuthorization();
    }

    private static async Task<string> ArrestOptions(string p,Guid? selected){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Id,ArrestNumber,PersonName,IncidentNumber FROM ArrestRecords ORDER BY ArrestedAt DESC LIMIT 300";var list=new List<string>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync()){var id=r.GetString(0);list.Add($"<option value='{H(id)}' {(selected?.ToString()==id?"selected":"")}>{H(r.GetString(1))} · {H(r.GetString(2))} · {H(r.GetString(3))}</option>");}return string.Join("",list);}
    private static async Task<string> FacilityOptions(string p){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Id,Name,Address FROM JailFacilities WHERE Active=1 ORDER BY Name";var list=new List<string>();try{await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync())list.Add($"<option value='{H(r.GetString(0))}'>{H(r.GetString(1))} · {H(r.GetString(2))}</option>");}catch(SqliteException){}return string.Join("",list);}
    private static async Task<(string Incident,string Name,string? Dob,string? License,string? Address,string Charges,string LegalBasis,string? Warrant,string Officer,string ArrestedAt,string Location)?> LoadArrest(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT IncidentNumber,PersonName,DateOfBirth,LicenseId,Address,Charges,LegalBasis,WarrantReference,ArrestingOfficer,ArrestedAt,ArrestLocation FROM ArrestRecords WHERE Id=$id";c.Parameters.AddWithValue("$id",id.ToString());await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?(r.GetString(0),r.GetString(1),N(r,2),N(r,3),N(r,4),r.GetString(5),r.GetString(6),N(r,7),r.GetString(8),r.GetString(9),r.GetString(10)):null;}
    private static async Task<(string Name,string Address,bool Active)?> LoadFacility(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Name,Address,Active FROM JailFacilities WHERE Id=$id";c.Parameters.AddWithValue("$id",id.ToString());await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?(r.GetString(0),r.GetString(1),r.GetInt64(2)==1):null;}
    private static async Task<(string Number,string Status,string Person,string Incident,string? Dob,string? License,string Charges,string ArrestingOfficer,string ArrestedAt,string ArrestLocation,string Facility,string FacilityAddress,string? JailBookingNumber,string? ConfirmedBy,string? ConfirmedAt,string? Property,string? Documents,string? JailNotes)?> LoadBooking(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT BookingNumber,Status,PersonName,IncidentNumber,DateOfBirth,LicenseId,Charges,ArrestingOfficer,ArrestedAt,ArrestLocation,FacilityName,FacilityAddress,JailBookingNumber,ConfirmedBy,ConfirmedAt,PropertyInventory,Documents,JailIntakeNotes FROM JailBookings WHERE Id=$id";c.Parameters.AddWithValue("$id",id.ToString());await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?(r.GetString(0),r.GetString(1),r.GetString(2),r.GetString(3),N(r,4),N(r,5),r.GetString(6),r.GetString(7),r.GetString(8),r.GetString(9),r.GetString(10),r.GetString(11),N(r,12),N(r,13),N(r,14),N(r,15),N(r,16),N(r,17)):null;}
    private static async Task Hist(string p,Guid id,string actor,string action,string detail)=>await Exec(p,"INSERT INTO JailBookingHistory(Id,BookingId,Actor,Action,Detail,OccurredAt) VALUES($i,$b,$a,$x,$d,$t)",("$i",Guid.NewGuid()),("$b",id),("$a",actor),("$x",action),("$d",detail),("$t",Now()));
    private static async Task<string> History(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Actor,Action,Detail,OccurredAt FROM JailBookingHistory WHERE BookingId=$b ORDER BY OccurredAt DESC";c.Parameters.AddWithValue("$b",id.ToString());var rows=new List<string>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<article><b>{H(r.GetString(1))}</b><small>{H(r.GetString(0))} · {H(r.GetString(3))}</small><p>{H(r.GetString(2))}</p></article>");return rows.Count==0?"<p class='muted'>No history.</p>":string.Join("",rows);}
    private static async Task Exec(string p,string sql,params(string Key,object? Value)[] ps){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText=sql;foreach(var x in ps)c.Parameters.AddWithValue(x.Key,x.Value?.ToString()??"");await c.ExecuteNonQueryAsync();}
    private static void EnsureSchema(string p){using var cn=Open(p);cn.Open();using var c=cn.CreateCommand();c.CommandText="""CREATE TABLE IF NOT EXISTS JailBookings(Id TEXT PRIMARY KEY,BookingNumber TEXT NOT NULL UNIQUE,ArrestId TEXT NOT NULL,IncidentNumber TEXT NOT NULL,PersonName TEXT NOT NULL,DateOfBirth TEXT NULL,LicenseId TEXT NULL,Address TEXT NULL,Charges TEXT NOT NULL,LegalBasis TEXT NOT NULL,WarrantReference TEXT NULL,ArrestingOfficer TEXT NOT NULL,ArrestedAt TEXT NOT NULL,ArrestLocation TEXT NOT NULL,FacilityId TEXT NOT NULL,FacilityName TEXT NOT NULL,FacilityAddress TEXT NOT NULL,Status TEXT NOT NULL,TransportUnit TEXT NULL,EstimatedArrival TEXT NULL,PropertyInventory TEXT NULL,Valuables TEXT NULL,Documents TEXT NULL,OfficerNotes TEXT NULL,JailBookingNumber TEXT NULL,JailIntakeNotes TEXT NULL,HousingAssignment TEXT NULL,IntakeOfficer TEXT NULL,ConfirmedBy TEXT NULL,ConfirmedAt TEXT NULL,RejectedReason TEXT NULL,RequestedBy TEXT NOT NULL,RequestedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL);CREATE TABLE IF NOT EXISTS JailBookingHistory(Id TEXT PRIMARY KEY,BookingId TEXT NOT NULL,Actor TEXT NOT NULL,Action TEXT NOT NULL,Detail TEXT NOT NULL,OccurredAt TEXT NOT NULL);CREATE TABLE IF NOT EXISTS JailFacilities(Id TEXT PRIMARY KEY,Name TEXT NOT NULL,Address TEXT NOT NULL,Phone TEXT NULL,BookingDeskEmail TEXT NULL,Active INTEGER NOT NULL,IntakeInstructions TEXT NULL,RequiredDocuments TEXT NULL,CreatedBy TEXT NOT NULL,CreatedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL);CREATE INDEX IF NOT EXISTS IX_JailBookings_Status ON JailBookings(Status);CREATE INDEX IF NOT EXISTS IX_JailBookings_Arrest ON JailBookings(ArrestId);""";c.ExecuteNonQuery();}
    private static SqliteConnection Open(string p)=>new($"Data Source={p}");private static string Now()=>DateTimeOffset.UtcNow.ToString("O");private static string? N(SqliteDataReader r,int i)=>r.IsDBNull(i)?null:r.GetString(i);private static bool CanPolice(ClaimsPrincipal u)=>u.IsInRole("Administrator")||u.IsInRole("Supervisor")||u.FindAll(DepartmentAccess.ClaimType).Any(c=>string.Equals(c.Value,"Police",StringComparison.OrdinalIgnoreCase));private static string H(string? s)=>WebUtility.HtmlEncode(s??"");private static IResult Html(string s)=>Results.Content(s,"text/html; charset=utf-8");private static string Page(string t,string b)=>$"<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>{H(t)} · CLT++ Employee</title><link rel='stylesheet' href='/app.css'></head><body><header class='top'><a href='/' class='brand'>CLT<span>++</span> <small>EMPLOYEE</small></a><div>County jail booking</div></header>{b}</body></html>";
}
