using System.Net;
using System.Security.Claims;
using System.Text;
using System.Text.Json;
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.Data.Sqlite;

namespace CltPlusPlus.Employee;

public static class PoliceCallChimeBridge
{
    public static void Map(WebApplication app)
    {
        var dbPath=app.Configuration["CLTPP_PUBLIC_SAFETY_DB"]??Path.Combine(AppContext.BaseDirectory,"data","public-safety.db");
        Directory.CreateDirectory(Path.GetDirectoryName(dbPath)!);Ensure(dbPath);

        app.MapGet("/police-calls/{callId:guid}/chime",async(Guid callId,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();var call=await LoadCall(dbPath,callId);if(call is null)return Results.NotFound();
            if(string.IsNullOrWhiteSpace(call.Value.Phone))return Results.BadRequest("This intake does not have a caller phone number.");
            var token=anti.GetAndStoreTokens(ctx).RequestToken!;var previous=await Sessions(dbPath,callId);
            return Html(Page("Chime call",$"""<main class='wrap'><a class='back' href='/police-calls/{callId}'>← Call intake</a><section class='page-head'><div><span class='eyebrow'>AMAZON CHIME SDK · PSTN</span><h1>{H(call.Value.Number)}</h1><p>Call {H(call.Value.Phone)} from the officer's browser microphone.</p></div></section><div class='notice'><b>Recorded call notice</b><p>The phone leg must hear an audible recording disclosure before recording starts. The officer also sees an on-screen recording indicator. Do not use this workflow for covert recording.</p></div><section class='card'><form method='post' action='/police-calls/{callId}/chime/start'><input type='hidden' name='__RequestVerificationToken' value='{H(token)}'/><label>Destination phone<input value='{H(call.Value.Phone)}' disabled/></label><label>Call purpose<textarea name='purpose' rows='4' required>{H(call.Value.Type)} intake follow-up</textarea></label><button>Start recorded Chime call</button></form></section><section class='card'><h2>Prior Chime calls</h2>{previous}</section></main>"""));
        }).RequireAuthorization();

        app.MapPost("/police-calls/{callId:guid}/chime/start",async(Guid callId,HttpContext ctx,IAntiforgery anti,IHttpClientFactory factory)=>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var call=await LoadCall(dbPath,callId);if(call is null)return Results.NotFound();var phone=(call.Value.Phone??"").Trim();if(string.IsNullOrWhiteSpace(phone))return Results.BadRequest("Caller phone number is required before a Chime call can start.");
            var form=await ctx.Request.ReadFormAsync();var purpose=form["purpose"].ToString().Trim();if(purpose.Length==0)return Results.BadRequest("Purpose is required.");
            var endpoint=app.Configuration["CLTPP_CHIME_POLICE_CALL_API_URL"];if(string.IsNullOrWhiteSpace(endpoint))return Results.BadRequest("Amazon Chime police-call integration is not configured (CLTPP_CHIME_POLICE_CALL_API_URL).");
            var id=Guid.NewGuid();var callbackSecret=Guid.NewGuid().ToString("N")+Guid.NewGuid().ToString("N");var callback=$"{ctx.Request.Scheme}://{ctx.Request.Host}/integrations/chime/police-calls/{id}/status?secret={Uri.EscapeDataString(callbackSecret)}";
            var body=new{referenceId=id.ToString(),policeCallId=callId.ToString(),destinationPhone=phone,fromPhone=app.Configuration["CLTPP_CHIME_FROM_PHONE_NUMBER"],sipMediaApplicationId=app.Configuration["CLTPP_CHIME_SIP_MEDIA_APPLICATION_ID"],mediaRegion=app.Configuration["CLTPP_CHIME_MEDIA_REGION"]??"us-east-1",record=true,recordingS3Bucket=app.Configuration["CLTPP_CHIME_RECORDING_S3_BUCKET"],recordingDisclosure=true,disclosureText="This call is being recorded for police call intake and report documentation.",officerExternalUserId=ctx.User.Identity?.Name??"officer",purpose,callbackUrl=callback};
            var client=factory.CreateClient();using var request=new HttpRequestMessage(HttpMethod.Post,endpoint);var apiKey=app.Configuration["CLTPP_CHIME_POLICE_CALL_API_KEY"];if(!string.IsNullOrWhiteSpace(apiKey))request.Headers.TryAddWithoutValidation("X-Api-Key",apiKey);request.Content=new StringContent(JsonSerializer.Serialize(body),Encoding.UTF8,"application/json");using var response=await client.SendAsync(request);var text=await response.Content.ReadAsStringAsync();if(!response.IsSuccessStatusCode)return Results.BadRequest($"Amazon Chime integration rejected the call: {(int)response.StatusCode} {response.StatusCode}.");
            ChimeStart? start;try{start=JsonSerializer.Deserialize<ChimeStart>(text,new JsonSerializerOptions{PropertyNameCaseInsensitive=true});}catch{return Results.BadRequest("Amazon Chime integration returned invalid JSON.");}if(start is null||string.IsNullOrWhiteSpace(start.MeetingId)||string.IsNullOrWhiteSpace(start.AttendeeId)||string.IsNullOrWhiteSpace(start.JoinToken))return Results.BadRequest("Amazon Chime integration did not return meeting/attendee credentials.");
            var now=Now();await Exec(dbPath,"""INSERT INTO PoliceCallChimeSessions(Id,PoliceCallId,OfficerUsername,DestinationPhone,Purpose,Status,ChimeMeetingId,MediaRegion,OfficerAttendeeId,OfficerJoinToken,SipMediaApplicationCallId,RecordingStatus,RecordingReference,CallbackSecret,CreatedAt,UpdatedAt) VALUES($i,$c,$o,$p,$purpose,'Connecting',$m,$r,$a,$j,$sip,$rs,$rr,$secret,$t,$t)""",("$i",id),("$c",callId),("$o",ctx.User.Identity?.Name??"officer"),("$p",phone),("$purpose",purpose),("$m",start.MeetingId),("$r",start.MediaRegion??"us-east-1"),("$a",start.AttendeeId),("$j",start.JoinToken),("$sip",start.SipMediaApplicationCallId),("$rs",start.RecordingStatus??"Requested"),("$rr",start.RecordingReference),("$secret",callbackSecret),("$t",now));await Hist(dbPath,callId,ctx.User.Identity?.Name??"officer","Chime call started",$"Session {id}; PSTN {phone}");return Results.Redirect($"/police-call-chime/{id}");
        }).RequireAuthorization();

        app.MapGet("/police-call-chime/{id:guid}",async(Guid id,HttpContext ctx)=>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();var s=await LoadSession(dbPath,id);if(s is null)return Results.NotFound();if(!string.Equals(s.Value.Officer,ctx.User.Identity?.Name,StringComparison.OrdinalIgnoreCase)&&!ctx.User.IsInRole("Supervisor")&&!ctx.User.IsInRole("Administrator"))return Results.Forbid();
            return Html(Page("Active Chime call",$"""<main class='wrap'><a class='back' href='/police-calls/{s.Value.CallId}'>← Call intake</a><section class='page-head'><div><span class='eyebrow'>AMAZON CHIME SDK · {H(s.Value.Status)}</span><h1>Recorded call to {H(s.Value.Phone)}</h1><p>{H(s.Value.Purpose)}</p></div></section><div class='notice'><b>Recording active/requested</b><p>The PSTN participant must receive the configured audible disclosure before recording. Recording status: {H(s.Value.RecordingStatus)}.</p></div><section class='card'><div id='chime-audio'><button id='join-call'>Enable microphone & join call</button><button id='leave-call' disabled>Leave call</button><p id='chime-status'>Microphone is not connected yet.</p><audio id='remote-audio' autoplay></audio></div></section><section class='card'><dl><dt>Chime meeting</dt><dd>{H(s.Value.MeetingId)}</dd><dt>SIP media call</dt><dd>{H(s.Value.SipCallId)}</dd><dt>Recording</dt><dd>{H(s.Value.RecordingReference)}</dd></dl></section><script>window.CLT_CHIME_CALL={JsonSerializer.Serialize(new{meetingId=s.Value.MeetingId,mediaRegion=s.Value.MediaRegion,attendeeId=s.Value.AttendeeId,joinToken=s.Value.JoinToken})};</script><script type='module' src='/police-chime-call.js'></script></main>"""));
        }).RequireAuthorization();

        app.MapPost("/integrations/chime/police-calls/{id:guid}/status",async(Guid id,HttpContext ctx,string secret)=>
        {
            var s=await LoadSession(dbPath,id);if(s is null||!string.Equals(secret,s.Value.CallbackSecret,StringComparison.Ordinal))return Results.Unauthorized();ChimeStatus? update;try{update=await JsonSerializer.DeserializeAsync<ChimeStatus>(ctx.Request.Body,new JsonSerializerOptions{PropertyNameCaseInsensitive=true});}catch{return Results.BadRequest();}if(update is null)return Results.BadRequest();await Exec(dbPath,"UPDATE PoliceCallChimeSessions SET Status=COALESCE(NULLIF($s,''),Status),SipMediaApplicationCallId=COALESCE(NULLIF($sip,''),SipMediaApplicationCallId),RecordingStatus=COALESCE(NULLIF($rs,''),RecordingStatus),RecordingReference=COALESCE(NULLIF($rr,''),RecordingReference),StartedAt=COALESCE(NULLIF($st,''),StartedAt),EndedAt=COALESCE(NULLIF($en,''),EndedAt),DurationSeconds=CASE WHEN $dur='' THEN DurationSeconds ELSE $dur END,UpdatedAt=$t WHERE Id=$i",("$s",update.Status),("$sip",update.SipMediaApplicationCallId),("$rs",update.RecordingStatus),("$rr",update.RecordingReference),("$st",update.StartedAt),("$en",update.EndedAt),("$dur",update.DurationSeconds?.ToString()),("$t",Now()),("$i",id));return Results.Ok();
        });
    }

    private sealed record ChimeStart(string? MeetingId,string? MediaRegion,string? AttendeeId,string? JoinToken,string? SipMediaApplicationCallId,string? RecordingStatus,string? RecordingReference);
    private sealed record ChimeStatus(string? Status,string? SipMediaApplicationCallId,string? RecordingStatus,string? RecordingReference,string? StartedAt,string? EndedAt,int? DurationSeconds);
    private sealed record Session(Guid Id,Guid CallId,string Officer,string Phone,string Purpose,string Status,string MeetingId,string MediaRegion,string AttendeeId,string JoinToken,string? SipCallId,string RecordingStatus,string? RecordingReference,string CallbackSecret);
    static async Task<(string Number,string Type,string? Phone)?> LoadCall(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT CallNumber,CallType,CallerPhone FROM PoliceCalls WHERE Id=$i";c.Parameters.AddWithValue("$i",id.ToString());await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?(r.GetString(0),r.GetString(1),N(r,2)):null;}
    static async Task<Session?> LoadSession(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Id,PoliceCallId,OfficerUsername,DestinationPhone,Purpose,Status,ChimeMeetingId,MediaRegion,OfficerAttendeeId,OfficerJoinToken,SipMediaApplicationCallId,RecordingStatus,RecordingReference,CallbackSecret FROM PoliceCallChimeSessions WHERE Id=$i";c.Parameters.AddWithValue("$i",id.ToString());await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?new(Guid.Parse(r.GetString(0)),Guid.Parse(r.GetString(1)),r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5),r.GetString(6),r.GetString(7),r.GetString(8),r.GetString(9),N(r,10),r.GetString(11),N(r,12),r.GetString(13)):null;}
    static async Task<string> Sessions(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Id,DestinationPhone,Status,RecordingStatus,CreatedAt,DurationSeconds FROM PoliceCallChimeSessions WHERE PoliceCallId=$i ORDER BY CreatedAt DESC";c.Parameters.AddWithValue("$i",id.ToString());var rows=new List<string>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<article><a href='/police-call-chime/{r.GetString(0)}'><b>{H(r.GetString(1))}</b></a><small>{H(r.GetString(2))} · recording {H(r.GetString(3))} · {H(r.GetString(4))}</small><p>{H(N(r,5))} seconds</p></article>");return rows.Count==0?"<p>No Chime calls yet.</p>":string.Join("",rows);}
    static async Task Hist(string p,Guid id,string actor,string action,string detail)=>await Exec(p,"INSERT INTO PoliceCallHistory(Id,PoliceCallId,Actor,Action,Detail,OccurredAt) VALUES($i,$c,$a,$x,$d,$t)",("$i",Guid.NewGuid()),("$c",id),("$a",actor),("$x",action),("$d",detail),("$t",Now()));
    static void Ensure(string p){using var cn=Open(p);cn.Open();var c=cn.CreateCommand();c.CommandText="CREATE TABLE IF NOT EXISTS PoliceCallChimeSessions(Id TEXT PRIMARY KEY,PoliceCallId TEXT NOT NULL,OfficerUsername TEXT NOT NULL,DestinationPhone TEXT NOT NULL,Purpose TEXT NOT NULL,Status TEXT NOT NULL,ChimeMeetingId TEXT NOT NULL,MediaRegion TEXT NOT NULL,OfficerAttendeeId TEXT NOT NULL,OfficerJoinToken TEXT NOT NULL,SipMediaApplicationCallId TEXT,RecordingStatus TEXT NOT NULL,RecordingReference TEXT,CallbackSecret TEXT NOT NULL,StartedAt TEXT,EndedAt TEXT,DurationSeconds INTEGER,CreatedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL);CREATE INDEX IF NOT EXISTS IX_PoliceCallChimeSessions_Call ON PoliceCallChimeSessions(PoliceCallId,CreatedAt);";c.ExecuteNonQuery();}
    static bool CanPolice(ClaimsPrincipal u)=>u.IsInRole("Administrator")||u.IsInRole("Supervisor")||u.Claims.Any(c=>c.Type==DepartmentAccess.ClaimType&&string.Equals(c.Value,"Police",StringComparison.OrdinalIgnoreCase));static SqliteConnection Open(string p)=>new($"Data Source={p}");static async Task Exec(string p,string sql,params(string,object?)[] ps){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText=sql;foreach(var x in ps)c.Parameters.AddWithValue(x.Item1,x.Item2?.ToString()??"");await c.ExecuteNonQueryAsync();}static string? N(SqliteDataReader r,int i)=>r.IsDBNull(i)?null:r.GetValue(i).ToString();static string Now()=>DateTimeOffset.UtcNow.ToString("O");static string H(object? x)=>WebUtility.HtmlEncode(x?.ToString()??"");static IResult Html(string x)=>Results.Content(x,"text/html; charset=utf-8");static string Page(string t,string b)=>$"<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width'><title>{H(t)} · CLT++ Employee</title><link rel='stylesheet' href='/app.css'></head><body>{b}</body></html>";
}
