using System.Net;
using System.Security.Claims;
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.Data.Sqlite;

namespace CltPlusPlus.Employee;

public static class PoliceCallAssignments
{
    public static void Map(WebApplication app)
    {
        var dbPath=app.Configuration["CLTPP_PUBLIC_SAFETY_DB"]??Path.Combine(AppContext.BaseDirectory,"data","public-safety.db");
        Directory.CreateDirectory(Path.GetDirectoryName(dbPath)!); Ensure(dbPath);

        app.MapGet("/police-call-assignment",async(HttpContext ctx,IAntiforgery anti)=>
        {
            if(!CanPolice(ctx.User)) return Results.Forbid();
            await using var cn=Open(dbPath); await cn.OpenAsync();
            var c=cn.CreateCommand();
            c.CommandText="SELECT c.Id,c.CallNumber,c.CallType,c.Location,c.Status,COALESCE((SELECT group_concat(a.OfficerKey || ' (' || a.Status || ')', ', ') FROM PoliceCallOfficerAssignments a WHERE a.PoliceCallId=c.Id AND a.Status<>'Cleared'),'') FROM PoliceCalls c WHERE c.Status<>'Closed' ORDER BY c.CreatedAt";
            var rows=new List<string>(); await using var r=await c.ExecuteReaderAsync();
            while(await r.ReadAsync()) rows.Add($"<tr><td>{H(r.GetString(1))}</td><td>{H(r.GetString(2))}</td><td>{H(r.GetString(3))}</td><td>{H(r.GetString(4))}</td><td>{H(r.GetString(5))}</td><td><a class='button' href='/police-call-assignment/{H(r.GetString(0))}'>Add officer</a></td></tr>");
            return Html(Page("Call assignment",$"<main class='wrap'><section class='page-head'><div><span class='eyebrow'>POLICE · DISPATCH</span><h1>Assign calls</h1><p>Multiple approved on-duty officers can be assigned to the same call independently.</p></div><a class='button' href='/officer-status/roster'>Officer roster</a></section><section class='table-card'><table><thead><tr><th>Call</th><th>Type</th><th>Location</th><th>Overall status</th><th>Officer assignments</th><th></th></tr></thead><tbody>{string.Join("",rows)}</tbody></table></section></main>"));
        }).RequireAuthorization();

        app.MapGet("/police-call-assignment/{id:guid}",async(Guid id,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!CanPolice(ctx.User)) return Results.Forbid(); var token=anti.GetAndStoreTokens(ctx).RequestToken!;
            await using var cn=Open(dbPath); await cn.OpenAsync();
            var c=cn.CreateCommand(); c.CommandText="SELECT CallNumber,CallType,Location FROM PoliceCalls WHERE Id=$i"; c.Parameters.AddWithValue("$i",id.ToString());
            await using var r=await c.ExecuteReaderAsync(); if(!await r.ReadAsync()) return Results.NotFound(); var num=r.GetString(0);var type=r.GetString(1);var loc=r.GetString(2); await r.DisposeAsync();
            var opts=await OfficerOptions(cn,id); var assigned=await AssignmentTable(cn,id);
            return Html(Page("Assign call",$"<main class='wrap'><a href='/police-call-assignment'>← Calls</a><section class='card'><span class='eyebrow'>POLICE · DISPATCH</span><h1>{H(num)}</h1><p>{H(type)} · {H(loc)}</p><form method='post' action='/police-call-assignment/{id}'><input type='hidden' name='__RequestVerificationToken' value='{H(token)}'/><label>Add approved on-duty officer<select name='officer' required><option value=''>Select officer</option>{opts}</select></label><button>Add to officer queue</button></form></section><section class='card'><h2>Assigned officers</h2>{assigned}</section></main>"));
        }).RequireAuthorization();

        app.MapPost("/police-call-assignment/{id:guid}",async(Guid id,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!CanPolice(ctx.User)) return Results.Forbid(); await anti.ValidateRequestAsync(ctx); var f=await ctx.Request.ReadFormAsync(); var officer=f["officer"].ToString().Trim(); if(officer.Length==0)return Results.BadRequest("Officer required.");
            await using var cn=Open(dbPath); await cn.OpenAsync(); if(!await IsOnDuty(cn,officer)) return Results.BadRequest("Calls can only be assigned to an approved on-duty officer queue.");
            var exists=cn.CreateCommand();exists.CommandText="SELECT COUNT(1) FROM PoliceCallOfficerAssignments WHERE PoliceCallId=$i AND OfficerKey=$o AND Status<>'Cleared'";exists.Parameters.AddWithValue("$i",id.ToString());exists.Parameters.AddWithValue("$o",officer);if(Convert.ToInt32(await exists.ExecuteScalarAsync())>0)return Results.BadRequest("That officer is already actively assigned to this call.");
            using var tx=cn.BeginTransaction(); var now=Now();
            var ins=cn.CreateCommand();ins.Transaction=tx;ins.CommandText="INSERT INTO PoliceCallOfficerAssignments(Id,PoliceCallId,OfficerKey,Status,AssignedBy,AssignedAt,UpdatedAt) SELECT $x,$i,$o,'Queued',$b,$t,$t WHERE EXISTS(SELECT 1 FROM PoliceCalls WHERE Id=$i AND Status<>'Closed')";ins.Parameters.AddWithValue("$x",Guid.NewGuid().ToString());ins.Parameters.AddWithValue("$i",id.ToString());ins.Parameters.AddWithValue("$o",officer);ins.Parameters.AddWithValue("$b",ctx.User.Identity?.Name??"dispatcher");ins.Parameters.AddWithValue("$t",now);if(await ins.ExecuteNonQueryAsync()!=1){tx.Rollback();return Results.NotFound();}
            await RecomputeCallStatus(cn,tx,id,now); await AddHistory(cn,tx,id,ctx.User.Identity?.Name??"dispatcher","Officer assigned","Added approved on-duty officer to call: "+officer,now); tx.Commit(); return Results.Redirect($"/police-call-assignment/{id}");
        }).RequireAuthorization();

        app.MapGet("/my-call-queue",async(HttpContext ctx,IAntiforgery anti)=>
        {
            if(!CanPolice(ctx.User)) return Results.Forbid(); var officer=OfficerKey(ctx.User); var token=anti.GetAndStoreTokens(ctx).RequestToken!;
            await using var cn=Open(dbPath);await cn.OpenAsync(); var onDuty=await IsOnDuty(cn,officer);
            var c=cn.CreateCommand();c.CommandText="SELECT c.Id,c.CallNumber,c.CallType,c.Priority,c.Location,a.Status,a.UpdatedAt FROM PoliceCallOfficerAssignments a JOIN PoliceCalls c ON c.Id=a.PoliceCallId WHERE a.OfficerKey=$o AND a.Status IN ('Queued','En route','On scene') AND c.Status<>'Closed' ORDER BY CASE a.Status WHEN 'En route' THEN 0 WHEN 'On scene' THEN 1 ELSE 2 END,a.UpdatedAt";c.Parameters.AddWithValue("$o",officer);
            var rows=new List<string>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync()){var id=r.GetString(0);var status=r.GetString(5);var action=status=="Queued"?$"<form method='post' action='/my-call-queue/{H(id)}/en-route'><input type='hidden' name='__RequestVerificationToken' value='{H(token)}'/><button {(onDuty?"":"disabled")}>Select call / En route</button></form>":status=="En route"?$"<form method='post' action='/my-call-queue/{H(id)}/on-scene'><input type='hidden' name='__RequestVerificationToken' value='{H(token)}'/><button {(onDuty?"":"disabled")}>Mark on scene</button></form>":"On scene";rows.Add($"<tr><td>{H(r.GetString(1))}</td><td>{H(r.GetString(2))}</td><td>{H(r.GetString(3))}</td><td>{H(r.GetString(4))}</td><td>{H(status)}</td><td>{action}</td></tr>");}
            return Html(Page("My call queue",$"<main class='wrap'><section class='page-head'><div><span class='eyebrow'>POLICE · OFFICER QUEUE</span><h1>My call queue</h1><p>{H(officer)} · {(onDuty?"Approved On Duty":"Not currently On Duty")}</p></div><a class='button' href='/officer-status'>My status</a></section><section class='table-card'><table><thead><tr><th>Call</th><th>Type</th><th>Priority</th><th>Location</th><th>My status</th><th>Action</th></tr></thead><tbody>{(rows.Count>0?string.Join("",rows):"<tr><td colspan='6'>No calls in your queue.</td></tr>")}</tbody></table></section></main>"));
        }).RequireAuthorization();

        app.MapPost("/my-call-queue/{id:guid}/en-route",async(Guid id,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var officer=OfficerKey(ctx.User);await using var cn=Open(dbPath);await cn.OpenAsync();if(!await IsOnDuty(cn,officer))return Results.BadRequest("You must have an approved On Duty status to select a call.");using var tx=cn.BeginTransaction();var now=Now();var c=cn.CreateCommand();c.Transaction=tx;c.CommandText="UPDATE PoliceCallOfficerAssignments SET Status='En route',EnRouteAt=$t,UpdatedAt=$t WHERE PoliceCallId=$i AND OfficerKey=$o AND Status='Queued'";c.Parameters.AddWithValue("$t",now);c.Parameters.AddWithValue("$i",id.ToString());c.Parameters.AddWithValue("$o",officer);if(await c.ExecuteNonQueryAsync()!=1){tx.Rollback();return Results.BadRequest("Call is not available in your queue.");}await SetOfficerStatus(cn,tx,officer,"En route",now);await RecomputeCallStatus(cn,tx,id,now);await AddHistory(cn,tx,id,officer,"En route",officer+" selected the call and is en route.",now);tx.Commit();return Results.Redirect("/my-call-queue");
        }).RequireAuthorization();

        app.MapPost("/my-call-queue/{id:guid}/on-scene",async(Guid id,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var officer=OfficerKey(ctx.User);await using var cn=Open(dbPath);await cn.OpenAsync();if(!await IsOnDuty(cn,officer))return Results.BadRequest("You must have an approved On Duty status.");using var tx=cn.BeginTransaction();var now=Now();var c=cn.CreateCommand();c.Transaction=tx;c.CommandText="UPDATE PoliceCallOfficerAssignments SET Status='On scene',OnSceneAt=$t,UpdatedAt=$t WHERE PoliceCallId=$i AND OfficerKey=$o AND Status='En route'";c.Parameters.AddWithValue("$t",now);c.Parameters.AddWithValue("$i",id.ToString());c.Parameters.AddWithValue("$o",officer);if(await c.ExecuteNonQueryAsync()!=1){tx.Rollback();return Results.BadRequest("Only your en-route assignment can be marked on scene.");}await SetOfficerStatus(cn,tx,officer,"On scene",now);await RecomputeCallStatus(cn,tx,id,now);await AddHistory(cn,tx,id,officer,"On scene",officer+" marked arrival on scene.",now);tx.Commit();return Results.Redirect("/my-call-queue");
        }).RequireAuthorization();
    }

    static async Task<string> OfficerOptions(SqliteConnection cn,Guid callId){var c=cn.CreateCommand();c.CommandText="SELECT s.OfficerKey,COALESCE(s.OperationalStatus,'Available') FROM OfficerDutyStatus s WHERE s.OnDuty=1 AND NOT EXISTS(SELECT 1 FROM PoliceCallOfficerAssignments a WHERE a.PoliceCallId=$i AND a.OfficerKey=s.OfficerKey AND a.Status<>'Cleared') ORDER BY CASE s.OperationalStatus WHEN 'Available' THEN 0 WHEN 'En route' THEN 1 WHEN 'On scene' THEN 2 ELSE 3 END,s.OfficerKey";c.Parameters.AddWithValue("$i",callId.ToString());var rows=new List<string>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<option value='{H(r.GetString(0))}'>{H(r.GetString(0))} · {H(r.GetString(1))}</option>");return string.Join("",rows);}
    static async Task<string> AssignmentTable(SqliteConnection cn,Guid callId){var c=cn.CreateCommand();c.CommandText="SELECT OfficerKey,Status,AssignedAt,COALESCE(EnRouteAt,''),COALESCE(OnSceneAt,'') FROM PoliceCallOfficerAssignments WHERE PoliceCallId=$i ORDER BY AssignedAt";c.Parameters.AddWithValue("$i",callId.ToString());var rows=new List<string>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<tr><td>{H(r.GetString(0))}</td><td>{H(r.GetString(1))}</td><td>{H(r.GetString(2))}</td><td>{H(r.GetString(3))}</td><td>{H(r.GetString(4))}</td></tr>");return rows.Count==0?"<p>No officers assigned.</p>":$"<table><thead><tr><th>Officer</th><th>Status</th><th>Assigned</th><th>En route</th><th>On scene</th></tr></thead><tbody>{string.Join("",rows)}</tbody></table>";}
    static async Task<bool> IsOnDuty(SqliteConnection cn,string officer){var c=cn.CreateCommand();c.CommandText="SELECT COUNT(1) FROM OfficerDutyStatus WHERE OfficerKey=$o AND OnDuty=1";c.Parameters.AddWithValue("$o",officer);return Convert.ToInt32(await c.ExecuteScalarAsync())==1;}
    static async Task SetOfficerStatus(SqliteConnection cn,SqliteTransaction tx,string officer,string status,string now){var c=cn.CreateCommand();c.Transaction=tx;c.CommandText="UPDATE OfficerDutyStatus SET OperationalStatus=$s,UpdatedAt=$t,UpdatedBy=$o WHERE OfficerKey=$o AND OnDuty=1";c.Parameters.AddWithValue("$s",status);c.Parameters.AddWithValue("$t",now);c.Parameters.AddWithValue("$o",officer);await c.ExecuteNonQueryAsync();var h=cn.CreateCommand();h.Transaction=tx;h.CommandText="INSERT INTO OfficerDutyStatusHistory(Id,OfficerKey,DutyState,OperationalStatus,ChangedBy,ChangedAt) VALUES($i,$o,'On duty',$s,$o,$t)";h.Parameters.AddWithValue("$i",Guid.NewGuid().ToString());h.Parameters.AddWithValue("$o",officer);h.Parameters.AddWithValue("$s",status);h.Parameters.AddWithValue("$t",now);await h.ExecuteNonQueryAsync();}
    static async Task RecomputeCallStatus(SqliteConnection cn,SqliteTransaction tx,Guid id,string now){var q=cn.CreateCommand();q.Transaction=tx;q.CommandText="SELECT CASE WHEN EXISTS(SELECT 1 FROM PoliceCallOfficerAssignments WHERE PoliceCallId=$i AND Status='On scene') THEN 'On scene' WHEN EXISTS(SELECT 1 FROM PoliceCallOfficerAssignments WHERE PoliceCallId=$i AND Status='En route') THEN 'En route' WHEN EXISTS(SELECT 1 FROM PoliceCallOfficerAssignments WHERE PoliceCallId=$i AND Status='Queued') THEN 'Queued' ELSE 'Open' END";q.Parameters.AddWithValue("$i",id.ToString());var status=(await q.ExecuteScalarAsync())?.ToString()??"Open";var u=cn.CreateCommand();u.Transaction=tx;u.CommandText="UPDATE PoliceCalls SET Status=$s,UpdatedAt=$t WHERE Id=$i AND Status<>'Closed'";u.Parameters.AddWithValue("$s",status);u.Parameters.AddWithValue("$t",now);u.Parameters.AddWithValue("$i",id.ToString());await u.ExecuteNonQueryAsync();}
    static async Task AddHistory(SqliteConnection cn,SqliteTransaction tx,Guid id,string actor,string action,string detail,string now){var h=cn.CreateCommand();h.Transaction=tx;h.CommandText="INSERT INTO PoliceCallHistory(Id,PoliceCallId,Actor,Action,Detail,OccurredAt) VALUES($x,$i,$a,$ac,$d,$t)";h.Parameters.AddWithValue("$x",Guid.NewGuid().ToString());h.Parameters.AddWithValue("$i",id.ToString());h.Parameters.AddWithValue("$a",actor);h.Parameters.AddWithValue("$ac",action);h.Parameters.AddWithValue("$d",detail);h.Parameters.AddWithValue("$t",now);await h.ExecuteNonQueryAsync();}
    static void Ensure(string p){using var cn=Open(p);cn.Open();var c=cn.CreateCommand();c.CommandText="CREATE TABLE IF NOT EXISTS PoliceCallOfficerAssignments(Id TEXT PRIMARY KEY,PoliceCallId TEXT NOT NULL,OfficerKey TEXT NOT NULL,Status TEXT NOT NULL,AssignedBy TEXT NOT NULL,AssignedAt TEXT NOT NULL,EnRouteAt TEXT,OnSceneAt TEXT,ClearedAt TEXT,UpdatedAt TEXT NOT NULL);CREATE UNIQUE INDEX IF NOT EXISTS IX_PoliceCallOfficerAssignments_Active ON PoliceCallOfficerAssignments(PoliceCallId,OfficerKey,Status);CREATE INDEX IF NOT EXISTS IX_PoliceCallOfficerAssignments_Officer ON PoliceCallOfficerAssignments(OfficerKey,Status,UpdatedAt);CREATE INDEX IF NOT EXISTS IX_PoliceCallOfficerAssignments_Call ON PoliceCallOfficerAssignments(PoliceCallId,Status);";c.ExecuteNonQuery();}
    static bool CanPolice(ClaimsPrincipal u)=>u.IsInRole("Administrator")||u.IsInRole("Supervisor")||u.Claims.Any(c=>c.Type==DepartmentAccess.ClaimType&&string.Equals(c.Value,"Police",StringComparison.OrdinalIgnoreCase));
    static string OfficerKey(ClaimsPrincipal u)=>u.FindFirstValue(ClaimTypes.Email)??u.Identity?.Name??"officer";
    static SqliteConnection Open(string p)=>new($"Data Source={p}"); static string Now()=>DateTimeOffset.UtcNow.ToString("O");static string H(object? x)=>WebUtility.HtmlEncode(x?.ToString()??"");static IResult Html(string x)=>Results.Content(x,"text/html; charset=utf-8");static string Page(string t,string b)=>$"<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width'><title>{H(t)} · CLT++ Employee</title><link rel='stylesheet' href='/app.css'></head><body>{b}</body></html>";
}
