using System.Net;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.Data.Sqlite;

namespace CltPlusPlus.Employee;

public static class PoliceFollowUpMeetings
{
    public static void Map(WebApplication app)
    {
        var dbPath=app.Configuration["CLTPP_PUBLIC_SAFETY_DB"]??Path.Combine(AppContext.BaseDirectory,"data","public-safety.db");
        Directory.CreateDirectory(Path.GetDirectoryName(dbPath)!);EnsureSchema(dbPath);

        app.MapGet("/follow-up-meetings/new",async(HttpContext ctx,IAntiforgery anti,Guid? expressReportId)=>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();
            var token=anti.GetAndStoreTokens(ctx).RequestToken!;var reports=await ReportOptions(dbPath,expressReportId);
            return Html(Page("New follow-up meeting",$"""<main class='wrap'><a class='back' href='/express-reports'>← Express reports</a><section class='card'><span class='eyebrow'>POLICE · VIRTUAL FOLLOW-UP</span><h1>Victim or suspect follow-up</h1><p>Create a Jitsi meeting tied to an Express Report and send an anonymous participant link by text message.</p><form method='post' action='/follow-up-meetings'><input type='hidden' name='__RequestVerificationToken' value='{H(token)}'/><label>Express Report<select name='expressReportId' required><option value=''>Select report</option>{reports}</select></label><label>Participant role<select name='participantRole'><option>Victim</option><option>Suspect</option></select></label><label>Participant name<input name='participantName' required/></label><label>Mobile phone<input name='phone' type='tel' required placeholder='+17045551212'/></label><label>Email (optional)<input name='email' type='email'/></label><label>Scheduled date/time<input name='scheduledAt' type='datetime-local'/></label><label>Meeting purpose<textarea name='purpose' rows='4' required></textarea></label><button>Create meeting</button></form></section></main>"""));
        }).RequireAuthorization();

        app.MapPost("/follow-up-meetings",async(HttpContext ctx,IAntiforgery anti)=>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();
            if(!Guid.TryParse(f["expressReportId"],out var reportId)||!await ReportExists(dbPath,reportId))return Results.BadRequest("Valid Express Report required.");
            var role=f["participantRole"].ToString();if(role is not ("Victim" or "Suspect"))return Results.BadRequest("Participant must be Victim or Suspect.");
            var name=f["participantName"].ToString().Trim();var phone=f["phone"].ToString().Trim();var purpose=f["purpose"].ToString().Trim();if(name.Length==0||phone.Length==0||purpose.Length==0)return Results.BadRequest("Participant name, mobile number, and purpose are required.");
            var id=Guid.NewGuid();var raw=Convert.ToHexString(RandomNumberGenerator.GetBytes(32)).ToLowerInvariant();var now=Now();
            await Exec(dbPath,"""INSERT INTO PoliceFollowUpMeetings(Id,ExpressReportId,ParticipantRole,ParticipantName,ParticipantEmail,ParticipantPhone,OfficerUsername,Status,ScheduledAt,Purpose,RoomName,InviteTokenHash,InviteStatus,RecordingStatus,CreatedAt,UpdatedAt) VALUES($i,$r,$role,$n,$e,$p,$o,'Scheduled',$at,$purpose,$room,$hash,'Not sent','Not started',$t,$t)""",("$i",id),("$r",reportId),("$role",role),("$n",name),("$e",f["email"]),("$p",phone),("$o",ctx.User.Identity?.Name??"officer"),("$at",f["scheduledAt"]),("$purpose",purpose),("$room",$"cltpp-police-followup-{id:N}"),("$hash",Hash(raw)),("$t",now));
            await Hist(dbPath,id,ctx.User.Identity?.Name??"officer","Created","Virtual follow-up meeting created.");
            return Results.Redirect($"/follow-up-meetings/{id}?invite={Uri.EscapeDataString(raw)}");
        }).RequireAuthorization();

        app.MapGet("/follow-up-meetings/{id:guid}",async(Guid id,HttpContext ctx,IAntiforgery anti,string? invite)=>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();var m=await Load(dbPath,id);if(m is null)return Results.NotFound();var token=anti.GetAndStoreTokens(ctx).RequestToken!;
            var link=string.IsNullOrWhiteSpace(invite)?"Hidden after creation; use Regenerate invite if needed.":$"{ctx.Request.Scheme}://{ctx.Request.Host}/follow-up/join/{id}?token={Uri.EscapeDataString(invite)}";
            var narrative=await Supplements(dbPath,m.Value.ExpressReportId,id);var history=await History(dbPath,id);
            return Html(Page("Follow-up meeting",$"""<main class='wrap'><a class='back' href='/express-reports/{m.Value.ExpressReportId}'>← Express Report</a><section class='page-head'><div><span class='eyebrow'>POLICE FOLLOW-UP · {H(m.Value.Status)}</span><h1>{H(m.Value.ReportNumber)}</h1><p>{H(m.Value.ParticipantRole)} · {H(m.Value.ParticipantName)}</p></div></section><div class='detail-grid'><section><section class='card'><dl><dt>Officer</dt><dd>{H(m.Value.Officer)}</dd><dt>Scheduled</dt><dd>{H(m.Value.ScheduledAt)}</dd><dt>Phone</dt><dd>{H(m.Value.Phone)}</dd><dt>Invite status</dt><dd>{H(m.Value.InviteStatus)}</dd><dt>Recording</dt><dd>{H(m.Value.RecordingStatus)} · {H(m.Value.RecordingReference)}</dd></dl><h2>Purpose</h2><p>{H(m.Value.Purpose)}</p><h3>Anonymous join link</h3><p style='overflow-wrap:anywhere'>{H(link)}</p><div class='notice'><b>Participant privacy</b><p>This anonymous link grants access only to this meeting. It does not expose the Express Report or other police data.</p></div></section><section class='card'><h2>Express Report supplements</h2>{narrative}</section></section><aside><section class='card'><h2>Invitation</h2><form method='post' action='/follow-up-meetings/{id}/send-sms'><input type='hidden' name='__RequestVerificationToken' value='{H(token)}'/><input type='hidden' name='inviteToken' value='{H(invite)}'/><button>Send text message with link</button></form><form method='post' action='/follow-up-meetings/{id}/regenerate'><input type='hidden' name='__RequestVerificationToken' value='{H(token)}'/><button class='secondary'>Regenerate anonymous link</button></form></section><section class='card'><h2>Complete meeting</h2><form method='post' action='/follow-up-meetings/{id}/complete'><input type='hidden' name='__RequestVerificationToken' value='{H(token)}'/><label>Outcome<select name='outcome'><option>Completed</option><option>Participant did not appear</option><option>Ended early</option><option>Reschedule needed</option><option>Other</option></select></label><label>Participants<textarea name='participants' rows='3'></textarea></label><label>Recording status<select name='recordingStatus'><option>Not recorded</option><option>Recording requested / pending backend</option><option>Recorded</option><option>Recording failed</option></select></label><label>Recording reference<input name='recordingReference'/></label><label>Meeting notes<textarea name='meetingNotes' rows='4'></textarea></label><label>Follow-up narrative for Express Report<textarea name='narrative' rows='9' required></textarea></label><button>Complete & append narrative</button></form></section><section class='card'><h2>History</h2>{history}</section></aside></div></main>"""));
        }).RequireAuthorization();

        app.MapPost("/follow-up-meetings/{id:guid}/send-sms",async(Guid id,HttpContext ctx,IAntiforgery anti,IHttpClientFactory factory)=>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var m=await Load(dbPath,id);if(m is null)return Results.NotFound();var f=await ctx.Request.ReadFormAsync();var raw=f["inviteToken"].ToString();if(string.IsNullOrWhiteSpace(raw)||!FixedEquals(m.Value.InviteTokenHash,Hash(raw)))return Results.BadRequest("The anonymous invite token is unavailable or no longer valid. Regenerate the link first.");
            var link=$"{ctx.Request.Scheme}://{ctx.Request.Host}/follow-up/join/{id}?token={Uri.EscapeDataString(raw)}";var text=$"CMPD virtual follow-up with {m.Value.Officer}. Join here: {link} Recording, if used, will be visibly disclosed in the meeting.";
            var endpoint=app.Configuration["CLTPP_AWS_SMS_API_URL"];if(string.IsNullOrWhiteSpace(endpoint))return Results.BadRequest("Amazon SMS notification endpoint is not configured (CLTPP_AWS_SMS_API_URL).");
            var client=factory.CreateClient();using var req=new HttpRequestMessage(HttpMethod.Post,endpoint);var apiKey=app.Configuration["CLTPP_AWS_SMS_API_KEY"];if(!string.IsNullOrWhiteSpace(apiKey))req.Headers.TryAddWithoutValidation("X-Api-Key",apiKey);req.Content=new StringContent(JsonSerializer.Serialize(new{phone=m.Value.Phone,message=text,category="PoliceFollowUpMeeting",referenceId=id.ToString()}),Encoding.UTF8,"application/json");using var response=await client.SendAsync(req);var providerRef=response.Headers.TryGetValues("x-amzn-requestid",out var vals)?vals.FirstOrDefault():null;var status=response.IsSuccessStatusCode?"Sent":"Failed";await Exec(dbPath,"UPDATE PoliceFollowUpMeetings SET InviteStatus=$s,InviteSentAt=$t,InviteProviderReference=$ref,UpdatedAt=$t WHERE Id=$id",("$s",status),("$t",Now()),("$ref",providerRef??response.StatusCode.ToString()),("$id",id));await Hist(dbPath,id,ctx.User.Identity?.Name??"officer","SMS invite "+status,$"Amazon notification result: {(int)response.StatusCode} {response.StatusCode}");if(!response.IsSuccessStatusCode)return Results.BadRequest("Amazon SMS provider did not accept the notification.");return Results.Redirect($"/follow-up-meetings/{id}");
        }).RequireAuthorization();

        app.MapPost("/follow-up-meetings/{id:guid}/regenerate",async(Guid id,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);if(await Load(dbPath,id) is null)return Results.NotFound();var raw=Convert.ToHexString(RandomNumberGenerator.GetBytes(32)).ToLowerInvariant();await Exec(dbPath,"UPDATE PoliceFollowUpMeetings SET InviteTokenHash=$h,InviteStatus='Not sent',InviteSentAt=NULL,UpdatedAt=$t WHERE Id=$id",("$h",Hash(raw)),("$t",Now()),("$id",id));await Hist(dbPath,id,ctx.User.Identity?.Name??"officer","Invite regenerated","Previous anonymous join token revoked.");return Results.Redirect($"/follow-up-meetings/{id}?invite={Uri.EscapeDataString(raw)}");
        }).RequireAuthorization();

        app.MapGet("/follow-up/join/{id:guid}",async(Guid id,HttpContext ctx,string token)=>
        {
            var m=await Load(dbPath,id);if(m is null||string.IsNullOrWhiteSpace(token)||!FixedEquals(m.Value.InviteTokenHash,Hash(token)))return Results.NotFound();var domain=app.Configuration["CLTPP_JITSI_DOMAIN"]??"meet.jit.si";await Exec(dbPath,"INSERT INTO PoliceFollowUpParticipants(Id,MeetingId,Role,DisplayName,JoinedAt,IpAddress,UserAgent) VALUES($i,$m,$r,$n,$t,$ip,$ua)",("$i",Guid.NewGuid()),("$m",id),("$r",m.Value.ParticipantRole),("$n",m.Value.ParticipantName),("$t",Now()),("$ip",ctx.Connection.RemoteIpAddress?.ToString()??""),("$ua",ctx.Request.Headers.UserAgent.ToString()));
            return Html(Page("Join virtual follow-up",$"""<main class='wrap'><section class='card'><span class='eyebrow'>CMPD VIRTUAL FOLLOW-UP</span><h1>Join as {H(m.Value.ParticipantRole)}</h1><p>Meeting with {H(m.Value.Officer)}.</p><div class='notice'><b>No CLT++ account required.</b><p>This private link is your authorization to enter this meeting. It does not provide access to police reports or evidence.</p></div><div class='notice'><b>Recording notice</b><p>If this meeting is recorded, recording must be visibly disclosed in Jitsi before or while recording is active.</p></div><div id='jitsi' style='min-height:600px'></div></section></main><script src='https://{H(domain)}/external_api.js'></script><script>new JitsiMeetExternalAPI('{Js(domain)}',{{roomName:'{Js(m.Value.Room)}',parentNode:document.querySelector('#jitsi'),userInfo:{{displayName:'{Js(m.Value.ParticipantName)}'}}}});</script>"""));
        });

        app.MapPost("/follow-up-meetings/{id:guid}/complete",async(Guid id,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var m=await Load(dbPath,id);if(m is null)return Results.NotFound();var f=await ctx.Request.ReadFormAsync();var narrative=f["narrative"].ToString().Trim();if(narrative.Length==0)return Results.BadRequest("Follow-up narrative is required.");var now=Now();await using var cn=Open(dbPath);await cn.OpenAsync();await using var tx=await cn.BeginTransactionAsync();var up=cn.CreateCommand();up.Transaction=tx;up.CommandText="UPDATE PoliceFollowUpMeetings SET Status='Completed',Outcome=$o,Participants=$p,RecordingStatus=$rs,RecordingReference=$rr,MeetingNotes=$n,EndedAt=$t,UpdatedAt=$t WHERE Id=$id";P(up,"$o",f["outcome"]);P(up,"$p",f["participants"]);P(up,"$rs",f["recordingStatus"]);P(up,"$rr",f["recordingReference"]);P(up,"$n",f["meetingNotes"]);P(up,"$t",now);P(up,"$id",id);await up.ExecuteNonQueryAsync();var s=cn.CreateCommand();s.Transaction=tx;s.CommandText="INSERT INTO ExpressReportSupplements(Id,ExpressReportId,SourceType,SourceId,ParticipantRole,Title,Narrative,AuthoredBy,AuthoredAt) VALUES($i,$r,'Virtual Follow-up Meeting',$source,$role,$title,$n,$by,$t)";P(s,"$i",Guid.NewGuid());P(s,"$r",m.Value.ExpressReportId);P(s,"$source",id);P(s,"$role",m.Value.ParticipantRole);P(s,"$title",$"Follow-up with {m.Value.ParticipantRole}: {m.Value.ParticipantName}");P(s,"$n",narrative);P(s,"$by",ctx.User.Identity?.Name??"officer");P(s,"$t",now);await s.ExecuteNonQueryAsync();await tx.CommitAsync();await Hist(dbPath,id,ctx.User.Identity?.Name??"officer","Completed","Meeting completed and Express Report supplement appended.");return Results.Redirect($"/follow-up-meetings/{id}");
        }).RequireAuthorization();
    }

    private sealed record Meeting(Guid Id,Guid ExpressReportId,string ReportNumber,string ParticipantRole,string ParticipantName,string? Email,string Phone,string Officer,string Status,string? ScheduledAt,string Purpose,string Room,string InviteTokenHash,string InviteStatus,string RecordingStatus,string? RecordingReference);
    private static async Task<Meeting?> Load(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT m.Id,m.ExpressReportId,r.ReportNumber,m.ParticipantRole,m.ParticipantName,m.ParticipantEmail,m.ParticipantPhone,m.OfficerUsername,m.Status,m.ScheduledAt,m.Purpose,m.RoomName,m.InviteTokenHash,m.InviteStatus,m.RecordingStatus,m.RecordingReference FROM PoliceFollowUpMeetings m JOIN ExpressReports r ON r.Id=m.ExpressReportId WHERE m.Id=$id";P(c,"$id",id);await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?new(Guid.Parse(r.GetString(0)),Guid.Parse(r.GetString(1)),r.GetString(2),r.GetString(3),r.GetString(4),N(r,5),r.GetString(6),r.GetString(7),r.GetString(8),N(r,9),r.GetString(10),r.GetString(11),r.GetString(12),r.GetString(13),r.GetString(14),N(r,15)):null;}
    private static async Task<string> ReportOptions(string p,Guid? selected){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Id,ReportNumber,COALESCE(Title,''),Status FROM ExpressReports ORDER BY UpdatedAt DESC LIMIT 200";var rows=new List<string>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync()){var x=r.GetString(0);rows.Add($"<option value='{H(x)}' {(selected?.ToString()==x?"selected":"")}>{H(r.GetString(1))} · {H(r.GetString(2))} · {H(r.GetString(3))}</option>");}return string.Join("",rows);}
    private static async Task<bool> ReportExists(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT 1 FROM ExpressReports WHERE Id=$id";P(c,"$id",id);return await c.ExecuteScalarAsync()!=null;}
    private static async Task<string> Supplements(string p,Guid reportId,Guid meetingId){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Title,Narrative,AuthoredBy,AuthoredAt FROM ExpressReportSupplements WHERE ExpressReportId=$r AND SourceId=$m ORDER BY AuthoredAt DESC";P(c,"$r",reportId);P(c,"$m",meetingId);var rows=new List<string>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<article><b>{H(r.GetString(0))}</b><small>{H(r.GetString(2))} · {H(r.GetString(3))}</small><p style='white-space:pre-wrap'>{H(r.GetString(1))}</p></article>");return rows.Count==0?"<p class='muted'>No supplement yet.</p>":string.Join("",rows);}
    private static async Task<string> History(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Actor,Action,Detail,OccurredAt FROM PoliceFollowUpMeetingHistory WHERE MeetingId=$id ORDER BY OccurredAt DESC";P(c,"$id",id);var rows=new List<string>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<article><b>{H(r.GetString(1))}</b><small>{H(r.GetString(0))} · {H(r.GetString(3))}</small><p>{H(r.GetString(2))}</p></article>");return rows.Count==0?"<p class='muted'>No history.</p>":string.Join("",rows);}
    private static async Task Hist(string p,Guid id,string actor,string action,string detail)=>await Exec(p,"INSERT INTO PoliceFollowUpMeetingHistory(Id,MeetingId,Actor,Action,Detail,OccurredAt) VALUES($i,$m,$a,$x,$d,$t)",("$i",Guid.NewGuid()),("$m",id),("$a",actor),("$x",action),("$d",detail),("$t",Now()));
    private static async Task Exec(string p,string sql,params(string Key,object? Value)[] ps){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText=sql;foreach(var x in ps)P(c,x.Key,x.Value);await c.ExecuteNonQueryAsync();}
    private static void EnsureSchema(string p){using var cn=Open(p);cn.Open();using var c=cn.CreateCommand();c.CommandText="""CREATE TABLE IF NOT EXISTS PoliceFollowUpMeetings(Id TEXT PRIMARY KEY,ExpressReportId TEXT NOT NULL,ParticipantRole TEXT NOT NULL,ParticipantName TEXT NOT NULL,ParticipantEmail TEXT NULL,ParticipantPhone TEXT NOT NULL,OfficerUsername TEXT NOT NULL,Status TEXT NOT NULL,ScheduledAt TEXT NULL,Purpose TEXT NOT NULL,RoomName TEXT NOT NULL,InviteTokenHash TEXT NOT NULL,InviteStatus TEXT NOT NULL,InviteSentAt TEXT NULL,InviteProviderReference TEXT NULL,RecordingStatus TEXT NOT NULL,RecordingReference TEXT NULL,Outcome TEXT NULL,Participants TEXT NULL,MeetingNotes TEXT NULL,EndedAt TEXT NULL,CreatedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL);CREATE TABLE IF NOT EXISTS PoliceFollowUpParticipants(Id TEXT PRIMARY KEY,MeetingId TEXT NOT NULL,Role TEXT NOT NULL,DisplayName TEXT NOT NULL,JoinedAt TEXT NOT NULL,IpAddress TEXT NULL,UserAgent TEXT NULL);CREATE TABLE IF NOT EXISTS PoliceFollowUpMeetingHistory(Id TEXT PRIMARY KEY,MeetingId TEXT NOT NULL,Actor TEXT NOT NULL,Action TEXT NOT NULL,Detail TEXT NOT NULL,OccurredAt TEXT NOT NULL);CREATE TABLE IF NOT EXISTS ExpressReportSupplements(Id TEXT PRIMARY KEY,ExpressReportId TEXT NOT NULL,SourceType TEXT NOT NULL,SourceId TEXT NOT NULL,ParticipantRole TEXT NULL,Title TEXT NOT NULL,Narrative TEXT NOT NULL,AuthoredBy TEXT NOT NULL,AuthoredAt TEXT NOT NULL);CREATE INDEX IF NOT EXISTS IX_FollowUp_Report ON PoliceFollowUpMeetings(ExpressReportId);CREATE INDEX IF NOT EXISTS IX_Supplements_Report ON ExpressReportSupplements(ExpressReportId);""";c.ExecuteNonQuery();}
    private static SqliteConnection Open(string p)=>new($"Data Source={p}");private static string Now()=>DateTimeOffset.UtcNow.ToString("O");private static string Hash(string s)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(s))).ToLowerInvariant();private static bool FixedEquals(string a,string b)=>CryptographicOperations.FixedTimeEquals(Encoding.UTF8.GetBytes(a),Encoding.UTF8.GetBytes(b));private static void P(SqliteCommand c,string k,object? v)=>c.Parameters.AddWithValue(k,v?.ToString()??"");private static string? N(SqliteDataReader r,int i)=>r.IsDBNull(i)?null:r.GetString(i);private static bool CanPolice(ClaimsPrincipal u)=>u.IsInRole("Administrator")||u.IsInRole("Supervisor")||u.FindAll(DepartmentAccess.ClaimType).Any(c=>c.Value.Equals("Police",StringComparison.OrdinalIgnoreCase));private static string H(string? s)=>WebUtility.HtmlEncode(s??"");private static string Js(string s)=>s.Replace("\\","\\\\").Replace("'","\\'");private static IResult Html(string s)=>Results.Content(s,"text/html; charset=utf-8");private static string Page(string t,string b)=>$"<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>{H(t)} · CLT++ Employee</title><link rel='stylesheet' href='/app.css'></head><body><header class='top'><a href='/' class='brand'>CLT<span>++</span> <small>EMPLOYEE</small></a><div>Police virtual follow-up</div></header>{b}</body></html>";
}
