using System.Net;
using System.Security.Claims;
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.Data.Sqlite;

namespace CltPlusPlus.Employee;

public static class SwatRequests
{
    public static void Map(WebApplication app)
    {
        EnsureSchema(app.Configuration);

        app.MapGet("/swat-requests", async (HttpContext ctx) =>
        {
            if (!CanPolice(ctx.User)) return Results.Forbid();
            await using var cn=Open(app.Configuration);await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="SELECT Id,RequestNumber,Address,Status,RequestedBy,CreatedAt,ReviewedBy FROM SwatRequests ORDER BY CreatedAt DESC LIMIT 200";var rows=new List<string>();await using var r=await cmd.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<tr><td><a href='/swat-requests/{r.GetString(0)}'><b>{H(r.GetString(1))}</b></a></td><td>{H(r.GetString(2))}</td><td><span class='status'>{H(r.GetString(3))}</span></td><td>{H(r.GetString(4))}</td><td>{H(r.GetString(5))}</td><td>{H(N(r,6))}</td></tr>");
            return Html(Page("SWAT requests",$"""<main class='wrap'><a class='back' href='/'>← Work queue</a><section class='page-head'><div><span class='eyebrow'>POLICE · SWAT REQUESTS</span><h1>SWAT requests</h1><p>Submit address-based requests for tactical-team review. This module does not contain tactical plans or operational instructions.</p></div><a class='button' href='/swat-requests/new'>New SWAT request</a></section><section class='table-card'><table><thead><tr><th>Request</th><th>Address</th><th>Status</th><th>Requested by</th><th>Created</th><th>Reviewed by</th></tr></thead><tbody>{(rows.Count>0?string.Join("",rows):"<tr><td colspan='6' class='empty'>No SWAT requests.</td></tr>")}</tbody></table></section></main>"""));
        }).RequireAuthorization();

        app.MapGet("/swat-requests/new", (HttpContext ctx,IAntiforgery anti) =>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();var token=anti.GetAndStoreTokens(ctx).RequestToken!;return Html(Page("New SWAT request",$"""<main class='wrap'><a class='back' href='/swat-requests'>← SWAT requests</a><section class='card'><span class='eyebrow'>POLICE · REQUEST SWAT</span><h1>Request tactical-team review</h1><div class='notice'><b>Request intake only</b><p>Provide the minimum operational context necessary for supervisory review. Do not enter tactical entry plans, positioning, weapons deployment, or other sensitive operational instructions.</p></div><form method='post' action='/swat-requests'><input type='hidden' name='__RequestVerificationToken' value='{H(token)}'/><label>Address<input name='address' required autocomplete='street-address'/></label><label>Incident / case number<input name='incidentNumber'/></label><label>Reason for request<textarea name='reason' rows='5' required placeholder='Briefly describe the incident and why tactical-team review is requested.'></textarea></label><label>Known immediate hazards<textarea name='hazards' rows='4' placeholder='High-level hazards relevant to responder safety; avoid tactical planning details.'></textarea></label><label>Contact / callback<input name='callback' placeholder='Officer phone, radio call sign, or unit'/></label><label>Urgency<select name='urgency'><option>Routine review</option><option>Priority</option><option>Immediate supervisory review</option></select></label><button>Submit SWAT request</button></form></section></main>"""));
        }).RequireAuthorization();

        app.MapPost("/swat-requests", async (HttpContext ctx,IAntiforgery anti) =>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();var address=f["address"].ToString().Trim();var reason=f["reason"].ToString().Trim();if(string.IsNullOrWhiteSpace(address)||string.IsNullOrWhiteSpace(reason))return Results.BadRequest("Address and reason are required.");var id=Guid.NewGuid();var number=$"SWR-{DateTime.UtcNow:yyMMdd}-{Random.Shared.Next(100000,999999)}";var now=DateTimeOffset.UtcNow.ToString("O");await using var cn=Open(app.Configuration);await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="""INSERT INTO SwatRequests(Id,RequestNumber,Address,IncidentNumber,Reason,Hazards,Callback,Urgency,Status,RequestedBy,CreatedAt,UpdatedAt) VALUES($id,$n,$a,$i,$r,$h,$c,$u,'Requested',$by,$now,$now)""";void P(string k,string v)=>cmd.Parameters.AddWithValue(k,v);P("$id",id.ToString());P("$n",number);P("$a",address);P("$i",f["incidentNumber"].ToString().Trim());P("$r",reason);P("$h",f["hazards"].ToString().Trim());P("$c",f["callback"].ToString().Trim());P("$u",f["urgency"].ToString());P("$by",ctx.User.Identity?.Name??"officer");P("$now",now);await cmd.ExecuteNonQueryAsync();await AddHistory(cn,id,ctx.User.Identity?.Name??"officer","Requested","SWAT review requested",now);return Results.Redirect($"/swat-requests/{id}");
        }).RequireAuthorization();

        app.MapGet("/swat-requests/{id:guid}", async (Guid id,HttpContext ctx,IAntiforgery anti) =>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();await using var cn=Open(app.Configuration);await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="SELECT RequestNumber,Address,IncidentNumber,Reason,Hazards,Callback,Urgency,Status,RequestedBy,CreatedAt,ReviewedBy,ReviewNote FROM SwatRequests WHERE Id=$id";cmd.Parameters.AddWithValue("$id",id.ToString());await using var r=await cmd.ExecuteReaderAsync();if(!await r.ReadAsync())return Results.NotFound();var token=anti.GetAndStoreTokens(ctx).RequestToken!;var review=CanReview(ctx.User)?$"""<section class='card'><h2>Supervisory review</h2><form method='post' action='/swat-requests/{id}/review'><input type='hidden' name='__RequestVerificationToken' value='{H(token)}'/><label>Disposition<select name='status'><option>Under review</option><option>Approved for coordination</option><option>Declined</option><option>Cancelled</option><option>Completed</option></select></label><label>Review note<textarea name='note' rows='5'></textarea></label><button>Save review</button></form></section>""":"<section class='card'><h2>Review</h2><p>Supervisory/tactical approval is required before coordination.</p></section>";var history=await History(app.Configuration,id);return Html(Page(r.GetString(0),$"""<main class='wrap'><a class='back' href='/swat-requests'>← SWAT requests</a><section class='page-head'><div><span class='eyebrow'>SWAT REQUEST · {H(r.GetString(7))}</span><h1>{H(r.GetString(0))}</h1><p>{H(r.GetString(1))}</p></div></section><div class='detail-grid'><section class='card'><dl><dt>Incident/case</dt><dd>{H(N(r,2))}</dd><dt>Urgency</dt><dd>{H(r.GetString(6))}</dd><dt>Requested by</dt><dd>{H(r.GetString(8))}</dd><dt>Callback</dt><dd>{H(N(r,5))}</dd><dt>Reviewed by</dt><dd>{H(N(r,10))}</dd></dl><h2>Reason</h2><p style='white-space:pre-wrap'>{H(r.GetString(3))}</p><h2>Immediate hazards</h2><p style='white-space:pre-wrap'>{H(N(r,4))}</p><h2>Review note</h2><p style='white-space:pre-wrap'>{H(N(r,11))}</p></section><aside>{review}<section class='card'><h2>History</h2>{history}</section></aside></div></main>"""));
        }).RequireAuthorization();

        app.MapPost("/swat-requests/{id:guid}/review", async (Guid id,HttpContext ctx,IAntiforgery anti) =>
        {
            if(!CanReview(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();var status=f["status"].ToString();var allowed=new[]{"Under review","Approved for coordination","Declined","Cancelled","Completed"};if(!allowed.Contains(status))return Results.BadRequest("Invalid disposition.");var now=DateTimeOffset.UtcNow.ToString("O");await using var cn=Open(app.Configuration);await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="UPDATE SwatRequests SET Status=$s,ReviewedBy=$by,ReviewNote=$n,UpdatedAt=$u WHERE Id=$id";cmd.Parameters.AddWithValue("$s",status);cmd.Parameters.AddWithValue("$by",ctx.User.Identity?.Name??"reviewer");cmd.Parameters.AddWithValue("$n",f["note"].ToString().Trim());cmd.Parameters.AddWithValue("$u",now);cmd.Parameters.AddWithValue("$id",id.ToString());if(await cmd.ExecuteNonQueryAsync()==0)return Results.NotFound();await AddHistory(cn,id,ctx.User.Identity?.Name??"reviewer","Reviewed",status,now);return Results.Redirect($"/swat-requests/{id}");
        }).RequireAuthorization();
    }

    private static void EnsureSchema(IConfiguration c){using var cn=Open(c);cn.Open();using var cmd=cn.CreateCommand();cmd.CommandText="""CREATE TABLE IF NOT EXISTS SwatRequests(Id TEXT PRIMARY KEY,RequestNumber TEXT NOT NULL UNIQUE,Address TEXT NOT NULL,IncidentNumber TEXT,Reason TEXT NOT NULL,Hazards TEXT,Callback TEXT,Urgency TEXT NOT NULL,Status TEXT NOT NULL,RequestedBy TEXT NOT NULL,CreatedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL,ReviewedBy TEXT,ReviewNote TEXT);CREATE TABLE IF NOT EXISTS SwatRequestHistory(Id TEXT PRIMARY KEY,SwatRequestId TEXT NOT NULL,Employee TEXT NOT NULL,Action TEXT NOT NULL,Note TEXT,CreatedAt TEXT NOT NULL);CREATE INDEX IF NOT EXISTS IX_SwatRequests_Status ON SwatRequests(Status);CREATE INDEX IF NOT EXISTS IX_SwatRequestHistory_Request ON SwatRequestHistory(SwatRequestId);""";cmd.ExecuteNonQuery();}
    private static async Task AddHistory(SqliteConnection cn,Guid id,string employee,string action,string note,string at){var cmd=cn.CreateCommand();cmd.CommandText="INSERT INTO SwatRequestHistory(Id,SwatRequestId,Employee,Action,Note,CreatedAt) VALUES($id,$r,$e,$a,$n,$t)";cmd.Parameters.AddWithValue("$id",Guid.NewGuid().ToString());cmd.Parameters.AddWithValue("$r",id.ToString());cmd.Parameters.AddWithValue("$e",employee);cmd.Parameters.AddWithValue("$a",action);cmd.Parameters.AddWithValue("$n",note);cmd.Parameters.AddWithValue("$t",at);await cmd.ExecuteNonQueryAsync();}
    private static async Task<string> History(IConfiguration c,Guid id){await using var cn=Open(c);await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="SELECT Employee,Action,Note,CreatedAt FROM SwatRequestHistory WHERE SwatRequestId=$id ORDER BY CreatedAt DESC";cmd.Parameters.AddWithValue("$id",id.ToString());var rows=new List<string>();await using var r=await cmd.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<article><b>{H(r.GetString(1))}</b><p>{H(N(r,2))}</p><small>{H(r.GetString(0))} · {H(r.GetString(3))}</small></article>");return rows.Count>0?string.Join("",rows):"<p class='muted'>No history.</p>";}
    private static SqliteConnection Open(IConfiguration c){var p=c["CLTPP_PUBLIC_SAFETY_DB"]??Path.Combine(AppContext.BaseDirectory,"data","public-safety.db");Directory.CreateDirectory(Path.GetDirectoryName(p)!);return new SqliteConnection($"Data Source={p}");}
    private static bool CanPolice(ClaimsPrincipal u)=>u.IsInRole("Administrator")||u.IsInRole("Supervisor")||u.FindAll(DepartmentAccess.ClaimType).Any(c=>c.Value.Equals("Police",StringComparison.OrdinalIgnoreCase));
    private static bool CanReview(ClaimsPrincipal u)=>u.IsInRole("Administrator")||u.IsInRole("Supervisor")||u.IsInRole("SWAT Supervisor");
    private static string? N(SqliteDataReader r,int i)=>r.IsDBNull(i)?null:r.GetString(i);private static string H(string? v)=>WebUtility.HtmlEncode(v??"");private static IResult Html(string s)=>Results.Content(s,"text/html; charset=utf-8");private static string Page(string title,string body)=>$"<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>{H(title)} · CLT++ Employee</title><link rel='stylesheet' href='/app.css'></head><body><header class='top'><a href='/' class='brand'>CLT<span>++</span> <small>EMPLOYEE</small></a><div>Public Safety</div></header>{body}</body></html>";
}
