using System.Net;
using System.Security.Claims;
using Amazon.SimpleEmailV2;
using Amazon.SimpleEmailV2.Model;
using Amazon.SimpleNotificationService;
using Amazon.SimpleNotificationService.Model;
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.Data.Sqlite;

namespace CltPlusPlus.Employee;

public static class TrespassAdmin
{
    public static void Map(WebApplication app)
    {
        EnsureSchema(app.Configuration);

        app.MapGet("/trespass-records", async (HttpContext ctx, IAntiforgery anti) =>
        {
            if (!CanPolice(ctx.User)) return Results.Forbid();
            await using var cn=Open(app.Configuration); await cn.OpenAsync();
            var cmd=cn.CreateCommand();cmd.CommandText="SELECT Id,RecordNumber,PropertyName,OffenderName,Status,CreatedByEmployee,CreatedAt FROM TrespassRecords ORDER BY CreatedAt DESC";
            var rows=new List<string>();await using var r=await cmd.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<tr><td><a href='/trespass-records/{r.GetString(0)}'><b>{H(r.GetString(1))}</b></a></td><td>{H(r.GetString(2))}</td><td>{H(r.GetString(3))}</td><td><span class='status'>{H(r.GetString(4))}</span></td><td>{H(r.GetString(5))}<small>{H(r.GetString(6))}</small></td></tr>");
            return Html(Page("Trespass records",$"""<main class='wrap'><a class='back' href='/'>← Work queue</a><section class='page-head'><div><span class='eyebrow'>POLICE · TRESPASS</span><h1>Trespass records</h1><p>Create and deliver completed trespass notices.</p></div><a class='button' href='/trespass-records/new'>New trespass record</a></section><section class='table-card'><table><thead><tr><th>Record</th><th>Property</th><th>Offender</th><th>Status</th><th>Officer / created</th></tr></thead><tbody>{(rows.Count>0?string.Join("",rows):"<tr><td colspan='5' class='empty'>No trespass records.</td></tr>")}</tbody></table></section></main>"""));
        }).RequireAuthorization();

        app.MapGet("/trespass-records/new", (HttpContext ctx, IAntiforgery anti) =>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();var token=anti.GetAndStoreTokens(ctx).RequestToken!;
            return Html(Page("New trespass record",$"""<main class='wrap'><a class='back' href='/trespass-records'>← Trespass records</a><section class='card'><span class='eyebrow'>POLICE · NEW TRESPASS RECORD</span><h1>Create trespass record</h1><form method='post' action='/trespass-records'><input type='hidden' name='__RequestVerificationToken' value='{H(token)}'/>
            <h2>Property</h2><label>Property / business name<input name='propertyName' required></label><label>Property address<input name='propertyAddress' required></label><label>Owner / authorized agent<input name='ownerName' required></label><div class='two'><label>Owner email<input type='email' name='ownerEmail'></label><label>Owner phone<input type='tel' name='ownerPhone'></label></div>
            <h2>Offender</h2><label>Full name<input name='offenderName' required></label><label>Date of birth<input name='offenderDob'></label><label>Address<input name='offenderAddress'></label><div class='two'><label>Email<input type='email' name='offenderEmail'></label><label>Phone<input type='tel' name='offenderPhone'></label></div><label>Driver license / ID reference<input name='offenderId'></label>
            <h2>Trespass notice</h2><label>Effective date/time<input type='datetime-local' name='effectiveAt' required></label><label>Scope / prohibited area<textarea name='scope' rows='4' required placeholder='Describe the property or areas covered by the notice.'></textarea></label><label>Conditions / instructions<textarea name='conditions' rows='4' placeholder='Conditions for return, exceptions, owner instructions, etc.'></textarea></label><label>Acknowledgment<select name='acknowledgment'><option>Verbally advised and acknowledged</option><option>Written copy furnished and acknowledged</option><option>Refused acknowledgment</option><option>Unable to obtain acknowledgment</option></select></label><label>Officer notes<textarea name='notes' rows='6'></textarea></label><button>Create completed trespass record</button></form></section></main>"""));
        }).RequireAuthorization();

        app.MapPost("/trespass-records", async (HttpContext ctx, IAntiforgery anti) =>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();
            var property=f["propertyName"].ToString().Trim();var address=f["propertyAddress"].ToString().Trim();var owner=f["ownerName"].ToString().Trim();var offender=f["offenderName"].ToString().Trim();var scope=f["scope"].ToString().Trim();
            if(new[]{property,address,owner,offender,scope}.Any(string.IsNullOrWhiteSpace))return Results.BadRequest("Property, owner, offender, and scope are required.");
            var id=Guid.NewGuid();var number=$"TRS-{DateTime.UtcNow:yyMMdd}-{Random.Shared.Next(100000,999999)}";var now=DateTimeOffset.UtcNow.ToString("O");
            await using var cn=Open(app.Configuration);await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="""INSERT INTO TrespassRecords(Id,RecordNumber,PropertyName,PropertyAddress,OwnerName,OwnerEmail,OwnerPhone,OffenderName,OffenderDob,OffenderAddress,OffenderEmail,OffenderPhone,OffenderIdReference,EffectiveAt,Scope,Conditions,Acknowledgment,OfficerNotes,Status,CreatedByEmployee,CreatedAt,CompletedAt) VALUES($id,$num,$pn,$pa,$on,$oe,$op,$fn,$dob,$oa,$fe,$fp,$fid,$eff,$scope,$cond,$ack,$notes,'Completed',$officer,$now,$now)""";
            void P(string k,string v)=>cmd.Parameters.AddWithValue(k,v);P("$id",id.ToString());P("$num",number);P("$pn",property);P("$pa",address);P("$on",owner);P("$oe",f["ownerEmail"].ToString().Trim());P("$op",f["ownerPhone"].ToString().Trim());P("$fn",offender);P("$dob",f["offenderDob"].ToString().Trim());P("$oa",f["offenderAddress"].ToString().Trim());P("$fe",f["offenderEmail"].ToString().Trim());P("$fp",f["offenderPhone"].ToString().Trim());P("$fid",f["offenderId"].ToString().Trim());P("$eff",f["effectiveAt"].ToString().Trim());P("$scope",scope);P("$cond",f["conditions"].ToString().Trim());P("$ack",f["acknowledgment"].ToString().Trim());P("$notes",f["notes"].ToString().Trim());P("$officer",ctx.User.Identity?.Name??"officer");P("$now",now);await cmd.ExecuteNonQueryAsync();return Results.Redirect($"/trespass-records/{id}");
        }).RequireAuthorization();

        app.MapGet("/trespass-records/{id:guid}", async (Guid id,HttpContext ctx,IAntiforgery anti) =>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();var rec=await Load(app.Configuration,id);if(rec is null)return Results.NotFound();var token=anti.GetAndStoreTokens(ctx).RequestToken!;
            var delivery=await DeliveryHistory(app.Configuration,id);
            return Html(Page(rec.RecordNumber,$"""<main class='wrap'><a class='back' href='/trespass-records'>← Trespass records</a><section class='page-head'><div><span class='eyebrow'>TRESPASS RECORD · {H(rec.Status)}</span><h1>{H(rec.RecordNumber)}</h1><p>{H(rec.PropertyName)} · {H(rec.PropertyAddress)}</p></div></section><div class='detail-grid'><section class='card'><h2>Completed notice</h2><dl><dt>Property owner / agent</dt><dd>{H(rec.OwnerName)}<br>{H(rec.OwnerEmail)} · {H(rec.OwnerPhone)}</dd><dt>Offender</dt><dd>{H(rec.OffenderName)}<br>{H(rec.OffenderEmail)} · {H(rec.OffenderPhone)}</dd><dt>Effective</dt><dd>{H(rec.EffectiveAt)}</dd><dt>Scope</dt><dd>{H(rec.Scope)}</dd><dt>Conditions</dt><dd>{H(rec.Conditions)}</dd><dt>Acknowledgment</dt><dd>{H(rec.Acknowledgment)}</dd><dt>Officer</dt><dd>{H(rec.CreatedBy)}</dd></dl><h3>Officer notes</h3><p style='white-space:pre-wrap'>{H(rec.Notes)}</p></section><aside><section class='card'><h2>Deliver completed notice</h2><p>Send the completed trespass record to the offender and property owner/agent using the contact information on the record.</p><form method='post' action='/trespass-records/{id}/send'><input type='hidden' name='__RequestVerificationToken' value='{H(token)}'/><label><input type='checkbox' name='email' value='true' checked> Email available recipients</label><label><input type='checkbox' name='sms' value='true' checked> Text available recipients</label><button>Send notice</button></form></section><section class='card'><h2>Delivery history</h2>{delivery}</section></aside></div></main>"""));
        }).RequireAuthorization();

        app.MapPost("/trespass-records/{id:guid}/send", async (Guid id,HttpContext ctx,IAntiforgery anti) =>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var rec=await Load(app.Configuration,id);if(rec is null)return Results.NotFound();var f=await ctx.Request.ReadFormAsync();var doEmail=f.ContainsKey("email");var doSms=f.ContainsKey("sms");var body=NoticeText(rec);var attempts=new List<(string recipient,string channel,bool ok,string detail)>();
            if(doEmail){foreach(var (who,email) in new[]{("Offender",rec.OffenderEmail),("Property owner",rec.OwnerEmail)}.Where(x=>!string.IsNullOrWhiteSpace(x.Item2))){var (ok,detail)=await SendEmail(app.Configuration,email!,rec.RecordNumber,body);attempts.Add((who+" "+email,"Email",ok,detail));}}
            if(doSms){foreach(var (who,phone) in new[]{("Offender",rec.OffenderPhone),("Property owner",rec.OwnerPhone)}.Where(x=>!string.IsNullOrWhiteSpace(x.Item2))){var (ok,detail)=await SendSms(app.Configuration,phone!,body);attempts.Add((who+" "+phone,"SMS",ok,detail));}}
            await LogAttempts(app.Configuration,id,ctx.User.Identity?.Name??"officer",attempts);return Results.Redirect($"/trespass-records/{id}");
        }).RequireAuthorization();
    }

    private sealed record Rec(Guid Id,string RecordNumber,string PropertyName,string PropertyAddress,string OwnerName,string OwnerEmail,string OwnerPhone,string OffenderName,string OffenderEmail,string OffenderPhone,string EffectiveAt,string Scope,string Conditions,string Acknowledgment,string Notes,string Status,string CreatedBy);
    private static string Db(IConfiguration c)=>c["CLTPP_PUBLIC_SAFETY_DB"]??Path.Combine(AppContext.BaseDirectory,"data","public-safety.db");
    private static SqliteConnection Open(IConfiguration c){var p=Db(c);Directory.CreateDirectory(Path.GetDirectoryName(p)!);return new SqliteConnection($"Data Source={p}");}
    private static void EnsureSchema(IConfiguration c){using var cn=Open(c);cn.Open();using var cmd=cn.CreateCommand();cmd.CommandText="""CREATE TABLE IF NOT EXISTS TrespassRecords(Id TEXT PRIMARY KEY,RecordNumber TEXT NOT NULL UNIQUE,PropertyName TEXT NOT NULL,PropertyAddress TEXT NOT NULL,OwnerName TEXT NOT NULL,OwnerEmail TEXT,OwnerPhone TEXT,OffenderName TEXT NOT NULL,OffenderDob TEXT,OffenderAddress TEXT,OffenderEmail TEXT,OffenderPhone TEXT,OffenderIdReference TEXT,EffectiveAt TEXT NOT NULL,Scope TEXT NOT NULL,Conditions TEXT,Acknowledgment TEXT,OfficerNotes TEXT,Status TEXT NOT NULL,CreatedByEmployee TEXT NOT NULL,CreatedAt TEXT NOT NULL,CompletedAt TEXT NOT NULL);CREATE TABLE IF NOT EXISTS TrespassDeliveries(Id TEXT PRIMARY KEY,TrespassRecordId TEXT NOT NULL,Recipient TEXT NOT NULL,Channel TEXT NOT NULL,Succeeded INTEGER NOT NULL,Detail TEXT,SentByEmployee TEXT NOT NULL,AttemptedAt TEXT NOT NULL);CREATE INDEX IF NOT EXISTS IX_TrespassRecords_Number ON TrespassRecords(RecordNumber);CREATE INDEX IF NOT EXISTS IX_TrespassDeliveries_Record ON TrespassDeliveries(TrespassRecordId);""";cmd.ExecuteNonQuery();}
    private static async Task<Rec?> Load(IConfiguration c,Guid id){await using var cn=Open(c);await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="SELECT RecordNumber,PropertyName,PropertyAddress,OwnerName,OwnerEmail,OwnerPhone,OffenderName,OffenderEmail,OffenderPhone,EffectiveAt,Scope,Conditions,Acknowledgment,OfficerNotes,Status,CreatedByEmployee FROM TrespassRecords WHERE Id=$id";cmd.Parameters.AddWithValue("$id",id.ToString());await using var r=await cmd.ExecuteReaderAsync();return await r.ReadAsync()?new(id,r.GetString(0),r.GetString(1),r.GetString(2),r.GetString(3),N(r,4),N(r,5),r.GetString(6),N(r,7),N(r,8),r.GetString(9),r.GetString(10),N(r,11),N(r,12),N(r,13),r.GetString(14),r.GetString(15)):null;}
    private static async Task<string> DeliveryHistory(IConfiguration c,Guid id){await using var cn=Open(c);await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="SELECT Recipient,Channel,Succeeded,Detail,SentByEmployee,AttemptedAt FROM TrespassDeliveries WHERE TrespassRecordId=$id ORDER BY AttemptedAt DESC";cmd.Parameters.AddWithValue("$id",id.ToString());var rows=new List<string>();await using var r=await cmd.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<article><b>{H(r.GetString(1))} · {(r.GetInt64(2)==1?"Sent":"Failed")}</b><p>{H(r.GetString(0))}</p><small>{H(N(r,3))} · {H(r.GetString(4))} · {H(r.GetString(5))}</small></article>");return rows.Count>0?string.Join("",rows):"<p class='muted'>No delivery attempts yet.</p>";}
    private static string NoticeText(Rec r)=>$"CLT++ Trespass Notice {r.RecordNumber}\nProperty: {r.PropertyName}, {r.PropertyAddress}\nOffender: {r.OffenderName}\nEffective: {r.EffectiveAt}\nScope: {r.Scope}\nConditions: {r.Conditions}\nAcknowledgment: {r.Acknowledgment}\nOfficer: {r.CreatedBy}\nThis message is a copy of the completed trespass record.";
    private static async Task<(bool,string)> SendSms(IConfiguration c,string phone,string body){try{var region=c["AWS_REGION"];using var sns=string.IsNullOrWhiteSpace(region)?new AmazonSimpleNotificationServiceClient():new AmazonSimpleNotificationServiceClient(Amazon.RegionEndpoint.GetBySystemName(region));var res=await sns.PublishAsync(new PublishRequest{PhoneNumber=phone,Message=body.Length>1400?body[..1400]:body});return(true,res.MessageId??"Sent");}catch(Exception ex){return(false,ex.Message);}}
    private static async Task<(bool,string)> SendEmail(IConfiguration c,string email,string record,string body){try{var from=c["CLTPP_SES_FROM"];if(string.IsNullOrWhiteSpace(from))return(false,"CLTPP_SES_FROM is not configured.");var region=c["AWS_REGION"];using var ses=string.IsNullOrWhiteSpace(region)?new AmazonSimpleEmailServiceV2Client():new AmazonSimpleEmailServiceV2Client(Amazon.RegionEndpoint.GetBySystemName(region));var res=await ses.SendEmailAsync(new SendEmailRequest{FromEmailAddress=from,Destination=new Destination{ToAddresses=new List<string>{email}},Content=new EmailContent{Simple=new Message{Subject=new Content{Data=$"Trespass notice {record}"},Body=new Body{Text=new Content{Data=body}}}}});return(true,res.MessageId??"Sent");}catch(Exception ex){return(false,ex.Message);}}
    private static async Task LogAttempts(IConfiguration c,Guid id,string officer,IEnumerable<(string recipient,string channel,bool ok,string detail)> attempts){await using var cn=Open(c);await cn.OpenAsync();foreach(var a in attempts){var cmd=cn.CreateCommand();cmd.CommandText="INSERT INTO TrespassDeliveries(Id,TrespassRecordId,Recipient,Channel,Succeeded,Detail,SentByEmployee,AttemptedAt) VALUES($id,$rid,$r,$c,$s,$d,$o,$t)";cmd.Parameters.AddWithValue("$id",Guid.NewGuid().ToString());cmd.Parameters.AddWithValue("$rid",id.ToString());cmd.Parameters.AddWithValue("$r",a.recipient);cmd.Parameters.AddWithValue("$c",a.channel);cmd.Parameters.AddWithValue("$s",a.ok?1:0);cmd.Parameters.AddWithValue("$d",a.detail);cmd.Parameters.AddWithValue("$o",officer);cmd.Parameters.AddWithValue("$t",DateTimeOffset.UtcNow.ToString("O"));await cmd.ExecuteNonQueryAsync();}}
    private static string N(SqliteDataReader r,int i)=>r.IsDBNull(i)?"":r.GetString(i);private static string H(string? v)=>WebUtility.HtmlEncode(v??"");private static bool CanPolice(ClaimsPrincipal u)=>u.IsInRole("Administrator")||u.IsInRole("Supervisor")||u.FindAll(DepartmentAccess.ClaimType).Any(c=>c.Value.Equals("Police",StringComparison.OrdinalIgnoreCase));private static IResult Html(string s)=>Results.Content(s,"text/html; charset=utf-8");private static string Page(string title,string body)=>$"<!doctype html><html lang='en'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>{H(title)} · CLT++ Employee</title><link rel='stylesheet' href='/app.css'></head><body><header class='top'><a href='/' class='brand'>CLT<span>++</span> <small>EMPLOYEE</small></a><div>Public Safety</div></header>{body}</body></html>";
}
