using System.Net;
using System.Security.Claims;
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.Data.Sqlite;

namespace CltPlusPlus.Employee;

public static class VcatRequests
{
    public static void Map(WebApplication app)
    {
        EnsureSchema(app.Configuration);

        app.MapGet("/vcat-requests", async (HttpContext ctx) =>
        {
            if (!CanPolice(ctx.User)) return Results.Forbid();
            await using var cn=Open(app.Configuration); await cn.OpenAsync();
            var cmd=cn.CreateCommand();cmd.CommandText="SELECT Id,RequestNumber,SubjectName,Status,Urgency,RequestedBy,CreatedAt FROM VcatRequests ORDER BY CreatedAt DESC LIMIT 200";
            var rows=new List<string>();await using var r=await cmd.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<tr><td><a href='/vcat-requests/{r.GetString(0)}'><b>{H(r.GetString(1))}</b></a></td><td>{H(r.GetString(2))}</td><td><span class='status'>{H(r.GetString(3))}</span></td><td>{H(r.GetString(4))}</td><td>{H(r.GetString(5))}</td><td>{H(r.GetString(6))}</td></tr>");
            return Html(Page("VCAT requests",$"""<main class='wrap'><a class='back' href='/'>← Work queue</a><section class='page-head'><div><span class='eyebrow'>POLICE · VCAT</span><h1>VCAT apprehension requests</h1><p>Request Violent Criminal Apprehension Team review for a wanted individual.</p></div><a class='button' href='/vcat-requests/new'>New VCAT request</a></section><section class='table-card'><table><thead><tr><th>Request</th><th>Individual</th><th>Status</th><th>Urgency</th><th>Requested by</th><th>Created</th></tr></thead><tbody>{(rows.Count>0?string.Join("",rows):"<tr><td colspan='6' class='empty'>No VCAT requests.</td></tr>")}</tbody></table></section></main>"""));
        }).RequireAuthorization();

        app.MapGet("/vcat-requests/new", async (HttpContext ctx,IAntiforgery anti,string? sourceType,string? sourceId) =>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();var token=anti.GetAndStoreTokens(ctx).RequestToken!;var s=await LoadCandidate(app.Configuration,sourceType,sourceId);
            return Html(Page("New VCAT request",$"""<main class='wrap'><a class='back' href='/vcat-requests'>← VCAT requests</a><section class='card'><span class='eyebrow'>POLICE · REQUEST VCAT</span><h1>Request VCAT review</h1><div class='notice'><b>Case-management intake only</b><p>Identity, legal basis, and case context only. Do not enter surveillance methods, covert sources, planned apprehension locations, or tactical instructions.</p></div><a class='button secondary' href='/vcat-requests/suspects'>Search existing suspect records</a>{(s is null?"":$"<div class='notice'><b>Reusing existing record</b><p>{H(s.SourceLabel)}</p></div>")}<form method='post' action='/vcat-requests'><input type='hidden' name='__RequestVerificationToken' value='{H(token)}'/><input type='hidden' name='sourceType' value='{H(s?.SourceType)}'/><input type='hidden' name='sourceId' value='{H(s?.SourceId)}'/><input type='hidden' name='sourceLabel' value='{H(s?.SourceLabel)}'/><h2>Wanted individual</h2><label>Full name<input name='subjectName' value='{H(s?.Name)}' required/></label><div class='two'><label>Date of birth<input name='dateOfBirth' value='{H(s?.Dob)}'/></label><label>Driver license / ID<input name='licenseId' value='{H(s?.LicenseId)}'/></label></div><label>Known aliases<textarea name='aliases' rows='2'>{H(s?.Aliases)}</textarea></label><label>Identifiers / descriptors<textarea name='identifiers' rows='3'>{H(s?.Identifiers)}</textarea></label><h2>Legal / case basis</h2><label>Case / incident number<input name='caseNumber' value='{H(s?.CaseNumber)}' required/></label><label>Warrant / process reference<input name='warrantReference' required/></label><label>Offense / charges<textarea name='charges' rows='3' required></textarea></label><label>Request rationale<textarea name='reason' rows='5' required></textarea></label><label>Last-known information<textarea name='lastKnown' rows='4'>{H(s?.LastKnown)}</textarea></label><label>Officer callback / unit<input name='callback'/></label><label>Urgency<select name='urgency'><option>Routine</option><option>Priority</option><option>Immediate review</option></select></label><button>Submit VCAT request</button></form></section></main>"""));
        }).RequireAuthorization();

        app.MapGet("/vcat-requests/suspects", async (HttpContext ctx,string? q) =>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();var matches=string.IsNullOrWhiteSpace(q)?new List<Candidate>():await SearchCandidates(app.Configuration,q.Trim());
            var rows=string.Join("",matches.Select(x=>$"<tr><td><b>{H(x.Name)}</b><small>{H(x.Dob)}</small></td><td>{H(x.SourceLabel)}</td><td>{H(x.CaseNumber)}</td><td>{H(x.LastKnown)}</td><td><a class='button' href='/vcat-requests/new?sourceType={U(x.SourceType)}&sourceId={U(x.SourceId)}'>Use record</a></td></tr>"));
            return Html(Page("Search suspects",$"""<main class='wrap'><a class='back' href='/vcat-requests/new'>← New VCAT request</a><section class='page-head'><div><span class='eyebrow'>VCAT · SUSPECT SEARCH</span><h1>Reuse suspect information</h1><p>Search existing public-safety records, preview the source, then explicitly copy selected identity fields into a VCAT request.</p></div></section><form class='filters' method='get'><input name='q' value='{H(q)}' placeholder='Name, DOB, license/ID, alias, case number'/><button>Search</button></form><section class='table-card'><table><thead><tr><th>Person</th><th>Source</th><th>Case / record</th><th>Last known</th><th></th></tr></thead><tbody>{(rows.Length>0?rows:"<tr><td colspan='5' class='empty'>No matching records.</td></tr>")}</tbody></table></section></main>"""));
        }).RequireAuthorization();

        app.MapPost("/vcat-requests", async (HttpContext ctx,IAntiforgery anti) =>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();var subject=f["subjectName"].ToString().Trim();var caseNo=f["caseNumber"].ToString().Trim();var warrant=f["warrantReference"].ToString().Trim();var charges=f["charges"].ToString().Trim();var reason=f["reason"].ToString().Trim();if(new[]{subject,caseNo,warrant,charges,reason}.Any(string.IsNullOrWhiteSpace))return Results.BadRequest("Subject, case number, warrant/process reference, charges, and reason are required.");var id=Guid.NewGuid();var num=$"VCR-{DateTime.UtcNow:yyMMdd}-{Random.Shared.Next(100000,999999)}";var now=DateTimeOffset.UtcNow.ToString("O");await using var cn=Open(app.Configuration);await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="""INSERT INTO VcatRequests(Id,RequestNumber,SubjectName,DateOfBirth,LicenseId,Aliases,Identifiers,CaseNumber,WarrantReference,Charges,Reason,LastKnown,Callback,Urgency,Status,RequestedBy,CreatedAt,UpdatedAt,SourceType,SourceId,SourceLabel) VALUES($id,$num,$sn,$dob,$dl,$al,$ids,$case,$wr,$ch,$reason,$lk,$cb,$urg,'Requested',$by,$now,$now,$st,$sid,$sl)""";void P(string k,string v)=>cmd.Parameters.AddWithValue(k,v);P("$id",id.ToString());P("$num",num);P("$sn",subject);P("$dob",f["dateOfBirth"].ToString().Trim());P("$dl",f["licenseId"].ToString().Trim());P("$al",f["aliases"].ToString());P("$ids",f["identifiers"].ToString());P("$case",caseNo);P("$wr",warrant);P("$ch",charges);P("$reason",reason);P("$lk",f["lastKnown"].ToString());P("$cb",f["callback"].ToString().Trim());P("$urg",f["urgency"].ToString());P("$by",ctx.User.Identity?.Name??"officer");P("$now",now);P("$st",f["sourceType"].ToString());P("$sid",f["sourceId"].ToString());P("$sl",f["sourceLabel"].ToString());await cmd.ExecuteNonQueryAsync();await AddHistory(cn,id,ctx.User.Identity?.Name??"officer","Requested",string.IsNullOrWhiteSpace(f["sourceId"])?"VCAT review requested":$"VCAT review requested using source {f["sourceLabel"]}",now);return Results.Redirect($"/vcat-requests/{id}");
        }).RequireAuthorization();

        app.MapGet("/vcat-requests/{id:guid}", async (Guid id,HttpContext ctx,IAntiforgery anti) =>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();await using var cn=Open(app.Configuration);await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="SELECT RequestNumber,SubjectName,DateOfBirth,LicenseId,Aliases,Identifiers,CaseNumber,WarrantReference,Charges,Reason,LastKnown,Callback,Urgency,Status,RequestedBy,CreatedAt,ReviewedBy,ReviewNote,SourceLabel FROM VcatRequests WHERE Id=$id";cmd.Parameters.AddWithValue("$id",id.ToString());await using var r=await cmd.ExecuteReaderAsync();if(!await r.ReadAsync())return Results.NotFound();var token=anti.GetAndStoreTokens(ctx).RequestToken!;var review=CanReview(ctx.User)?$"""<section class='card'><h2>VCAT review</h2><form method='post' action='/vcat-requests/{id}/review'><input type='hidden' name='__RequestVerificationToken' value='{H(token)}'/><label>Status<select name='status'><option>Under review</option><option>Accepted</option><option>Needs information</option><option>Declined</option><option>Located / apprehended</option><option>Closed</option></select></label><label>Review note<textarea name='note' rows='5'></textarea></label><button>Save review</button></form></section>""":"<section class='card'><h2>VCAT review</h2><p>VCAT/supervisory review is required before team action.</p></section>";var history=await History(app.Configuration,id);return Html(Page(r.GetString(0),$"""<main class='wrap'><a class='back' href='/vcat-requests'>← VCAT requests</a><section class='page-head'><div><span class='eyebrow'>VCAT REQUEST · {H(r.GetString(13))}</span><h1>{H(r.GetString(0))}</h1><p>{H(r.GetString(1))}</p></div></section><div class='detail-grid'><section class='card'><dl><dt>DOB</dt><dd>{H(N(r,2))}</dd><dt>License / ID</dt><dd>{H(N(r,3))}</dd><dt>Aliases</dt><dd>{H(N(r,4))}</dd><dt>Case</dt><dd>{H(r.GetString(6))}</dd><dt>Warrant/process</dt><dd>{H(r.GetString(7))}</dd><dt>Urgency</dt><dd>{H(r.GetString(12))}</dd><dt>Requested by</dt><dd>{H(r.GetString(14))}</dd><dt>Reused source</dt><dd>{H(N(r,18))}</dd><dt>Reviewed by</dt><dd>{H(N(r,16))}</dd></dl><h2>Charges</h2><p style='white-space:pre-wrap'>{H(r.GetString(8))}</p><h2>Reason</h2><p style='white-space:pre-wrap'>{H(r.GetString(9))}</p><h2>Last-known information</h2><p style='white-space:pre-wrap'>{H(N(r,10))}</p><h2>Review note</h2><p style='white-space:pre-wrap'>{H(N(r,17))}</p></section><aside>{review}<section class='card'><h2>History</h2>{history}</section></aside></div></main>"""));
        }).RequireAuthorization();

        app.MapPost("/vcat-requests/{id:guid}/review", async (Guid id,HttpContext ctx,IAntiforgery anti) =>
        {
            if(!CanReview(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();var status=f["status"].ToString();var allowed=new[]{"Under review","Accepted","Needs information","Declined","Located / apprehended","Closed"};if(!allowed.Contains(status))return Results.BadRequest("Invalid status.");var now=DateTimeOffset.UtcNow.ToString("O");await using var cn=Open(app.Configuration);await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="UPDATE VcatRequests SET Status=$s,ReviewedBy=$by,ReviewNote=$n,UpdatedAt=$u WHERE Id=$id";cmd.Parameters.AddWithValue("$s",status);cmd.Parameters.AddWithValue("$by",ctx.User.Identity?.Name??"reviewer");cmd.Parameters.AddWithValue("$n",f["note"].ToString().Trim());cmd.Parameters.AddWithValue("$u",now);cmd.Parameters.AddWithValue("$id",id.ToString());if(await cmd.ExecuteNonQueryAsync()==0)return Results.NotFound();await AddHistory(cn,id,ctx.User.Identity?.Name??"reviewer","Reviewed",status,now);return Results.Redirect($"/vcat-requests/{id}");
        }).RequireAuthorization();
    }

    private sealed record Candidate(string SourceType,string SourceId,string SourceLabel,string Name,string? Dob,string? LicenseId,string? Aliases,string? Identifiers,string? CaseNumber,string? LastKnown);
    private static async Task<List<Candidate>> SearchCandidates(IConfiguration c,string q){var list=new List<Candidate>();await using var cn=Open(c);await cn.OpenAsync();if(await Table(cn,"IncidentNarratives")){var cmd=cn.CreateCommand();cmd.CommandText="SELECT Id,IncidentNumber,COALESCE(FirstName,'')||' '||COALESCE(LastName,''),DateOfBirth,LicenseNumber,Address,PersonRole FROM IncidentNarratives WHERE PersonRole IN ('Suspect','Offender') AND (FirstName LIKE $q OR LastName LIKE $q OR DateOfBirth LIKE $q OR LicenseNumber LIKE $q OR IncidentNumber LIKE $q) LIMIT 50";cmd.Parameters.AddWithValue("$q","%"+q+"%");await using var r=await cmd.ExecuteReaderAsync();while(await r.ReadAsync())list.Add(new("IncidentNarrative",r.GetString(0),$"Incident narrative · {N(r,6)}",r.GetString(2).Trim(),N(r,3),N(r,4),null,null,r.GetString(1),N(r,5)));}if(await Table(cn,"TrespassRecords")){var cmd=cn.CreateCommand();cmd.CommandText="SELECT Id,RecordNumber,OffenderName,OffenderDob,OffenderIdReference,OffenderAddress FROM TrespassRecords WHERE OffenderName LIKE $q OR OffenderDob LIKE $q OR OffenderIdReference LIKE $q OR RecordNumber LIKE $q LIMIT 50";cmd.Parameters.AddWithValue("$q","%"+q+"%");await using var r=await cmd.ExecuteReaderAsync();while(await r.ReadAsync())list.Add(new("TrespassRecord",r.GetString(0),"Trespass record",r.GetString(2),N(r,3),N(r,4),null,null,r.GetString(1),N(r,5)));}if(await Table(cn,"BoloRecords")){var cmd=cn.CreateCommand();cmd.CommandText="SELECT Id,TrackingNumber,SubjectName,SubjectDescription,LastKnownLocation FROM BoloRecords WHERE SubjectName LIKE $q OR SubjectDescription LIKE $q OR TrackingNumber LIKE $q LIMIT 50";cmd.Parameters.AddWithValue("$q","%"+q+"%");await using var r=await cmd.ExecuteReaderAsync();while(await r.ReadAsync())if(!string.IsNullOrWhiteSpace(N(r,2)))list.Add(new("BOLO",r.GetString(0),"BOLO",N(r,2)!,null,null,null,N(r,3),r.GetString(1),N(r,4)));}return list.Take(100).ToList();}
    private static async Task<Candidate?> LoadCandidate(IConfiguration c,string? type,string? id){if(string.IsNullOrWhiteSpace(type)||string.IsNullOrWhiteSpace(id))return null;return (await SearchCandidates(c,id)).FirstOrDefault(x=>x.SourceType==type&&x.SourceId==id)??await LoadById(c,type,id);}
    private static async Task<Candidate?> LoadById(IConfiguration c,string type,string id){await using var cn=Open(c);await cn.OpenAsync();if(type=="IncidentNarrative"&&await Table(cn,"IncidentNarratives")){var cmd=cn.CreateCommand();cmd.CommandText="SELECT IncidentNumber,COALESCE(FirstName,'')||' '||COALESCE(LastName,''),DateOfBirth,LicenseNumber,Address,PersonRole FROM IncidentNarratives WHERE Id=$id";cmd.Parameters.AddWithValue("$id",id);await using var r=await cmd.ExecuteReaderAsync();if(await r.ReadAsync())return new(type,id,$"Incident narrative · {N(r,5)}",r.GetString(1).Trim(),N(r,2),N(r,3),null,null,r.GetString(0),N(r,4));}if(type=="TrespassRecord"&&await Table(cn,"TrespassRecords")){var cmd=cn.CreateCommand();cmd.CommandText="SELECT RecordNumber,OffenderName,OffenderDob,OffenderIdReference,OffenderAddress FROM TrespassRecords WHERE Id=$id";cmd.Parameters.AddWithValue("$id",id);await using var r=await cmd.ExecuteReaderAsync();if(await r.ReadAsync())return new(type,id,"Trespass record",r.GetString(1),N(r,2),N(r,3),null,null,r.GetString(0),N(r,4));}if(type=="BOLO"&&await Table(cn,"BoloRecords")){var cmd=cn.CreateCommand();cmd.CommandText="SELECT TrackingNumber,SubjectName,SubjectDescription,LastKnownLocation FROM BoloRecords WHERE Id=$id";cmd.Parameters.AddWithValue("$id",id);await using var r=await cmd.ExecuteReaderAsync();if(await r.ReadAsync())return new(type,id,"BOLO",N(r,1)??"",null,null,null,N(r,2),r.GetString(0),N(r,3));}return null;}
    private static async Task<bool> Table(SqliteConnection cn,string name){var cmd=cn.CreateCommand();cmd.CommandText="SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name=$n";cmd.Parameters.AddWithValue("$n",name);return Convert.ToInt32(await cmd.ExecuteScalarAsync())>0;}
    private static void EnsureSchema(IConfiguration c){using var cn=Open(c);cn.Open();using var cmd=cn.CreateCommand();cmd.CommandText="""CREATE TABLE IF NOT EXISTS VcatRequests(Id TEXT PRIMARY KEY,RequestNumber TEXT NOT NULL UNIQUE,SubjectName TEXT NOT NULL,DateOfBirth TEXT,LicenseId TEXT,Aliases TEXT,Identifiers TEXT,CaseNumber TEXT NOT NULL,WarrantReference TEXT NOT NULL,Charges TEXT NOT NULL,Reason TEXT NOT NULL,LastKnown TEXT,Callback TEXT,Urgency TEXT NOT NULL,Status TEXT NOT NULL,RequestedBy TEXT NOT NULL,CreatedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL,ReviewedBy TEXT,ReviewNote TEXT,SourceType TEXT,SourceId TEXT,SourceLabel TEXT);CREATE TABLE IF NOT EXISTS VcatRequestHistory(Id TEXT PRIMARY KEY,VcatRequestId TEXT NOT NULL,Employee TEXT NOT NULL,Action TEXT NOT NULL,Note TEXT,CreatedAt TEXT NOT NULL);CREATE INDEX IF NOT EXISTS IX_VcatRequests_Status ON VcatRequests(Status);CREATE INDEX IF NOT EXISTS IX_VcatRequestHistory_Request ON VcatRequestHistory(VcatRequestId);""";cmd.ExecuteNonQuery();}
    private static async Task AddHistory(SqliteConnection cn,Guid id,string employee,string action,string note,string at){var cmd=cn.CreateCommand();cmd.CommandText="INSERT INTO VcatRequestHistory(Id,VcatRequestId,Employee,Action,Note,CreatedAt) VALUES($id,$r,$e,$a,$n,$t)";cmd.Parameters.AddWithValue("$id",Guid.NewGuid().ToString());cmd.Parameters.AddWithValue("$r",id.ToString());cmd.Parameters.AddWithValue("$e",employee);cmd.Parameters.AddWithValue("$a",action);cmd.Parameters.AddWithValue("$n",note);cmd.Parameters.AddWithValue("$t",at);await cmd.ExecuteNonQueryAsync();}
    private static async Task<string> History(IConfiguration c,Guid id){await using var cn=Open(c);await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="SELECT Employee,Action,Note,CreatedAt FROM VcatRequestHistory WHERE VcatRequestId=$id ORDER BY CreatedAt DESC";cmd.Parameters.AddWithValue("$id",id.ToString());var rows=new List<string>();await using var r=await cmd.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<article><b>{H(r.GetString(1))}</b><p>{H(N(r,2))}</p><small>{H(r.GetString(0))} · {H(r.GetString(3))}</small></article>");return rows.Count>0?string.Join("",rows):"<p class='muted'>No history.</p>";}
    private static SqliteConnection Open(IConfiguration c){var p=c["CLTPP_PUBLIC_SAFETY_DB"]??Path.Combine(AppContext.BaseDirectory,"data","public-safety.db");Directory.CreateDirectory(Path.GetDirectoryName(p)!);return new SqliteConnection($"Data Source={p}");}
    private static bool CanPolice(ClaimsPrincipal u)=>u.IsInRole("Administrator")||u.IsInRole("Supervisor")||u.FindAll(DepartmentAccess.ClaimType).Any(c=>c.Value.Equals("Police",StringComparison.OrdinalIgnoreCase));private static bool CanReview(ClaimsPrincipal u)=>u.IsInRole("Administrator")||u.IsInRole("Supervisor")||u.IsInRole("VCAT Supervisor");
    private static string? N(SqliteDataReader r,int i)=>r.IsDBNull(i)?null:r.GetString(i);private static string H(string? v)=>WebUtility.HtmlEncode(v??"");private static string U(string v)=>Uri.EscapeDataString(v);private static IResult Html(string s)=>Results.Content(s,"text/html; charset=utf-8");private static string Page(string title,string body)=>$"<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>{H(title)} · CLT++ Employee</title><link rel='stylesheet' href='/app.css'></head><body><header class='top'><a href='/' class='brand'>CLT<span>++</span> <small>EMPLOYEE</small></a><div>Public Safety</div></header>{body}</body></html>";
}
