using System.Net;
using System.Security.Claims;
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.Data.Sqlite;

namespace CltPlusPlus.Employee;

public static class WarrantQueue
{
    public static void Map(WebApplication app)
    {
        var dbPath=app.Configuration["CLTPP_PUBLIC_SAFETY_DB"]??Path.Combine(AppContext.BaseDirectory,"data","public-safety.db");
        Directory.CreateDirectory(Path.GetDirectoryName(dbPath)!);EnsureSchema(dbPath);

        app.MapGet("/warrants",async(HttpContext ctx,string? q,string? status)=>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();
            await using var cn=Open(dbPath);await cn.OpenAsync();var cmd=cn.CreateCommand();
            cmd.CommandText="""SELECT Id,WarrantNumber,SubjectName,DateOfBirth,LicenseId,IncidentNumber,Status,IssuedBy,IssuedAt,ServedBy,ServedAt FROM ArrestWarrants WHERE ($q='' OR SubjectName LIKE $like OR DateOfBirth LIKE $like OR LicenseId LIKE $like OR IncidentNumber LIKE $like OR WarrantNumber LIKE $like) AND ($status='' OR Status=$status) ORDER BY CASE WHEN Status='Active' THEN 0 ELSE 1 END,IssuedAt DESC LIMIT 500""";
            cmd.Parameters.AddWithValue("$q",q??"");cmd.Parameters.AddWithValue("$like","%"+(q??"")+"%");cmd.Parameters.AddWithValue("$status",status??"");
            var rows=new List<string>();await using var r=await cmd.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<tr><td><a href='/warrants/{r.GetString(0)}'><b>{H(r.GetString(1))}</b></a></td><td>{H(r.GetString(2))}<small>{H(N(r,3))}</small></td><td>{H(N(r,4))}</td><td>{H(r.GetString(5))}</td><td><span class='status'>{H(r.GetString(6))}</span></td><td>{H(r.GetString(7))}<small>{H(r.GetString(8))}</small></td><td>{H(N(r,9))}<small>{H(N(r,10))}</small></td></tr>");
            var options=new[]{"","Active","Recalled","Served / Arrest Completed"};var statusOptions=string.Join("",options.Select(x=>$"<option value='{H(x)}' {(string.Equals(x,status,StringComparison.OrdinalIgnoreCase)?"selected":"")}>{H(string.IsNullOrWhiteSpace(x)?"All statuses":x)}</option>"));
            return Html(Page("Warrants",$"""<main class='wrap'><a class='back' href='/'>← Work queue</a><section class='page-head'><div><span class='eyebrow'>POLICE · WARRANTS</span><h1>Warrant queue</h1><p>View all warrant records. Officers must independently verify identity and warrant status before taking action.</p></div></section><form class='filters' method='get'><input name='q' value='{H(q)}' placeholder='Name, DOB, license/ID, incident, warrant number'/><select name='status'>{statusOptions}</select><button>Search</button></form><section class='table-card'><table><thead><tr><th>Warrant</th><th>Subject</th><th>License / ID</th><th>Incident</th><th>Status</th><th>Issued</th><th>Served</th></tr></thead><tbody>{(rows.Count>0?string.Join("",rows):"<tr><td colspan='7' class='empty'>No warrants found.</td></tr>")}</tbody></table></section></main>"""));
        }).RequireAuthorization();

        app.MapGet("/warrants/{id:guid}",async(Guid id,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();var w=await Load(dbPath,id);if(w is null)return Results.NotFound();var token=anti.GetAndStoreTokens(ctx).RequestToken!;var action=w.Value.Status=="Active"?$"""<section class='card'><h2>Mark arrest complete</h2><div class='notice'><b>Verify before serving</b><p>Confirm the person and active warrant independently. This action records service; it does not determine identity or legal authority.</p></div><form method='post' action='/warrants/{id}/serve'><input type='hidden' name='__RequestVerificationToken' value='{H(token)}'/><label>Arrest / service date-time<input type='datetime-local' name='servedAt' required/></label><label>Arrest location<input name='arrestLocation' required/></label><label>Booking / custody destination<input name='bookingDestination'/></label><label>Execution notes<textarea name='notes' rows='5'></textarea></label><label><input type='checkbox' name='verified' value='true' required/> I verified the subject and active warrant before marking service complete.</label><button>Mark arrest complete</button></form></section>""":"";var hist=await HistoryHtml(dbPath,id);return Html(Page(w.Value.Number,$"""<main class='wrap'><a class='back' href='/warrants'>← Warrant queue</a><section class='page-head'><div><span class='eyebrow'>WARRANT · {H(w.Value.Status)}</span><h1>{H(w.Value.Number)}</h1><p>{H(w.Value.SubjectName)}</p></div></section><div class='detail-grid'><section class='card'><dl><dt>DOB</dt><dd>{H(w.Value.DateOfBirth)}</dd><dt>License / ID</dt><dd>{H(w.Value.LicenseId)}</dd><dt>Address</dt><dd>{H(w.Value.Address)}</dd><dt>Incident</dt><dd>{H(w.Value.IncidentNumber)}</dd><dt>Issued by</dt><dd>{H(w.Value.IssuedBy)}</dd><dt>Issued</dt><dd>{H(w.Value.IssuedAt)}</dd><dt>Served by</dt><dd>{H(w.Value.ServedBy)}</dd><dt>Served</dt><dd>{H(w.Value.ServedAt)}</dd></dl><h2>Charges / statutes</h2><p style='white-space:pre-wrap'>{H(w.Value.Charges)}</p><h2>Judicial basis</h2><p style='white-space:pre-wrap'>{H(w.Value.JudicialBasis)}</p><h2>Conditions</h2><p style='white-space:pre-wrap'>{H(w.Value.Conditions)}</p></section><aside>{action}</aside></div><section class='card'><h2>Warrant history</h2>{hist}</section></main>"""));
        }).RequireAuthorization();

        app.MapPost("/warrants/{id:guid}/serve",async(Guid id,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!CanPolice(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();if(!string.Equals(f["verified"],"true",StringComparison.OrdinalIgnoreCase))return Results.BadRequest("Identity and warrant verification confirmation is required.");var w=await Load(dbPath,id);if(w is null)return Results.NotFound();if(!w.Value.Status.Equals("Active",StringComparison.OrdinalIgnoreCase))return Results.Conflict(new{error="Only an active warrant can be marked served."});var at=DateTimeOffset.TryParse(f["servedAt"],out var d)?d.ToString("O"):DateTimeOffset.UtcNow.ToString("O");var loc=f["arrestLocation"].ToString().Trim();if(string.IsNullOrWhiteSpace(loc))return Results.BadRequest("Arrest location is required.");var officer=ctx.User.Identity?.Name??"officer";await using var cn=Open(dbPath);await cn.OpenAsync();await using var tx=await cn.BeginTransactionAsync();var cmd=cn.CreateCommand();cmd.Transaction=tx;cmd.CommandText="UPDATE ArrestWarrants SET Status='Served / Arrest Completed',ServedBy=$by,ServedAt=$at,ArrestLocation=$loc,BookingDestination=$book,ServiceNotes=$notes,UpdatedAt=$u WHERE Id=$id AND Status='Active'";cmd.Parameters.AddWithValue("$by",officer);cmd.Parameters.AddWithValue("$at",at);cmd.Parameters.AddWithValue("$loc",loc);cmd.Parameters.AddWithValue("$book",f["bookingDestination"].ToString().Trim());cmd.Parameters.AddWithValue("$notes",f["notes"].ToString());cmd.Parameters.AddWithValue("$u",DateTimeOffset.UtcNow.ToString("O"));cmd.Parameters.AddWithValue("$id",id.ToString());var changed=await cmd.ExecuteNonQueryAsync();if(changed!=1){await tx.RollbackAsync();return Results.Conflict(new{error="Warrant status changed before service could be recorded."});}var hist=cn.CreateCommand();hist.Transaction=tx;hist.CommandText="INSERT INTO WarrantHistory(Id,WarrantId,Actor,Action,Detail,OccurredAt) VALUES($i,$w,$a,'Served / Arrest Completed',$d,$t)";hist.Parameters.AddWithValue("$i",Guid.NewGuid().ToString());hist.Parameters.AddWithValue("$w",id.ToString());hist.Parameters.AddWithValue("$a",officer);hist.Parameters.AddWithValue("$d",$"Arrest completed at {loc}. Booking/custody: {f["bookingDestination"]}. {f["notes"]}".Trim());hist.Parameters.AddWithValue("$t",DateTimeOffset.UtcNow.ToString("O"));await hist.ExecuteNonQueryAsync();await tx.CommitAsync();return Results.Redirect($"/warrants/{id}");
        }).RequireAuthorization();
    }

    private static async Task<(Guid Id,string Number,string SubjectName,string? DateOfBirth,string? LicenseId,string? Address,string IncidentNumber,string Charges,string JudicialBasis,string? Conditions,string Status,string IssuedBy,string IssuedAt,string? ServedBy,string? ServedAt)?> Load(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Id,WarrantNumber,SubjectName,DateOfBirth,LicenseId,SubjectAddress,IncidentNumber,Charges,JudicialBasis,Conditions,Status,IssuedBy,IssuedAt,ServedBy,ServedAt FROM ArrestWarrants WHERE Id=$id";c.Parameters.AddWithValue("$id",id.ToString());await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?(Guid.Parse(r.GetString(0)),r.GetString(1),r.GetString(2),N(r,3),N(r,4),N(r,5),r.GetString(6),r.GetString(7),r.GetString(8),N(r,9),r.GetString(10),r.GetString(11),r.GetString(12),N(r,13),N(r,14)):null;}
    private static async Task<string> HistoryHtml(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Actor,Action,Detail,OccurredAt FROM WarrantHistory WHERE WarrantId=$id ORDER BY OccurredAt DESC";c.Parameters.AddWithValue("$id",id.ToString());var rows=new List<string>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<article><b>{H(r.GetString(1))}</b><small>{H(r.GetString(0))} · {H(r.GetString(3))}</small><p>{H(r.GetString(2))}</p></article>");return rows.Count==0?"<p class='muted'>No history recorded.</p>":string.Join("",rows);}
    private static void EnsureSchema(string p){using var cn=Open(p);cn.Open();using var cmd=cn.CreateCommand();cmd.CommandText="""CREATE TABLE IF NOT EXISTS ArrestWarrants(Id TEXT PRIMARY KEY,WarrantNumber TEXT NOT NULL UNIQUE,ComplaintId TEXT NULL,IncidentNumber TEXT NOT NULL,SubjectName TEXT NOT NULL,DateOfBirth TEXT NULL,LicenseId TEXT NULL,SubjectAddress TEXT NULL,Charges TEXT NOT NULL,JudicialBasis TEXT NOT NULL,Conditions TEXT NULL,Status TEXT NOT NULL,IssuedBy TEXT NOT NULL,IssuedAt TEXT NOT NULL,RecalledBy TEXT NULL,RecalledAt TEXT NULL,RecallReason TEXT NULL,ServedBy TEXT NULL,ServedAt TEXT NULL,ArrestLocation TEXT NULL,BookingDestination TEXT NULL,ServiceNotes TEXT NULL,UpdatedAt TEXT NOT NULL);CREATE TABLE IF NOT EXISTS WarrantHistory(Id TEXT PRIMARY KEY,WarrantId TEXT NOT NULL,Actor TEXT NOT NULL,Action TEXT NOT NULL,Detail TEXT NOT NULL,OccurredAt TEXT NOT NULL);CREATE INDEX IF NOT EXISTS IX_Warrants_Status ON ArrestWarrants(Status);CREATE INDEX IF NOT EXISTS IX_Warrants_Subject ON ArrestWarrants(SubjectName);""";cmd.ExecuteNonQuery();}
    private static SqliteConnection Open(string p)=>new($"Data Source={p}");private static bool CanPolice(ClaimsPrincipal u)=>u.IsInRole("Administrator")||u.IsInRole("Supervisor")||u.FindAll(DepartmentAccess.ClaimType).Any(c=>string.Equals(c.Value,"Police",StringComparison.OrdinalIgnoreCase));private static string? N(SqliteDataReader r,int i)=>r.IsDBNull(i)?null:r.GetString(i);private static string H(string? s)=>WebUtility.HtmlEncode(s??"");private static IResult Html(string s)=>Results.Content(s,"text/html; charset=utf-8");private static string Page(string t,string b)=>$"<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>{H(t)} · CLT++ Employee</title><link rel='stylesheet' href='/app.css'></head><body><header class='top'><a href='/' class='brand'>CLT<span>++</span> <small>EMPLOYEE</small></a><div>Police warrant queue</div></header>{b}</body></html>";
}
