import { FormEvent, useEffect, useMemo, useState } from 'react'
import { getServices, submitRequest, trackRequest, validateAddress } from './api'
import CrimeReportWizard from './CrimeReportWizard'
import type { Draft, Service, SubmissionResult } from './types'

const categories=['All','Police','Fire','Streets & Transportation','Solid Waste','Neighborhoods','Trees & Environment','Water','Animals']
const steps=['Location','Details','Contact','Summary']
const blankDraft=():Draft=>({location:'',details:{},contact:{anonymous:false}})

function App(){
  const [services,setServices]=useState<Service[]>([])
  const [selected,setSelected]=useState<Service|null>(null)
  const [category,setCategory]=useState('All')
  const [query,setQuery]=useState('')
  const [step,setStep]=useState(0)
  const [draft,setDraft]=useState<Draft>(blankDraft())
  const [result,setResult]=useState<SubmissionResult|null>(null)
  const [error,setError]=useState('')
  const [showTrack,setShowTrack]=useState(false)
  const [trackNumber,setTrackNumber]=useState('')
  const [tracked,setTracked]=useState<any>(null)
  const [trackError,setTrackError]=useState('')

  useEffect(()=>{getServices().then(setServices).catch(e=>setError(e.message))},[])
  const filtered=useMemo(()=>services.filter(s=>(category==='All'||s.category===category)&&(!query||`${s.title} ${s.description} ${s.category}`.toLowerCase().includes(query.toLowerCase()))),[services,category,query])

  function openService(service:Service){setSelected(service);setStep(0);setResult(null);setError('');setDraft({...blankDraft(),contact:{anonymous:service.id==='crime-tip'}});window.scrollTo(0,0)}
  async function finish(){if(!selected)return;try{setResult(await submitRequest(selected,draft))}catch(e){setError(e instanceof Error?e.message:'Submission failed')}}
  async function doTrack(e:FormEvent){e.preventDefault();setTrackError('');setTracked(null);try{setTracked(await trackRequest(trackNumber.trim()))}catch(e){setTrackError(e instanceof Error?e.message:'Not found')}}

  if(selected?.id==='crime-report')return <div className="shell"><TopBar onHome={()=>setSelected(null)} onTrack={()=>setShowTrack(true)}/><CrimeReportWizard service={selected} onBack={()=>setSelected(null)}/><Footer/>{showTrack&&<TrackModal {...{trackNumber,setTrackNumber,tracked,trackError,doTrack}} onClose={()=>setShowTrack(false)}/>}</div>

  if(selected)return <div className="shell"><TopBar onHome={()=>setSelected(null)} onTrack={()=>setShowTrack(true)}/><main className="wrap wizard"><button className="link" onClick={()=>setSelected(null)}>← Back to services</button><div className="wizard-head"><div><span className="eyebrow">{selected.category}</span><h1>{selected.title}</h1><p>{selected.description}</p></div>{selected.category==='Police'&&<div className="police-mark">POLICE<br/><b>CLT++</b></div>}{selected.category==='Fire'&&<div className="police-mark">FIRE<br/><b>CLT++</b></div>}</div>{(selected.category==='Police'||selected.category==='Fire')&&<div className="alert"><b>Emergency? Call 911.</b><span>This prototype does not dispatch police, fire, EMS, or transmit requests to City systems.</span></div>}<div className="stepper">{steps.map((s,i)=><div className={i<=step?'step active':'step'} key={s}><b>{i+1}</b><span>{s}</span></div>)}</div>{result?<Success result={result} onDone={()=>setSelected(null)}/>:<GenericWizard service={selected} draft={draft} setDraft={setDraft} step={step} setStep={setStep} error={error} setError={setError} finish={finish}/>}</main><Footer/>{showTrack&&<TrackModal {...{trackNumber,setTrackNumber,tracked,trackError,doTrack}} onClose={()=>setShowTrack(false)}/>}</div>

  return <div className="shell"><TopBar onHome={()=>{}} onTrack={()=>setShowTrack(true)}/><main><section className="hero"><div className="wrap"><span className="pill">UNOFFICIAL DEMO</span><h1>Charlotte services,<br/><em>made clearer.</em></h1><p>Find a service, send the details, and keep your tracking number. CLT++ is a prototype—not a City of Charlotte system.</p><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="What can we help with?"/></div></div></section><section className="wrap catalog"><div className="title-row"><div><span className="eyebrow">SERVICE CATALOG</span><h2>Start a request</h2></div><button className="link" onClick={()=>setShowTrack(true)}>Track a request →</button></div><div className="tabs">{categories.map(c=><button className={category===c?'active':''} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div>{category==='Police'&&<div className="police-banner"><b>Police services</b><span>For emergencies, crimes in progress, or a suspect on scene, call 911.</span></div>}{category==='Fire'&&<div className="police-banner"><b>Fire services</b><span>For active fire, smoke, gas, explosion, medical emergency, or immediate danger, call 911.</span></div>}<div className="grid">{filtered.map(s=><button className={`card ${s.category==='Police'?'police':''}`} onClick={()=>openService(s)} key={s.id}><div className="icon">{s.category==='Police'?'⬟':s.category==='Fire'?'△':'○'}</div><div><small>{s.category}</small><h3>{s.title}</h3><p>{s.description}</p>{s.badge&&<span className="badge">{s.badge}</span>}<strong>Start request →</strong></div></button>)}</div></section></main><Footer/>{showTrack&&<TrackModal {...{trackNumber,setTrackNumber,tracked,trackError,doTrack}} onClose={()=>setShowTrack(false)}/>}</div>
}

function GenericWizard({service,draft,setDraft,step,setStep,error,setError,finish}:{service:Service;draft:Draft;setDraft:(d:Draft)=>void;step:number;setStep:(n:number)=>void;error:string;setError:(s:string)=>void;finish:()=>void}){
  const [checking,setChecking]=useState(false)
  const setDetail=(name:string,value:unknown)=>setDraft({...draft,details:{...draft.details,[name]:value}})
  async function checkAddress(){if(!draft.location.trim())return setError('Enter an address first.');setChecking(true);setError('');try{const r=await validateAddress(draft.location);if(!r.valid){setDetail('addressValidated',false);setError(r.warning||'No address match found.');return}setDraft({...draft,location:r.normalizedAddress||draft.location,details:{...draft.details,addressValidated:true,latitude:r.latitude,longitude:r.longitude,addressWarning:r.warning||''}});if(r.warning)setError(r.warning)}catch(e){setError(e instanceof Error?e.message:'Unable to validate address')}finally{setChecking(false)}}
  function next(){setError('');if(step===0&&!draft.location.trim()&&service.id!=='crime-tip')return setError('Add a location to continue.');if(step===2&&service.id!=='crime-tip'&&!draft.contact.email?.trim())return setError('Add an email address for follow-up.');setStep(Math.min(3,step+1))}
  return <section className="panel">{step===0&&<><span className="eyebrow">STEP 1</span><h2>{service.id==='crime-tip'?'Where is this happening?':'Location'}</h2><p className="intro">Enter a street address when one is available. CLT++ validates addresses through the U.S. Census Geocoder.</p><Field label={service.id==='crime-tip'?'Address or location (optional)':'Address or location'}><div className="inline"><input value={draft.location} onChange={e=>setDraft({...draft,location:e.target.value})} placeholder="Street address, Charlotte NC"/>{draft.location.trim()&&<button className="btn secondary" type="button" onClick={checkAddress} disabled={checking}>{checking?'Checking…':'Validate'}</button>}</div></Field>{draft.details.addressValidated===true&&<div className="valid">✓ Address matched</div>}</>}{step===1&&<Details service={service} draft={draft} setDetail={setDetail}/>} {step===2&&<Contact service={service} draft={draft} setDraft={setDraft}/>} {step===3&&<Summary service={service} draft={draft}/>} {error&&<div className="error">{error}</div>}<div className="actions">{step>0&&<button className="btn secondary" onClick={()=>setStep(step-1)}>Back</button>}{step<3?<button className="btn primary" onClick={next}>Continue</button>:<button className="btn primary" onClick={finish}>Submit to CLT++ demo</button>}</div></section>
}

function Details({service,draft,setDetail}:{service:Service;draft:Draft;setDetail:(n:string,v:unknown)=>void}){
  if(service.id==='crime-tip')return <><span className="eyebrow">STEP 2 · ANONYMOUS TIP</span><h2>What do you know?</h2><Field label="Crime or concern"><input value={(draft.details.crimeType as string)??''} onChange={e=>setDetail('crimeType',e.target.value)} placeholder="Burglary, robbery, drugs, weapons, violent crime, etc."/></Field><Field label="Tip narrative"><textarea rows={8} value={(draft.details.description as string)??''} onChange={e=>setDetail('description',e.target.value)}/></Field><Two a={<Field label="Person / suspect details"><textarea rows={5} value={(draft.details.suspect as string)??''} onChange={e=>setDetail('suspect',e.target.value)}/></Field>} b={<Field label="Vehicle details"><textarea rows={5} value={(draft.details.vehicle as string)??''} onChange={e=>setDetail('vehicle',e.target.value)}/></Field>}/><Field label="Weapons / drugs / evidence / online identifiers"><textarea rows={5} value={(draft.details.evidence as string)??''} onChange={e=>setDetail('evidence',e.target.value)}/></Field></>
  return <><span className="eyebrow">STEP 2</span><h2>Request details</h2><Field label="What do you need?"><textarea rows={8} value={(draft.details.description as string)??''} onChange={e=>setDetail('description',e.target.value)} placeholder="Include dates, names, account/report numbers, property or event details, and any other information needed to process the request."/></Field><Two a={<Field label="Date / time"><input type="datetime-local" value={(draft.details.occurredAt as string)??''} onChange={e=>setDetail('occurredAt',e.target.value)}/></Field>} b={<Field label="Reference / report / permit number"><input value={(draft.details.referenceNumber as string)??''} onChange={e=>setDetail('referenceNumber',e.target.value)}/></Field>}/></>
}

function Contact({service,draft,setDraft}:{service:Service;draft:Draft;setDraft:(d:Draft)=>void}){const c=draft.contact;const update=(k:string,v:string|boolean)=>setDraft({...draft,contact:{...c,[k]:v}});return <><span className="eyebrow">STEP 3</span><h2>{service.id==='crime-tip'?'Stay anonymous or opt in to contact':'How can we reach you?'}</h2>{service.id==='crime-tip'&&<label className="check"><input type="checkbox" checked={c.anonymous} onChange={e=>update('anonymous',e.target.checked)}/><span><b>Submit anonymously</b><small>Name, email, and phone are not required.</small></span></label>}{!c.anonymous&&<><Two a={<Field label="Name"><input value={c.name??''} onChange={e=>update('name',e.target.value)}/></Field>} b={<Field label="Email"><input type="email" value={c.email??''} onChange={e=>update('email',e.target.value)}/></Field>}/><Two a={<Field label="Phone"><input value={c.phone??''} onChange={e=>update('phone',e.target.value)}/></Field>} b={<Field label="Preferred contact"><select value={c.preferredMethod??''} onChange={e=>update('preferredMethod',e.target.value)}><option value="">No preference</option><option>Email</option><option>Phone</option><option>Text</option></select></Field>}/></>}</>}
function Summary({service,draft}:{service:Service;draft:Draft}){return <><span className="eyebrow">STEP 4</span><h2>Review your submission</h2><div className="summary"><h3>{service.title}</h3><Row k="Location" v={draft.location||'Not provided'}/>{Object.entries(draft.details).filter(([,v])=>v!==''&&v!==false).map(([k,v])=><Row key={k} k={pretty(k)} v={String(v)}/>)}<Row k="Contact" v={draft.contact.anonymous?'Anonymous':[draft.contact.name,draft.contact.email,draft.contact.phone].filter(Boolean).join(' · ')||'Not provided'}/></div><div className="notice"><b>Prototype destination only</b><p>This submission is stored in CLT++ and is not automatically sent to City of Charlotte, CMPD, Charlotte Fire, 311, Crime Stoppers, or another agency system.</p></div></>}
function Success({result,onDone}:{result:SubmissionResult;onDone:()=>void}){return <section className="success"><div className="success-mark">✓</div><span className="eyebrow">SUBMITTED TO CLT++</span><h2>Your demo request is saved.</h2><div className="tracking">{result.trackingNumber}</div><p>Status: <b>{result.status}</b></p><div className="notice"><b>Not an official agency submission</b><p>{result.disclaimer}</p></div><button className="btn primary" onClick={onDone}>Return to services</button></section>}
function TrackModal({onClose,trackNumber,setTrackNumber,tracked,trackError,doTrack}:any){return <div className="modal-bg" onMouseDown={onClose}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={onClose}>×</button><span className="eyebrow">TRACK A REQUEST</span><h2>Check your CLT++ status</h2><form onSubmit={doTrack}><input value={trackNumber} onChange={e=>setTrackNumber(e.target.value)} placeholder="CLTPP-260820-123456 or TMP-..."/><button className="btn primary">Look up</button></form>{trackError&&<div className="error">{trackError}</div>}{tracked&&<div className="track-result"><b>{tracked.serviceTitle}</b><span>{tracked.trackingNumber}</span><strong>{tracked.status}</strong></div>}</div></div>}
function TopBar({onHome,onTrack}:{onHome:()=>void;onTrack:()=>void}){return <><div className="disclaimer">Unofficial prototype · Not affiliated with the City of Charlotte, CMPD, or Charlotte Fire</div><header><button className="brand" onClick={onHome}>CLT<span>++</span></button><nav><button onClick={onHome}>Services</button><button onClick={onTrack}>Track request</button><a href="tel:311">Call 311</a></nav></header></>}
function Footer(){return <footer><b>CLT<span>++</span></b><p>Unofficial civic-service prototype. Not a City of Charlotte, CMPD, Charlotte Fire, 311, or Crime Stoppers website.</p><div><a href="tel:911">Emergency: 911</a><a href="tel:311">Non-emergency: 311</a><a href="tel:+17043341600">Crime Stoppers: 704-334-1600</a></div></footer>}
function Field({label,children}:{label:string;children:any}){return <label className="field"><span>{label}</span>{children}</label>}
function Two({a,b}:{a:any;b:any}){return <div className="two">{a}{b}</div>}
function Row({k,v}:{k:string;v:string}){return <div className="row"><span>{k}</span><b>{v}</b></div>}
function pretty(s:string){return s.replace(/([A-Z])/g,' $1').replace(/^./,x=>x.toUpperCase())}
export default App
