import { FormEvent, useEffect, useState } from 'react'
import { createResidentVehicle, deleteResidentVehicle, externalLoginUrl, getAuthProviders, getCivicProfile, getResident, getResidentVehicles, loginResident, logoutResident, registerResident, saveHomeAddress } from './api'
import type { AuthProvider, CivicPlace, CivicProfile, ResidentAccount, ResidentVehicle, ResidentVehicleInput } from './types'

const blankVehicle:ResidentVehicleInput={licensePlate:'',plateState:'NC',year:'',make:'',model:'',bodyType:'',color:'',vin:'',nickname:''}

export default function ResidentPortal(){
  const [account,setAccount]=useState<ResidentAccount|null>(null)
  const [providers,setProviders]=useState<AuthProvider[]>([])
  const [profile,setProfile]=useState<CivicProfile|null>(null)
  const [vehicles,setVehicles]=useState<ResidentVehicle[]>([])
  const [vehicle,setVehicle]=useState<ResidentVehicleInput>(blankVehicle)
  const [mode,setMode]=useState<'login'|'register'>('login')
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [name,setName]=useState('')
  const [address,setAddress]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)

  useEffect(()=>{Promise.all([getResident(),getAuthProviders()]).then(async([a,p])=>{setAccount(a);setProviders(p);setAddress(a?.homeAddress??'');if(a){getResidentVehicles().then(setVehicles).catch(()=>{});if(a.homeAddress)getCivicProfile().then(setProfile).catch(()=>{})}}).catch(()=>{})},[])

  async function authSubmit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const a=mode==='register'?await registerResident(email,password,name):await loginResident(email,password);setAccount(a);setAddress(a.homeAddress??'');setVehicles(await getResidentVehicles())}catch(e){setError(e instanceof Error?e.message:'Unable to sign in')}finally{setBusy(false)}}
  async function saveAddress(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const a=await saveHomeAddress(address);setAccount(a);setAddress(a.homeAddress??address);setProfile(await getCivicProfile())}catch(e){setError(e instanceof Error?e.message:'Unable to save address')}finally{setBusy(false)}}
  async function saveVehicle(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await createResidentVehicle(vehicle);setVehicles(await getResidentVehicles());setVehicle(blankVehicle)}catch(e){setError(e instanceof Error?e.message:'Unable to save vehicle')}finally{setBusy(false)}}
  async function removeVehicle(id:string){setBusy(true);setError('');try{await deleteResidentVehicle(id);setVehicles(await getResidentVehicles())}catch(e){setError(e instanceof Error?e.message:'Unable to remove vehicle')}finally{setBusy(false)}}
  async function signOut(){await logoutResident();setAccount(null);setProfile(null);setVehicles([]);window.history.pushState({},'', '/account')}

  if(!account)return <div className="account-shell"><section className="account-card"><span className="eyebrow">CLT++ RESIDENT ACCOUNT</span><h1>{mode==='login'?'Sign in':'Create your account'}</h1><p>Save your home address and vehicles, track requests, and see the public services and representatives tied to where you live.</p><form onSubmit={authSubmit}>{mode==='register'&&<label className="field"><span>Name</span><input value={name} onChange={e=>setName(e.target.value)}/></label>}<label className="field"><span>Email address</span><input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="field"><span>Password</span><input type="password" required minLength={10} value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<div className="error">{error}</div>}<button className="btn primary full" disabled={busy}>{busy?'Working…':mode==='login'?'Sign in':'Create account'}</button></form><div className="auth-divider"><span>or continue with</span></div><div className="provider-grid">{providers.map(p=><a key={p.id} className={`provider ${!p.enabled?'disabled':''}`} href={p.enabled?externalLoginUrl(p.id):undefined}>{p.id}{!p.enabled&&<small>Not configured</small>}</a>)}</div><button className="link account-toggle" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'Need an account? Create one':'Already have an account? Sign in'}</button></section></div>

  return <main className="wrap resident-page"><div className="resident-head"><div><span className="eyebrow">MY CLT++</span><h1>My District</h1><p>{account.displayName||account.email}</p></div><div className="resident-actions"><a className="btn secondary" href="/">Services</a><button className="btn secondary" onClick={signOut}>Sign out</button></div></div><section className="panel address-panel"><h2>Home address</h2><p className="intro">Your address is validated before it is used for district and nearby-location lookups.</p><form className="address-form" onSubmit={saveAddress}><input required value={address} onChange={e=>setAddress(e.target.value)} placeholder="Street address, Charlotte NC"/><button className="btn primary" disabled={busy}>{busy?'Looking up…':'Save & update district'}</button></form>{error&&<div className="error">{error}</div>}</section><VehicleSection vehicles={vehicles} vehicle={vehicle} setVehicle={setVehicle} saveVehicle={saveVehicle} removeVehicle={removeVehicle} busy={busy}/>{profile?<CivicDashboard p={profile}/>:<section className="empty-profile"><h2>Add your home address</h2><p>Your council district, representatives, public-safety locations, schools, DMV, post office, hospitals, and emergency room will appear here.</p></section>}</main>
}

function VehicleSection({vehicles,vehicle,setVehicle,saveVehicle,removeVehicle,busy}:{vehicles:ResidentVehicle[];vehicle:ResidentVehicleInput;setVehicle:(v:ResidentVehicleInput)=>void;saveVehicle:(e:FormEvent)=>void;removeVehicle:(id:string)=>void;busy:boolean}){const set=(k:keyof ResidentVehicleInput,v:string)=>setVehicle({...vehicle,[k]:v});return <section className="panel vehicle-panel"><span className="eyebrow">MY VEHICLES</span><h2>Saved vehicles</h2><p className="intro">Store vehicles for faster reuse in service requests and reporting forms. Only your signed-in account can access them.</p><div className="vehicle-list">{vehicles.map(v=><article key={v.id}><div><strong>{v.nickname||`${v.year||''} ${v.make||''} ${v.model||''}`.trim()||'Vehicle'}</strong><span>{v.plateState} {v.licensePlate}{v.bodyType?` · ${v.bodyType}`:''}{v.color?` · ${v.color}`:''}</span></div><button className="link" onClick={()=>removeVehicle(v.id)} disabled={busy}>Remove</button></article>)}{!vehicles.length&&<p className="muted">No vehicles saved yet.</p>}</div><form className="vehicle-form" onSubmit={saveVehicle}><div className="two"><label className="field"><span>License plate *</span><input required value={vehicle.licensePlate} onChange={e=>set('licensePlate',e.target.value)} placeholder="ABC1234"/></label><label className="field"><span>Plate state</span><input value={vehicle.plateState} onChange={e=>set('plateState',e.target.value)} maxLength={3}/></label></div><div className="three"><label className="field"><span>Year</span><input value={vehicle.year??''} onChange={e=>set('year',e.target.value)} maxLength={4}/></label><label className="field"><span>Make</span><input value={vehicle.make??''} onChange={e=>set('make',e.target.value)}/></label><label className="field"><span>Model</span><input value={vehicle.model??''} onChange={e=>set('model',e.target.value)}/></label></div><div className="three"><label className="field"><span>Car / body type</span><select value={vehicle.bodyType??''} onChange={e=>set('bodyType',e.target.value)}><option value="">Select</option><option>Sedan</option><option>SUV</option><option>Pickup</option><option>Van</option><option>Coupe</option><option>Hatchback</option><option>Wagon</option><option>Motorcycle</option><option>Commercial vehicle</option><option>Other</option></select></label><label className="field"><span>Color</span><input value={vehicle.color??''} onChange={e=>set('color',e.target.value)}/></label><label className="field"><span>Nickname</span><input value={vehicle.nickname??''} onChange={e=>set('nickname',e.target.value)} placeholder="Daily driver"/></label></div><label className="field"><span>VIN (optional)</span><input value={vehicle.vin??''} onChange={e=>set('vin',e.target.value)} maxLength={17}/></label><button className="btn primary" disabled={busy}>Save vehicle</button></form></section>}

function CivicDashboard({p}:{p:CivicProfile}){return <div className="civic-grid"><section className="civic-card span2"><span className="eyebrow">YOUR REPRESENTATION</span><h2>Districts & representatives</h2><div className="rep-grid"><Rep title={`Charlotte City Council · District ${p.councilDistrict??'—'}`} name={p.councilMember??'Representative unavailable'} email={p.councilEmail}/>{p.representatives.map((r,i)=><Rep key={i} title={`${r.chamber}${r.district?` · District ${r.district}`:''}`} name={r.name} phone={r.phone} url={r.website}/>)}</div></section><PlaceCard title="CMPD division" place={p.policeDivisionOffice} kicker={p.policeDivision||'Police division'}/><PlaceCard title="Nearest fire station" place={p.fireStation}/><PlaceCard title="Nearest DMV" place={p.dmvOffice}/><PlaceCard title="Nearest post office" place={p.postOffice}/><PlaceCard title="Nearest emergency room" place={p.emergencyRoom} emphasis/><section className="civic-card span2"><span className="eyebrow">HEALTH CARE</span><h2>Nearby hospitals</h2><PlaceList items={p.hospitals}/></section><section className="civic-card span2"><span className="eyebrow">EDUCATION</span><h2>Nearby public schools</h2><PlaceList items={p.nearbySchools}/><a className="btn secondary inline-btn" href={p.schoolAssignmentUrl} target="_blank" rel="noreferrer">Verify assigned school with CMS</a></section></div>}
function Rep({title,name,email,phone,url}:{title:string;name:string;email?:string|null;phone?:string|null;url?:string}){return <article className="rep"><small>{title}</small><strong>{name}</strong>{email&&<a href={`mailto:${email}`}>{email}</a>}{phone&&<a href={`tel:${phone}`}>{phone}</a>}{url&&<a href={url} target="_blank" rel="noreferrer">Official contact page →</a>}</article>}
function PlaceCard({title,place,kicker,emphasis}:{title:string;place?:CivicPlace|null;kicker?:string;emphasis?:boolean}){return <section className={`civic-card ${emphasis?'emergency-card':''}`}><span className="eyebrow">{kicker||title}</span><h2>{place?.name||'Location unavailable'}</h2>{place&&<><p>{place.address||'Address unavailable'}</p>{place.distanceMiles!=null&&<b>{place.distanceMiles.toFixed(2)} miles away</b>}{place.phone&&<a href={`tel:${place.phone}`}>{place.phone}</a>}{place.website&&<a href={place.website} target="_blank" rel="noreferrer">Website →</a>}</>}</section>}
function PlaceList({items}:{items:CivicPlace[]}){return <div className="place-list">{items.length?items.map((x,i)=><article key={`${x.name}-${i}`}><div><strong>{x.name}</strong><span>{x.address}</span></div><div>{x.distanceMiles!=null&&<b>{x.distanceMiles.toFixed(2)} mi</b>}{x.phone&&<a href={`tel:${x.phone}`}>{x.phone}</a>}</div></article>):<p className="muted">No nearby results returned.</p>}</div>}
