<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>CltPlusPlus.Api</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Stripe.net" Version="52.3.0" />
  </ItemGroup>
</Project>
