using System.Net;
using System.Security.Claims;
using System.Security.Cryptography;
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.Data.Sqlite;

namespace CltPlusPlus.Partners;

public static class AttorneyClerkWorkflows
{
    public static void Map(WebApplication app, string dbPath)
    {
        EnsureSchema(dbPath);

        app.MapGet("/attorney/register", (HttpContext ctx, IAntiforgery anti) =>
        {
            if(ctx.User.Identity?.IsAuthenticated==true)return Results.Redirect("/");
            var t=anti.GetAndStoreTokens(ctx).RequestToken!;
            return Html(Page("Attorney registration",$"""<main class='login-shell'><section class='login-card'><div class='brand'>CMPD <span>Partners</span></div><span class='eyebrow'>ATTORNEY ACCOUNT</span><h1>Create attorney account</h1><p>Attorney accounts require court-clerk approval before case access is enabled.</p><form method='post' action='/attorney/register'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><label>Email / username<input type='email' name='email' required autocomplete='email'/></label><label>First name<input name='firstName' required/></label><label>Middle name<input name='middleName'/></label><label>Last name<input name='lastName' required/></label><label>North Carolina State Bar number<input name='barNumber' required/></label><label>Firm / organization<input name='organization'/></label><label>Phone<input name='phone' type='tel'/></label><label>Password<input type='password' name='password' minlength='12' required autocomplete='new-password'/></label><button>Create account request</button></form><p><a href='/login'>Back to sign in</a></p></section></main>"""));
        });

        app.MapPost("/attorney/register",async(HttpContext ctx,IAntiforgery anti)=>
        {
            await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();var email=f["email"].ToString().Trim().ToLowerInvariant();var first=f["firstName"].ToString().Trim();var last=f["lastName"].ToString().Trim();var bar=f["barNumber"].ToString().Trim();var password=f["password"].ToString();if(string.IsNullOrWhiteSpace(email)||string.IsNullOrWhiteSpace(first)||string.IsNullOrWhiteSpace(last)||string.IsNullOrWhiteSpace(bar)||password.Length<12)return Results.BadRequest("Email, first/last name, bar number, and a password of at least 12 characters are required.");var salt=RandomNumberGenerator.GetBytes(32);var hash=Hash(password,salt);try{await Exec(dbPath,"""INSERT INTO PartnerAccounts(Id,Username,Role,FirstName,MiddleName,LastName,BarNumber,Organization,Phone,PasswordSalt,PasswordHash,Status,CreatedAt,UpdatedAt) VALUES($i,$u,'Attorney',$f,$m,$l,$b,$o,$p,$s,$h,'Pending Clerk Approval',$t,$t)""",("$i",Guid.NewGuid()),("$u",email),("$f",first),("$m",f["middleName"]),("$l",last),("$b",bar),("$o",f["organization"]),("$p",f["phone"]),("$s",Convert.ToBase64String(salt)),("$h",Convert.ToBase64String(hash)),("$t",Now()));}catch(SqliteException){return Results.Conflict(new{error="An account with that email or bar number already exists."});}return Html(Page("Registration submitted","<main class='login-shell'><section class='login-card'><h1>Registration submitted</h1><p>Your attorney account is pending court-clerk approval. Case access remains disabled until approval.</p><a class='button' href='/login'>Return to sign in</a></section></main>"));
        });

        app.MapGet("/clerk/attorneys",async(HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsClerk(ctx.User))return Results.Forbid();var t=anti.GetAndStoreTokens(ctx).RequestToken!;await using var cn=Open(dbPath);await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="SELECT Id,Username,FirstName,MiddleName,LastName,BarNumber,Organization,Status,CreatedAt FROM PartnerAccounts WHERE Role='Attorney' ORDER BY CASE WHEN Status='Pending Clerk Approval' THEN 0 ELSE 1 END,CreatedAt DESC";var rows=new List<string>();await using var r=await cmd.ExecuteReaderAsync();while(await r.ReadAsync()){var id=r.GetString(0);var status=r.GetString(7);var action=status=="Pending Clerk Approval"?$"<form method='post' action='/clerk/attorneys/{id}/status' style='display:flex;gap:.35rem'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><button name='status' value='Active'>Approve</button><button name='status' value='Denied' class='secondary'>Deny</button></form>":$"<span class='status'>{H(status)}</span>";rows.Add($"<tr><td><b>{H(r.GetString(1))}</b><small>{H(r.GetString(2))} {H(N(r,3))} {H(r.GetString(4))}</small></td><td>{H(r.GetString(5))}</td><td>{H(N(r,6))}</td><td>{action}</td><td><a href='/clerk/attorneys/{id}/assign'>Add case</a></td></tr>");}return Html(Page("Attorney accounts",$"<main class='wrap'><a class='back' href='/'>← CMPD Partners</a><section class='page-head'><div><span class='eyebrow'>COURT CLERK</span><h1>Attorney accounts</h1><p>Approve attorney access and add verified cases to an attorney workload.</p></div></section><section class='table-card'><table><thead><tr><th>Attorney</th><th>NC Bar #</th><th>Organization</th><th>Status</th><th>Workload</th></tr></thead><tbody>{string.Join("",rows)}</tbody></table></section></main>"));
        }).RequireAuthorization();

        app.MapPost("/clerk/attorneys/{id:guid}/status",async(Guid id,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsClerk(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();var status=f["status"].ToString();if(status is not ("Active" or "Denied" or "Suspended"))return Results.BadRequest("Invalid account status.");await Exec(dbPath,"UPDATE PartnerAccounts SET Status=$s,ApprovedBy=$by,ApprovedAt=$t,UpdatedAt=$t WHERE Id=$id AND Role='Attorney'",("$s",status),("$by",ctx.User.Identity?.Name??"clerk"),("$t",Now()),("$id",id));return Results.Redirect("/clerk/attorneys");
        }).RequireAuthorization();

        app.MapGet("/clerk/attorneys/{attorneyId:guid}/assign",async(Guid attorneyId,HttpContext ctx,IAntiforgery anti,string? complaintNumber,string? lastName,string? middleName,string? firstName,string? dateOfBirth)=>
        {
            if(!IsClerk(ctx.User))return Results.Forbid();var attorney=await LoadAttorney(dbPath,attorneyId);if(attorney is null)return Results.NotFound();var t=anti.GetAndStoreTokens(ctx).RequestToken!;string result="";if(!string.IsNullOrWhiteSpace(complaintNumber)){var match=await FindComplaint(dbPath,complaintNumber,lastName,middleName,firstName,dateOfBirth);result=match is null?"<div class='error'><b>No exact case match.</b><p>Complaint number and defendant first, middle, last name and date of birth must match the complaint record. Middle name may be blank only when the complaint has no middle name.</p></div>":$"""<div class='success'><b>Verified complaint match</b><p>{H(match.Value.Number)} · {H(match.Value.First)} {H(match.Value.Middle)} {H(match.Value.Last)} · DOB {H(match.Value.Dob)}</p></div><form method='post' action='/clerk/attorneys/{attorneyId}/assign'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><input type='hidden' name='complaintId' value='{match.Value.Id}'/><label>Representation role<select name='representationRole'><option>Defense Counsel</option><option>Appointed Counsel</option><option>Public Defender</option><option>Standby Counsel</option><option>Other</option></select></label><label>Clerk note<textarea name='note' rows='3'></textarea></label><button>Add case to attorney workload</button></form>""";}return Html(Page("Assign attorney case",$"""<main class='wrap'><a class='back' href='/clerk/attorneys'>← Attorney accounts</a><section class='page-head'><div><span class='eyebrow'>COURT CLERK · CASE ACCESS</span><h1>Add case to workload</h1><p>{H(attorney.Value.Name)} · NC Bar {H(attorney.Value.Bar)} · {H(attorney.Value.Status)}</p></div></section><section class='card'><div class='notice'><b>Exact identity verification required</b><p>Search requires complaint number plus defendant last, middle, first name and date of birth. The attorney cannot self-add a case.</p></div><form method='get'><label>Complaint number<input name='complaintNumber' value='{H(complaintNumber)}' required/></label><label>Last name<input name='lastName' value='{H(lastName)}' required/></label><label>Middle name<input name='middleName' value='{H(middleName)}'/></label><label>First name<input name='firstName' value='{H(firstName)}' required/></label><label>Date of birth<input name='dateOfBirth' value='{H(dateOfBirth)}' required placeholder='YYYY-MM-DD'/></label><button>Verify complaint</button></form></section>{result}</main>"""));
        }).RequireAuthorization();

        app.MapPost("/clerk/attorneys/{attorneyId:guid}/assign",async(Guid attorneyId,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsClerk(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var attorney=await LoadAttorney(dbPath,attorneyId);if(attorney is null||attorney.Value.Status!="Active")return Results.BadRequest("Attorney account must be active.");var f=await ctx.Request.ReadFormAsync();if(!Guid.TryParse(f["complaintId"],out var complaintId)||await ComplaintExists(dbPath,complaintId)==false)return Results.BadRequest("Valid complaint required.");try{await Exec(dbPath,"""INSERT INTO AttorneyCaseAssignments(Id,AttorneyAccountId,ComplaintId,RepresentationRole,Status,AssignedBy,AssignedAt,ClerkNote) VALUES($i,$a,$c,$r,'Active',$by,$t,$n)""",("$i",Guid.NewGuid()),("$a",attorneyId),("$c",complaintId),("$r",f["representationRole"]),("$by",ctx.User.Identity?.Name??"clerk"),("$t",Now()),("$n",f["note"]));}catch(SqliteException){return Results.Conflict(new{error="This case is already on the attorney's workload."});}return Results.Redirect($"/clerk/attorneys/{attorneyId}/assign");
        }).RequireAuthorization();

        app.MapGet("/attorney/cases",async(HttpContext ctx)=>
        {
            if(!IsAttorney(ctx.User))return Results.Forbid();var acct=await LoadAccountByUsername(dbPath,ctx.User.Identity?.Name??"");if(acct is null||acct.Value.Status!="Active")return Results.Forbid();await using var cn=Open(dbPath);await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="""SELECT d.Id,d.ComplaintNumber,d.IncidentNumber,d.SubjectFirstName,d.SubjectMiddleName,d.SubjectLastName,d.DateOfBirth,d.Status,a.RepresentationRole,a.AssignedAt FROM AttorneyCaseAssignments a JOIN DaComplaints d ON d.Id=a.ComplaintId WHERE a.AttorneyAccountId=$a AND a.Status='Active' ORDER BY a.AssignedAt DESC""";cmd.Parameters.AddWithValue("$a",acct.Value.Id.ToString());var rows=new List<string>();await using var r=await cmd.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<tr><td><a href='/attorney/cases/{r.GetString(0)}'><b>{H(r.GetString(1))}</b></a></td><td>{H(r.GetString(2))}</td><td>{H(N(r,3))} {H(N(r,4))} {H(N(r,5))}<small>{H(N(r,6))}</small></td><td>{H(r.GetString(7))}</td><td>{H(r.GetString(8))}</td><td>{H(r.GetString(9))}</td></tr>");return Html(Page("My cases",$"<main class='wrap'><a class='back' href='/'>← CMPD Partners</a><section class='page-head'><div><span class='eyebrow'>ATTORNEY</span><h1>My workload</h1><p>Cases added by an authorized court clerk.</p></div></section><section class='table-card'><table><thead><tr><th>Complaint</th><th>Incident</th><th>Defendant</th><th>Status</th><th>Role</th><th>Added</th></tr></thead><tbody>{(rows.Count>0?string.Join("",rows):"<tr><td colspan='6'>No cases assigned.</td></tr>")}</tbody></table></section></main>"));
        }).RequireAuthorization();

        app.MapGet("/attorney/cases/{complaintId:guid}",async(Guid complaintId,HttpContext ctx)=>
        {
            if(!IsAttorney(ctx.User))return Results.Forbid();var acct=await LoadAccountByUsername(dbPath,ctx.User.Identity?.Name??"");if(acct is null||acct.Value.Status!="Active")return Results.Forbid();await using var cn=Open(dbPath);await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="""SELECT d.ComplaintNumber,d.IncidentNumber,d.SubjectFirstName,d.SubjectMiddleName,d.SubjectLastName,d.DateOfBirth,d.ComplaintNarrative,d.ReviewRequest,d.Status,a.RepresentationRole FROM AttorneyCaseAssignments a JOIN DaComplaints d ON d.Id=a.ComplaintId WHERE a.AttorneyAccountId=$a AND a.ComplaintId=$c AND a.Status='Active'""";cmd.Parameters.AddWithValue("$a",acct.Value.Id.ToString());cmd.Parameters.AddWithValue("$c",complaintId.ToString());await using var r=await cmd.ExecuteReaderAsync();if(!await r.ReadAsync())return Results.Forbid();return Html(Page(r.GetString(0),$"<main class='wrap'><a class='back' href='/attorney/cases'>← My workload</a><section class='page-head'><div><span class='eyebrow'>ATTORNEY CASE · {H(r.GetString(8))}</span><h1>{H(r.GetString(0))}</h1><p>{H(N(r,2))} {H(N(r,3))} {H(N(r,4))} · DOB {H(N(r,5))}</p></div></section><section class='card'><dl><dt>Incident</dt><dd>{H(r.GetString(1))}</dd><dt>Representation</dt><dd>{H(r.GetString(9))}</dd></dl><h2>Complaint narrative</h2><p style='white-space:pre-wrap'>{H(r.GetString(6))}</p><h2>Requested prosecutorial review</h2><p style='white-space:pre-wrap'>{H(r.GetString(7))}</p></section></main>"));
        }).RequireAuthorization();
    }

    public static async Task<(string Username,string Role)?> AuthenticateAsync(string dbPath,string username,string password)
    {
        EnsureSchema(dbPath);await using var cn=Open(dbPath);await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="SELECT Username,Role,PasswordSalt,PasswordHash,Status FROM PartnerAccounts WHERE lower(Username)=lower($u)";cmd.Parameters.AddWithValue("$u",username.Trim());await using var r=await cmd.ExecuteReaderAsync();if(!await r.ReadAsync()||r.GetString(4)!="Active")return null;try{var salt=Convert.FromBase64String(r.GetString(2));var expected=Convert.FromBase64String(r.GetString(3));var actual=Hash(password,salt);return CryptographicOperations.FixedTimeEquals(expected,actual)?(r.GetString(0),r.GetString(1)):null;}catch{return null;}
    }

    private static byte[] Hash(string password,byte[] salt)=>Rfc2898DeriveBytes.Pbkdf2(password,salt,600_000,HashAlgorithmName.SHA256,32);
    private static async Task<(Guid Id,string Name,string Bar,string Status)?> LoadAttorney(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Id,FirstName,MiddleName,LastName,BarNumber,Status FROM PartnerAccounts WHERE Id=$i AND Role='Attorney'";c.Parameters.AddWithValue("$i",id.ToString());await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?(Guid.Parse(r.GetString(0)),string.Join(" ",new[]{r.GetString(1),N(r,2),r.GetString(3)}.Where(x=>!string.IsNullOrWhiteSpace(x))),r.GetString(4),r.GetString(5)):null;}
    private static async Task<(Guid Id,string Status)?> LoadAccountByUsername(string p,string u){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Id,Status FROM PartnerAccounts WHERE lower(Username)=lower($u)";c.Parameters.AddWithValue("$u",u);await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?(Guid.Parse(r.GetString(0)),r.GetString(1)):null;}
    private static async Task<(Guid Id,string Number,string First,string Middle,string Last,string Dob)?> FindComplaint(string p,string? number,string? last,string? middle,string? first,string? dob){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="""SELECT Id,ComplaintNumber,COALESCE(SubjectFirstName,''),COALESCE(SubjectMiddleName,''),COALESCE(SubjectLastName,''),COALESCE(DateOfBirth,'') FROM DaComplaints WHERE upper(ComplaintNumber)=upper($n) AND upper(COALESCE(SubjectLastName,''))=upper($l) AND upper(COALESCE(SubjectMiddleName,''))=upper($m) AND upper(COALESCE(SubjectFirstName,''))=upper($f) AND COALESCE(DateOfBirth,'')=$d LIMIT 1""";c.Parameters.AddWithValue("$n",(number??"").Trim());c.Parameters.AddWithValue("$l",(last??"").Trim());c.Parameters.AddWithValue("$m",(middle??"").Trim());c.Parameters.AddWithValue("$f",(first??"").Trim());c.Parameters.AddWithValue("$d",(dob??"").Trim());await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?(Guid.Parse(r.GetString(0)),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5)):null;}
    private static async Task<bool> ComplaintExists(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT 1 FROM DaComplaints WHERE Id=$i";c.Parameters.AddWithValue("$i",id.ToString());return await c.ExecuteScalarAsync()!=null;}
    private static async Task Exec(string p,string sql,params (string Key,object? Value)[] ps){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText=sql;foreach(var x in ps)c.Parameters.AddWithValue(x.Key,x.Value?.ToString()??"");await c.ExecuteNonQueryAsync();}
    private static void EnsureSchema(string p){Directory.CreateDirectory(Path.GetDirectoryName(p)!);using var cn=Open(p);cn.Open();using var c=cn.CreateCommand();c.CommandText="""CREATE TABLE IF NOT EXISTS PartnerAccounts(Id TEXT PRIMARY KEY,Username TEXT NOT NULL UNIQUE,Role TEXT NOT NULL,FirstName TEXT NOT NULL,MiddleName TEXT NULL,LastName TEXT NOT NULL,BarNumber TEXT NULL UNIQUE,Organization TEXT NULL,Phone TEXT NULL,PasswordSalt TEXT NOT NULL,PasswordHash TEXT NOT NULL,Status TEXT NOT NULL,CreatedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL,ApprovedBy TEXT NULL,ApprovedAt TEXT NULL);CREATE TABLE IF NOT EXISTS AttorneyCaseAssignments(Id TEXT PRIMARY KEY,AttorneyAccountId TEXT NOT NULL,ComplaintId TEXT NOT NULL,RepresentationRole TEXT NOT NULL,Status TEXT NOT NULL,AssignedBy TEXT NOT NULL,AssignedAt TEXT NOT NULL,ClerkNote TEXT NULL,UNIQUE(AttorneyAccountId,ComplaintId));CREATE INDEX IF NOT EXISTS IX_AttorneyCases_Attorney ON AttorneyCaseAssignments(AttorneyAccountId);""";c.ExecuteNonQuery();EnsureComplaintColumns(cn);}
    private static void EnsureComplaintColumns(SqliteConnection cn){var existing=new HashSet<string>(StringComparer.OrdinalIgnoreCase);using(var c=cn.CreateCommand()){c.CommandText="PRAGMA table_info(DaComplaints)";using var r=c.ExecuteReader();while(r.Read())existing.Add(r.GetString(1));}foreach(var col in new[]{("SubjectFirstName","TEXT NULL"),("SubjectMiddleName","TEXT NULL"),("SubjectLastName","TEXT NULL")})if(!existing.Contains(col.Item1)){using var alter=cn.CreateCommand();alter.CommandText=$"ALTER TABLE DaComplaints ADD COLUMN {col.Item1} {col.Item2}";alter.ExecuteNonQuery();}}
    private static SqliteConnection Open(string p)=>new($"Data Source={p}");private static string Now()=>DateTimeOffset.UtcNow.ToString("O");private static bool IsClerk(ClaimsPrincipal u)=>u.IsInRole("CourtClerk")||u.IsInRole("Administrator");private static bool IsAttorney(ClaimsPrincipal u)=>u.IsInRole("Attorney")||u.IsInRole("Administrator");private static string? N(SqliteDataReader r,int i)=>r.IsDBNull(i)?null:r.GetString(i);private static string H(string? s)=>WebUtility.HtmlEncode(s??"");private static IResult Html(string s)=>Results.Content(s,"text/html; charset=utf-8");private static string Page(string t,string b)=>$"<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>{H(t)} · CMPD Partners</title><link rel='stylesheet' href='/app.css'></head><body><header class='top'><a href='/' class='brand'>CMPD <span>Partners</span></a><div>Attorney & court clerk</div></header>{b}</body></html>";
}
