using System.Net;
using System.Security.Claims;
using System.Security.Cryptography;
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.Data.Sqlite;

namespace CltPlusPlus.Partners;

public static class BailBondsmanWorkflows
{
    public static void Map(WebApplication app,string justiceDb,string bailDb)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(bailDb)!);Ensure(bailDb);

        app.MapGet("/bondsman/register",(HttpContext ctx,IAntiforgery anti)=>
        {
            if(ctx.User.Identity?.IsAuthenticated==true)return Results.Redirect("/");var t=anti.GetAndStoreTokens(ctx).RequestToken!;
            return Html(Page("Bail bondsman registration",$"""<main class='login-shell'><section class='login-card'><span class='eyebrow'>BAIL BONDSMAN</span><h1>Create bondsman account</h1><p>Account approval is required before bond or offender information is available.</p><form method='post' action='/bondsman/register'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><label>Email<input type='email' name='email' required/></label><label>First name<input name='firstName' required/></label><label>Middle name<input name='middleName'/></label><label>Last name<input name='lastName' required/></label><label>Company / agency<input name='company' required/></label><label>NC license number<input name='licenseNumber' required/></label><label>License expiration<input type='date' name='licenseExpires' required/></label><label>Phone<input type='tel' name='phone' required/></label><label>Business address<textarea name='businessAddress' required></textarea></label><label>Password<input type='password' name='password' minlength='12' required/></label><button>Request account</button></form></section></main>"""));
        });

        app.MapPost("/bondsman/register",async(HttpContext ctx,IAntiforgery anti)=>
        {
            await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();var email=f["email"].ToString().Trim().ToLowerInvariant();var password=f["password"].ToString();if(email.Length==0||password.Length<12)return Results.BadRequest("Valid email and 12-character password required.");var salt=RandomNumberGenerator.GetBytes(32);var hash=Rfc2898DeriveBytes.Pbkdf2(password,salt,600000,HashAlgorithmName.SHA256,32);try{await Exec(bailDb,"""INSERT INTO BondsmanAccounts(Id,Username,FirstName,MiddleName,LastName,Company,LicenseNumber,LicenseExpires,Phone,BusinessAddress,PasswordSalt,PasswordHash,Status,CreatedAt,UpdatedAt) VALUES($i,$u,$f,$m,$l,$c,$lic,$exp,$p,$a,$s,$h,'Pending Clerk Approval',$t,$t)""",("$i",Guid.NewGuid()),("$u",email),("$f",f["firstName"]),("$m",f["middleName"]),("$l",f["lastName"]),("$c",f["company"]),("$lic",f["licenseNumber"]),("$exp",f["licenseExpires"]),("$p",f["phone"]),("$a",f["businessAddress"]),("$s",Convert.ToBase64String(salt)),("$h",Convert.ToBase64String(hash)),("$t",Now()));}catch(SqliteException){return Results.Conflict(new{error="Account or license already exists."});}return Html(Page("Registration submitted","<main class='login-shell'><section class='login-card'><h1>Registration submitted</h1><p>Your account is pending clerk approval.</p><a href='/login'>Return to sign in</a></section></main>"));
        });

        app.MapGet("/clerk/bondsmen",async(HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsClerk(ctx.User))return Results.Forbid();var t=anti.GetAndStoreTokens(ctx).RequestToken!;await using var cn=Open(bailDb);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Id,Username,FirstName,MiddleName,LastName,Company,LicenseNumber,LicenseExpires,Phone,Status FROM BondsmanAccounts ORDER BY CASE WHEN Status='Pending Clerk Approval' THEN 0 ELSE 1 END,CreatedAt DESC";var rows=new List<string>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync()){var action=r.GetString(9)=="Pending Clerk Approval"?$"<form method='post' action='/clerk/bondsmen/{r.GetString(0)}/status'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><button name='status' value='Active'>Approve</button> <button name='status' value='Denied'>Deny</button></form>":H(r.GetString(9));rows.Add($"<tr><td>{H(r.GetString(2))} {H(N(r,3))} {H(r.GetString(4))}<small>{H(r.GetString(1))}</small></td><td>{H(r.GetString(5))}</td><td>{H(r.GetString(6))}<small>Expires {H(r.GetString(7))}</small></td><td>{action}</td></tr>");}return Html(Page("Bondsmen",$"<main class='wrap'><a class='back' href='/'>← Justice Partners</a><section class='page-head'><div><span class='eyebrow'>COURT CLERK</span><h1>Bail bondsman accounts</h1></div></section><section class='table-card'><table><thead><tr><th>Bondsman</th><th>Company</th><th>License</th><th>Status</th></tr></thead><tbody>{string.Join("",rows)}</tbody></table></section></main>"));
        }).RequireAuthorization();

        app.MapPost("/clerk/bondsmen/{id:guid}/status",async(Guid id,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsClerk(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();var s=f["status"].ToString();if(s is not ("Active" or "Denied" or "Suspended"))return Results.BadRequest();await Exec(bailDb,"UPDATE BondsmanAccounts SET Status=$s,ApprovedBy=$by,ApprovedAt=$t,UpdatedAt=$t WHERE Id=$i",("$s",s),("$by",ctx.User.Identity?.Name??"clerk"),("$t",Now()),("$i",id));return Results.Redirect("/clerk/bondsmen");
        }).RequireAuthorization();

        app.MapGet("/bondsman",async(HttpContext ctx)=>
        {
            if(!IsBondsman(ctx.User)||!await Active(bailDb,ctx.User.Identity?.Name??""))return Results.Forbid();var rows=await CaseloadRows(justiceDb,bailDb,ctx.User.Identity?.Name??"");return Html(Page("My bonds",$"<main class='wrap'><a class='back' href='/'>← Justice Partners</a><section class='page-head'><div><span class='eyebrow'>BAIL BONDSMAN</span><h1>My bonded offenders</h1><p>Only offenders linked to your active bonds are shown.</p></div></section><section class='table-card'><table><thead><tr><th>Complaint</th><th>Offender</th><th>Bond</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows}</tbody></table></section></main>"));
        }).RequireAuthorization();

        app.MapGet("/bondsman/bonds/{postingId:guid}",async(Guid postingId,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsBondsman(ctx.User)||!await OwnsBond(justiceDb,bailDb,postingId,ctx.User.Identity?.Name??""))return Results.Forbid();var b=await Bond(justiceDb,postingId);if(b is null)return Results.NotFound();var t=anti.GetAndStoreTokens(ctx).RequestToken!;var meetings=await Meetings(bailDb,postingId);return Html(Page("Bond",$"""<main class='wrap'><a class='back' href='/bondsman'>← My bonds</a><section class='page-head'><div><span class='eyebrow'>BOND · {H(b.Value.Status)}</span><h1>{H(b.Value.Complaint)}</h1><p>{H(b.Value.Subject)}</p></div></section><div class='detail-grid'><section class='card'><dl><dt>Method</dt><dd>{H(b.Value.Method)}</dd><dt>Amount</dt><dd>{H(b.Value.Amount)}</dd><dt>Conditions</dt><dd>{H(b.Value.Conditions)}</dd></dl><h2>Virtual meetings</h2>{meetings}</section><aside><section class='card'><h2>Schedule virtual meeting</h2><div class='notice'><b>Private bondsman-client meeting</b><p>The offender receives a scoped anonymous link. Court, police, and prosecutor records are not exposed through that link.</p></div><form method='post' action='/bondsman/bonds/{postingId}/meetings'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><label>Date/time<input type='datetime-local' name='scheduledAt' required/></label><label>Duration minutes<input type='number' name='durationMinutes' min='10' max='180' value='30'/></label><label>Offender mobile phone<input type='tel' name='phone' required/></label><label>Purpose / agenda<textarea name='purpose' required></textarea></label><label><input type='checkbox' name='record' value='true'/> Record meeting with visible participant notice</label><button>Schedule meeting</button></form></section></aside></div></main>"""));
        }).RequireAuthorization();

        app.MapPost("/bondsman/bonds/{postingId:guid}/meetings",async(Guid postingId,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsBondsman(ctx.User)||!await OwnsBond(justiceDb,bailDb,postingId,ctx.User.Identity?.Name??""))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();if(!DateTimeOffset.TryParse(f["scheduledAt"],out var at))return Results.BadRequest("Valid meeting time required.");var raw=Convert.ToHexString(RandomNumberGenerator.GetBytes(32)).ToLowerInvariant();var hash=Convert.ToHexString(SHA256.HashData(System.Text.Encoding.UTF8.GetBytes(raw))).ToLowerInvariant();var id=Guid.NewGuid();await Exec(bailDb,"""INSERT INTO BondsmanVirtualMeetings(Id,BailPostingId,BondsmanUsername,ScheduledAt,DurationMinutes,OffenderPhone,Purpose,RoomName,InviteTokenHash,InviteRevoked,Status,RecordingRequested,RecordingStatus,CreatedAt,UpdatedAt) VALUES($i,$b,$u,$at,$d,$p,$purpose,$room,$h,0,'Scheduled',$rec,'Not started',$t,$t)""",("$i",id),("$b",postingId),("$u",ctx.User.Identity?.Name??"bondsman"),("$at",at.ToString("O")),("$d",f["durationMinutes"]),("$p",f["phone"]),("$purpose",f["purpose"]),("$room",$"cltpp-bond-{id:N}"),("$h",hash),("$rec",f["record"].ToString()=="true"?1:0),("$t",Now()));var baseUrl=app.Configuration["CLTPP_PUBLIC_BASE_URL"]?.TrimEnd('/')??$"{ctx.Request.Scheme}://{ctx.Request.Host}";var link=$"{baseUrl}/bond-meeting/{id}?token={raw}";await Exec(bailDb,"INSERT INTO BondsmanMeetingHistory(Id,MeetingId,Actor,Action,Detail,OccurredAt) VALUES($i,$m,$a,'Scheduled',$d,$t)",("$i",Guid.NewGuid()),("$m",id),("$a",ctx.User.Identity?.Name??"bondsman"),("$d",$"Scheduled {at:O}; invite {link}"),("$t",Now()));return Results.Redirect($"/bondsman/bonds/{postingId}");
        }).RequireAuthorization();

        app.MapGet("/bond-meeting/{id:guid}",async(Guid id,HttpContext ctx,string token)=>
        {
            var m=await MeetingByToken(bailDb,id,token);if(m is null)return Html(Page("Invalid meeting","<main class='login-shell'><section class='login-card'><h1>Meeting link unavailable</h1><p>This link is invalid, revoked, or expired.</p></section></main>"));var domain=app.Configuration["CLTPP_JITSI_DOMAIN"]??"meet.jit.si";var notice=m.Value.RecordingRequested?"<div class='notice'><b>Recording notice</b><p>This meeting is configured to be recorded. Joining acknowledges that visible recording notice has been provided. Recording must not begin covertly.</p></div>":"";return Html(Page("Bond meeting",$"""<main class='wrap'><section class='page-head'><div><span class='eyebrow'>VIRTUAL BOND MEETING</span><h1>Meeting with your bail bondsman</h1><p>{H(m.Value.Purpose)}</p></div></section>{notice}<section class='card'><div id='jitsi' style='min-height:560px'></div></section><script src='https://{H(domain)}/external_api.js'></script><script>new JitsiMeetExternalAPI('{Js(domain)}',{{roomName:'{Js(m.Value.Room)}',parentNode:document.querySelector('#jitsi'),userInfo:{{displayName:'Bond Client'}}}});</script></main>"""));
        });
    }

    public static async Task<(string Username,string Role)?> AuthenticateAsync(string bailDb,string username,string password){Ensure(bailDb);await using var cn=Open(bailDb);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Username,PasswordSalt,PasswordHash,Status FROM BondsmanAccounts WHERE lower(Username)=lower($u)";c.Parameters.AddWithValue("$u",username.Trim());await using var r=await c.ExecuteReaderAsync();if(!await r.ReadAsync()||r.GetString(3)!="Active")return null;try{var salt=Convert.FromBase64String(r.GetString(1));var expected=Convert.FromBase64String(r.GetString(2));var actual=Rfc2898DeriveBytes.Pbkdf2(password,salt,600000,HashAlgorithmName.SHA256,32);return CryptographicOperations.FixedTimeEquals(expected,actual)?(r.GetString(0),"BailBondsman"):null;}catch{return null;}}

    static async Task<string> CaseloadRows(string j,string b,string u){await using var cn=Open(j);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Id,ComplaintId,Method,Amount,Status FROM BailPostings WHERE lower(SubmittedBy)=lower($u) OR lower(COALESCE(SuretyLicenseOrReference,''))=lower((SELECT LicenseNumber FROM BondsmanAccounts LIMIT 0)) ORDER BY SubmittedAt DESC";c.Parameters.AddWithValue("$u",u);var rows=new List<string>();try{await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync()){var posting=Guid.Parse(r.GetString(0));var complaint=await Complaint(j,Guid.Parse(r.GetString(1)));if(complaint!=null)rows.Add($"<tr><td>{H(complaint.Value.Number)}</td><td>{H(complaint.Value.Subject)}</td><td>{H(r.GetString(2))} · {H(r.GetString(3))}</td><td>{H(r.GetString(4))}</td><td><a href='/bondsman/bonds/{posting}'>Manage</a></td></tr>");}}catch{}return rows.Count==0?"<tr><td colspan='5'>No bonded offenders.</td></tr>":string.Join("",rows);}
    static async Task<bool> OwnsBond(string j,string b,Guid posting,string u){await using var cn=Open(j);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT SubmittedBy,SuretyName,SuretyLicenseOrReference FROM BailPostings WHERE Id=$i";c.Parameters.AddWithValue("$i",posting.ToString());await using var r=await c.ExecuteReaderAsync();if(!await r.ReadAsync())return false;var submitted=r.GetString(0);if(string.Equals(submitted,u,StringComparison.OrdinalIgnoreCase))return true;var acct=await Account(b,u);return acct!=null&&(string.Equals(N(r,1),acct.Value.Company,StringComparison.OrdinalIgnoreCase)||string.Equals(N(r,2),acct.Value.License,StringComparison.OrdinalIgnoreCase));}
    static async Task<(string Company,string License)?> Account(string p,string u){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Company,LicenseNumber FROM BondsmanAccounts WHERE lower(Username)=lower($u) AND Status='Active'";c.Parameters.AddWithValue("$u",u);await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?(r.GetString(0),r.GetString(1)):null;}
    static async Task<bool> Active(string p,string u)=>await Account(p,u)!=null;
    static async Task<(string Complaint,string Subject,string Method,string Amount,string Status,string Conditions)?> Bond(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT d.ComplaintNumber,d.SubjectName,b.Method,b.Amount,b.Status,COALESCE(o.Conditions,'') FROM BailPostings b JOIN DaComplaints d ON d.Id=b.ComplaintId LEFT JOIN JudicialOrders o ON o.Id=b.JudicialOrderId WHERE b.Id=$i";c.Parameters.AddWithValue("$i",id.ToString());await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?(r.GetString(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5)):null;}
    static async Task<(string Number,string Subject)?> Complaint(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT ComplaintNumber,SubjectName FROM DaComplaints WHERE Id=$i";c.Parameters.AddWithValue("$i",id.ToString());await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?(r.GetString(0),r.GetString(1)):null;}
    static async Task<string> Meetings(string p,Guid bond){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT ScheduledAt,DurationMinutes,Purpose,Status,RecordingStatus FROM BondsmanVirtualMeetings WHERE BailPostingId=$b ORDER BY ScheduledAt DESC";c.Parameters.AddWithValue("$b",bond.ToString());var rows=new List<string>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<article><b>{H(r.GetString(0))} · {r.GetInt32(1)} min</b><p>{H(r.GetString(2))}</p><small>{H(r.GetString(3))} · recording {H(r.GetString(4))}</small></article>");return rows.Count==0?"<p class='muted'>No virtual meetings.</p>":string.Join("",rows);}
    static async Task<(string Room,string Purpose,bool RecordingRequested)?> MeetingByToken(string p,Guid id,string token){var hash=Convert.ToHexString(SHA256.HashData(System.Text.Encoding.UTF8.GetBytes(token??""))).ToLowerInvariant();await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT RoomName,Purpose,RecordingRequested FROM BondsmanVirtualMeetings WHERE Id=$i AND InviteTokenHash=$h AND InviteRevoked=0 AND Status='Scheduled'";c.Parameters.AddWithValue("$i",id.ToString());c.Parameters.AddWithValue("$h",hash);await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?(r.GetString(0),r.GetString(1),r.GetInt32(2)==1):null;}
    static bool IsBondsman(ClaimsPrincipal u)=>u.IsInRole("BailBondsman")||u.IsInRole("Administrator");static bool IsClerk(ClaimsPrincipal u)=>u.IsInRole("CourtClerk")||u.IsInRole("Administrator");
    static void Ensure(string p){using var cn=Open(p);cn.Open();var c=cn.CreateCommand();c.CommandText="""CREATE TABLE IF NOT EXISTS BondsmanAccounts(Id TEXT PRIMARY KEY,Username TEXT NOT NULL UNIQUE,FirstName TEXT NOT NULL,MiddleName TEXT,LastName TEXT NOT NULL,Company TEXT NOT NULL,LicenseNumber TEXT NOT NULL UNIQUE,LicenseExpires TEXT NOT NULL,Phone TEXT NOT NULL,BusinessAddress TEXT NOT NULL,PasswordSalt TEXT NOT NULL,PasswordHash TEXT NOT NULL,Status TEXT NOT NULL,ApprovedBy TEXT,ApprovedAt TEXT,CreatedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL);CREATE TABLE IF NOT EXISTS BondsmanVirtualMeetings(Id TEXT PRIMARY KEY,BailPostingId TEXT NOT NULL,BondsmanUsername TEXT NOT NULL,ScheduledAt TEXT NOT NULL,DurationMinutes INTEGER NOT NULL,OffenderPhone TEXT NOT NULL,Purpose TEXT NOT NULL,RoomName TEXT NOT NULL,InviteTokenHash TEXT NOT NULL,InviteRevoked INTEGER NOT NULL,Status TEXT NOT NULL,RecordingRequested INTEGER NOT NULL,RecordingStatus TEXT NOT NULL,RecordingReference TEXT,CreatedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL);CREATE TABLE IF NOT EXISTS BondsmanMeetingHistory(Id TEXT PRIMARY KEY,MeetingId TEXT NOT NULL,Actor TEXT NOT NULL,Action TEXT NOT NULL,Detail TEXT NOT NULL,OccurredAt TEXT NOT NULL);CREATE INDEX IF NOT EXISTS IX_BondsmanMeeting_Bond ON BondsmanVirtualMeetings(BailPostingId,ScheduledAt);""";c.ExecuteNonQuery();}
    static SqliteConnection Open(string p)=>new($"Data Source={p}");static async Task Exec(string p,string sql,params(string,object?)[] ps){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText=sql;foreach(var x in ps)c.Parameters.AddWithValue(x.Item1,x.Item2?.ToString()??"");await c.ExecuteNonQueryAsync();}static string? N(SqliteDataReader r,int i)=>r.IsDBNull(i)?null:r.GetString(i);static string Now()=>DateTimeOffset.UtcNow.ToString("O");static string H(object? x)=>WebUtility.HtmlEncode(x?.ToString()??"");static string Js(string s)=>s.Replace("\\","\\\\").Replace("'","\\'");static IResult Html(string x)=>Results.Content(x,"text/html; charset=utf-8");static string Page(string t,string b)=>$"<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width'><title>{H(t)} · CLT++ Justice Partners</title><link rel='stylesheet' href='/app.css'></head><body>{b}</body></html>";
}
