using System.Net;
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.Data.Sqlite;

namespace CltPlusPlus.Partners;

public static class BailWorkflows
{
    public static void Map(WebApplication app,string dbPath)
    {
        Ensure(dbPath);
        app.MapGet("/bail",async(HttpContext ctx,IAntiforgery anti,string? complaintNumber)=>
        {
            if(!CanUse(ctx.User))return Results.Forbid();var t=anti.GetAndStoreTokens(ctx).RequestToken!;
            var caseHtml=string.IsNullOrWhiteSpace(complaintNumber)?"":await CaseHtml(dbPath,complaintNumber,t,ctx.User.IsInRole("CountyJail")||ctx.User.IsInRole("CourtClerk"));
            return Html(Page("Post bail",$"""<main class='wrap'><a class='back' href='/'>← Justice Partners</a><section class='page-head'><div><span class='eyebrow'>PRETRIAL RELEASE</span><h1>Post bail / satisfy release conditions</h1><p>Records satisfaction of a judicially ordered release condition. This screen does not set or modify bail.</p></div></section><div class='notice'><b>Release requires verification.</b><p>A payment or surety submission does not itself release the defendant. An authorized judicial, law-enforcement, or custodial official must verify that all release conditions have been met.</p></div><form class='filters' method='get'><input name='complaintNumber' value='{H(complaintNumber)}' placeholder='Complaint number' required/><button>Find case</button></form>{caseHtml}</main>"""));
        }).RequireAuthorization();

        app.MapPost("/bail/{complaintId:guid}/submit",async(Guid complaintId,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!CanUse(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var order=await ActiveReleaseOrder(dbPath,complaintId);if(order is null)return Results.BadRequest("No active judicial release order with a bond condition was found.");var f=await ctx.Request.ReadFormAsync();var method=f["method"].ToString();if(!new[]{"Cash deposit","Surety","Mortgage"}.Contains(method))return Results.BadRequest("Invalid bail method.");var id=Guid.NewGuid();await Exec(dbPath,"INSERT INTO BailPostings(Id,ComplaintId,JudicialOrderId,Method,Amount,PayerName,PayerRelationship,SuretyName,SuretyLicenseOrReference,ReceiptReference,Status,SubmittedBy,SubmittedAt) VALUES($i,$c,$o,$m,$a,$p,$pr,$s,$sr,$rr,'Submitted - verification required',$by,$t)",("$i",id),("$c",complaintId),("$o",order.Value.Id),("$m",method),("$a",f["amount"]),("$p",f["payerName"]),("$pr",f["payerRelationship"]),("$s",f["suretyName"]),("$sr",f["suretyReference"]),("$rr",f["receiptReference"]),("$by",ctx.User.Identity?.Name??"defendant"),("$t",Now()));return Results.Redirect($"/bail?complaintNumber={Uri.EscapeDataString(order.Value.ComplaintNumber)}");
        }).RequireAuthorization();

        app.MapPost("/bail/postings/{id:guid}/verify",async(Guid id,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!ctx.User.IsInRole("CountyJail")&&!ctx.User.IsInRole("CourtClerk"))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();var status=f["status"].ToString();if(status!="Verified"&&status!="Rejected")return Results.BadRequest();await Exec(dbPath,"UPDATE BailPostings SET Status=$s,VerifiedBy=$by,VerifiedAt=$t,VerificationNotes=$n WHERE Id=$i AND Status='Submitted - verification required'",("$s",status),("$by",ctx.User.Identity?.Name??"official"),("$t",Now()),("$n",f["notes"]),("$i",id));return Results.Redirect("/bail?complaintNumber="+Uri.EscapeDataString(f["complaintNumber"]));
        }).RequireAuthorization();
    }

    static async Task<string> CaseHtml(string p,string number,string token,bool verifier){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Id,ComplaintNumber,SubjectName FROM DaComplaints WHERE ComplaintNumber=$n";c.Parameters.AddWithValue("$n",number);await using var r=await c.ExecuteReaderAsync();if(!await r.ReadAsync())return "<section class='card'><p>No complaint found.</p></section>";var id=Guid.Parse(r.GetString(0));var subject=r.GetString(2);await r.CloseAsync();var order=await ActiveReleaseOrder(p,id);if(order is null)return $"<section class='card'><h2>{H(number)}</h2><p>{H(subject)}</p><div class='notice'><b>No payable bail condition found.</b><p>The defendant cannot use this workflow until an authorized judicial official has entered an active release order requiring a secured appearance bond.</p></div></section>";var postings=await Postings(p,id,token,number,verifier);return $"""<section class='card'><span class='eyebrow'>ACTIVE JUDICIAL RELEASE ORDER</span><h2>{H(number)} · {H(subject)}</h2><dl><dt>Release type</dt><dd>{H(order.Value.ReleaseType)}</dd><dt>Bond amount</dt><dd>{H(order.Value.Amount)}</dd><dt>Conditions</dt><dd>{H(order.Value.Conditions)}</dd><dt>Issued by</dt><dd>{H(order.Value.IssuedBy)}</dd></dl><h3>Submit bail</h3><form method='post' action='/bail/{id}/submit'><input type='hidden' name='__RequestVerificationToken' value='{H(token)}'/><label>Method<select name='method'><option>Cash deposit</option><option>Surety</option><option>Mortgage</option></select></label><label>Amount / value<input name='amount' required/></label><label>Payer / surety principal<input name='payerName' required/></label><label>Relationship to defendant<input name='payerRelationship'/></label><label>Surety / bonding entity<input name='suretyName'/></label><label>Surety license or reference<input name='suretyReference'/></label><label>Payment/receipt reference<input name='receiptReference'/></label><button>Submit for official verification</button></form></section><section class='card'><h2>Bail submissions</h2>{postings}</section>""";}
    static async Task<string> Postings(string p,Guid id,string token,string complaint,bool verifier){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Id,Method,Amount,PayerName,Status,SubmittedBy,SubmittedAt,COALESCE(VerifiedBy,''),COALESCE(VerifiedAt,''),COALESCE(VerificationNotes,'') FROM BailPostings WHERE ComplaintId=$c ORDER BY SubmittedAt DESC";c.Parameters.AddWithValue("$c",id);var rows=new List<string>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync()){var verify=verifier&&r.GetString(4)=="Submitted - verification required"?$"<form method='post' action='/bail/postings/{r.GetString(0)}/verify'><input type='hidden' name='__RequestVerificationToken' value='{H(token)}'/><input type='hidden' name='complaintNumber' value='{H(complaint)}'/><label>Official notes<textarea name='notes'></textarea></label><button name='status' value='Verified'>Verify conditions met</button> <button name='status' value='Rejected'>Reject</button></form>":"";rows.Add($"<article><b>{H(r.GetString(1))} · {H(r.GetString(2))}</b><small>{H(r.GetString(4))} · submitted {H(r.GetString(6))} by {H(r.GetString(5))}</small><p>Payer: {H(r.GetString(3))}</p>{verify}</article>");}return rows.Count==0?"<p class='muted'>No bail submissions.</p>":string.Join("",rows);}
    static async Task<(Guid Id,string ComplaintNumber,string ReleaseType,string Amount,string Conditions,string IssuedBy)?> ActiveReleaseOrder(string p,Guid complaint){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT o.Id,d.ComplaintNumber,COALESCE(o.ReleaseType,''),COALESCE(o.BondAmount,''),COALESCE(o.Conditions,''),o.IssuedBy FROM JudicialOrders o JOIN DaComplaints d ON d.Id=o.ComplaintId WHERE o.ComplaintId=$c AND o.Status='Active' AND COALESCE(o.BondAmount,'')<>'' ORDER BY o.IssuedAt DESC LIMIT 1";c.Parameters.AddWithValue("$c",complaint);await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?(Guid.Parse(r.GetString(0)),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5)):null;}
    static bool CanUse(System.Security.Claims.ClaimsPrincipal u)=>u.Identity?.IsAuthenticated==true;
    static void Ensure(string p){using var cn=Open(p);cn.Open();using var c=cn.CreateCommand();c.CommandText="CREATE TABLE IF NOT EXISTS BailPostings(Id TEXT PRIMARY KEY,ComplaintId TEXT NOT NULL,JudicialOrderId TEXT NOT NULL,Method TEXT NOT NULL,Amount TEXT NOT NULL,PayerName TEXT NOT NULL,PayerRelationship TEXT NULL,SuretyName TEXT NULL,SuretyLicenseOrReference TEXT NULL,ReceiptReference TEXT NULL,Status TEXT NOT NULL,SubmittedBy TEXT NOT NULL,SubmittedAt TEXT NOT NULL,VerifiedBy TEXT NULL,VerifiedAt TEXT NULL,VerificationNotes TEXT NULL);CREATE INDEX IF NOT EXISTS IX_BailPostings_Complaint ON BailPostings(ComplaintId,SubmittedAt);";c.ExecuteNonQuery();}
    static SqliteConnection Open(string p)=>new($"Data Source={p}");static async Task Exec(string p,string sql,params(string,object?)[] ps){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText=sql;foreach(var x in ps)c.Parameters.AddWithValue(x.Item1,x.Item2?.ToString()??"");await c.ExecuteNonQueryAsync();}static string Now()=>DateTimeOffset.UtcNow.ToString("O");static string H(object? x)=>WebUtility.HtmlEncode(x?.ToString()??"");static IResult Html(string x)=>Results.Content(x,"text/html; charset=utf-8");static string Page(string t,string b)=>$"<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width'><title>{H(t)} · CLT++</title><link rel='stylesheet' href='/app.css'></head><body>{b}</body></html>";
}
