using System.Net;
using System.Security.Claims;
using System.Security.Cryptography;
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.Data.Sqlite;

namespace CltPlusPlus.Partners;

public static class BailBondsmanWorkflows
{
    public static void Map(WebApplication app,string justiceDb,string bailDb)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(bailDb)!);Ensure(bailDb);
        app.MapGet("/bondsman/register",(HttpContext ctx,IAntiforgery anti)=>{if(ctx.User.Identity?.IsAuthenticated==true)return Results.Redirect("/");var t=anti.GetAndStoreTokens(ctx).RequestToken!;return Html(Page("Bondsman registration",$"<main class='login-shell'><section class='login-card'><h1>Bail bondsman registration</h1><form method='post' action='/bondsman/register'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><label>Email<input type='email' name='email' required/></label><label>First name<input name='firstName' required/></label><label>Middle name<input name='middleName'/></label><label>Last name<input name='lastName' required/></label><label>Company<input name='company' required/></label><label>NC license number<input name='licenseNumber' required/></label><label>License expiration<input type='date' name='licenseExpires' required/></label><label>Phone<input type='tel' name='phone' required/></label><label>Business address<textarea name='businessAddress' required></textarea></label><label>Password<input type='password' minlength='12' name='password' required/></label><button>Request account</button></form></section></main>"));});
        app.MapPost("/bondsman/register",async(HttpContext ctx,IAntiforgery anti)=>{await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();var u=f["email"].ToString().Trim().ToLowerInvariant();var pw=f["password"].ToString();if(u.Length==0||pw.Length<12)return Results.BadRequest();var salt=RandomNumberGenerator.GetBytes(32);var hash=Rfc2898DeriveBytes.Pbkdf2(pw,salt,600000,HashAlgorithmName.SHA256,32);try{await Exec(bailDb,"INSERT INTO BondsmanAccounts(Id,Username,FirstName,MiddleName,LastName,Company,LicenseNumber,LicenseExpires,Phone,BusinessAddress,PasswordSalt,PasswordHash,Status,CreatedAt,UpdatedAt) VALUES($i,$u,$f,$m,$l,$c,$lic,$e,$p,$a,$s,$h,'Pending Clerk Approval',$t,$t)",( "$i",Guid.NewGuid()),("$u",u),("$f",f["firstName"]),("$m",f["middleName"]),("$l",f["lastName"]),("$c",f["company"]),("$lic",f["licenseNumber"]),("$e",f["licenseExpires"]),("$p",f["phone"]),("$a",f["businessAddress"]),("$s",Convert.ToBase64String(salt)),("$h",Convert.ToBase64String(hash)),("$t",Now()));}catch(SqliteException){return Results.Conflict(new{error="Account or license already exists."});}return Html(Page("Submitted","<main class='login-shell'><section class='login-card'><h1>Registration submitted</h1><p>Access remains disabled until clerk approval.</p></section></main>"));});
        app.MapGet("/clerk/bondsmen",async(HttpContext ctx,IAntiforgery anti)=>{if(!IsClerk(ctx.User))return Results.Forbid();var t=anti.GetAndStoreTokens(ctx).RequestToken!;await using var cn=Open(bailDb);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Id,Username,FirstName,MiddleName,LastName,Company,LicenseNumber,LicenseExpires,Status FROM BondsmanAccounts ORDER BY CASE WHEN Status='Pending Clerk Approval' THEN 0 ELSE 1 END,CreatedAt DESC";var rows=new List<string>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync()){var a=r.GetString(8)=="Pending Clerk Approval"?$"<form method='post' action='/clerk/bondsmen/{r.GetString(0)}/status'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><button name='status' value='Active'>Approve</button> <button name='status' value='Denied'>Deny</button></form>":H(r.GetString(8));rows.Add($"<tr><td>{H(r.GetString(2))} {H(N(r,3))} {H(r.GetString(4))}<small>{H(r.GetString(1))}</small></td><td>{H(r.GetString(5))}</td><td>{H(r.GetString(6))}<small>Expires {H(r.GetString(7))}</small></td><td>{a}</td></tr>");}return Html(Page("Bondsmen",$"<main class='wrap'><h1>Bail bondsman accounts</h1><table><tbody>{string.Join("",rows)}</tbody></table></main>"));}).RequireAuthorization();
        app.MapPost("/clerk/bondsmen/{id:guid}/status",async(Guid id,HttpContext ctx,IAntiforgery anti)=>{if(!IsClerk(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();var s=f["status"].ToString();if(s is not ("Active" or "Denied" or "Suspended"))return Results.BadRequest();await Exec(bailDb,"UPDATE BondsmanAccounts SET Status=$s,ApprovedBy=$by,ApprovedAt=$t,UpdatedAt=$t WHERE Id=$i",("$s",s),("$by",ctx.User.Identity?.Name??"clerk"),("$t",Now()),("$i",id));return Results.Redirect("/clerk/bondsmen");}).RequireAuthorization();
        app.MapGet("/bondsman",async(HttpContext ctx)=>{if(!IsBondsman(ctx.User)||!await Active(bailDb,ctx.User.Identity?.Name??""))return Results.Forbid();var u=ctx.User.Identity?.Name??"";await using var cn=Open(justiceDb);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT b.Id,d.ComplaintNumber,d.SubjectName,b.Method,b.Amount,b.Status FROM BailPostings b JOIN DaComplaints d ON d.Id=b.ComplaintId WHERE lower(b.SubmittedBy)=lower($u) ORDER BY b.SubmittedAt DESC";c.Parameters.AddWithValue("$u",u);var rows=new List<string>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<tr><td>{H(r.GetString(1))}</td><td>{H(r.GetString(2))}</td><td>{H(r.GetString(3))} · {H(r.GetString(4))}</td><td>{H(r.GetString(5))}</td><td><a href='/bondsman/bonds/{r.GetString(0)}'>Manage</a></td></tr>");return Html(Page("My bonds",$"<main class='wrap'><section class='page-head'><div><h1>My bonded offenders</h1><p>Only bonds submitted by this bondsman account are visible.</p></div><a class='button' href='/bail'>Post bond</a></section><table><tbody>{(rows.Count>0?string.Join("",rows):"<tr><td>No active bonds.</td></tr>")}</tbody></table></main>"));}).RequireAuthorization();
        app.MapGet("/bondsman/bonds/{postingId:guid}",async(Guid postingId,HttpContext ctx,IAntiforgery anti)=>{if(!IsBondsman(ctx.User)||!await Owns(justiceDb,postingId,ctx.User.Identity?.Name??""))return Results.Forbid();var b=await Bond(justiceDb,postingId);if(b is null)return Results.NotFound();var t=anti.GetAndStoreTokens(ctx).RequestToken!;var meetings=await MeetingList(bailDb,postingId);return Html(Page("Bond",$"""<main class='wrap'><a href='/bondsman'>← My bonds</a><section class='card'><h1>{H(b.Value.Complaint)} · {H(b.Value.Subject)}</h1><p>{H(b.Value.Method)} · {H(b.Value.Amount)} · {H(b.Value.Status)}</p><p>{H(b.Value.Conditions)}</p><h2>Virtual meetings</h2>{meetings}</section><section class='card'><h2>Schedule virtual meeting</h2><form method='post' action='/bondsman/bonds/{postingId}/meetings'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><label>Date/time<input type='datetime-local' name='scheduledAt' required/></label><label>Duration minutes<input type='number' name='durationMinutes' value='30' min='10' max='180'/></label><label>Offender mobile<input type='tel' name='phone' required/></label><label>Purpose<textarea name='purpose' required></textarea></label><label><input type='checkbox' name='record' value='true'/> Record with visible notice</label><button>Schedule meeting</button></form></section></main>"""));}).RequireAuthorization();
        app.MapPost("/bondsman/bonds/{postingId:guid}/meetings",async(Guid postingId,HttpContext ctx,IAntiforgery anti)=>{if(!IsBondsman(ctx.User)||!await Owns(justiceDb,postingId,ctx.User.Identity?.Name??""))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();if(!DateTimeOffset.TryParse(f["scheduledAt"],out var at))return Results.BadRequest();var token=Convert.ToHexString(RandomNumberGenerator.GetBytes(32)).ToLowerInvariant();var hash=HashToken(token);var id=Guid.NewGuid();await Exec(bailDb,"INSERT INTO BondsmanVirtualMeetings(Id,BailPostingId,BondsmanUsername,ScheduledAt,DurationMinutes,OffenderPhone,Purpose,RoomName,InviteTokenHash,InviteRevoked,Status,RecordingRequested,RecordingStatus,CreatedAt,UpdatedAt) VALUES($i,$b,$u,$at,$d,$p,$purpose,$room,$h,0,'Scheduled',$rec,'Not started',$t,$t)",( "$i",id),("$b",postingId),("$u",ctx.User.Identity?.Name??"bondsman"),("$at",at.ToString("O")),("$d",f["durationMinutes"]),("$p",f["phone"]),("$purpose",f["purpose"]),("$room",$"cltpp-bond-{id:N}"),("$h",hash),("$rec",f["record"].ToString()=="true"?1:0),("$t",Now()));var baseUrl=app.Configuration["CLTPP_PUBLIC_BASE_URL"]?.TrimEnd('/')??$"{ctx.Request.Scheme}://{ctx.Request.Host}";var link=$"{baseUrl}/bond-meeting/{id}?token={token}";await Exec(bailDb,"INSERT INTO BondsmanMeetingHistory(Id,MeetingId,Actor,Action,Detail,OccurredAt) VALUES($i,$m,$a,'Scheduled',$d,$t)",( "$i",Guid.NewGuid()),("$m",id),("$a",ctx.User.Identity?.Name??"bondsman"),("$d",$"Scheduled {at:O}; offender link {link}"),("$t",Now()));return Results.Redirect($"/bondsman/bonds/{postingId}");}).RequireAuthorization();
        app.MapGet("/bond-meeting/{id:guid}",async(Guid id,string token)=>{var m=await LoadMeeting(bailDb,id,token);if(m is null)return Results.NotFound();var domain=app.Configuration["CLTPP_JITSI_DOMAIN"]??"meet.jit.si";var notice=m.Value.Record?"<div class='notice'><b>Recording notice</b><p>This meeting is configured to be recorded. Recording must be visible to participants and may not begin covertly.</p></div>":"";return Html(Page("Bond meeting",$"<main class='wrap'><h1>Virtual meeting with your bail bondsman</h1><p>{H(m.Value.Purpose)}</p>{notice}<div id='jitsi' style='min-height:560px'></div><script src='https://{H(domain)}/external_api.js'></script><script>new JitsiMeetExternalAPI('{Js(domain)}',{{roomName:'{Js(m.Value.Room)}',parentNode:document.querySelector('#jitsi'),userInfo:{{displayName:'Bond Client'}}}});</script></main>"));});
    }
    public static async Task<(string Username,string Role)?> AuthenticateAsync(string bailDb,string username,string password){Ensure(bailDb);await using var cn=Open(bailDb);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Username,PasswordSalt,PasswordHash,Status FROM BondsmanAccounts WHERE lower(Username)=lower($u)";c.Parameters.AddWithValue("$u",username.Trim());await using var r=await c.ExecuteReaderAsync();if(!await r.ReadAsync()||r.GetString(3)!="Active")return null;try{var salt=Convert.FromBase64String(r.GetString(1));var expected=Convert.FromBase64String(r.GetString(2));var actual=Rfc2898DeriveBytes.Pbkdf2(password,salt,600000,HashAlgorithmName.SHA256,32);return CryptographicOperations.FixedTimeEquals(expected,actual)?(r.GetString(0),"BailBondsman"):null;}catch{return null;}}
    static async Task<bool> Owns(string p,Guid id,string u){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT 1 FROM BailPostings WHERE Id=$i AND lower(SubmittedBy)=lower($u)";c.Parameters.AddWithValue("$i",id.ToString());c.Parameters.AddWithValue("$u",u);return await c.ExecuteScalarAsync()!=null;}
    static async Task<(string Complaint,string Subject,string Method,string Amount,string Status,string Conditions)?> Bond(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT d.ComplaintNumber,d.SubjectName,b.Method,b.Amount,b.Status,COALESCE(o.Conditions,'') FROM BailPostings b JOIN DaComplaints d ON d.Id=b.ComplaintId LEFT JOIN JudicialOrders o ON o.Id=b.JudicialOrderId WHERE b.Id=$i";c.Parameters.AddWithValue("$i",id.ToString());await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?(r.GetString(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5)):null;}
    static async Task<bool> Active(string p,string u){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT 1 FROM BondsmanAccounts WHERE lower(Username)=lower($u) AND Status='Active'";c.Parameters.AddWithValue("$u",u);return await c.ExecuteScalarAsync()!=null;}
    static async Task<string> MeetingList(string p,Guid b){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT ScheduledAt,DurationMinutes,Purpose,Status,RecordingStatus FROM BondsmanVirtualMeetings WHERE BailPostingId=$b ORDER BY ScheduledAt DESC";c.Parameters.AddWithValue("$b",b.ToString());var rows=new List<string>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<article><b>{H(r.GetString(0))} · {r.GetInt32(1)} min</b><p>{H(r.GetString(2))}</p><small>{H(r.GetString(3))} · recording {H(r.GetString(4))}</small></article>");return rows.Count==0?"<p>No virtual meetings scheduled.</p>":string.Join("",rows);}
    static async Task<(string Room,string Purpose,bool Record)?> LoadMeeting(string p,Guid id,string token){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT RoomName,Purpose,RecordingRequested FROM BondsmanVirtualMeetings WHERE Id=$i AND InviteTokenHash=$h AND InviteRevoked=0 AND Status='Scheduled'";c.Parameters.AddWithValue("$i",id.ToString());c.Parameters.AddWithValue("$h",HashToken(token));await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?(r.GetString(0),r.GetString(1),r.GetInt32(2)==1):null;}
    static string HashToken(string t)=>Convert.ToHexString(SHA256.HashData(System.Text.Encoding.UTF8.GetBytes(t??""))).ToLowerInvariant();static bool IsBondsman(ClaimsPrincipal u)=>u.IsInRole("BailBondsman")||u.IsInRole("Administrator");static bool IsClerk(ClaimsPrincipal u)=>u.IsInRole("CourtClerk")||u.IsInRole("Administrator");
    static void Ensure(string p){using var cn=Open(p);cn.Open();var c=cn.CreateCommand();c.CommandText="CREATE TABLE IF NOT EXISTS BondsmanAccounts(Id TEXT PRIMARY KEY,Username TEXT NOT NULL UNIQUE,FirstName TEXT NOT NULL,MiddleName TEXT,LastName TEXT NOT NULL,Company TEXT NOT NULL,LicenseNumber TEXT NOT NULL UNIQUE,LicenseExpires TEXT NOT NULL,Phone TEXT NOT NULL,BusinessAddress TEXT NOT NULL,PasswordSalt TEXT NOT NULL,PasswordHash TEXT NOT NULL,Status TEXT NOT NULL,ApprovedBy TEXT,ApprovedAt TEXT,CreatedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL);CREATE TABLE IF NOT EXISTS BondsmanVirtualMeetings(Id TEXT PRIMARY KEY,BailPostingId TEXT NOT NULL,BondsmanUsername TEXT NOT NULL,ScheduledAt TEXT NOT NULL,DurationMinutes INTEGER NOT NULL,OffenderPhone TEXT NOT NULL,Purpose TEXT NOT NULL,RoomName TEXT NOT NULL,InviteTokenHash TEXT NOT NULL,InviteRevoked INTEGER NOT NULL,Status TEXT NOT NULL,RecordingRequested INTEGER NOT NULL,RecordingStatus TEXT NOT NULL,RecordingReference TEXT,CreatedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL);CREATE TABLE IF NOT EXISTS BondsmanMeetingHistory(Id TEXT PRIMARY KEY,MeetingId TEXT NOT NULL,Actor TEXT NOT NULL,Action TEXT NOT NULL,Detail TEXT NOT NULL,OccurredAt TEXT NOT NULL);";c.ExecuteNonQuery();}
    static SqliteConnection Open(string p)=>new($"Data Source={p}");static async Task Exec(string p,string sql,params(string,object?)[] ps){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText=sql;foreach(var x in ps)c.Parameters.AddWithValue(x.Item1,x.Item2?.ToString()??"");await c.ExecuteNonQueryAsync();}static string? N(SqliteDataReader r,int i)=>r.IsDBNull(i)?null:r.GetString(i);static string Now()=>DateTimeOffset.UtcNow.ToString("O");static string H(object? x)=>WebUtility.HtmlEncode(x?.ToString()??"");static string Js(string s)=>s.Replace("\\","\\\\").Replace("'","\\'");static IResult Html(string x)=>Results.Content(x,"text/html; charset=utf-8");static string Page(string t,string b)=>$"<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width'><title>{H(t)} · CLT++ Justice Partners</title><link rel='stylesheet' href='/app.css'></head><body>{b}</body></html>";
}
