using System.Net;
using System.Security.Claims;
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.Data.Sqlite;

namespace CltPlusPlus.Partners;

public static class CriminalJusticeWorkflows
{
    public static void Map(WebApplication app, string dbPath)
    {
        EnsureSchema(dbPath);

        app.MapGet("/criminal-justice", async (HttpContext ctx, string? q, string? status) =>
        {
            if (!CanJustice(ctx.User)) return Results.Forbid();
            await using var cn = Open(dbPath); await cn.OpenAsync();
            var cmd = cn.CreateCommand();
            cmd.CommandText = """SELECT Id,ComplaintNumber,IncidentNumber,SubjectName,Status,FiledBy,FiledAt FROM DaComplaints WHERE ($q='' OR ComplaintNumber LIKE $like OR IncidentNumber LIKE $like OR SubjectName LIKE $like) AND ($status='' OR Status=$status) ORDER BY FiledAt DESC LIMIT 300""";
            cmd.Parameters.AddWithValue("$q", q ?? ""); cmd.Parameters.AddWithValue("$like", "%" + (q ?? "") + "%"); cmd.Parameters.AddWithValue("$status", status ?? "");
            var rows = new List<string>(); await using var r = await cmd.ExecuteReaderAsync();
            while (await r.ReadAsync()) rows.Add($"<tr><td><a href='/criminal-justice/complaints/{r.GetString(0)}'><b>{H(r.GetString(1))}</b></a></td><td>{H(r.GetString(2))}</td><td>{H(r.GetString(3))}</td><td><span class='status'>{H(r.GetString(4))}</span></td><td>{H(r.GetString(5))}</td><td>{H(r.GetString(6))}</td></tr>");
            return Html(Page("Criminal justice", $"""<main class='wrap'><a class='back' href='/'>← CMPD Partners</a><section class='page-head'><div><span class='eyebrow'>NORTH CAROLINA CRIMINAL PROCESS</span><h1>Complaints & cases</h1><p>Human-entered prosecutor and judicial workflow records linked to police-filed DA complaints.</p></div></section><div class='notice'><b>Decision support is not automated.</b><p>CLT++ does not recommend charges, probable cause, release conditions, guilt, plea terms, or sentence. Authorized officials record their own decisions.</p></div><form class='filters'><input name='q' value='{H(q)}' placeholder='Complaint, incident, defendant'/><select name='status'><option value=''>All statuses</option>{Opts(new[]{"Filed","DA Review","Accepted for Prosecution","Declined","Dismissed","Pending Court","Disposed","Closed"},status)}</select><button>Search</button></form><section class='table-card'><table><thead><tr><th>Complaint</th><th>Incident</th><th>Defendant</th><th>Status</th><th>Filed by</th><th>Filed</th></tr></thead><tbody>{(rows.Count>0?string.Join("",rows):"<tr><td colspan='6'>No complaints found.</td></tr>")}</tbody></table></section></main>"""));
        }).RequireAuthorization();

        app.MapGet("/criminal-justice/complaints/{id:guid}", async (Guid id, HttpContext ctx, IAntiforgery anti) =>
        {
            if (!CanJustice(ctx.User)) return Results.Forbid();
            var c = await LoadComplaint(dbPath,id); if(c is null) return Results.NotFound();
            var token=anti.GetAndStoreTokens(ctx).RequestToken!; var report=await ReportHtml(dbPath,c.Value.ExpressReportId);
            var notes=await NotesHtml(dbPath,id); var charges=await ChargesHtml(dbPath,id); var events=await EventsHtml(dbPath,id); var orders=await OrdersHtml(dbPath,id); var disposition=await DispositionHtml(dbPath,id); var history=await HistoryHtml(dbPath,id);
            var da=IsDa(ctx.User)?DaPanel(id,token,c.Value.Status):""; var judge=IsJudge(ctx.User)?JudgePanel(id,token,c.Value.SubjectName,c.Value.IncidentNumber):"";
            return Html(Page(c.Value.Number,$"""<main class='wrap'><a class='back' href='/criminal-justice'>← Complaints & cases</a><section class='page-head'><div><span class='eyebrow'>DA COMPLAINT · {H(c.Value.Status)}</span><h1>{H(c.Value.Number)}</h1><p>{H(c.Value.SubjectName)} · Incident {H(c.Value.IncidentNumber)}</p></div></section><div class='detail-grid'><section><section class='card'><h2>Complaint</h2><dl><dt>DOB</dt><dd>{H(c.Value.Dob)}</dd><dt>Filed by</dt><dd>{H(c.Value.FiledBy)}</dd><dt>Filed</dt><dd>{H(c.Value.FiledAt)}</dd><dt>Requested review</dt><dd>{H(c.Value.ReviewRequest)}</dd></dl><h3>Officer complaint narrative</h3><p style='white-space:pre-wrap'>{H(c.Value.Narrative)}</p><h3>Supporting references</h3><p style='white-space:pre-wrap'>{H(c.Value.Supporting)}</p></section>{report}<section class='card'><h2>Charges</h2>{charges}</section><section class='card'><h2>Court events</h2>{events}</section><section class='card'><h2>Judicial orders & findings</h2>{orders}</section><section class='card'><h2>Plea / disposition / judgment</h2>{disposition}</section><section class='card'><h2>Case history</h2>{history}</section></section><aside>{da}{judge}<section class='card'><h2>DA notes</h2>{notes}</section></aside></div></main>"""));
        }).RequireAuthorization();

        app.MapPost("/criminal-justice/complaints/{id:guid}/notes", async (Guid id,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsDa(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);if(await LoadComplaint(dbPath,id) is null)return Results.NotFound();var f=await ctx.Request.ReadFormAsync();var note=f["note"].ToString().Trim();if(note.Length==0)return Results.BadRequest("Note is required.");await Exec(dbPath,"INSERT INTO DaComplaintNotes(Id,ComplaintId,Author,Note,CreatedAt) VALUES($i,$c,$a,$n,$t)",("$i",Guid.NewGuid().ToString()),("$c",id.ToString()),("$a",ctx.User.Identity?.Name??"prosecutor"),("$n",note),("$t",Now()));await Audit(dbPath,id,ctx.User,"DA note added","Prosecutor work-product note recorded.");return Results.Redirect($"/criminal-justice/complaints/{id}");
        }).RequireAuthorization();

        app.MapPost("/criminal-justice/complaints/{id:guid}/da-status", async(Guid id,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsDa(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();var s=f["status"].ToString();var allowed=new[]{"DA Review","Accepted for Prosecution","Declined","Dismissed","Deferred","Referred","Pending Court","Disposed","Closed"};if(!allowed.Contains(s))return Results.BadRequest("Invalid status.");await Exec(dbPath,"UPDATE DaComplaints SET Status=$s,UpdatedAt=$t WHERE Id=$id",("$s",s),("$t",Now()),("$id",id.ToString()));await Audit(dbPath,id,ctx.User,"DA status",s+": "+f["reason"]);return Results.Redirect($"/criminal-justice/complaints/{id}");
        }).RequireAuthorization();

        app.MapPost("/criminal-justice/complaints/{id:guid}/charges",async(Guid id,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsDa(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);if(await LoadComplaint(dbPath,id)is null)return Results.NotFound();var f=await ctx.Request.ReadFormAsync();var statute=f["statute"].ToString().Trim();var title=f["title"].ToString().Trim();var level=f["level"].ToString().Trim();if(new[]{statute,title,level}.Any(string.IsNullOrWhiteSpace))return Results.BadRequest("Statute, offense, and level/class are required.");var chargeId=Guid.NewGuid();await Exec(dbPath,"""INSERT INTO DaComplaintCharges(Id,ComplaintId,StatuteCitation,OffenseTitle,OffenseLevel,CountNumber,Allegation,Status,SourceVersion,CreatedBy,CreatedAt,UpdatedAt) VALUES($i,$c,$s,$o,$l,$count,$a,'Proposed',$v,$by,$t,$t)""",("$i",chargeId.ToString()),("$c",id.ToString()),("$s",statute),("$o",title),("$l",level),("$count",f["count"]),("$a",f["allegation"]),("$v",f["sourceVersion"]),("$by",ctx.User.Identity?.Name??"prosecutor"),("$t",Now()));await Audit(dbPath,id,ctx.User,"Charge added",$"{statute} {title} ({level})");return Results.Redirect($"/criminal-justice/complaints/{id}");
        }).RequireAuthorization();

        app.MapPost("/criminal-justice/complaints/{id:guid}/events",async(Guid id,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!CanJustice(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();var type=f["eventType"].ToString().Trim();var date=f["eventDate"].ToString().Trim();if(type.Length==0||date.Length==0)return Results.BadRequest("Event type and date are required.");await Exec(dbPath,"""INSERT INTO CriminalCourtEvents(Id,ComplaintId,EventType,CourtLevel,ScheduledAt,Result,ContinuanceReason,NextDate,Notes,RecordedBy,RecordedAt) VALUES($i,$c,$e,$level,$d,$r,$cr,$next,$n,$by,$t)""",("$i",Guid.NewGuid().ToString()),("$c",id.ToString()),("$e",type),("$level",f["courtLevel"]),("$d",date),("$r",f["result"]),("$cr",f["continuanceReason"]),("$next",f["nextDate"]),("$n",f["notes"]),("$by",ctx.User.Identity?.Name??"partner"),("$t",Now()));await Audit(dbPath,id,ctx.User,"Court event",type+" · "+f["result"]);return Results.Redirect($"/criminal-justice/complaints/{id}");
        }).RequireAuthorization();

        app.MapPost("/criminal-justice/complaints/{id:guid}/judicial-order",async(Guid id,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsJudge(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();var type=f["orderType"].ToString().Trim();var finding=f["finding"].ToString().Trim();if(type.Length==0||finding.Length==0)return Results.BadRequest("Order/finding type and judicial finding are required.");var orderId=Guid.NewGuid();await Exec(dbPath,"""INSERT INTO JudicialOrders(Id,ComplaintId,OrderType,Finding,ReleaseType,BondAmount,Conditions,EffectiveAt,Status,IssuedBy,IssuedAt,UpdatedAt) VALUES($i,$c,$o,$f,$r,$b,$cond,$e,'Active',$by,$t,$t)""",("$i",orderId.ToString()),("$c",id.ToString()),("$o",type),("$f",finding),("$r",f["releaseType"]),("$b",f["bondAmount"]),("$cond",f["conditions"]),("$e",f["effectiveAt"]),("$by",ctx.User.Identity?.Name??"judge"),("$t",Now()));await Audit(dbPath,id,ctx.User,"Judicial order",type+": "+finding);return Results.Redirect($"/criminal-justice/complaints/{id}");
        }).RequireAuthorization();

        app.MapPost("/criminal-justice/complaints/{id:guid}/disposition",async(Guid id,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!CanJustice(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();var type=f["dispositionType"].ToString().Trim();if(type.Length==0)return Results.BadRequest("Disposition is required.");var judicial=IsJudge(ctx.User);var da=IsDa(ctx.User);if(!judicial&&!da)return Results.Forbid();await Exec(dbPath,"""INSERT INTO CriminalDispositions(Id,ComplaintId,DispositionType,Plea,Adjudication,SentenceType,ActiveMonths,IntermediateMonths,CommunityMonths,Fine,Restitution,ProbationConditions,AppealNotice,Notes,RecordedBy,RecordedAt) VALUES($i,$c,$d,$p,$a,$s,$am,$im,$cm,$fine,$rest,$pc,$appeal,$n,$by,$t)""",("$i",Guid.NewGuid().ToString()),("$c",id.ToString()),("$d",type),("$p",f["plea"]),("$a",f["adjudication"]),("$s",f["sentenceType"]),("$am",f["activeMonths"]),("$im",f["intermediateMonths"]),("$cm",f["communityMonths"]),("$fine",f["fine"]),("$rest",f["restitution"]),("$pc",f["probationConditions"]),("$appeal",f["appealNotice"]),("$n",f["notes"]),("$by",ctx.User.Identity?.Name??"partner"),("$t",Now()));await Exec(dbPath,"UPDATE DaComplaints SET Status='Disposed',UpdatedAt=$t WHERE Id=$id",("$t",Now()),("$id",id.ToString()));await Audit(dbPath,id,ctx.User,"Disposition",type);return Results.Redirect($"/criminal-justice/complaints/{id}");
        }).RequireAuthorization();

        app.MapGet("/judge/warrants",async(HttpContext ctx)=>
        {
            if(!IsJudge(ctx.User))return Results.Forbid();await using var cn=Open(dbPath);await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="SELECT Id,WarrantNumber,SubjectName,IncidentNumber,Status,IssuedAt,RecalledAt,ServedAt FROM ArrestWarrants ORDER BY IssuedAt DESC LIMIT 500";var rows=new List<string>();await using var r=await cmd.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<tr><td><a href='/judge/warrants/{r.GetString(0)}'><b>{H(r.GetString(1))}</b></a></td><td>{H(r.GetString(2))}</td><td>{H(r.GetString(3))}</td><td>{H(r.GetString(4))}</td><td>{H(r.GetString(5))}</td><td>{H(N(r,6))}</td><td>{H(N(r,7))}</td></tr>");return Html(Page("Warrants",$"<main class='wrap'><a class='back' href='/'>← CMPD Partners</a><section class='page-head'><div><span class='eyebrow'>JUDGE</span><h1>Arrest warrants</h1><p>Issue and recall judicial warrants. Served status is recorded by law enforcement.</p></div></section><section class='table-card'><table><thead><tr><th>Warrant</th><th>Subject</th><th>Incident</th><th>Status</th><th>Issued</th><th>Recalled</th><th>Served</th></tr></thead><tbody>{string.Join("",rows)}</tbody></table></section></main>"));
        }).RequireAuthorization();

        app.MapGet("/judge/warrants/{id:guid}",async(Guid id,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsJudge(ctx.User))return Results.Forbid();var w=await LoadWarrant(dbPath,id);if(w is null)return Results.NotFound();var t=anti.GetAndStoreTokens(ctx).RequestToken!;var recall=w.Value.Status=="Active"?$"<section class='card'><h2>Recall warrant</h2><form method='post' action='/judge/warrants/{id}/recall'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><label>Recall reason<textarea name='reason' required rows='5'></textarea></label><button>Recall warrant</button></form></section>":"";return Html(Page(w.Value.Number,$"<main class='wrap'><a class='back' href='/judge/warrants'>← Warrants</a><section class='page-head'><div><span class='eyebrow'>WARRANT · {H(w.Value.Status)}</span><h1>{H(w.Value.Number)}</h1><p>{H(w.Value.Subject)}</p></div></section><div class='detail-grid'><section class='card'><dl><dt>Incident</dt><dd>{H(w.Value.Incident)}</dd><dt>DOB</dt><dd>{H(w.Value.Dob)}</dd><dt>License / ID</dt><dd>{H(w.Value.License)}</dd><dt>Issued by</dt><dd>{H(w.Value.IssuedBy)}</dd><dt>Issued</dt><dd>{H(w.Value.IssuedAt)}</dd></dl><h2>Charges</h2><p>{H(w.Value.Charges)}</p><h2>Probable-cause / judicial basis</h2><p style='white-space:pre-wrap'>{H(w.Value.Basis)}</p></section><aside>{recall}</aside></div></main>"));
        }).RequireAuthorization();

        app.MapPost("/judge/warrants/{id:guid}/recall",async(Guid id,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsJudge(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();var reason=f["reason"].ToString().Trim();if(reason.Length==0)return Results.BadRequest("Recall reason is required.");var who=ctx.User.Identity?.Name??"judge";await using var cn=Open(dbPath);await cn.OpenAsync();await using var tx=await cn.BeginTransactionAsync();var cmd=cn.CreateCommand();cmd.Transaction=tx;cmd.CommandText="UPDATE ArrestWarrants SET Status='Recalled',RecalledBy=$by,RecalledAt=$t,RecallReason=$r,UpdatedAt=$t WHERE Id=$id AND Status='Active'";cmd.Parameters.AddWithValue("$by",who);cmd.Parameters.AddWithValue("$t",Now());cmd.Parameters.AddWithValue("$r",reason);cmd.Parameters.AddWithValue("$id",id.ToString());if(await cmd.ExecuteNonQueryAsync()!=1){await tx.RollbackAsync();return Results.Conflict(new{error="Only an active warrant can be recalled."});}var hist=cn.CreateCommand();hist.Transaction=tx;hist.CommandText="INSERT INTO WarrantHistory(Id,WarrantId,Actor,Action,Detail,OccurredAt) VALUES($i,$w,$a,'Recalled',$d,$t)";hist.Parameters.AddWithValue("$i",Guid.NewGuid().ToString());hist.Parameters.AddWithValue("$w",id.ToString());hist.Parameters.AddWithValue("$a",who);hist.Parameters.AddWithValue("$d",reason);hist.Parameters.AddWithValue("$t",Now());await hist.ExecuteNonQueryAsync();await tx.CommitAsync();return Results.Redirect($"/judge/warrants/{id}");
        }).RequireAuthorization();
    }

    private static string DaPanel(Guid id,string t,string status)=>$"""<section class='card'><h2>District Attorney</h2><form method='post' action='/criminal-justice/complaints/{id}/da-status'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><label>Complaint status<select name='status'>{Opts(new[]{"DA Review","Accepted for Prosecution","Declined","Dismissed","Deferred","Referred","Pending Court","Disposed","Closed"},status)}</select></label><label>Reason / disposition note<textarea name='reason' rows='3'></textarea></label><button>Update DA status</button></form><hr/><form method='post' action='/criminal-justice/complaints/{id}/notes'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><label>DA work-product note<textarea name='note' rows='5' required></textarea></label><button>Add note</button></form><hr/><h3>Add charge</h3><div class='notice'><b>Prosecutor selection required</b><p>Verify the current statute and classification. CLT++ does not select charges.</p></div><form method='post' action='/criminal-justice/complaints/{id}/charges'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><label>NC General Statute<input name='statute' placeholder='14-72' required/></label><label>Offense title<input name='title' required/></label><label>Level / class<select name='level' required><option value=''>Select</option>{Opts(new[]{"Class A felony","Class B1 felony","Class B2 felony","Class C felony","Class D felony","Class E felony","Class F felony","Class G felony","Class H felony","Class I felony","Class A1 misdemeanor","Class 1 misdemeanor","Class 2 misdemeanor","Class 3 misdemeanor","Infraction / other"},null)}</select></label><label>Count<input name='count' value='1'/></label><label>Allegation<textarea name='allegation' rows='4'></textarea></label><input type='hidden' name='sourceVersion' value='NC General Statutes through S.L. 2026-30'/><button>Add proposed charge</button></form>{EventForm(id,t,true)}{DispositionForm(id,t)}""";
    private static string JudgePanel(Guid id,string t,string subject,string incident)=>$"""<section class='card'><h2>Judge</h2><div class='notice'><b>Independent judicial decision required</b><p>Record the judge's own findings; CLT++ does not calculate probable cause, bond, or sentence.</p></div><form method='post' action='/criminal-justice/complaints/{id}/judicial-order'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><label>Order / finding<select name='orderType'>{Opts(new[]{"First Appearance","Probable Cause Finding","Probable Cause Waived / Bind Over","Pretrial Release Order","Bond Modification","Conditions of Release","Continuance Order","Motion Ruling","Order for Arrest","Failure to Appear Order","Competency / Capacity Order","Probation Violation Order","Judgment / Sentencing Order","Other Judicial Order"},null)}</select></label><label>Judicial finding / ruling<textarea name='finding' rows='6' required></textarea></label><label>Release type<select name='releaseType'><option></option>{Opts(new[]{"Written Promise","Unsecured Bond","Custody Release","Secured Bond","Electronic Monitoring / Other Conditions","No release ordered / statutory hold","Not applicable"},null)}</select></label><label>Bond amount<input name='bondAmount' inputmode='decimal'/></label><label>Conditions<textarea name='conditions' rows='4'></textarea></label><label>Effective date/time<input type='datetime-local' name='effectiveAt'/></label><button>Record judicial order</button></form>{EventForm(id,t,false)}{DispositionForm(id,t)}<p><a class='button' href='/judge/warrants'>View warrant docket</a></p></section>""";
    private static string EventForm(Guid id,string t,bool da)=>$"""<hr/><h3>Record court event</h3><form method='post' action='/criminal-justice/complaints/{id}/events'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><label>Event type<select name='eventType'>{Opts(new[]{"Initial Appearance","First Appearance","Bond Review","Probable Cause Hearing","District Court Setting","District Court Trial","Grand Jury / Indictment","Superior Court Arraignment","Plea Hearing","Motion Hearing","Superior Court Trial","Sentencing","Probation Review / Violation","Appeal / Notice of Appeal","Remand","Other"},null)}</select></label><label>Court level<select name='courtLevel'><option>Magistrate</option><option>District Court</option><option>Superior Court</option><option>Appellate</option></select></label><label>Date/time<input type='datetime-local' name='eventDate' required/></label><label>Result<textarea name='result' rows='3'></textarea></label><label>Continuance reason<textarea name='continuanceReason' rows='2'></textarea></label><label>Next date<input type='datetime-local' name='nextDate'/></label><label>Notes<textarea name='notes' rows='3'></textarea></label><button>Record event</button></form>""";
    private static string DispositionForm(Guid id,string t)=>$"""<hr/><h3>Plea / disposition / judgment</h3><form method='post' action='/criminal-justice/complaints/{id}/disposition'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><label>Disposition<select name='dispositionType'>{Opts(new[]{"Dismissed","Deferred Prosecution","Plea Accepted","Guilty Verdict","Not Guilty / Acquitted","Prayer for Judgment Continued","Judgment Entered","Probation Violation Disposition","Remanded","Other"},null)}</select></label><label>Plea<input name='plea'/></label><label>Adjudication / findings<textarea name='adjudication' rows='3'></textarea></label><label>Sentence type<select name='sentenceType'><option></option><option>Active</option><option>Intermediate</option><option>Community</option><option>Fine / costs only</option><option>Not applicable</option></select></label><label>Active months<input name='activeMonths'/></label><label>Intermediate months<input name='intermediateMonths'/></label><label>Community / probation months<input name='communityMonths'/></label><label>Fine / costs<input name='fine'/></label><label>Restitution<input name='restitution'/></label><label>Probation / special conditions<textarea name='probationConditions' rows='4'></textarea></label><label>Appeal / notice<textarea name='appealNotice' rows='2'></textarea></label><label>Notes<textarea name='notes' rows='3'></textarea></label><button>Record disposition</button></form>""";

    private static async Task<(Guid Id,string Number,Guid ExpressReportId,string IncidentNumber,string SubjectName,string? Dob,string Narrative,string ReviewRequest,string? Supporting,string Status,string FiledBy,string FiledAt)?> LoadComplaint(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Id,ComplaintNumber,ExpressReportId,IncidentNumber,SubjectName,DateOfBirth,ComplaintNarrative,ReviewRequest,SupportingReferences,Status,FiledBy,FiledAt FROM DaComplaints WHERE Id=$id";c.Parameters.AddWithValue("$id",id.ToString());await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?(Guid.Parse(r.GetString(0)),r.GetString(1),Guid.Parse(r.GetString(2)),r.GetString(3),r.GetString(4),N(r,5),r.GetString(6),r.GetString(7),N(r,8),r.GetString(9),r.GetString(10),r.GetString(11)):null;}
    private static async Task<(string Number,string Subject,string Incident,string Status,string Charges,string Basis,string? Dob,string? License,string IssuedBy,string IssuedAt)?> LoadWarrant(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT WarrantNumber,SubjectName,IncidentNumber,Status,Charges,JudicialBasis,DateOfBirth,LicenseId,IssuedBy,IssuedAt FROM ArrestWarrants WHERE Id=$id";c.Parameters.AddWithValue("$id",id.ToString());await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?(r.GetString(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5),N(r,6),N(r,7),r.GetString(8),r.GetString(9)):null;}
    private static async Task<string> ReportHtml(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT ReportNumber,Status,COALESCE(Title,''),COALESCE(Transcript,''),COALESCE(Location,''),CreatedBy,CreatedAt FROM ExpressReports WHERE Id=$id";c.Parameters.AddWithValue("$id",id.ToString());await using var r=await c.ExecuteReaderAsync();if(!await r.ReadAsync())return "<section class='card'><h2>Linked Express Report</h2><p>Report unavailable.</p></section>";return $"<section class='card'><h2>Linked Express Report · read only</h2><dl><dt>Report</dt><dd>{H(r.GetString(0))}</dd><dt>Status</dt><dd>{H(r.GetString(1))}</dd><dt>Location</dt><dd>{H(r.GetString(4))}</dd><dt>Officer</dt><dd>{H(r.GetString(5))}</dd></dl><h3>{H(r.GetString(2))}</h3><p style='white-space:pre-wrap'>{H(r.GetString(3))}</p></section>";}
    private static async Task<string> NotesHtml(string p,Guid id)=>await ListHtml(p,"SELECT Author,CreatedAt,Note FROM DaComplaintNotes WHERE ComplaintId=$id ORDER BY CreatedAt DESC",id,r=>$"<article><b>{H(r.GetString(0))}</b><small>{H(r.GetString(1))}</small><p>{H(r.GetString(2))}</p></article>","No DA notes.");
    private static async Task<string> ChargesHtml(string p,Guid id)=>await ListHtml(p,"SELECT StatuteCitation,OffenseTitle,OffenseLevel,CountNumber,Status,CreatedBy,CreatedAt FROM DaComplaintCharges WHERE ComplaintId=$id ORDER BY CreatedAt",id,r=>$"<article><b>{H(r.GetString(0))} · {H(r.GetString(1))}</b><span>{H(r.GetString(2))} · Count {H(N(r,3))} · {H(r.GetString(4))}</span><small>{H(r.GetString(5))} · {H(r.GetString(6))}</small></article>","No charges recorded.");
    private static async Task<string> EventsHtml(string p,Guid id)=>await ListHtml(p,"SELECT EventType,CourtLevel,ScheduledAt,Result,NextDate,RecordedBy FROM CriminalCourtEvents WHERE ComplaintId=$id ORDER BY ScheduledAt",id,r=>$"<article><b>{H(r.GetString(0))} · {H(r.GetString(1))}</b><span>{H(r.GetString(2))}</span><p>{H(N(r,3))}</p><small>Next: {H(N(r,4))} · {H(r.GetString(5))}</small></article>","No court events recorded.");
    private static async Task<string> OrdersHtml(string p,Guid id)=>await ListHtml(p,"SELECT OrderType,Finding,ReleaseType,BondAmount,Conditions,Status,IssuedBy,IssuedAt FROM JudicialOrders WHERE ComplaintId=$id ORDER BY IssuedAt DESC",id,r=>$"<article><b>{H(r.GetString(0))} · {H(r.GetString(5))}</b><p>{H(r.GetString(1))}</p><span>{H(N(r,2))} {H(N(r,3))}</span><p>{H(N(r,4))}</p><small>{H(r.GetString(6))} · {H(r.GetString(7))}</small></article>","No judicial orders recorded.");
    private static async Task<string> DispositionHtml(string p,Guid id)=>await ListHtml(p,"SELECT DispositionType,Plea,Adjudication,SentenceType,ActiveMonths,IntermediateMonths,CommunityMonths,Fine,Restitution,AppealNotice,RecordedBy,RecordedAt FROM CriminalDispositions WHERE ComplaintId=$id ORDER BY RecordedAt DESC",id,r=>$"<article><b>{H(r.GetString(0))}</b><span>Plea: {H(N(r,1))} · {H(N(r,3))}</span><p>{H(N(r,2))}</p><small>Active {H(N(r,4))} mo · Intermediate {H(N(r,5))} mo · Community {H(N(r,6))} mo · Fine {H(N(r,7))} · Restitution {H(N(r,8))}</small><p>{H(N(r,9))}</p><small>{H(r.GetString(10))} · {H(r.GetString(11))}</small></article>","No disposition recorded.");
    private static async Task<string> HistoryHtml(string p,Guid id)=>await ListHtml(p,"SELECT Actor,Action,Detail,OccurredAt FROM CriminalJusticeAudit WHERE ComplaintId=$id ORDER BY OccurredAt DESC",id,r=>$"<article><b>{H(r.GetString(1))}</b><small>{H(r.GetString(0))} · {H(r.GetString(3))}</small><p>{H(r.GetString(2))}</p></article>","No history recorded.");
    private static async Task<string> ListHtml(string p,string sql,Guid id,Func<SqliteDataReader,string> row,string empty){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText=sql;c.Parameters.AddWithValue("$id",id.ToString());var list=new List<string>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync())list.Add(row(r));return list.Count==0?$"<p class='muted'>{H(empty)}</p>":string.Join("",list);}
    private static async Task Exec(string p,string sql,params (string Key,object? Value)[] ps){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText=sql;foreach(var x in ps)c.Parameters.AddWithValue(x.Key,x.Value?.ToString()??"");await c.ExecuteNonQueryAsync();}
    private static async Task Audit(string p,Guid id,ClaimsPrincipal u,string action,string detail)=>await Exec(p,"INSERT INTO CriminalJusticeAudit(Id,ComplaintId,Actor,Role,Action,Detail,OccurredAt) VALUES($i,$c,$a,$r,$x,$d,$t)",("$i",Guid.NewGuid()),("$c",id),("$a",u.Identity?.Name??"partner"),("$r",u.FindFirstValue(ClaimTypes.Role)??"Partner"),("$x",action),("$d",detail),("$t",Now()));
    private static void EnsureSchema(string p){Directory.CreateDirectory(Path.GetDirectoryName(p)!);using var cn=Open(p);cn.Open();using var c=cn.CreateCommand();c.CommandText="""
CREATE TABLE IF NOT EXISTS DaComplaintNotes(Id TEXT PRIMARY KEY,ComplaintId TEXT NOT NULL,Author TEXT NOT NULL,Note TEXT NOT NULL,CreatedAt TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS DaComplaintCharges(Id TEXT PRIMARY KEY,ComplaintId TEXT NOT NULL,StatuteCitation TEXT NOT NULL,OffenseTitle TEXT NOT NULL,OffenseLevel TEXT NOT NULL,CountNumber TEXT NULL,Allegation TEXT NULL,Status TEXT NOT NULL,SourceVersion TEXT NOT NULL,CreatedBy TEXT NOT NULL,CreatedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS CriminalCourtEvents(Id TEXT PRIMARY KEY,ComplaintId TEXT NOT NULL,EventType TEXT NOT NULL,CourtLevel TEXT NOT NULL,ScheduledAt TEXT NOT NULL,Result TEXT NULL,ContinuanceReason TEXT NULL,NextDate TEXT NULL,Notes TEXT NULL,RecordedBy TEXT NOT NULL,RecordedAt TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS JudicialOrders(Id TEXT PRIMARY KEY,ComplaintId TEXT NOT NULL,OrderType TEXT NOT NULL,Finding TEXT NOT NULL,ReleaseType TEXT NULL,BondAmount TEXT NULL,Conditions TEXT NULL,EffectiveAt TEXT NULL,Status TEXT NOT NULL,IssuedBy TEXT NOT NULL,IssuedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS CriminalDispositions(Id TEXT PRIMARY KEY,ComplaintId TEXT NOT NULL,DispositionType TEXT NOT NULL,Plea TEXT NULL,Adjudication TEXT NULL,SentenceType TEXT NULL,ActiveMonths TEXT NULL,IntermediateMonths TEXT NULL,CommunityMonths TEXT NULL,Fine TEXT NULL,Restitution TEXT NULL,ProbationConditions TEXT NULL,AppealNotice TEXT NULL,Notes TEXT NULL,RecordedBy TEXT NOT NULL,RecordedAt TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS CriminalJusticeAudit(Id TEXT PRIMARY KEY,ComplaintId TEXT NOT NULL,Actor TEXT NOT NULL,Role TEXT NOT NULL,Action TEXT NOT NULL,Detail TEXT NOT NULL,OccurredAt TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS IX_DaComplaintNotes_Complaint ON DaComplaintNotes(ComplaintId);CREATE INDEX IF NOT EXISTS IX_DaCharges_Complaint ON DaComplaintCharges(ComplaintId);CREATE INDEX IF NOT EXISTS IX_CourtEvents_Complaint ON CriminalCourtEvents(ComplaintId);CREATE INDEX IF NOT EXISTS IX_JudicialOrders_Complaint ON JudicialOrders(ComplaintId);CREATE INDEX IF NOT EXISTS IX_Dispositions_Complaint ON CriminalDispositions(ComplaintId);CREATE INDEX IF NOT EXISTS IX_CriminalAudit_Complaint ON CriminalJusticeAudit(ComplaintId);
""";c.ExecuteNonQuery();}
    private static SqliteConnection Open(string p)=>new($"Data Source={p}"); private static string Now()=>DateTimeOffset.UtcNow.ToString("O");
    private static bool IsDa(ClaimsPrincipal u)=>u.IsInRole("DistrictAttorney")||u.IsInRole("Administrator"); private static bool IsJudge(ClaimsPrincipal u)=>u.IsInRole("Judge")||u.IsInRole("Administrator"); private static bool CanJustice(ClaimsPrincipal u)=>IsDa(u)||IsJudge(u)||u.IsInRole("Magistrate");
    private static string? N(SqliteDataReader r,int i)=>r.IsDBNull(i)?null:r.GetString(i); private static string H(string? s)=>WebUtility.HtmlEncode(s??""); private static IResult Html(string s)=>Results.Content(s,"text/html; charset=utf-8"); private static string Opts(IEnumerable<string> values,string? selected)=>string.Join("",values.Select(x=>$"<option value='{H(x)}' {(string.Equals(x,selected,StringComparison.OrdinalIgnoreCase)?"selected":"")}>{H(x)}</option>"));
    private static string Page(string t,string b)=>$"<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>{H(t)} · CMPD Partners</title><link rel='stylesheet' href='/app.css'></head><body><header class='top'><a href='/' class='brand'>CMPD <span>Partners</span></a><div>North Carolina criminal justice</div></header>{b}</body></html>";
}
