using System.Net;
using System.Security.Claims;
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.Data.Sqlite;

namespace CltPlusPlus.Partners;

public static class DaAvailabilityWorkflows
{
    public static void Map(WebApplication app,string dbPath)
    {
        EnsureSchema(dbPath);

        app.MapGet("/da/availability",async(HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsDa(ctx.User))return Results.Forbid();var t=anti.GetAndStoreTokens(ctx).RequestToken!;var user=ctx.User.Identity?.Name??"prosecutor";var windows=await WindowsHtml(dbPath,user,t);var exceptions=await ExceptionsHtml(dbPath,user,t);return Html(Page("DA availability",$"""<main class='wrap'><a class='back' href='/'>← CMPD Partners</a><section class='page-head'><div><span class='eyebrow'>DISTRICT ATTORNEY · AVAILABILITY</span><h1>Appointment availability</h1><p>Publish recurring weekly windows and date-specific exceptions for defense appointments.</p></div></section><div class='detail-grid'><section><section class='card'><h2>Weekly availability</h2><form method='post' action='/da/availability/windows'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><label>Day<select name='dayOfWeek'>{Opts(Enum.GetNames<DayOfWeek>(),null)}</select></label><label>Start time<input type='time' name='startTime' required/></label><label>End time<input type='time' name='endTime' required/></label><label>Slot length<select name='slotMinutes'><option>15</option><option selected>30</option><option>45</option><option>60</option></select></label><button>Add weekly window</button></form>{windows}</section></section><aside><section class='card'><h2>Date exception / blackout</h2><form method='post' action='/da/availability/exceptions'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><label>Date<input type='date' name='date' required/></label><label>Type<select name='type'><option>Unavailable</option><option>Custom Availability</option></select></label><label>Start time<input type='time' name='startTime'/></label><label>End time<input type='time' name='endTime'/></label><label>Note<textarea name='note' rows='3'></textarea></label><button>Add exception</button></form>{exceptions}</section></aside></div></main>"""));
        }).RequireAuthorization();

        app.MapPost("/da/availability/windows",async(HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsDa(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();if(!Enum.TryParse<DayOfWeek>(f["dayOfWeek"],out var day)||!TimeOnly.TryParse(f["startTime"],out var start)||!TimeOnly.TryParse(f["endTime"],out var end)||end<=start)return Results.BadRequest("Valid day/start/end required.");if(!int.TryParse(f["slotMinutes"],out var slot)||slot<10||slot>120)return Results.BadRequest("Invalid slot length.");await Exec(dbPath,"INSERT INTO DaAvailabilityWindows(Id,DaUsername,DayOfWeek,StartTime,EndTime,SlotMinutes,Active,CreatedAt) VALUES($i,$u,$d,$s,$e,$m,1,$t)",("$i",Guid.NewGuid()),("$u",ctx.User.Identity?.Name??"prosecutor"),("$d",(int)day),("$s",start.ToString("HH:mm")),("$e",end.ToString("HH:mm")),("$m",slot),("$t",Now()));return Results.Redirect("/da/availability");
        }).RequireAuthorization();

        app.MapPost("/da/availability/windows/{id:guid}/delete",async(Guid id,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsDa(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);await Exec(dbPath,"UPDATE DaAvailabilityWindows SET Active=0 WHERE Id=$id AND DaUsername=$u",("$id",id),("$u",ctx.User.Identity?.Name??"prosecutor"));return Results.Redirect("/da/availability");
        }).RequireAuthorization();

        app.MapPost("/da/availability/exceptions",async(HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsDa(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();if(!DateOnly.TryParse(f["date"],out var date))return Results.BadRequest("Date required.");var type=f["type"].ToString();if(type is not ("Unavailable" or "Custom Availability"))return Results.BadRequest("Invalid exception type.");if(type=="Custom Availability"&&(!TimeOnly.TryParse(f["startTime"],out var s)||!TimeOnly.TryParse(f["endTime"],out var e)||e<=s))return Results.BadRequest("Custom availability requires valid start/end times.");await Exec(dbPath,"INSERT INTO DaAvailabilityExceptions(Id,DaUsername,Date,Type,StartTime,EndTime,Note,CreatedAt) VALUES($i,$u,$d,$type,$s,$e,$n,$t)",("$i",Guid.NewGuid()),("$u",ctx.User.Identity?.Name??"prosecutor"),("$d",date.ToString("yyyy-MM-dd")),("$type",type),("$s",f["startTime"]),("$e",f["endTime"]),("$n",f["note"]),("$t",Now()));return Results.Redirect("/da/availability");
        }).RequireAuthorization();

        app.MapGet("/attorney/cases/{complaintId:guid}/available-slots",async(Guid complaintId,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsAttorney(ctx.User))return Results.Forbid();var acct=await Account(dbPath,ctx.User.Identity?.Name??"");if(acct is null||acct.Value.Status!="Active"||!await AttorneyAssigned(dbPath,complaintId,acct.Value.Id))return Results.Forbid();var c=await Complaint(dbPath,complaintId);if(c is null)return Results.NotFound();var t=anti.GetAndStoreTokens(ctx).RequestToken!;var slots=await BuildSlots(dbPath,DateOnly.FromDateTime(DateTime.Now),14);var buttons=slots.Count==0?"<p class='muted'>No DA appointment slots are currently published.</p>":string.Join("",slots.Select(s=>$"<form method='post' action='/attorney/cases/{complaintId}/book-slot' class='slot'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><input type='hidden' name='start' value='{H(s.Start)}'/><input type='hidden' name='daUsername' value='{H(s.Da)}'/><input type='hidden' name='durationMinutes' value='{s.Minutes}'/><label><b>{H(s.Start)}</b><span>{s.Minutes} minutes · {H(s.Da)}</span><textarea name='purpose' rows='2' placeholder='Purpose / agenda' required></textarea></label><button>Choose this slot</button></form>"));return Html(Page("Available DA appointments",$"<main class='wrap'><a class='back' href='/attorney/cases/{complaintId}'>← Case</a><section class='page-head'><div><span class='eyebrow'>DEFENSE ATTORNEY</span><h1>Choose a DA appointment</h1><p>{H(c.Value.Number)} · {H(c.Value.Subject)}</p></div></section><section class='card'><p>Available slots shown below reflect the DA's published hours, exceptions, and existing bookings.</p>{buttons}</section></main>"));
        }).RequireAuthorization();

        app.MapPost("/attorney/cases/{complaintId:guid}/book-slot",async(Guid complaintId,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsAttorney(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var acct=await Account(dbPath,ctx.User.Identity?.Name??"");if(acct is null||acct.Value.Status!="Active"||!await AttorneyAssigned(dbPath,complaintId,acct.Value.Id))return Results.Forbid();var f=await ctx.Request.ReadFormAsync();if(!DateTimeOffset.TryParse(f["start"],out var start)||!int.TryParse(f["durationMinutes"],out var minutes)||minutes<10)return Results.BadRequest("Invalid slot.");var da=f["daUsername"].ToString();if(!await SlotStillAvailable(dbPath,da,start,minutes))return Results.Conflict(new{error="That slot is no longer available. Please choose another."});var id=Guid.NewGuid();var now=Now();await using var cn=Open(dbPath);await cn.OpenAsync();await using var tx=await cn.BeginTransactionAsync();var conflict=cn.CreateCommand();conflict.Transaction=tx;conflict.CommandText="SELECT 1 FROM DaDefenseAppointments WHERE Status='Scheduled' AND DaUsername=$da AND datetime(ScheduledAt) < datetime($end) AND datetime(ScheduledAt,'+'||DurationMinutes||' minutes') > datetime($start) LIMIT 1";conflict.Parameters.AddWithValue("$da",da);conflict.Parameters.AddWithValue("$start",start.ToString("O"));conflict.Parameters.AddWithValue("$end",start.AddMinutes(minutes).ToString("O"));if(await conflict.ExecuteScalarAsync()!=null){await tx.RollbackAsync();return Results.Conflict(new{error="That slot was just booked."});}var ins=cn.CreateCommand();ins.Transaction=tx;ins.CommandText="INSERT INTO DaDefenseAppointments(Id,ComplaintId,AttorneyAccountId,RequestedByRole,RequestedBy,Status,ProposedAt,ScheduledAt,DurationMinutes,Purpose,RoomName,CreatedAt,UpdatedAt,DaUsername) VALUES($i,$c,$a,'Attorney',$by,'Scheduled',$at,$at,$d,$p,$r,$t,$t,$da)";ins.Parameters.AddWithValue("$i",id.ToString());ins.Parameters.AddWithValue("$c",complaintId.ToString());ins.Parameters.AddWithValue("$a",acct.Value.Id.ToString());ins.Parameters.AddWithValue("$by",ctx.User.Identity?.Name??"attorney");ins.Parameters.AddWithValue("$at",start.ToString("O"));ins.Parameters.AddWithValue("$d",minutes);ins.Parameters.AddWithValue("$p",f["purpose"].ToString());ins.Parameters.AddWithValue("$r",$"cltpp-da-defense-{id:N}");ins.Parameters.AddWithValue("$t",now);ins.Parameters.AddWithValue("$da",da);await ins.ExecuteNonQueryAsync();await tx.CommitAsync();return Results.Redirect($"/da-defense-appointments/{id}");
        }).RequireAuthorization();
    }

    private static async Task<List<(string Start,int Minutes,string Da)>> BuildSlots(string p,DateOnly from,int days){var result=new List<(string,int,string)>();await using var cn=Open(p);await cn.OpenAsync();var das=new List<string>();var q=cn.CreateCommand();q.CommandText="SELECT DISTINCT DaUsername FROM DaAvailabilityWindows WHERE Active=1";await using(var r=await q.ExecuteReaderAsync())while(await r.ReadAsync())das.Add(r.GetString(0));foreach(var da in das){for(int i=0;i<days;i++){var date=from.AddDays(i);var ex=await ExceptionFor(cn,da,date);if(ex?.Type=="Unavailable")continue;var windows=ex?.Type=="Custom Availability"?new[]{(ex.Value.Start!,ex.Value.End!,30)}:await WindowsFor(cn,da,date.DayOfWeek);foreach(var w in windows){if(!TimeOnly.TryParse(w.Item1,out var start)||!TimeOnly.TryParse(w.Item2,out var end))continue;var cur=date.ToDateTime(start);var until=date.ToDateTime(end);while(cur.AddMinutes(w.Item3)<=until){var dto=new DateTimeOffset(cur);if(dto>DateTimeOffset.Now.AddMinutes(5)&&await SlotStillAvailable(p,da,dto,w.Item3))result.Add((dto.ToString("O"),w.Item3,da));cur=cur.AddMinutes(w.Item3);}}}}return result.OrderBy(x=>x.Item1).Take(120).ToList();}
    private static async Task<bool> SlotStillAvailable(string p,string da,DateTimeOffset start,int minutes){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT 1 FROM DaDefenseAppointments WHERE Status='Scheduled' AND DaUsername=$da AND datetime(ScheduledAt) < datetime($end) AND datetime(ScheduledAt,'+'||DurationMinutes||' minutes') > datetime($start) LIMIT 1";c.Parameters.AddWithValue("$da",da);c.Parameters.AddWithValue("$start",start.ToString("O"));c.Parameters.AddWithValue("$end",start.AddMinutes(minutes).ToString("O"));return await c.ExecuteScalarAsync()==null;}
    private static async Task<List<(string,string,int)>> WindowsFor(SqliteConnection cn,string da,DayOfWeek day){var c=cn.CreateCommand();c.CommandText="SELECT StartTime,EndTime,SlotMinutes FROM DaAvailabilityWindows WHERE DaUsername=$u AND DayOfWeek=$d AND Active=1 ORDER BY StartTime";c.Parameters.AddWithValue("$u",da);c.Parameters.AddWithValue("$d",(int)day);var rows=new List<(string,string,int)>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add((r.GetString(0),r.GetString(1),r.GetInt32(2)));return rows;}
    private static async Task<(string Type,string? Start,string? End)?> ExceptionFor(SqliteConnection cn,string da,DateOnly date){var c=cn.CreateCommand();c.CommandText="SELECT Type,StartTime,EndTime FROM DaAvailabilityExceptions WHERE DaUsername=$u AND Date=$d ORDER BY CreatedAt DESC LIMIT 1";c.Parameters.AddWithValue("$u",da);c.Parameters.AddWithValue("$d",date.ToString("yyyy-MM-dd"));await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?(r.GetString(0),N(r,1),N(r,2)):null;}
    private static async Task<string> WindowsHtml(string p,string da,string t){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Id,DayOfWeek,StartTime,EndTime,SlotMinutes FROM DaAvailabilityWindows WHERE DaUsername=$u AND Active=1 ORDER BY DayOfWeek,StartTime";c.Parameters.AddWithValue("$u",da);var rows=new List<string>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<article><b>{(DayOfWeek)r.GetInt32(1)} · {H(r.GetString(2))}–{H(r.GetString(3))}</b><span>{r.GetInt32(4)} minute slots</span><form method='post' action='/da/availability/windows/{r.GetString(0)}/delete'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><button class='secondary'>Remove</button></form></article>");return rows.Count==0?"<p class='muted'>No weekly windows.</p>":string.Join("",rows);}
    private static async Task<string> ExceptionsHtml(string p,string da,string t){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Date,Type,StartTime,EndTime,Note FROM DaAvailabilityExceptions WHERE DaUsername=$u AND date(Date)>=date('now') ORDER BY Date";c.Parameters.AddWithValue("$u",da);var rows=new List<string>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<article><b>{H(r.GetString(0))} · {H(r.GetString(1))}</b><span>{H(N(r,2))} {H(N(r,3))}</span><p>{H(N(r,4))}</p></article>");return rows.Count==0?"<p class='muted'>No upcoming exceptions.</p>":string.Join("",rows);}
    private static async Task<(Guid Id,string Status)?> Account(string p,string username){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Id,Status FROM PartnerAccounts WHERE lower(Username)=lower($u) AND Role='Attorney'";c.Parameters.AddWithValue("$u",username);await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?(Guid.Parse(r.GetString(0)),r.GetString(1)):null;}
    private static async Task<bool> AttorneyAssigned(string p,Guid complaintId,Guid attorneyId){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT 1 FROM AttorneyCaseAssignments WHERE ComplaintId=$c AND AttorneyAccountId=$a AND Status='Active'";c.Parameters.AddWithValue("$c",complaintId.ToString());c.Parameters.AddWithValue("$a",attorneyId.ToString());return await c.ExecuteScalarAsync()!=null;}
    private static async Task<(string Number,string Subject)?> Complaint(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT ComplaintNumber,SubjectName FROM DaComplaints WHERE Id=$id";c.Parameters.AddWithValue("$id",id.ToString());await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?(r.GetString(0),r.GetString(1)):null;}
    private static async Task Exec(string p,string sql,params(string Key,object? Value)[] ps){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText=sql;foreach(var x in ps)c.Parameters.AddWithValue(x.Key,x.Value?.ToString()??"");await c.ExecuteNonQueryAsync();}
    private static void EnsureSchema(string p){Directory.CreateDirectory(Path.GetDirectoryName(p)!);using var cn=Open(p);cn.Open();using var c=cn.CreateCommand();c.CommandText="""CREATE TABLE IF NOT EXISTS DaAvailabilityWindows(Id TEXT PRIMARY KEY,DaUsername TEXT NOT NULL,DayOfWeek INTEGER NOT NULL,StartTime TEXT NOT NULL,EndTime TEXT NOT NULL,SlotMinutes INTEGER NOT NULL,Active INTEGER NOT NULL,CreatedAt TEXT NOT NULL);CREATE TABLE IF NOT EXISTS DaAvailabilityExceptions(Id TEXT PRIMARY KEY,DaUsername TEXT NOT NULL,Date TEXT NOT NULL,Type TEXT NOT NULL,StartTime TEXT NULL,EndTime TEXT NULL,Note TEXT NULL,CreatedAt TEXT NOT NULL);CREATE INDEX IF NOT EXISTS IX_DaAvailability_UserDay ON DaAvailabilityWindows(DaUsername,DayOfWeek,Active);CREATE INDEX IF NOT EXISTS IX_DaAvailabilityExceptions_UserDate ON DaAvailabilityExceptions(DaUsername,Date);""";c.ExecuteNonQuery();EnsureAppointmentColumn(cn);}
    private static void EnsureAppointmentColumn(SqliteConnection cn){var cols=new HashSet<string>(StringComparer.OrdinalIgnoreCase);using(var c=cn.CreateCommand()){c.CommandText="PRAGMA table_info(DaDefenseAppointments)";using var r=c.ExecuteReader();while(r.Read())cols.Add(r.GetString(1));}if(!cols.Contains("DaUsername")){using var c=cn.CreateCommand();c.CommandText="ALTER TABLE DaDefenseAppointments ADD COLUMN DaUsername TEXT NULL";c.ExecuteNonQuery();}}
    private static SqliteConnection Open(string p)=>new($"Data Source={p}");private static string Now()=>DateTimeOffset.UtcNow.ToString("O");private static string? N(SqliteDataReader r,int i)=>r.IsDBNull(i)?null:r.GetValue(i)?.ToString();private static bool IsDa(ClaimsPrincipal u)=>u.IsInRole("DistrictAttorney")||u.IsInRole("Administrator");private static bool IsAttorney(ClaimsPrincipal u)=>u.IsInRole("Attorney")||u.IsInRole("Administrator");private static string Opts(IEnumerable<string> xs,string? s)=>string.Join("",xs.Select(x=>$"<option value='{H(x)}' {(string.Equals(x,s,StringComparison.OrdinalIgnoreCase)?"selected":"")}>{H(x)}</option>"));private static string H(string? s)=>WebUtility.HtmlEncode(s??"");private static IResult Html(string s)=>Results.Content(s,"text/html; charset=utf-8");private static string Page(string t,string b)=>$"<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>{H(t)} · CMPD Partners</title><link rel='stylesheet' href='/app.css'></head><body><header class='top'><a href='/' class='brand'>CMPD <span>Partners</span></a><div>DA availability</div></header>{b}</body></html>";
}
