using System.Net;
using System.Security.Claims;
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.Data.Sqlite;

namespace CltPlusPlus.Partners;

public static class DaDefenseAppointments
{
    public static void Map(WebApplication app,string dbPath)
    {
        EnsureSchema(dbPath);

        app.MapGet("/criminal-justice/complaints/{complaintId:guid}/appointments/new",async(Guid complaintId,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsDa(ctx.User))return Results.Forbid();var c=await Complaint(dbPath,complaintId);if(c is null)return Results.NotFound();var attorneys=await AttorneyOptions(dbPath,complaintId);var t=anti.GetAndStoreTokens(ctx).RequestToken!;return Html(Page("Schedule appointment",$"""<main class='wrap'><a class='back' href='/criminal-justice/complaints/{complaintId}'>← Complaint</a><section class='card'><span class='eyebrow'>DISTRICT ATTORNEY · DEFENSE APPOINTMENT</span><h1>Schedule virtual appointment</h1><p>{H(c.Value.Number)} · {H(c.Value.Subject)}</p><form method='post' action='/da-defense-appointments'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><input type='hidden' name='complaintId' value='{complaintId}'/><label>Defense attorney<select name='attorneyAccountId' required><option value=''>Select assigned attorney</option>{attorneys}</select></label><label>Date/time<input type='datetime-local' name='scheduledAt' required/></label><label>Duration minutes<input type='number' name='durationMinutes' min='10' max='180' value='30' required/></label><label>Purpose / agenda<textarea name='purpose' rows='4' required></textarea></label><button>Schedule virtual appointment</button></form></section></main>"""));
        }).RequireAuthorization();

        app.MapPost("/da-defense-appointments",async(HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsDa(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();if(!Guid.TryParse(f["complaintId"],out var complaintId)||!Guid.TryParse(f["attorneyAccountId"],out var attorneyId))return Results.BadRequest("Complaint and attorney are required.");if(!await AttorneyAssigned(dbPath,complaintId,attorneyId))return Results.BadRequest("Attorney must be actively assigned to the complaint.");if(!DateTimeOffset.TryParse(f["scheduledAt"],out var at))return Results.BadRequest("Valid appointment time required.");var purpose=f["purpose"].ToString().Trim();if(purpose.Length==0)return Results.BadRequest("Purpose is required.");var id=Guid.NewGuid();var now=Now();await Exec(dbPath,"""INSERT INTO DaDefenseAppointments(Id,ComplaintId,AttorneyAccountId,RequestedByRole,RequestedBy,Status,ProposedAt,ScheduledAt,DurationMinutes,Purpose,RoomName,CreatedAt,UpdatedAt) VALUES($i,$c,$a,'DistrictAttorney',$by,'Scheduled',$at,$at,$d,$p,$r,$t,$t)""",("$i",id),("$c",complaintId),("$a",attorneyId),("$by",ctx.User.Identity?.Name??"prosecutor"),("$at",at.ToString("O")),("$d",f["durationMinutes"]),("$p",purpose),("$r",$"cltpp-da-defense-{id:N}"),("$t",now));await Hist(dbPath,id,ctx.User.Identity?.Name??"prosecutor","Scheduled",$"Scheduled for {at:O}");return Results.Redirect($"/da-defense-appointments/{id}");
        }).RequireAuthorization();

        app.MapGet("/attorney/cases/{complaintId:guid}/appointment-request",async(Guid complaintId,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsAttorney(ctx.User))return Results.Forbid();var acct=await Account(dbPath,ctx.User.Identity?.Name??"");if(acct is null||acct.Value.Status!="Active"||!await AttorneyAssigned(dbPath,complaintId,acct.Value.Id))return Results.Forbid();var c=await Complaint(dbPath,complaintId);if(c is null)return Results.NotFound();var t=anti.GetAndStoreTokens(ctx).RequestToken!;return Html(Page("Request DA appointment",$"""<main class='wrap'><a class='back' href='/attorney/cases/{complaintId}'>← Case</a><section class='card'><span class='eyebrow'>DEFENSE ATTORNEY · APPOINTMENT REQUEST</span><h1>Request virtual appointment with DA</h1><p>{H(c.Value.Number)} · {H(c.Value.Subject)}</p><form method='post' action='/attorney/appointment-requests'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><input type='hidden' name='complaintId' value='{complaintId}'/><label>Preferred date/time<input type='datetime-local' name='proposedAt' required/></label><label>Duration minutes<input type='number' name='durationMinutes' min='10' max='180' value='30' required/></label><label>Purpose / agenda<textarea name='purpose' rows='4' required></textarea></label><button>Request appointment</button></form></section></main>"""));
        }).RequireAuthorization();

        app.MapPost("/attorney/appointment-requests",async(HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsAttorney(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var acct=await Account(dbPath,ctx.User.Identity?.Name??"");if(acct is null||acct.Value.Status!="Active")return Results.Forbid();var f=await ctx.Request.ReadFormAsync();if(!Guid.TryParse(f["complaintId"],out var complaintId)||!await AttorneyAssigned(dbPath,complaintId,acct.Value.Id))return Results.Forbid();if(!DateTimeOffset.TryParse(f["proposedAt"],out var at))return Results.BadRequest("Valid proposed time required.");var purpose=f["purpose"].ToString().Trim();if(purpose.Length==0)return Results.BadRequest("Purpose is required.");var id=Guid.NewGuid();var now=Now();await Exec(dbPath,"""INSERT INTO DaDefenseAppointments(Id,ComplaintId,AttorneyAccountId,RequestedByRole,RequestedBy,Status,ProposedAt,ScheduledAt,DurationMinutes,Purpose,RoomName,CreatedAt,UpdatedAt) VALUES($i,$c,$a,'Attorney',$by,'Requested',$at,NULL,$d,$p,$r,$t,$t)""",("$i",id),("$c",complaintId),("$a",acct.Value.Id),("$by",ctx.User.Identity?.Name??"attorney"),("$at",at.ToString("O")),("$d",f["durationMinutes"]),("$p",purpose),("$r",$"cltpp-da-defense-{id:N}"),("$t",now));await Hist(dbPath,id,ctx.User.Identity?.Name??"attorney","Requested",$"Requested {at:O}");return Results.Redirect($"/da-defense-appointments/{id}");
        }).RequireAuthorization();

        app.MapGet("/da/appointment-requests",async(HttpContext ctx)=>
        {
            if(!IsDa(ctx.User))return Results.Forbid();await using var cn=Open(dbPath);await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="""SELECT x.Id,d.ComplaintNumber,d.SubjectName,a.FirstName||' '||COALESCE(a.MiddleName||' ','')||a.LastName,x.Status,x.ProposedAt,x.ScheduledAt,x.Purpose FROM DaDefenseAppointments x JOIN DaComplaints d ON d.Id=x.ComplaintId JOIN PartnerAccounts a ON a.Id=x.AttorneyAccountId ORDER BY CASE WHEN x.Status='Requested' THEN 0 ELSE 1 END,x.UpdatedAt DESC""";var rows=new List<string>();await using var r=await cmd.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<tr><td><a href='/da-defense-appointments/{r.GetString(0)}'><b>{H(r.GetString(1))}</b></a></td><td>{H(r.GetString(2))}</td><td>{H(r.GetString(3))}</td><td>{H(r.GetString(4))}</td><td>{H(r.GetString(5))}</td><td>{H(N(r,6))}</td><td>{H(r.GetString(7))}</td></tr>");return Html(Page("DA appointments",$"<main class='wrap'><a class='back' href='/'>← CMPD Partners</a><section class='page-head'><div><span class='eyebrow'>DISTRICT ATTORNEY</span><h1>Defense appointments</h1><p>Requests and scheduled virtual meetings with defense counsel.</p></div></section><section class='table-card'><table><thead><tr><th>Complaint</th><th>Defendant</th><th>Attorney</th><th>Status</th><th>Proposed</th><th>Scheduled</th><th>Purpose</th></tr></thead><tbody>{(rows.Count>0?string.Join("",rows):"<tr><td colspan='7'>No appointments.</td></tr>")}</tbody></table></section></main>"));
        }).RequireAuthorization();

        app.MapGet("/attorney/appointments",async(HttpContext ctx)=>
        {
            if(!IsAttorney(ctx.User))return Results.Forbid();var acct=await Account(dbPath,ctx.User.Identity?.Name??"");if(acct is null||acct.Value.Status!="Active")return Results.Forbid();await using var cn=Open(dbPath);await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="SELECT x.Id,d.ComplaintNumber,d.SubjectName,x.Status,x.ProposedAt,x.ScheduledAt,x.Purpose FROM DaDefenseAppointments x JOIN DaComplaints d ON d.Id=x.ComplaintId WHERE x.AttorneyAccountId=$a ORDER BY x.UpdatedAt DESC";cmd.Parameters.AddWithValue("$a",acct.Value.Id.ToString());var rows=new List<string>();await using var r=await cmd.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<tr><td><a href='/da-defense-appointments/{r.GetString(0)}'><b>{H(r.GetString(1))}</b></a></td><td>{H(r.GetString(2))}</td><td>{H(r.GetString(3))}</td><td>{H(r.GetString(4))}</td><td>{H(N(r,5))}</td><td>{H(r.GetString(6))}</td></tr>");return Html(Page("Appointments",$"<main class='wrap'><a class='back' href='/'>← CMPD Partners</a><section class='page-head'><div><span class='eyebrow'>DEFENSE ATTORNEY</span><h1>DA appointments</h1><p>Your appointment requests and scheduled virtual meetings.</p></div></section><section class='table-card'><table><thead><tr><th>Complaint</th><th>Client</th><th>Status</th><th>Proposed</th><th>Scheduled</th><th>Purpose</th></tr></thead><tbody>{(rows.Count>0?string.Join("",rows):"<tr><td colspan='6'>No appointments.</td></tr>")}</tbody></table></section></main>"));
        }).RequireAuthorization();

        app.MapGet("/da-defense-appointments/{id:guid}",async(Guid id,HttpContext ctx,IAntiforgery anti)=>
        {
            var x=await Load(dbPath,id);if(x is null)return Results.NotFound();var isDa=IsDa(ctx.User);var isAttorney=IsAttorney(ctx.User)&&await OwnsAttorney(dbPath,x.Value.AttorneyAccountId,ctx.User.Identity?.Name??"");if(!isDa&&!isAttorney&&!ctx.User.IsInRole("Administrator"))return Results.Forbid();var t=anti.GetAndStoreTokens(ctx).RequestToken!;var domain=app.Configuration["CLTPP_JITSI_DOMAIN"]??"meet.jit.si";var daActions=isDa&&x.Value.Status=="Requested"?$"""<section class='card'><h2>Respond to request</h2><form method='post' action='/da-defense-appointments/{id}/respond'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><label>Action<select name='action'><option>Accept</option><option>Reschedule</option><option>Decline</option></select></label><label>Scheduled date/time<input type='datetime-local' name='scheduledAt'/></label><label>Response note<textarea name='note' rows='3'></textarea></label><button>Submit response</button></form></section>""":"";var meeting=x.Value.Status=="Scheduled"?$"""<section class='card'><h2>Virtual appointment</h2><p>Scheduled {H(x.Value.ScheduledAt)} · {x.Value.DurationMinutes} minutes</p><div id='jitsi' style='min-height:520px'></div><script src='https://{H(domain)}/external_api.js'></script><script>new JitsiMeetExternalAPI('{Js(domain)}',{{roomName:'{Js(x.Value.Room)}',parentNode:document.querySelector('#jitsi'),userInfo:{{displayName:'{Js(ctx.User.Identity?.Name??"Justice Partner")}'}}}});</script></section>""":"";var hist=await History(dbPath,id);return Html(Page("DA-defense appointment",$"""<main class='wrap'><a class='back' href='{(isDa?"/da/appointment-requests":"/attorney/appointments")}'>← Appointments</a><section class='page-head'><div><span class='eyebrow'>DA–DEFENSE APPOINTMENT · {H(x.Value.Status)}</span><h1>{H(x.Value.ComplaintNumber)}</h1><p>{H(x.Value.Subject)} · {H(x.Value.AttorneyName)}</p></div></section><div class='detail-grid'><section><section class='card'><dl><dt>Requested by</dt><dd>{H(x.Value.RequestedBy)} · {H(x.Value.RequestedByRole)}</dd><dt>Proposed</dt><dd>{H(x.Value.ProposedAt)}</dd><dt>Scheduled</dt><dd>{H(x.Value.ScheduledAt)}</dd><dt>Duration</dt><dd>{x.Value.DurationMinutes} minutes</dd></dl><h2>Purpose / agenda</h2><p style='white-space:pre-wrap'>{H(x.Value.Purpose)}</p><h2>Response note</h2><p style='white-space:pre-wrap'>{H(x.Value.ResponseNote)}</p></section>{meeting}</section><aside>{daActions}<section class='card'><h2>History</h2>{hist}</section></aside></div></main>"""));
        }).RequireAuthorization();

        app.MapPost("/da-defense-appointments/{id:guid}/respond",async(Guid id,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsDa(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var x=await Load(dbPath,id);if(x is null)return Results.NotFound();var f=await ctx.Request.ReadFormAsync();var action=f["action"].ToString();if(action is not ("Accept" or "Reschedule" or "Decline"))return Results.BadRequest("Invalid action.");string status;string? scheduled=null;if(action=="Decline")status="Declined";else{if(action=="Accept")scheduled=x.Value.ProposedAt;else{if(!DateTimeOffset.TryParse(f["scheduledAt"],out var at))return Results.BadRequest("A new time is required to reschedule.");scheduled=at.ToString("O");}status="Scheduled";}var rows=await ExecRows(dbPath,"UPDATE DaDefenseAppointments SET Status=$s,ScheduledAt=$at,ResponseNote=$n,RespondedBy=$by,RespondedAt=$t,UpdatedAt=$t WHERE Id=$id AND Status='Requested'",("$s",status),("$at",scheduled),("$n",f["note"]),("$by",ctx.User.Identity?.Name??"prosecutor"),("$t",Now()),("$id",id));if(rows!=1)return Results.Conflict(new{error="This request is no longer pending."});await Hist(dbPath,id,ctx.User.Identity?.Name??"prosecutor",action,$"{status} {scheduled} {f["note"]}");return Results.Redirect($"/da-defense-appointments/{id}");
        }).RequireAuthorization();
    }

    private static async Task<string> AttorneyOptions(string p,Guid complaintId){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT a.Id,a.FirstName,a.MiddleName,a.LastName,a.Username,x.RepresentationRole FROM AttorneyCaseAssignments x JOIN PartnerAccounts a ON a.Id=x.AttorneyAccountId WHERE x.ComplaintId=$c AND x.Status='Active' AND a.Status='Active' ORDER BY a.LastName,a.FirstName";c.Parameters.AddWithValue("$c",complaintId.ToString());var rows=new List<string>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<option value='{H(r.GetString(0))}'>{H(r.GetString(1))} {H(N(r,2))} {H(r.GetString(3))} · {H(r.GetString(5))}</option>");return string.Join("",rows);}
    private static async Task<bool> AttorneyAssigned(string p,Guid complaintId,Guid attorneyId){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT 1 FROM AttorneyCaseAssignments x JOIN PartnerAccounts a ON a.Id=x.AttorneyAccountId WHERE x.ComplaintId=$c AND x.AttorneyAccountId=$a AND x.Status='Active' AND a.Status='Active'";c.Parameters.AddWithValue("$c",complaintId.ToString());c.Parameters.AddWithValue("$a",attorneyId.ToString());return await c.ExecuteScalarAsync()!=null;}
    private static async Task<bool> OwnsAttorney(string p,Guid id,string username){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT 1 FROM PartnerAccounts WHERE Id=$i AND lower(Username)=lower($u) AND Role='Attorney' AND Status='Active'";c.Parameters.AddWithValue("$i",id.ToString());c.Parameters.AddWithValue("$u",username);return await c.ExecuteScalarAsync()!=null;}
    private static async Task<(Guid Id,string Status)?> Account(string p,string username){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Id,Status FROM PartnerAccounts WHERE lower(Username)=lower($u) AND Role='Attorney'";c.Parameters.AddWithValue("$u",username);await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?(Guid.Parse(r.GetString(0)),r.GetString(1)):null;}
    private static async Task<(string Number,string Subject)?> Complaint(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT ComplaintNumber,SubjectName FROM DaComplaints WHERE Id=$id";c.Parameters.AddWithValue("$id",id.ToString());await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?(r.GetString(0),r.GetString(1)):null;}
    private static async Task<(Guid ComplaintId,Guid AttorneyAccountId,string RequestedByRole,string RequestedBy,string Status,string ProposedAt,string? ScheduledAt,int DurationMinutes,string Purpose,string Room,string ComplaintNumber,string Subject,string AttorneyName,string? ResponseNote)?> Load(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="""SELECT x.ComplaintId,x.AttorneyAccountId,x.RequestedByRole,x.RequestedBy,x.Status,x.ProposedAt,x.ScheduledAt,x.DurationMinutes,x.Purpose,x.RoomName,d.ComplaintNumber,d.SubjectName,a.FirstName||' '||COALESCE(a.MiddleName||' ','')||a.LastName,x.ResponseNote FROM DaDefenseAppointments x JOIN DaComplaints d ON d.Id=x.ComplaintId JOIN PartnerAccounts a ON a.Id=x.AttorneyAccountId WHERE x.Id=$id""";c.Parameters.AddWithValue("$id",id.ToString());await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?(Guid.Parse(r.GetString(0)),Guid.Parse(r.GetString(1)),r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5),N(r,6),r.GetInt32(7),r.GetString(8),r.GetString(9),r.GetString(10),r.GetString(11),r.GetString(12),N(r,13)):null;}
    private static async Task Hist(string p,Guid id,string actor,string action,string detail)=>await Exec(p,"INSERT INTO DaDefenseAppointmentHistory(Id,AppointmentId,Actor,Action,Detail,OccurredAt) VALUES($i,$a,$by,$x,$d,$t)",("$i",Guid.NewGuid()),("$a",id),("$by",actor),("$x",action),("$d",detail),("$t",Now()));
    private static async Task<string> History(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Actor,Action,Detail,OccurredAt FROM DaDefenseAppointmentHistory WHERE AppointmentId=$id ORDER BY OccurredAt DESC";c.Parameters.AddWithValue("$id",id.ToString());var rows=new List<string>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<article><b>{H(r.GetString(1))}</b><small>{H(r.GetString(0))} · {H(r.GetString(3))}</small><p>{H(r.GetString(2))}</p></article>");return rows.Count==0?"<p class='muted'>No history.</p>":string.Join("",rows);}
    private static async Task Exec(string p,string sql,params(string Key,object? Value)[] ps)=>_ = await ExecRows(p,sql,ps);
    private static async Task<int> ExecRows(string p,string sql,params(string Key,object? Value)[] ps){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText=sql;foreach(var x in ps)c.Parameters.AddWithValue(x.Key,x.Value?.ToString()??"");return await c.ExecuteNonQueryAsync();}
    private static void EnsureSchema(string p){Directory.CreateDirectory(Path.GetDirectoryName(p)!);using var cn=Open(p);cn.Open();using var c=cn.CreateCommand();c.CommandText="""CREATE TABLE IF NOT EXISTS DaDefenseAppointments(Id TEXT PRIMARY KEY,ComplaintId TEXT NOT NULL,AttorneyAccountId TEXT NOT NULL,RequestedByRole TEXT NOT NULL,RequestedBy TEXT NOT NULL,Status TEXT NOT NULL,ProposedAt TEXT NOT NULL,ScheduledAt TEXT NULL,DurationMinutes INTEGER NOT NULL,Purpose TEXT NOT NULL,RoomName TEXT NOT NULL UNIQUE,ResponseNote TEXT NULL,RespondedBy TEXT NULL,RespondedAt TEXT NULL,CreatedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL);CREATE TABLE IF NOT EXISTS DaDefenseAppointmentHistory(Id TEXT PRIMARY KEY,AppointmentId TEXT NOT NULL,Actor TEXT NOT NULL,Action TEXT NOT NULL,Detail TEXT NOT NULL,OccurredAt TEXT NOT NULL);CREATE INDEX IF NOT EXISTS IX_DaDefenseAppointments_Complaint ON DaDefenseAppointments(ComplaintId,UpdatedAt);CREATE INDEX IF NOT EXISTS IX_DaDefenseAppointments_Attorney ON DaDefenseAppointments(AttorneyAccountId,UpdatedAt);""";c.ExecuteNonQuery();}
    private static SqliteConnection Open(string p)=>new($"Data Source={p}");private static string Now()=>DateTimeOffset.UtcNow.ToString("O");private static string? N(SqliteDataReader r,int i)=>r.IsDBNull(i)?null:r.GetValue(i)?.ToString();private static bool IsDa(ClaimsPrincipal u)=>u.IsInRole("DistrictAttorney")||u.IsInRole("Administrator");private static bool IsAttorney(ClaimsPrincipal u)=>u.IsInRole("Attorney")||u.IsInRole("Administrator");private static string H(string? s)=>WebUtility.HtmlEncode(s??"");private static string Js(string s)=>s.Replace("\\","\\\\").Replace("'","\\'");private static IResult Html(string s)=>Results.Content(s,"text/html; charset=utf-8");private static string Page(string t,string b)=>$"<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>{H(t)} · CMPD Partners</title><link rel='stylesheet' href='/app.css'></head><body><header class='top'><a href='/' class='brand'>CMPD <span>Partners</span></a><div>DA–Defense appointments</div></header>{b}</body></html>";
}
