using System.Net;
using System.Security.Claims;
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.Data.Sqlite;

namespace CltPlusPlus.Partners;

public static class ElectronicMonitoringWorkflows
{
    public static void Map(WebApplication app,string dbPath)
    {
        EnsureSchema(dbPath);

        app.MapGet("/judge/electronic-monitoring/new/{complaintId:guid}",async(Guid complaintId,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsJudge(ctx.User))return Results.Forbid();var c=await Complaint(dbPath,complaintId);if(c is null)return Results.NotFound();var t=anti.GetAndStoreTokens(ctx).RequestToken!;return Html(Page("Electronic monitoring order",$"""<main class='wrap'><a class='back' href='/criminal-justice/complaints/{complaintId}'>← Complaint</a><section class='page-head'><div><span class='eyebrow'>JUDGE · RELEASE ORDER</span><h1>Electronic monitoring</h1><p>{H(c.Value.Number)} · {H(c.Value.Subject)}</p></div></section><section class='card'><div class='notice'><b>Judicial decision required</b><p>CLT++ records the judge's order. It does not recommend electronic monitoring or release conditions.</p></div><form method='post' action='/judge/electronic-monitoring'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><input type='hidden' name='complaintId' value='{complaintId}'/><label>Effective date/time<input type='datetime-local' name='effectiveAt' required/></label><label>Review / end date<input type='datetime-local' name='reviewAt'/></label><label>Monitoring conditions<textarea name='conditions' rows='7' required placeholder='Court-ordered geographic, curfew, reporting, or other monitoring conditions'></textarea></label><label>Release / bond reference<input name='releaseReference'/></label><label>Judicial findings / basis<textarea name='finding' rows='6' required></textarea></label><button>Issue electronic monitoring order</button></form></section></main>"""));
        }).RequireAuthorization();

        app.MapPost("/judge/electronic-monitoring",async(HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsJudge(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();if(!Guid.TryParse(f["complaintId"],out var cid))return Results.BadRequest("Complaint required.");var c=await Complaint(dbPath,cid);if(c is null)return Results.NotFound();var conditions=f["conditions"].ToString().Trim();var finding=f["finding"].ToString().Trim();var effective=f["effectiveAt"].ToString().Trim();if(string.IsNullOrWhiteSpace(conditions)||string.IsNullOrWhiteSpace(finding)||string.IsNullOrWhiteSpace(effective))return Results.BadRequest("Effective time, conditions, and judicial finding are required.");var id=Guid.NewGuid();var now=Now();var judge=ctx.User.Identity?.Name??"judge";await Exec(dbPath,"""INSERT INTO ElectronicMonitoringOrders(Id,ComplaintId,IncidentNumber,SubjectName,DateOfBirth,Status,EffectiveAt,ReviewAt,Conditions,ReleaseReference,JudicialFinding,IssuedBy,IssuedAt,UpdatedAt) VALUES($i,$c,$inc,$s,$dob,'Ordered / Jail Notification Pending',$e,$r,$cond,$ref,$f,$by,$t,$t)""",("$i",id),("$c",cid),("$inc",c.Value.Incident),("$s",c.Value.Subject),("$dob",c.Value.Dob),("$e",effective),("$r",f["reviewAt"]),("$cond",conditions),("$ref",f["releaseReference"]),("$f",finding),("$by",judge),("$t",now));await Exec(dbPath,"""INSERT INTO JailPartnerNotifications(Id,Type,RelatedId,ComplaintId,SubjectName,IncidentNumber,Message,Status,CreatedAt,CreatedBy) VALUES($i,'Electronic Monitoring Eligibility',$r,$c,$s,$inc,$m,'Unread',$t,$by)""",("$i",Guid.NewGuid()),("$r",id),("$c",cid),("$s",c.Value.Subject),("$inc",c.Value.Incident),("$m",$"Judge {judge} ordered release onto electronic monitoring effective {effective}. Review conditions and coordinate release with CMPD monitoring staff."),("$t",now),("$by",judge));await Exec(dbPath,"""INSERT INTO ElectronicMonitoringCases(Id,OrderId,ComplaintId,IncidentNumber,SubjectName,DateOfBirth,Status,Conditions,CreatedAt,UpdatedAt) VALUES($i,$o,$c,$inc,$s,$dob,'Awaiting Jail Eligibility / Device Assignment',$cond,$t,$t)""",("$i",Guid.NewGuid()),("$o",id),("$c",cid),("$inc",c.Value.Incident),("$s",c.Value.Subject),("$dob",c.Value.Dob),("$cond",conditions),("$t",now));return Results.Redirect($"/criminal-justice/complaints/{cid}");
        }).RequireAuthorization();

        app.MapGet("/jail/electronic-monitoring",async(HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsJail(ctx.User))return Results.Forbid();var t=anti.GetAndStoreTokens(ctx).RequestToken!;await using var cn=Open(dbPath);await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="SELECT n.Id,n.RelatedId,n.SubjectName,n.IncidentNumber,n.Message,n.Status,n.CreatedAt,o.EffectiveAt,o.Conditions FROM JailPartnerNotifications n JOIN ElectronicMonitoringOrders o ON o.Id=n.RelatedId WHERE n.Type='Electronic Monitoring Eligibility' ORDER BY CASE WHEN n.Status='Unread' THEN 0 ELSE 1 END,n.CreatedAt DESC";var rows=new List<string>();await using var r=await cmd.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<article class='card'><span class='eyebrow'>{H(r.GetString(5))}</span><h2>{H(r.GetString(2))}</h2><p>Incident {H(r.GetString(3))} · Effective {H(r.GetString(7))}</p><p>{H(r.GetString(4))}</p><h3>Conditions</h3><p style='white-space:pre-wrap'>{H(r.GetString(8))}</p><form method='post' action='/jail/electronic-monitoring/{r.GetString(1)}/eligibility'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><label>Jail disposition<select name='status'><option>Eligible / Ready for Monitoring</option><option>Hold - Intake Action Required</option><option>Released to CMPD Monitoring</option></select></label><label>Jail note<textarea name='note' rows='3'></textarea></label><button>Update eligibility</button></form></article>");return Html(Page("Electronic monitoring eligibility",$"<main class='wrap'><a class='back' href='/'>← CMPD Partners</a><section class='page-head'><div><span class='eyebrow'>COUNTY JAIL</span><h1>Electronic monitoring releases</h1><p>Judicially ordered monitoring eligibility notifications.</p></div></section>{(rows.Count>0?string.Join("",rows):"<section class='card'><p>No monitoring eligibility notifications.</p></section>")}</main>"));
        }).RequireAuthorization();

        app.MapPost("/jail/electronic-monitoring/{orderId:guid}/eligibility",async(Guid orderId,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsJail(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();var status=f["status"].ToString();var allowed=new[]{"Eligible / Ready for Monitoring","Hold - Intake Action Required","Released to CMPD Monitoring"};if(!allowed.Contains(status))return Results.BadRequest("Invalid status.");var now=Now();var who=ctx.User.Identity?.Name??"jail";await Exec(dbPath,"UPDATE ElectronicMonitoringOrders SET Status=$s,JailDisposition=$s,JailNote=$n,JailConfirmedBy=$by,JailConfirmedAt=$t,UpdatedAt=$t WHERE Id=$id",("$s",status),("$n",f["note"]),("$by",who),("$t",now),("$id",orderId));await Exec(dbPath,"UPDATE JailPartnerNotifications SET Status='Acknowledged' WHERE RelatedId=$id AND Type='Electronic Monitoring Eligibility'",("$id",orderId));await Exec(dbPath,"UPDATE ElectronicMonitoringCases SET Status=$s,UpdatedAt=$t WHERE OrderId=$id",("$s",status),("$t",now),("$id",orderId));return Results.Redirect("/jail/electronic-monitoring");
        }).RequireAuthorization();
    }

    private static async Task<(string Number,string Incident,string Subject,string? Dob)?> Complaint(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT ComplaintNumber,IncidentNumber,SubjectName,DateOfBirth FROM DaComplaints WHERE Id=$id";c.Parameters.AddWithValue("$id",id.ToString());await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?(r.GetString(0),r.GetString(1),r.GetString(2),N(r,3)):null;}
    private static void EnsureSchema(string p){Directory.CreateDirectory(Path.GetDirectoryName(p)!);using var cn=Open(p);cn.Open();using var c=cn.CreateCommand();c.CommandText="""CREATE TABLE IF NOT EXISTS ElectronicMonitoringOrders(Id TEXT PRIMARY KEY,ComplaintId TEXT NOT NULL,IncidentNumber TEXT NOT NULL,SubjectName TEXT NOT NULL,DateOfBirth TEXT NULL,Status TEXT NOT NULL,EffectiveAt TEXT NOT NULL,ReviewAt TEXT NULL,Conditions TEXT NOT NULL,ReleaseReference TEXT NULL,JudicialFinding TEXT NOT NULL,IssuedBy TEXT NOT NULL,IssuedAt TEXT NOT NULL,JailDisposition TEXT NULL,JailNote TEXT NULL,JailConfirmedBy TEXT NULL,JailConfirmedAt TEXT NULL,UpdatedAt TEXT NOT NULL);CREATE TABLE IF NOT EXISTS JailPartnerNotifications(Id TEXT PRIMARY KEY,Type TEXT NOT NULL,RelatedId TEXT NOT NULL,ComplaintId TEXT NULL,SubjectName TEXT NOT NULL,IncidentNumber TEXT NULL,Message TEXT NOT NULL,Status TEXT NOT NULL,CreatedAt TEXT NOT NULL,CreatedBy TEXT NOT NULL);CREATE TABLE IF NOT EXISTS ElectronicMonitoringCases(Id TEXT PRIMARY KEY,OrderId TEXT NOT NULL UNIQUE,ComplaintId TEXT NOT NULL,IncidentNumber TEXT NOT NULL,SubjectName TEXT NOT NULL,DateOfBirth TEXT NULL,Status TEXT NOT NULL,Conditions TEXT NOT NULL,DeviceId TEXT NULL,DeviceType TEXT NULL,AssignedBy TEXT NULL,AssignedAt TEXT NULL,ActivatedAt TEXT NULL,DeactivatedAt TEXT NULL,ClosureReason TEXT NULL,CreatedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL);CREATE TABLE IF NOT EXISTS ElectronicMonitoringEvents(Id TEXT PRIMARY KEY,CaseId TEXT NOT NULL,EventType TEXT NOT NULL,EventAt TEXT NOT NULL,Location TEXT NULL,Detail TEXT NULL,Disposition TEXT NULL,RecordedBy TEXT NOT NULL,RecordedAt TEXT NOT NULL);CREATE INDEX IF NOT EXISTS IX_EMOrders_Complaint ON ElectronicMonitoringOrders(ComplaintId);CREATE INDEX IF NOT EXISTS IX_EMCases_Status ON ElectronicMonitoringCases(Status);""";c.ExecuteNonQuery();}
    private static async Task Exec(string p,string sql,params(string Key,object? Value)[] ps){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText=sql;foreach(var x in ps)c.Parameters.AddWithValue(x.Key,x.Value?.ToString()??"");await c.ExecuteNonQueryAsync();}
    private static SqliteConnection Open(string p)=>new($"Data Source={p}");private static string Now()=>DateTimeOffset.UtcNow.ToString("O");private static string? N(SqliteDataReader r,int i)=>r.IsDBNull(i)?null:r.GetString(i);private static bool IsJudge(ClaimsPrincipal u)=>u.IsInRole("Judge")||u.IsInRole("Administrator");private static bool IsJail(ClaimsPrincipal u)=>u.IsInRole("CountyJail")||u.IsInRole("Administrator");private static string H(string? s)=>WebUtility.HtmlEncode(s??"");private static IResult Html(string s)=>Results.Content(s,"text/html; charset=utf-8");private static string Page(string t,string b)=>$"<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>{H(t)} · CMPD Partners</title><link rel='stylesheet' href='/app.css'></head><body><header class='top'><a href='/' class='brand'>CMPD <span>Partners</span></a><div>Electronic monitoring</div></header>{b}</body></html>";
}
