using System.Net;
using System.Security.Claims;
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.Data.Sqlite;

namespace CltPlusPlus.Partners;

public static class PleaOfferWorkflows
{
    public static void Map(WebApplication app,string dbPath)
    {
        EnsureSchema(dbPath);

        app.MapGet("/criminal-justice/complaints/{complaintId:guid}/plea-offers/new",async(Guid complaintId,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsDa(ctx.User))return Results.Forbid();var c=await Complaint(dbPath,complaintId);if(c is null)return Results.NotFound();var attorneys=await AttorneyOptions(dbPath,complaintId);var t=anti.GetAndStoreTokens(ctx).RequestToken!;return Html(Page("New plea offer",$"""<main class='wrap'><a class='back' href='/criminal-justice/complaints/{complaintId}'>← Complaint</a><section class='page-head'><div><span class='eyebrow'>DISTRICT ATTORNEY · PLEA OFFER</span><h1>Create plea offer</h1><p>{H(c.Value.Number)} · {H(c.Value.Subject)}</p></div></section><section class='card'><div class='notice'><b>Prosecutor-entered legal decision</b><p>CLT++ records and transmits the offer. It does not recommend plea terms or whether either party should accept them.</p></div><form method='post' action='/plea-offers'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><input type='hidden' name='complaintId' value='{complaintId}'/><label>Defense attorney<select name='attorneyAccountId' required><option value=''>Select assigned defense attorney</option>{attorneys}</select></label><label>Offer title<input name='title' required placeholder='Plea offer'/></label><label>Proposed charge resolution<textarea name='chargeTerms' rows='5' required placeholder='Charges/counts to plead to, dismiss, amend, or consolidate'></textarea></label><label>Proposed sentencing / disposition terms<textarea name='dispositionTerms' rows='5' required></textarea></label><label>Other conditions<textarea name='otherTerms' rows='4'></textarea></label><label>Expiration date/time<input type='datetime-local' name='expiresAt' required/></label><label>DA note to defense<textarea name='message' rows='4'></textarea></label><button>Submit plea offer to defense</button></form></section></main>"""));
        }).RequireAuthorization();

        app.MapPost("/plea-offers",async(HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsDa(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();if(!Guid.TryParse(f["complaintId"],out var complaintId)||!Guid.TryParse(f["attorneyAccountId"],out var attorneyId))return Results.BadRequest("Complaint and defense attorney are required.");if(await Complaint(dbPath,complaintId) is null)return Results.NotFound();if(!await AttorneyAssigned(dbPath,complaintId,attorneyId))return Results.BadRequest("The selected defense attorney is not actively assigned to this complaint.");if(!DateTimeOffset.TryParse(f["expiresAt"],out var expires)||expires<=DateTimeOffset.UtcNow)return Results.BadRequest("Expiration must be in the future.");var title=f["title"].ToString().Trim();var charges=f["chargeTerms"].ToString().Trim();var disposition=f["dispositionTerms"].ToString().Trim();if(new[]{title,charges,disposition}.Any(string.IsNullOrWhiteSpace))return Results.BadRequest("Title, charge terms, and disposition terms are required.");var id=Guid.NewGuid();var now=Now();var by=ctx.User.Identity?.Name??"prosecutor";await Exec(dbPath,"""INSERT INTO PleaOffers(Id,ComplaintId,AttorneyAccountId,Version,Title,ChargeTerms,DispositionTerms,OtherTerms,MessageToDefense,Status,ExpiresAt,CreatedBy,CreatedAt,SentAt,UpdatedAt) VALUES($i,$c,$a,1,$title,$charges,$disp,$other,$msg,'Pending Defense Response',$exp,$by,$t,$t,$t)""",("$i",id),("$c",complaintId),("$a",attorneyId),("$title",title),("$charges",charges),("$disp",disposition),("$other",f["otherTerms"]),("$msg",f["message"]),("$exp",expires.ToString("O")),("$by",by),("$t",now));await Hist(dbPath,id,by,"Offer submitted",$"Submitted to attorney account {attorneyId}; expires {expires:O}");return Results.Redirect($"/plea-offers/{id}");
        }).RequireAuthorization();

        app.MapGet("/plea-offers/{id:guid}",async(Guid id,HttpContext ctx,IAntiforgery anti)=>
        {
            var o=await Offer(dbPath,id);if(o is null)return Results.NotFound();var isDa=IsDa(ctx.User);var isAttorney=IsAttorney(ctx.User)&&await OwnsOffer(dbPath,o.Value.AttorneyAccountId,ctx.User.Identity?.Name??"");if(!isDa&&!isAttorney&&!ctx.User.IsInRole("Administrator"))return Results.Forbid();await ExpireIfNeeded(dbPath,id,o.Value.Status,o.Value.ExpiresAt);o=await Offer(dbPath,id);var t=anti.GetAndStoreTokens(ctx).RequestToken!;var response=isAttorney&&o!.Value.Status=="Pending Defense Response"?$"""<section class='card'><h2>Defense response</h2><form method='post' action='/plea-offers/{id}/respond'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><label>Response<select name='response' required><option value=''>Select</option><option>Accepted</option><option>Rejected</option></select></label><label>Defense note<textarea name='note' rows='4'></textarea></label><button>Submit response</button></form></section>""":"";var withdraw=isDa&&o!.Value.Status=="Pending Defense Response"?$"""<section class='card'><h2>DA action</h2><form method='post' action='/plea-offers/{id}/withdraw'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><label>Withdrawal reason<textarea name='reason' rows='3' required></textarea></label><button class='secondary'>Withdraw offer</button></form></section>""":"";var history=await History(dbPath,id);return Html(Page(o!.Value.Title,$"""<main class='wrap'><a class='back' href='/criminal-justice/complaints/{o.Value.ComplaintId}'>← Complaint</a><section class='page-head'><div><span class='eyebrow'>PLEA OFFER · {H(o.Value.Status)}</span><h1>{H(o.Value.Title)}</h1><p>{H(o.Value.ComplaintNumber)} · {H(o.Value.Subject)}</p></div></section><div class='detail-grid'><section class='card'><dl><dt>Defense attorney</dt><dd>{H(o.Value.AttorneyName)}</dd><dt>Version</dt><dd>{o.Value.Version}</dd><dt>Sent</dt><dd>{H(o.Value.SentAt)}</dd><dt>Expires</dt><dd>{H(o.Value.ExpiresAt)}</dd><dt>Response at</dt><dd>{H(o.Value.RespondedAt)}</dd></dl><h2>Charge resolution</h2><p style='white-space:pre-wrap'>{H(o.Value.ChargeTerms)}</p><h2>Disposition / sentencing terms</h2><p style='white-space:pre-wrap'>{H(o.Value.DispositionTerms)}</p><h2>Other terms</h2><p style='white-space:pre-wrap'>{H(o.Value.OtherTerms)}</p><h2>DA message</h2><p style='white-space:pre-wrap'>{H(o.Value.Message)}</p><h2>Defense response note</h2><p style='white-space:pre-wrap'>{H(o.Value.ResponseNote)}</p></section><aside>{response}{withdraw}<section class='card'><h2>Offer history</h2>{history}</section></aside></div></main>"""));
        }).RequireAuthorization();

        app.MapGet("/attorney/plea-offers",async(HttpContext ctx)=>
        {
            if(!IsAttorney(ctx.User))return Results.Forbid();var acct=await Account(dbPath,ctx.User.Identity?.Name??"");if(acct is null||acct.Value.Status!="Active")return Results.Forbid();await using var cn=Open(dbPath);await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="""SELECT p.Id,d.ComplaintNumber,d.SubjectName,p.Title,p.Status,p.ExpiresAt,p.SentAt FROM PleaOffers p JOIN DaComplaints d ON d.Id=p.ComplaintId WHERE p.AttorneyAccountId=$a ORDER BY CASE WHEN p.Status='Pending Defense Response' THEN 0 ELSE 1 END,p.SentAt DESC""";cmd.Parameters.AddWithValue("$a",acct.Value.Id.ToString());var rows=new List<string>();await using var r=await cmd.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<tr><td><a href='/plea-offers/{r.GetString(0)}'><b>{H(r.GetString(1))}</b></a></td><td>{H(r.GetString(2))}</td><td>{H(r.GetString(3))}</td><td><span class='status'>{H(r.GetString(4))}</span></td><td>{H(r.GetString(5))}</td><td>{H(r.GetString(6))}</td></tr>");return Html(Page("Plea offers",$"<main class='wrap'><a class='back' href='/'>← CMPD Partners</a><section class='page-head'><div><span class='eyebrow'>DEFENSE ATTORNEY</span><h1>Plea offers</h1><p>Offers submitted by the District Attorney for cases on your workload.</p></div></section><section class='table-card'><table><thead><tr><th>Complaint</th><th>Client</th><th>Offer</th><th>Status</th><th>Expires</th><th>Sent</th></tr></thead><tbody>{(rows.Count>0?string.Join("",rows):"<tr><td colspan='6'>No plea offers.</td></tr>")}</tbody></table></section></main>"));
        }).RequireAuthorization();

        app.MapPost("/plea-offers/{id:guid}/respond",async(Guid id,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsAttorney(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var o=await Offer(dbPath,id);if(o is null)return Results.NotFound();if(!await OwnsOffer(dbPath,o.Value.AttorneyAccountId,ctx.User.Identity?.Name??""))return Results.Forbid();var f=await ctx.Request.ReadFormAsync();var response=f["response"].ToString();if(response is not ("Accepted" or "Rejected"))return Results.BadRequest("Response must be Accepted or Rejected.");var now=DateTimeOffset.UtcNow;if(DateTimeOffset.TryParse(o.Value.ExpiresAt,out var exp)&&now>=exp){await ExpireIfNeeded(dbPath,id,o.Value.Status,o.Value.ExpiresAt);return Results.Conflict(new{error="This plea offer has expired."});}await using var cn=Open(dbPath);await cn.OpenAsync();await using var tx=await cn.BeginTransactionAsync();var cmd=cn.CreateCommand();cmd.Transaction=tx;cmd.CommandText="UPDATE PleaOffers SET Status=$s,ResponseNote=$n,RespondedBy=$by,RespondedAt=$t,UpdatedAt=$t WHERE Id=$id AND Status='Pending Defense Response'";cmd.Parameters.AddWithValue("$s",response);cmd.Parameters.AddWithValue("$n",f["note"].ToString());cmd.Parameters.AddWithValue("$by",ctx.User.Identity?.Name??"attorney");cmd.Parameters.AddWithValue("$t",now.ToString("O"));cmd.Parameters.AddWithValue("$id",id.ToString());if(await cmd.ExecuteNonQueryAsync()!=1){await tx.RollbackAsync();return Results.Conflict(new{error="This offer is no longer pending."});}var hist=cn.CreateCommand();hist.Transaction=tx;hist.CommandText="INSERT INTO PleaOfferHistory(Id,PleaOfferId,Actor,Action,Detail,OccurredAt) VALUES($i,$p,$a,$x,$d,$t)";hist.Parameters.AddWithValue("$i",Guid.NewGuid().ToString());hist.Parameters.AddWithValue("$p",id.ToString());hist.Parameters.AddWithValue("$a",ctx.User.Identity?.Name??"attorney");hist.Parameters.AddWithValue("$x",response);hist.Parameters.AddWithValue("$d",f["note"].ToString());hist.Parameters.AddWithValue("$t",now.ToString("O"));await hist.ExecuteNonQueryAsync();await tx.CommitAsync();return Results.Redirect($"/plea-offers/{id}");
        }).RequireAuthorization();

        app.MapPost("/plea-offers/{id:guid}/withdraw",async(Guid id,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsDa(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();var reason=f["reason"].ToString().Trim();if(reason.Length==0)return Results.BadRequest("Withdrawal reason is required.");var who=ctx.User.Identity?.Name??"prosecutor";var rows=await ExecRows(dbPath,"UPDATE PleaOffers SET Status='Withdrawn',WithdrawnBy=$by,WithdrawnAt=$t,WithdrawalReason=$r,UpdatedAt=$t WHERE Id=$id AND Status='Pending Defense Response'",("$by",who),("$t",Now()),("$r",reason),("$id",id));if(rows!=1)return Results.Conflict(new{error="Only a pending offer can be withdrawn."});await Hist(dbPath,id,who,"Withdrawn",reason);return Results.Redirect($"/plea-offers/{id}");
        }).RequireAuthorization();
    }

    public static async Task<string> ComplaintOffersHtml(string dbPath,Guid complaintId,ClaimsPrincipal user)
    {
        EnsureSchema(dbPath);await using var cn=Open(dbPath);await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="SELECT Id,Title,Status,ExpiresAt,SentAt FROM PleaOffers WHERE ComplaintId=$c ORDER BY SentAt DESC";cmd.Parameters.AddWithValue("$c",complaintId.ToString());var rows=new List<string>();await using var r=await cmd.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<article><a href='/plea-offers/{r.GetString(0)}'><b>{H(r.GetString(1))}</b></a><span>{H(r.GetString(2))}</span><small>Expires {H(r.GetString(3))} · Sent {H(r.GetString(4))}</small></article>");var create=IsDa(user)?$"<p><a class='button' href='/criminal-justice/complaints/{complaintId}/plea-offers/new'>Create plea offer</a></p>":"";return create+(rows.Count==0?"<p class='muted'>No plea offers.</p>":string.Join("",rows));
    }

    private static async Task ExpireIfNeeded(string p,Guid id,string status,string expiresAt){if(status!="Pending Defense Response"||!DateTimeOffset.TryParse(expiresAt,out var exp)||DateTimeOffset.UtcNow<exp)return;var rows=await ExecRows(p,"UPDATE PleaOffers SET Status='Expired',UpdatedAt=$t WHERE Id=$id AND Status='Pending Defense Response' AND ExpiresAt<=$t",("$t",Now()),("$id",id));if(rows==1)await Hist(p,id,"system","Expired","Offer expired without a defense response.");}
    private static async Task<string> AttorneyOptions(string p,Guid complaintId){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="""SELECT a.Id,a.FirstName,a.MiddleName,a.LastName,a.Username,x.RepresentationRole FROM AttorneyCaseAssignments x JOIN PartnerAccounts a ON a.Id=x.AttorneyAccountId WHERE x.ComplaintId=$c AND x.Status='Active' AND a.Status='Active' ORDER BY a.LastName,a.FirstName""";c.Parameters.AddWithValue("$c",complaintId.ToString());var rows=new List<string>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<option value='{H(r.GetString(0))}'>{H(r.GetString(1))} {H(N(r,2))} {H(r.GetString(3))} · {H(r.GetString(5))} · {H(r.GetString(4))}</option>");return string.Join("",rows);}
    private static async Task<bool> AttorneyAssigned(string p,Guid complaintId,Guid attorneyId){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT 1 FROM AttorneyCaseAssignments x JOIN PartnerAccounts a ON a.Id=x.AttorneyAccountId WHERE x.ComplaintId=$c AND x.AttorneyAccountId=$a AND x.Status='Active' AND a.Status='Active'";c.Parameters.AddWithValue("$c",complaintId.ToString());c.Parameters.AddWithValue("$a",attorneyId.ToString());return await c.ExecuteScalarAsync()!=null;}
    private static async Task<bool> OwnsOffer(string p,Guid attorneyId,string username){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT 1 FROM PartnerAccounts WHERE Id=$i AND lower(Username)=lower($u) AND Role='Attorney' AND Status='Active'";c.Parameters.AddWithValue("$i",attorneyId.ToString());c.Parameters.AddWithValue("$u",username);return await c.ExecuteScalarAsync()!=null;}
    private static async Task<(Guid Id,string Status)?> Account(string p,string username){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Id,Status FROM PartnerAccounts WHERE lower(Username)=lower($u) AND Role='Attorney'";c.Parameters.AddWithValue("$u",username);await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?(Guid.Parse(r.GetString(0)),r.GetString(1)):null;}
    private static async Task<(string Number,string Subject)?> Complaint(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT ComplaintNumber,SubjectName FROM DaComplaints WHERE Id=$id";c.Parameters.AddWithValue("$id",id.ToString());await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?(r.GetString(0),r.GetString(1)):null;}
    private static async Task<(Guid ComplaintId,Guid AttorneyAccountId,int Version,string Title,string ChargeTerms,string DispositionTerms,string? OtherTerms,string? Message,string Status,string ExpiresAt,string SentAt,string ComplaintNumber,string Subject,string AttorneyName,string? RespondedAt,string? ResponseNote)?> Offer(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="""SELECT p.ComplaintId,p.AttorneyAccountId,p.Version,p.Title,p.ChargeTerms,p.DispositionTerms,p.OtherTerms,p.MessageToDefense,p.Status,p.ExpiresAt,p.SentAt,d.ComplaintNumber,d.SubjectName,a.FirstName||' '||COALESCE(a.MiddleName||' ','')||a.LastName,p.RespondedAt,p.ResponseNote FROM PleaOffers p JOIN DaComplaints d ON d.Id=p.ComplaintId JOIN PartnerAccounts a ON a.Id=p.AttorneyAccountId WHERE p.Id=$id""";c.Parameters.AddWithValue("$id",id.ToString());await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?(Guid.Parse(r.GetString(0)),Guid.Parse(r.GetString(1)),r.GetInt32(2),r.GetString(3),r.GetString(4),r.GetString(5),N(r,6),N(r,7),r.GetString(8),r.GetString(9),r.GetString(10),r.GetString(11),r.GetString(12),r.GetString(13),N(r,14),N(r,15)):null;}
    private static async Task Hist(string p,Guid id,string actor,string action,string detail)=>await Exec(p,"INSERT INTO PleaOfferHistory(Id,PleaOfferId,Actor,Action,Detail,OccurredAt) VALUES($i,$p,$a,$x,$d,$t)",("$i",Guid.NewGuid()),("$p",id),("$a",actor),("$x",action),("$d",detail),("$t",Now()));
    private static async Task<string> History(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Actor,Action,Detail,OccurredAt FROM PleaOfferHistory WHERE PleaOfferId=$id ORDER BY OccurredAt DESC";c.Parameters.AddWithValue("$id",id.ToString());var rows=new List<string>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<article><b>{H(r.GetString(1))}</b><small>{H(r.GetString(0))} · {H(r.GetString(3))}</small><p>{H(r.GetString(2))}</p></article>");return rows.Count==0?"<p class='muted'>No history.</p>":string.Join("",rows);}
    private static async Task Exec(string p,string sql,params(string Key,object? Value)[] ps)=>_ = await ExecRows(p,sql,ps);
    private static async Task<int> ExecRows(string p,string sql,params(string Key,object? Value)[] ps){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText=sql;foreach(var x in ps)c.Parameters.AddWithValue(x.Key,x.Value?.ToString()??"");return await c.ExecuteNonQueryAsync();}
    private static void EnsureSchema(string p){Directory.CreateDirectory(Path.GetDirectoryName(p)!);using var cn=Open(p);cn.Open();using var c=cn.CreateCommand();c.CommandText="""CREATE TABLE IF NOT EXISTS PleaOffers(Id TEXT PRIMARY KEY,ComplaintId TEXT NOT NULL,AttorneyAccountId TEXT NOT NULL,Version INTEGER NOT NULL,Title TEXT NOT NULL,ChargeTerms TEXT NOT NULL,DispositionTerms TEXT NOT NULL,OtherTerms TEXT NULL,MessageToDefense TEXT NULL,Status TEXT NOT NULL,ExpiresAt TEXT NOT NULL,CreatedBy TEXT NOT NULL,CreatedAt TEXT NOT NULL,SentAt TEXT NOT NULL,RespondedBy TEXT NULL,RespondedAt TEXT NULL,ResponseNote TEXT NULL,WithdrawnBy TEXT NULL,WithdrawnAt TEXT NULL,WithdrawalReason TEXT NULL,UpdatedAt TEXT NOT NULL);CREATE TABLE IF NOT EXISTS PleaOfferHistory(Id TEXT PRIMARY KEY,PleaOfferId TEXT NOT NULL,Actor TEXT NOT NULL,Action TEXT NOT NULL,Detail TEXT NOT NULL,OccurredAt TEXT NOT NULL);CREATE INDEX IF NOT EXISTS IX_PleaOffers_Complaint ON PleaOffers(ComplaintId,SentAt);CREATE INDEX IF NOT EXISTS IX_PleaOffers_Attorney ON PleaOffers(AttorneyAccountId,Status);""";c.ExecuteNonQuery();}
    private static SqliteConnection Open(string p)=>new($"Data Source={p}");private static string Now()=>DateTimeOffset.UtcNow.ToString("O");private static string? N(SqliteDataReader r,int i)=>r.IsDBNull(i)?null:r.GetValue(i)?.ToString();private static bool IsDa(ClaimsPrincipal u)=>u.IsInRole("DistrictAttorney")||u.IsInRole("Administrator");private static bool IsAttorney(ClaimsPrincipal u)=>u.IsInRole("Attorney")||u.IsInRole("Administrator");private static string H(string? s)=>WebUtility.HtmlEncode(s??"");private static IResult Html(string s)=>Results.Content(s,"text/html; charset=utf-8");private static string Page(string t,string b)=>$"<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>{H(t)} · CMPD Partners</title><link rel='stylesheet' href='/app.css'></head><body><header class='top'><a href='/' class='brand'>CMPD <span>Partners</span></a><div>Plea offers</div></header>{b}</body></html>";
}
