using System.Net;
using System.Security.Claims;
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.Data.Sqlite;

namespace CltPlusPlus.Partners;

public static class ProbationWorkflows
{
    public static void Map(WebApplication app,string dbPath)
    {
        EnsureSchema(dbPath);

        app.MapGet("/probation",async(HttpContext ctx)=>
        {
            if(!IsProbation(ctx.User))return Results.Forbid();await using var cn=Open(dbPath);await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="""SELECT p.Id,d.ComplaintNumber,d.SubjectName,d.IncidentNumber,p.Status,p.AssignedOfficer,p.StartDate,p.EndDate FROM DeferredDispositionCases p JOIN DaComplaints d ON d.Id=p.ComplaintId ORDER BY CASE WHEN p.Status IN ('Pending Assignment','Active') THEN 0 ELSE 1 END,p.UpdatedAt DESC""";var rows=new List<string>();await using var r=await cmd.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<tr><td><a href='/probation/{r.GetString(0)}'><b>{H(r.GetString(1))}</b></a></td><td>{H(r.GetString(2))}</td><td>{H(r.GetString(3))}</td><td><span class='status'>{H(r.GetString(4))}</span></td><td>{H(N(r,5))}</td><td>{H(N(r,6))}</td><td>{H(N(r,7))}</td></tr>");return Html(Page("Probation",$"<main class='wrap'><a class='back' href='/'>← CMPD Partners</a><section class='page-head'><div><span class='eyebrow'>PROBATION · DEFERRED DISPOSITIONS</span><h1>Deferred disposition caseload</h1><p>Supervise court-ordered deferred-disposition conditions and report outcomes back to the court.</p></div></section><section class='table-card'><table><thead><tr><th>Complaint</th><th>Person</th><th>Incident</th><th>Status</th><th>Officer</th><th>Start</th><th>End</th></tr></thead><tbody>{(rows.Count>0?string.Join("",rows):"<tr><td colspan='7'>No deferred-disposition cases.</td></tr>")}</tbody></table></section></main>"));
        }).RequireAuthorization();

        app.MapGet("/probation/{id:guid}",async(Guid id,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsProbation(ctx.User))return Results.Forbid();var c=await Load(dbPath,id);if(c is null)return Results.NotFound();var t=anti.GetAndStoreTokens(ctx).RequestToken!;var events=await Events(dbPath,id);var assignment=string.IsNullOrWhiteSpace(c.Value.AssignedOfficer)?$"<form method='post' action='/probation/{id}/assign'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><button>Accept assignment</button></form>":"";return Html(Page(c.Value.ComplaintNumber,$"""<main class='wrap'><a class='back' href='/probation'>← Caseload</a><section class='page-head'><div><span class='eyebrow'>DEFERRED DISPOSITION · {H(c.Value.Status)}</span><h1>{H(c.Value.ComplaintNumber)}</h1><p>{H(c.Value.SubjectName)} · Incident {H(c.Value.IncidentNumber)}</p></div></section><div class='detail-grid'><section class='card'><dl><dt>Assigned officer</dt><dd>{H(c.Value.AssignedOfficer)}</dd><dt>Start</dt><dd>{H(c.Value.StartDate)}</dd><dt>End</dt><dd>{H(c.Value.EndDate)}</dd></dl><h2>Court-ordered conditions</h2><p style='white-space:pre-wrap'>{H(c.Value.Conditions)}</p><h2>Case events</h2>{events}</section><aside><section class='card'><h2>Probation actions</h2>{assignment}<form method='post' action='/probation/{id}/event'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><label>Event type<select name='eventType'><option>Initial Intake</option><option>Scheduled Check-in</option><option>Office Visit</option><option>Phone Contact</option><option>Condition Verification</option><option>Compliance Note</option><option>Noncompliance Note</option><option>Modification Request</option><option>Court Referral</option><option>Completion Review</option><option>Other</option></select></label><label>Date/time<input type='datetime-local' name='eventAt' required/></label><label>Details<textarea name='detail' rows='5' required></textarea></label><label>Disposition / follow-up<textarea name='disposition' rows='3'></textarea></label><button>Record event</button></form><hr/><form method='post' action='/probation/{id}/status'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><label>Status<select name='status'><option>Active</option><option>Pending Court Review</option><option>Completed - Conditions Satisfied</option><option>Closed - Court Disposition</option></select></label><label>Officer summary<textarea name='summary' rows='5' required></textarea></label><button>Update case status</button></form></section></aside></div></main>"""));
        }).RequireAuthorization();

        app.MapPost("/probation/{id:guid}/assign",async(Guid id,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsProbation(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var who=ctx.User.Identity?.Name??"probation";await Exec(dbPath,"UPDATE DeferredDispositionCases SET AssignedOfficer=$o,Status='Active',UpdatedAt=$t WHERE Id=$id AND (AssignedOfficer IS NULL OR AssignedOfficer='')",("$o",who),("$t",Now()),("$id",id));await Hist(dbPath,id,who,"Assigned","Probation officer accepted assignment.");return Results.Redirect($"/probation/{id}");
        }).RequireAuthorization();

        app.MapPost("/probation/{id:guid}/event",async(Guid id,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsProbation(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();var type=f["eventType"].ToString();var detail=f["detail"].ToString().Trim();if(string.IsNullOrWhiteSpace(type)||string.IsNullOrWhiteSpace(detail))return Results.BadRequest("Event type and detail are required.");await Exec(dbPath,"INSERT INTO DeferredDispositionEvents(Id,CaseId,EventType,EventAt,Detail,Disposition,RecordedBy,RecordedAt) VALUES($i,$c,$e,$at,$d,$disp,$by,$t)",("$i",Guid.NewGuid()),("$c",id),("$e",type),("$at",f["eventAt"]),("$d",detail),("$disp",f["disposition"]),("$by",ctx.User.Identity?.Name??"probation"),("$t",Now()));await Hist(dbPath,id,ctx.User.Identity?.Name??"probation",type,detail);return Results.Redirect($"/probation/{id}");
        }).RequireAuthorization();

        app.MapPost("/probation/{id:guid}/status",async(Guid id,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsProbation(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();var status=f["status"].ToString();var allowed=new[]{"Active","Pending Court Review","Completed - Conditions Satisfied","Closed - Court Disposition"};if(!allowed.Contains(status))return Results.BadRequest("Invalid status.");var summary=f["summary"].ToString().Trim();if(summary.Length==0)return Results.BadRequest("Summary is required.");var now=Now();await Exec(dbPath,"UPDATE DeferredDispositionCases SET Status=$s,OfficerSummary=$sum,UpdatedAt=$t,CompletedAt=CASE WHEN $s LIKE 'Completed%' OR $s LIKE 'Closed%' THEN $t ELSE CompletedAt END WHERE Id=$id",("$s",status),("$sum",summary),("$t",now),("$id",id));await Hist(dbPath,id,ctx.User.Identity?.Name??"probation","Status changed",status+": "+summary);return Results.Redirect($"/probation/{id}");
        }).RequireAuthorization();
    }

    public static async Task EnsureFromDisposition(string dbPath,Guid complaintId,string conditions,string? startDate,string? endDate,string createdBy)
    {
        EnsureSchema(dbPath);await using var cn=Open(dbPath);await cn.OpenAsync();var chk=cn.CreateCommand();chk.CommandText="SELECT Id FROM DeferredDispositionCases WHERE ComplaintId=$c AND Status NOT LIKE 'Closed%' LIMIT 1";chk.Parameters.AddWithValue("$c",complaintId.ToString());if(await chk.ExecuteScalarAsync()!=null)return;var id=Guid.NewGuid();var now=Now();var ins=cn.CreateCommand();ins.CommandText="INSERT INTO DeferredDispositionCases(Id,ComplaintId,Status,Conditions,StartDate,EndDate,CreatedBy,CreatedAt,UpdatedAt) VALUES($i,$c,'Pending Assignment',$cond,$s,$e,$by,$t,$t)";ins.Parameters.AddWithValue("$i",id.ToString());ins.Parameters.AddWithValue("$c",complaintId.ToString());ins.Parameters.AddWithValue("$cond",conditions);ins.Parameters.AddWithValue("$s",startDate??"");ins.Parameters.AddWithValue("$e",endDate??"");ins.Parameters.AddWithValue("$by",createdBy);ins.Parameters.AddWithValue("$t",now);await ins.ExecuteNonQueryAsync();
    }

    private static async Task<(string ComplaintNumber,string SubjectName,string IncidentNumber,string Status,string? AssignedOfficer,string? StartDate,string? EndDate,string Conditions)?> Load(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT d.ComplaintNumber,d.SubjectName,d.IncidentNumber,p.Status,p.AssignedOfficer,p.StartDate,p.EndDate,p.Conditions FROM DeferredDispositionCases p JOIN DaComplaints d ON d.Id=p.ComplaintId WHERE p.Id=$id";c.Parameters.AddWithValue("$id",id.ToString());await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?(r.GetString(0),r.GetString(1),r.GetString(2),r.GetString(3),N(r,4),N(r,5),N(r,6),r.GetString(7)):null;}
    private static async Task<string> Events(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT EventType,EventAt,Detail,Disposition,RecordedBy,RecordedAt FROM DeferredDispositionEvents WHERE CaseId=$id ORDER BY EventAt DESC";c.Parameters.AddWithValue("$id",id.ToString());var rows=new List<string>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<article><b>{H(r.GetString(0))}</b><small>{H(r.GetString(1))} · {H(r.GetString(4))}</small><p>{H(r.GetString(2))}</p><small>{H(N(r,3))}</small></article>");return rows.Count==0?"<p class='muted'>No probation events.</p>":string.Join("",rows);}
    private static async Task Hist(string p,Guid id,string actor,string action,string detail)=>await Exec(p,"INSERT INTO DeferredDispositionHistory(Id,CaseId,Actor,Action,Detail,OccurredAt) VALUES($i,$c,$a,$x,$d,$t)",("$i",Guid.NewGuid()),("$c",id),("$a",actor),("$x",action),("$d",detail),("$t",Now()));
    private static async Task Exec(string p,string sql,params(string Key,object? Value)[] ps){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText=sql;foreach(var x in ps)c.Parameters.AddWithValue(x.Key,x.Value?.ToString()??"");await c.ExecuteNonQueryAsync();}
    private static void EnsureSchema(string p){Directory.CreateDirectory(Path.GetDirectoryName(p)!);using var cn=Open(p);cn.Open();using var c=cn.CreateCommand();c.CommandText="""CREATE TABLE IF NOT EXISTS DeferredDispositionCases(Id TEXT PRIMARY KEY,ComplaintId TEXT NOT NULL,Status TEXT NOT NULL,AssignedOfficer TEXT NULL,Conditions TEXT NOT NULL,StartDate TEXT NULL,EndDate TEXT NULL,OfficerSummary TEXT NULL,CreatedBy TEXT NOT NULL,CreatedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL,CompletedAt TEXT NULL);CREATE TABLE IF NOT EXISTS DeferredDispositionEvents(Id TEXT PRIMARY KEY,CaseId TEXT NOT NULL,EventType TEXT NOT NULL,EventAt TEXT NOT NULL,Detail TEXT NOT NULL,Disposition TEXT NULL,RecordedBy TEXT NOT NULL,RecordedAt TEXT NOT NULL);CREATE TABLE IF NOT EXISTS DeferredDispositionHistory(Id TEXT PRIMARY KEY,CaseId TEXT NOT NULL,Actor TEXT NOT NULL,Action TEXT NOT NULL,Detail TEXT NOT NULL,OccurredAt TEXT NOT NULL);CREATE INDEX IF NOT EXISTS IX_DeferredCases_Complaint ON DeferredDispositionCases(ComplaintId);CREATE INDEX IF NOT EXISTS IX_DeferredCases_Status ON DeferredDispositionCases(Status);""";c.ExecuteNonQuery();}
    private static SqliteConnection Open(string p)=>new($"Data Source={p}");private static string Now()=>DateTimeOffset.UtcNow.ToString("O");private static string? N(SqliteDataReader r,int i)=>r.IsDBNull(i)?null:r.GetString(i);private static bool IsProbation(ClaimsPrincipal u)=>u.IsInRole("ProbationOfficer")||u.IsInRole("Administrator");private static string H(string? s)=>WebUtility.HtmlEncode(s??"");private static IResult Html(string s)=>Results.Content(s,"text/html; charset=utf-8");private static string Page(string t,string b)=>$"<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>{H(t)} · CMPD Partners</title><link rel='stylesheet' href='/app.css'></head><body><header class='top'><a href='/' class='brand'>CMPD <span>Partners</span></a><div>Probation</div></header>{b}</body></html>";
}
