using System.Net;
using System.Security.Claims;
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.Data.Sqlite;

var builder=WebApplication.CreateBuilder(args);
builder.Services.AddAntiforgery();
builder.Services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme).AddCookie(o=>{o.LoginPath="/login";o.AccessDeniedPath="/forbidden";o.Cookie.Name="cltpp.partners";o.Cookie.HttpOnly=true;o.Cookie.SameSite=SameSiteMode.Strict;o.Cookie.SecurePolicy=CookieSecurePolicy.SameAsRequest;o.ExpireTimeSpan=TimeSpan.FromHours(8);});
builder.Services.AddAuthorization();
var app=builder.Build();
app.UseStaticFiles();app.UseAuthentication();app.UseAuthorization();
var dbPath=app.Configuration["CLTPP_PUBLIC_SAFETY_DB"]??Path.Combine(AppContext.BaseDirectory,"data","public-safety.db");
var evidenceRoot=app.Configuration["CLTPP_PUBLIC_SAFETY_EVIDENCE_PATH"]??Path.Combine(AppContext.BaseDirectory,"data","public-safety-evidence");
Directory.CreateDirectory(Path.GetDirectoryName(dbPath)!);Directory.CreateDirectory(evidenceRoot);EnsureSchema();
var users=LoadUsers(app.Configuration,app.Environment);

app.MapGet("/login",(HttpContext ctx,IAntiforgery anti)=>{if(ctx.User.Identity?.IsAuthenticated==true)return Results.Redirect("/");var t=anti.GetAndStoreTokens(ctx).RequestToken!;return Html(Page("Partner sign in",$"""<main class='login-shell'><section class='login-card'><div class='brand'>CMPD <span>Partners</span></div><h1>Justice partner sign in</h1><p>Authorized magistrate and District Attorney access to linked CMPD workflows.</p><form method='post' action='/login'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><label>Username<input name='username' required autocomplete='username'/></label><label>Password<input type='password' name='password' required autocomplete='current-password'/></label><button>Sign in</button></form>{(app.Environment.IsDevelopment()?"<p class='muted'>Configure PARTNER_USERS for development access.</p>":"")}</section></main>"""));});
app.MapPost("/login",async(HttpContext ctx,IAntiforgery anti)=>{await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();var u=users.FirstOrDefault(x=>string.Equals(x.Username,f["username"],StringComparison.OrdinalIgnoreCase)&&x.Password==f["password"]);if(u is null)return Html(Page("Sign in failed","<main class='login-shell'><section class='login-card'><h1>Sign in failed</h1><a href='/login'>Try again</a></section></main>"),401);var id=new ClaimsIdentity(new[]{new Claim(ClaimTypes.Name,u.Username),new Claim(ClaimTypes.Role,u.Role)},CookieAuthenticationDefaults.AuthenticationScheme);await ctx.SignInAsync(new ClaimsPrincipal(id));return Results.Redirect("/");});
app.MapPost("/logout",async(HttpContext ctx,IAntiforgery anti)=>{await anti.ValidateRequestAsync(ctx);await ctx.SignOutAsync();return Results.Redirect("/login");}).RequireAuthorization();

app.MapGet("/",(HttpContext ctx,IAntiforgery anti)=>{var t=anti.GetAndStoreTokens(ctx).RequestToken!;var role=ctx.User.FindFirstValue(ClaimTypes.Role)??"Partner";var cards=new List<string>();if(IsMag(ctx.User))cards.Add("<a class='tool-card' href='/magistrate/standby'><b>Magistrate standby</b><span>Set availability and join assigned virtual hearings.</span></a>");if(IsMag(ctx.User)||IsDa(ctx.User))cards.Add("<a class='tool-card' href='/express-reports'><b>Express reports</b><span>Read authorized report details and evidence metadata.</span></a>");return Html(Page("CMPD Partners",$"""<main class='wrap'><section class='page-head'><div><span class='eyebrow'>{H(role)}</span><h1>CMPD Partners</h1><p>Role-limited justice partner access.</p></div><form method='post' action='/logout'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><button>Sign out</button></form></section><div class='tool-grid'>{string.Join("",cards)}</div></main>"""));}).RequireAuthorization();

app.MapGet("/magistrate/standby",async(HttpContext ctx,IAntiforgery anti)=>{if(!IsMag(ctx.User))return Results.Forbid();var t=anti.GetAndStoreTokens(ctx).RequestToken!;var user=ctx.User.Identity?.Name??"";var available=await GetStandby(user);var hearings=await MagistrateHearings(user);return Html(Page("Magistrate standby",$"""<main class='wrap'><a class='back' href='/'>← CMPD Partners</a><section class='page-head'><div><span class='eyebrow'>MAGISTRATE</span><h1>Virtual hearing standby</h1><p>Status: <b>{(available?"Available":"Unavailable")}</b></p></div></section><section class='card'><form method='post' action='/magistrate/standby'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><input type='hidden' name='available' value='{(!available).ToString().ToLowerInvariant()}'/><button>{(available?"Go unavailable":"Stand by now")}</button></form></section><section class='card'><h2>Assigned hearings</h2>{hearings}</section></main>"""));}).RequireAuthorization();
app.MapPost("/magistrate/standby",async(HttpContext ctx,IAntiforgery anti)=>{if(!IsMag(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();await SetStandby(ctx.User.Identity?.Name??"magistrate",bool.TryParse(f["available"],out var a)&&a);return Results.Redirect("/magistrate/standby");}).RequireAuthorization();

app.MapGet("/hearings/{id:guid}",async(Guid id,HttpContext ctx)=>{if(!IsMag(ctx.User))return Results.Forbid();var h=await LoadHearing(id);if(h is null||!string.Equals(h.Value.Magistrate,ctx.User.Identity?.Name,StringComparison.OrdinalIgnoreCase))return Results.Forbid();var r=await LoadReport(h.Value.ExpressReportId);if(r is null)return Results.NotFound();var evidence=await EvidenceHtml(r.Value.Id,true);var domain=app.Configuration["CLTPP_JITSI_DOMAIN"]??"meet.jit.si";return Html(Page(h.Value.Number,$"""<main class='wrap'><a class='back' href='/magistrate/standby'>← Standby</a><section class='page-head'><div><span class='eyebrow'>VIRTUAL HEARING · {H(h.Value.Status)}</span><h1>{H(h.Value.Number)}</h1><p>Express report {H(r.Value.Number)}</p></div></section><div class='notice'><b>Recording notice</b><p>If recording is enabled, Jitsi must visibly notify participants. No covert recording is supported.</p></div><div class='detail-grid'><section class='card'><h2>Hearing</h2><dl><dt>Officer</dt><dd>{H(h.Value.Officer)}</dd><dt>Purpose</dt><dd>{H(h.Value.Purpose)}</dd><dt>Room</dt><dd>{H(h.Value.Room)}</dd></dl><div id='jitsi' style='min-height:520px'></div></section><aside>{ReportHtml(r.Value,evidence)}</aside></div><script src='https://{H(domain)}/external_api.js'></script><script>new JitsiMeetExternalAPI('{Js(domain)}',{{roomName:'{Js(h.Value.Room)}',parentNode:document.querySelector('#jitsi'),userInfo:{{displayName:'{Js(ctx.User.Identity?.Name??"magistrate")}'}}}});</script></main>"""));}).RequireAuthorization();

app.MapGet("/express-reports",async(HttpContext ctx,string? q)=>{if(!IsMag(ctx.User)&&!IsDa(ctx.User))return Results.Forbid();await using var cn=Open();await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="SELECT Id,ReportNumber,Status,COALESCE(Title,''),COALESCE(Location,''),CreatedBy,UpdatedAt FROM ExpressReports WHERE ($q='' OR ReportNumber LIKE $like OR Title LIKE $like OR Location LIKE $like OR Transcript LIKE $like) ORDER BY UpdatedAt DESC LIMIT 200";cmd.Parameters.AddWithValue("$q",q??"");cmd.Parameters.AddWithValue("$like","%"+(q??"")+"%");var rows=new List<string>();await using var rd=await cmd.ExecuteReaderAsync();while(await rd.ReadAsync())rows.Add($"<tr><td><a href='/express-reports/{rd.GetString(0)}'><b>{H(rd.GetString(1))}</b></a></td><td>{H(rd.GetString(2))}</td><td>{H(rd.GetString(3))}</td><td>{H(rd.GetString(4))}</td><td>{H(rd.GetString(5))}</td><td>{H(rd.GetString(6))}</td></tr>");return Html(Page("Express reports",$"""<main class='wrap'><a class='back' href='/'>← CMPD Partners</a><section class='page-head'><div><span class='eyebrow'>READ ONLY</span><h1>Express reports</h1><p>Authorized partner access. No report edits are available in this application.</p></div></section><form class='filters'><input name='q' value='{H(q)}' placeholder='Report number, title, location, narrative'/><button>Search</button></form><section class='table-card'><table><thead><tr><th>Report</th><th>Status</th><th>Title</th><th>Location</th><th>Officer</th><th>Updated</th></tr></thead><tbody>{(rows.Count>0?string.Join("",rows):"<tr><td colspan='6'>No reports found.</td></tr>")}</tbody></table></section></main>"""));}).RequireAuthorization();

app.MapGet("/express-reports/{id:guid}",async(Guid id,HttpContext ctx)=>{if(!IsMag(ctx.User)&&!IsDa(ctx.User))return Results.Forbid();var r=await LoadReport(id);if(r is null)return Results.NotFound();var evidence=await EvidenceHtml(id,true);return Html(Page(r.Value.Number,$"""<main class='wrap'><a class='back' href='/express-reports'>← Express reports</a><section class='page-head'><div><span class='eyebrow'>EXPRESS REPORT · READ ONLY</span><h1>{H(r.Value.Number)}</h1><p>{H(r.Value.Title)}</p></div></section>{ReportHtml(r.Value,evidence)}</main>"""));}).RequireAuthorization();

app.MapGet("/express-reports/{reportId:guid}/evidence/{attachmentId:guid}",async(Guid reportId,Guid attachmentId,HttpContext ctx)=>{if(!IsMag(ctx.User)&&!IsDa(ctx.User))return Results.Forbid();await using var cn=Open();await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="SELECT StoredPath,ContentType,OriginalName FROM ExpressReportAttachments WHERE Id=$a AND ExpressReportId=$r";cmd.Parameters.AddWithValue("$a",attachmentId.ToString());cmd.Parameters.AddWithValue("$r",reportId.ToString());await using var rd=await cmd.ExecuteReaderAsync();if(!await rd.ReadAsync())return Results.NotFound();var p=rd.GetString(0);if(!File.Exists(p))return Results.NotFound();return Results.File(p,rd.GetString(1),rd.GetString(2));}).RequireAuthorization();
app.MapGet("/forbidden",()=>Html(Page("Access denied","<main class='login-shell'><section class='login-card'><h1>Access denied</h1><p>Your partner role does not authorize that resource.</p></section></main>"),403));
app.Run();

SqliteConnection Open()=>new($"Data Source={dbPath}");
void EnsureSchema(){using var cn=Open();cn.Open();using var cmd=cn.CreateCommand();cmd.CommandText="""CREATE TABLE IF NOT EXISTS MagistrateStandby(Username TEXT PRIMARY KEY,Available INTEGER NOT NULL,UpdatedAt TEXT NOT NULL);CREATE TABLE IF NOT EXISTS VirtualHearings(Id TEXT PRIMARY KEY,HearingNumber TEXT NOT NULL UNIQUE,ExpressReportId TEXT NOT NULL,IncidentNumber TEXT NOT NULL,OfficerUsername TEXT NOT NULL,MagistrateUsername TEXT NOT NULL,Status TEXT NOT NULL,RoomName TEXT NOT NULL,Purpose TEXT NOT NULL,CreatedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL,CompletedAt TEXT NULL,OfficerSummary TEXT NULL,RecordingStatus TEXT NOT NULL,RecordingReference TEXT NULL);""";cmd.ExecuteNonQuery();}
async Task<bool> GetStandby(string u){await using var cn=Open();await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Available FROM MagistrateStandby WHERE Username=$u";c.Parameters.AddWithValue("$u",u);var x=await c.ExecuteScalarAsync();return x is long l&&l==1;}
async Task SetStandby(string u,bool a){await using var cn=Open();await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="INSERT INTO MagistrateStandby(Username,Available,UpdatedAt) VALUES($u,$a,$t) ON CONFLICT(Username) DO UPDATE SET Available=$a,UpdatedAt=$t";c.Parameters.AddWithValue("$u",u);c.Parameters.AddWithValue("$a",a?1:0);c.Parameters.AddWithValue("$t",DateTimeOffset.UtcNow.ToString("O"));await c.ExecuteNonQueryAsync();}
async Task<string> MagistrateHearings(string u){await using var cn=Open();await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Id,HearingNumber,IncidentNumber,OfficerUsername,Status,CreatedAt FROM VirtualHearings WHERE MagistrateUsername=$u ORDER BY CreatedAt DESC LIMIT 100";c.Parameters.AddWithValue("$u",u);var rows=new List<string>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<article><a href='/hearings/{r.GetString(0)}'><b>{H(r.GetString(1))}</b></a><span>{H(r.GetString(2))} · {H(r.GetString(4))}</span><small>Officer {H(r.GetString(3))} · {H(r.GetString(5))}</small></article>");return rows.Count==0?"<p class='muted'>No assigned hearings.</p>":string.Join("",rows);}
async Task<(Guid Id,string Number,Guid ExpressReportId,string Officer,string Magistrate,string Status,string Room,string Purpose)?> LoadHearing(Guid id){await using var cn=Open();await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Id,HearingNumber,ExpressReportId,OfficerUsername,MagistrateUsername,Status,RoomName,Purpose FROM VirtualHearings WHERE Id=$id";c.Parameters.AddWithValue("$id",id.ToString());await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?(Guid.Parse(r.GetString(0)),r.GetString(1),Guid.Parse(r.GetString(2)),r.GetString(3),r.GetString(4),r.GetString(5),r.GetString(6),r.GetString(7)):null;}
async Task<(Guid Id,string Number,string Status,string Title,string Transcript,string Location,string CreatedBy,string CreatedAt,string? SubmittedBy,string? SubmittedAt)?> LoadReport(Guid id){await using var cn=Open();await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Id,ReportNumber,Status,COALESCE(Title,''),COALESCE(Transcript,''),COALESCE(Location,''),CreatedBy,CreatedAt,SubmittedBy,SubmittedAt FROM ExpressReports WHERE Id=$id";c.Parameters.AddWithValue("$id",id.ToString());await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?(Guid.Parse(r.GetString(0)),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5),r.GetString(6),r.GetString(7),N(r,8),N(r,9)):null;}
async Task<string> EvidenceHtml(Guid id,bool links){await using var cn=Open();await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Id,OriginalName,ContentType,ByteLength,Sha256,UploadedBy,UploadedAt,OfficerNote FROM ExpressReportAttachments WHERE ExpressReportId=$id ORDER BY UploadedAt";c.Parameters.AddWithValue("$id",id.ToString());var rows=new List<string>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync()){var name=H(r.GetString(1));var label=links?$"<a href='/express-reports/{id}/evidence/{r.GetString(0)}'><b>{name}</b></a>":$"<b>{name}</b>";rows.Add($"<article>{label}<small>{H(r.GetString(2))} · {r.GetInt64(3)} bytes · SHA-256 {H(r.GetString(4))}</small><p>{H(N(r,7))}</p><small>Uploaded by {H(r.GetString(5))} · {H(r.GetString(6))}</small></article>");}return rows.Count==0?"<p class='muted'>No attached evidence.</p>":string.Join("",rows);}
string ReportHtml((Guid Id,string Number,string Status,string Title,string Transcript,string Location,string CreatedBy,string CreatedAt,string? SubmittedBy,string? SubmittedAt) r,string evidence)=>$"""<section class='card'><h2>Full Express Report</h2><dl><dt>Status</dt><dd>{H(r.Status)}</dd><dt>Title</dt><dd>{H(r.Title)}</dd><dt>Location</dt><dd>{H(r.Location)}</dd><dt>Created by</dt><dd>{H(r.CreatedBy)}</dd><dt>Created</dt><dd>{H(r.CreatedAt)}</dd><dt>Submitted by</dt><dd>{H(r.SubmittedBy)}</dd><dt>Submitted</dt><dd>{H(r.SubmittedAt)}</dd></dl><h3>Transcript / narrative</h3><p style='white-space:pre-wrap'>{H(r.Transcript)}</p><h3>Evidence</h3>{evidence}</section>""";
static bool IsMag(ClaimsPrincipal u)=>u.IsInRole("Magistrate")||u.IsInRole("Administrator");static bool IsDa(ClaimsPrincipal u)=>u.IsInRole("DistrictAttorney")||u.IsInRole("Administrator");
static List<PartnerUser> LoadUsers(IConfiguration c,IWebHostEnvironment env){var raw=c["PARTNER_USERS"];if(string.IsNullOrWhiteSpace(raw)&&env.IsDevelopment())raw="magistrate.demo:ChangeMe!:Magistrate;da.demo:ChangeMe!:DistrictAttorney";if(string.IsNullOrWhiteSpace(raw))return new();return raw.Split(';',StringSplitOptions.RemoveEmptyEntries).Select(x=>{var p=x.Split(':',3);return new PartnerUser(p[0],p.Length>1?p[1]:"",p.Length>2?p[2]:"Partner");}).ToList();}
static string? N(SqliteDataReader r,int i)=>r.IsDBNull(i)?null:r.GetString(i);static string H(string? s)=>WebUtility.HtmlEncode(s??"");static string Js(string s)=>s.Replace("\\","\\\\").Replace("'","\\'");static IResult Html(string s,int code=200)=>Results.Content(s,"text/html; charset=utf-8",statusCode:code);static string Page(string t,string b)=>$"<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>{H(t)} · CMPD Partners</title><link rel='stylesheet' href='/app.css'></head><body><header class='top'><a href='/' class='brand'>CMPD <span>Partners</span></a><div>Justice partner portal</div></header>{b}<footer>CMPD Partners · Authorized users only</footer></body></html>";
record PartnerUser(string Username,string Password,string Role);
