using System.Net;
using System.Security.Claims;
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.Data.Sqlite;

namespace CltPlusPlus.Partners;

public static class SocialWorkWorkflows
{
    public static void Map(WebApplication app,string dbPath)
    {
        EnsureSchema(dbPath);

        app.MapGet("/providers",async(HttpContext ctx,string? q,string? category)=>
        {
            if(!IsSocialWorker(ctx.User))return Results.Forbid();await using var cn=Open(dbPath);await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="""SELECT Id,Name,Category,ServiceArea,Phone,Email,Website,AvailabilityStatus,Active,UpdatedAt FROM SocialWorkProviders WHERE ($q='' OR Name LIKE $like OR Category LIKE $like OR Services LIKE $like OR Eligibility LIKE $like OR NavigationNotes LIKE $like) AND ($cat='' OR Category=$cat) ORDER BY Active DESC,Name""";cmd.Parameters.AddWithValue("$q",q??"");cmd.Parameters.AddWithValue("$like","%"+(q??"")+"%");cmd.Parameters.AddWithValue("$cat",category??"");var rows=new List<string>();await using var r=await cmd.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<tr><td><a href='/providers/{r.GetString(0)}'><b>{H(r.GetString(1))}</b></a></td><td>{H(r.GetString(2))}</td><td>{H(N(r,3))}</td><td>{H(N(r,4))}<small>{H(N(r,5))}</small></td><td>{H(N(r,7))}</td><td>{(r.GetInt64(8)==1?"Active":"Inactive")}</td><td>{H(r.GetString(9))}</td></tr>");var cats=new[]{"Housing","Food / Nutrition","Benefits / Insurance","Transportation","Employment / Education","Behavioral Health","Substance Use Treatment","Primary Care","Family / Child Services","Legal / Administrative Support","Emergency Assistance","Other"};return Html(Page("Provider directory",$"""<main class='wrap'><a class='back' href='/'>← CMPD Partners</a><section class='page-head'><div><span class='eyebrow'>DEPARTMENT OF HEALTH · RESOURCE NAVIGATION</span><h1>Providers & resources</h1><p>Shared directory maintained by social workers for client navigation and referrals.</p></div><a class='button' href='/providers/new'>Add provider/resource</a></section><form class='filters'><input name='q' value='{H(q)}' placeholder='Provider, service, eligibility, notes'/><select name='category'><option value=''>All categories</option>{Opts(cats,category)}</select><button>Search</button></form><section class='table-card'><table><thead><tr><th>Provider/resource</th><th>Category</th><th>Service area</th><th>Contact</th><th>Availability</th><th>Status</th><th>Updated</th></tr></thead><tbody>{(rows.Count>0?string.Join("",rows):"<tr><td colspan='7'>No providers/resources found.</td></tr>")}</tbody></table></section></main>"""));
        }).RequireAuthorization();

        app.MapGet("/providers/new",(HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsSocialWorker(ctx.User))return Results.Forbid();var t=anti.GetAndStoreTokens(ctx).RequestToken!;return Html(Page("Add provider",ProviderForm(null,t)));
        }).RequireAuthorization();

        app.MapPost("/providers",async(HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsSocialWorker(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();var name=f["name"].ToString().Trim();var services=f["services"].ToString().Trim();if(name.Length==0||services.Length==0)return Results.BadRequest("Name and services are required.");var id=Guid.NewGuid();var now=Now();await Exec(dbPath,"""INSERT INTO SocialWorkProviders(Id,Name,Category,Services,Eligibility,ServiceArea,Languages,Phone,Email,Website,Address,ReferralProcess,CostInsurance,Hours,AvailabilityStatus,NavigationNotes,Active,CreatedBy,CreatedAt,UpdatedBy,UpdatedAt) VALUES($i,$n,$c,$s,$e,$area,$lang,$p,$email,$web,$addr,$ref,$cost,$hours,$avail,$notes,$active,$by,$t,$by,$t)""",("$i",id),("$n",name),("$c",f["category"]),("$s",services),("$e",f["eligibility"]),("$area",f["serviceArea"]),("$lang",f["languages"]),("$p",f["phone"]),("$email",f["email"]),("$web",f["website"]),("$addr",f["address"]),("$ref",f["referralProcess"]),("$cost",f["costInsurance"]),("$hours",f["hours"]),("$avail",f["availabilityStatus"]),("$notes",f["navigationNotes"]),("$active",f["active"]=="true"?1:0),("$by",ctx.User.Identity?.Name??"socialworker"),("$t",now));return Results.Redirect($"/providers/{id}");
        }).RequireAuthorization();

        app.MapGet("/providers/{id:guid}",async(Guid id,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsSocialWorker(ctx.User))return Results.Forbid();var p=await LoadProvider(dbPath,id);if(p is null)return Results.NotFound();var t=anti.GetAndStoreTokens(ctx).RequestToken!;return Html(Page(p.Value.Name,$"""<main class='wrap'><a class='back' href='/providers'>← Provider directory</a><section class='page-head'><div><span class='eyebrow'>{H(p.Value.Category)} · {(p.Value.Active?"ACTIVE":"INACTIVE")}</span><h1>{H(p.Value.Name)}</h1><p>{H(p.Value.ServiceArea)}</p></div></section><div class='detail-grid'><section class='card'><h2>Services</h2><p style='white-space:pre-wrap'>{H(p.Value.Services)}</p><dl><dt>Eligibility</dt><dd>{H(p.Value.Eligibility)}</dd><dt>Languages</dt><dd>{H(p.Value.Languages)}</dd><dt>Phone</dt><dd>{H(p.Value.Phone)}</dd><dt>Email</dt><dd>{H(p.Value.Email)}</dd><dt>Website</dt><dd>{H(p.Value.Website)}</dd><dt>Address</dt><dd>{H(p.Value.Address)}</dd><dt>Hours</dt><dd>{H(p.Value.Hours)}</dd><dt>Availability</dt><dd>{H(p.Value.Availability)}</dd><dt>Cost / insurance</dt><dd>{H(p.Value.CostInsurance)}</dd><dt>Referral process</dt><dd>{H(p.Value.ReferralProcess)}</dd></dl><h2>Navigation notes</h2><p style='white-space:pre-wrap'>{H(p.Value.NavigationNotes)}</p></section><aside><section class='card'><h2>Update resource</h2><form method='post' action='/providers/{id}'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/>{ProviderFields(p)}<button>Save changes</button></form></section></aside></div></main>"""));
        }).RequireAuthorization();

        app.MapPost("/providers/{id:guid}",async(Guid id,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsSocialWorker(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);var f=await ctx.Request.ReadFormAsync();var name=f["name"].ToString().Trim();var services=f["services"].ToString().Trim();if(name.Length==0||services.Length==0)return Results.BadRequest("Name and services are required.");await Exec(dbPath,"""UPDATE SocialWorkProviders SET Name=$n,Category=$c,Services=$s,Eligibility=$e,ServiceArea=$area,Languages=$lang,Phone=$p,Email=$email,Website=$web,Address=$addr,ReferralProcess=$ref,CostInsurance=$cost,Hours=$hours,AvailabilityStatus=$avail,NavigationNotes=$notes,Active=$active,UpdatedBy=$by,UpdatedAt=$t WHERE Id=$id""",("$n",name),("$c",f["category"]),("$s",services),("$e",f["eligibility"]),("$area",f["serviceArea"]),("$lang",f["languages"]),("$p",f["phone"]),("$email",f["email"]),("$web",f["website"]),("$addr",f["address"]),("$ref",f["referralProcess"]),("$cost",f["costInsurance"]),("$hours",f["hours"]),("$avail",f["availabilityStatus"]),("$notes",f["navigationNotes"]),("$active",f["active"]=="true"?1:0),("$by",ctx.User.Identity?.Name??"socialworker"),("$t",Now()),("$id",id));return Results.Redirect($"/providers/{id}");
        }).RequireAuthorization();

        app.MapGet("/social-work",async(HttpContext ctx)=>
        {
            if(!IsSocialWorker(ctx.User))return Results.Forbid();var user=ctx.User.Identity?.Name??"";await using var cn=Open(dbPath);await cn.OpenAsync();var cmd=cn.CreateCommand();cmd.CommandText="""SELECT a.Id,d.ComplaintNumber,d.SubjectName,d.IncidentNumber,p.Status,a.Priority,a.AssignedAt FROM SocialWorkAssignments a JOIN DeferredDispositionCases p ON p.Id=a.ProbationCaseId JOIN DaComplaints d ON d.Id=a.ComplaintId WHERE lower(a.SocialWorkerUsername)=lower($u) AND a.Status='Assigned' AND (a.AccessEndDate IS NULL OR a.AccessEndDate='' OR date(a.AccessEndDate)>=date('now')) ORDER BY CASE a.Priority WHEN 'Urgent' THEN 0 WHEN 'Priority' THEN 1 ELSE 2 END,a.AssignedAt DESC""";cmd.Parameters.AddWithValue("$u",user);var rows=new List<string>();await using var r=await cmd.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<tr><td><a href='/social-work/{r.GetString(0)}'><b>{H(r.GetString(1))}</b></a></td><td>{H(r.GetString(2))}</td><td>{H(r.GetString(3))}</td><td>{H(r.GetString(4))}</td><td>{H(r.GetString(5))}</td><td>{H(r.GetString(6))}</td></tr>");return Html(Page("Social work",$"<main class='wrap'><a class='back' href='/'>← CMPD Partners</a><section class='page-head'><div><span class='eyebrow'>DEPARTMENT OF HEALTH · SOCIAL WORK</span><h1>Assigned probation referrals</h1><p>Care-management cases assigned by probation officers.</p></div><a class='button' href='/providers'>Provider & resource directory</a></section><section class='table-card'><table><thead><tr><th>Complaint</th><th>Person</th><th>Incident</th><th>Probation status</th><th>Priority</th><th>Assigned</th></tr></thead><tbody>{(rows.Count>0?string.Join("",rows):"<tr><td colspan='6'>No active social-work assignments.</td></tr>")}</tbody></table></section></main>"));
        }).RequireAuthorization();

        app.MapGet("/social-work/{assignmentId:guid}",async(Guid assignmentId,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsSocialWorker(ctx.User))return Results.Forbid();var a=await LoadAssignment(dbPath,assignmentId,ctx.User.Identity?.Name??"");if(a is null)return Results.Forbid();var t=anti.GetAndStoreTokens(ctx).RequestToken!;var providers=await ProviderOptions(dbPath);var referrals=await ReferralHtml(dbPath,assignmentId);return Html(Page(a.Value.Complaint,$"""<main class='wrap'><a class='back' href='/social-work'>← Assigned referrals</a><section class='page-head'><div><span class='eyebrow'>SOCIAL WORK · {H(a.Value.Status)}</span><h1>{H(a.Value.Complaint)}</h1><p>{H(a.Value.Subject)} · Incident {H(a.Value.Incident)}</p></div><a class='button' href='/providers'>Browse resources</a></section><div class='detail-grid'><section class='card'><h2>Referral context</h2><dl><dt>Probation officer</dt><dd>{H(a.Value.ProbationOfficer)}</dd><dt>Priority</dt><dd>{H(a.Value.Priority)}</dd><dt>Probation status</dt><dd>{H(a.Value.ProbationStatus)}</dd></dl><h3>Relevant conditions</h3><p style='white-space:pre-wrap'>{H(a.Value.Conditions)}</p><h3>Requested services</h3><p style='white-space:pre-wrap'>{H(a.Value.RequestedServices)}</p><h2>Service referrals</h2>{referrals}</section><aside><section class='card'><h2>Create referral from directory</h2><form method='post' action='/social-work/{assignmentId}/resource-referral'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/><label>Provider/resource<select name='providerId' required><option value=''>Select resource</option>{providers}</select></label><label>Referral note<textarea name='detail' rows='4' required></textarea></label><label>Status<select name='status'><option>Referred</option><option>Scheduled</option><option>Waitlisted</option><option>Accepted</option><option>Completed</option></select></label><button>Add client referral</button></form></section></aside></div></main>"""));
        }).RequireAuthorization();

        app.MapPost("/social-work/{assignmentId:guid}/resource-referral",async(Guid assignmentId,HttpContext ctx,IAntiforgery anti)=>
        {
            if(!IsSocialWorker(ctx.User))return Results.Forbid();await anti.ValidateRequestAsync(ctx);if(await LoadAssignment(dbPath,assignmentId,ctx.User.Identity?.Name??"") is null)return Results.Forbid();var f=await ctx.Request.ReadFormAsync();if(!Guid.TryParse(f["providerId"],out var providerId))return Results.BadRequest("Provider/resource is required.");var p=await LoadProvider(dbPath,providerId);if(p is null||!p.Value.Active)return Results.BadRequest("Active provider/resource required.");var detail=f["detail"].ToString().Trim();if(detail.Length==0)return Results.BadRequest("Referral note is required.");await Exec(dbPath,"""INSERT INTO SocialWorkReferrals(Id,AssignmentId,ProviderId,Category,Provider,Detail,Status,CreatedBy,CreatedAt,UpdatedAt) VALUES($i,$a,$pid,$c,$p,$d,$s,$by,$t,$t)""",("$i",Guid.NewGuid()),("$a",assignmentId),("$pid",providerId),("$c",p.Value.Category),("$p",p.Value.Name),("$d",detail),("$s",f["status"]),("$by",ctx.User.Identity?.Name??"socialworker"),("$t",Now()));return Results.Redirect($"/social-work/{assignmentId}");
        }).RequireAuthorization();
    }

    private static string ProviderForm((Guid Id,string Name,string Category,string Services,string? Eligibility,string? ServiceArea,string? Languages,string? Phone,string? Email,string? Website,string? Address,string? ReferralProcess,string? CostInsurance,string? Hours,string? Availability,string? NavigationNotes,bool Active)? p,string t)=>$"""<main class='wrap'><a class='back' href='/providers'>← Provider directory</a><section class='card'><span class='eyebrow'>RESOURCE DIRECTORY</span><h1>{(p is null?"Add provider/resource":"Edit provider/resource")}</h1><form method='post' action='{(p is null?"/providers":$"/providers/{p.Value.Id}")}'><input type='hidden' name='__RequestVerificationToken' value='{H(t)}'/>{ProviderFields(p)}<button>{(p is null?"Add resource":"Save changes")}</button></form></section></main>""";
    private static string ProviderFields((Guid Id,string Name,string Category,string Services,string? Eligibility,string? ServiceArea,string? Languages,string? Phone,string? Email,string? Website,string? Address,string? ReferralProcess,string? CostInsurance,string? Hours,string? Availability,string? NavigationNotes,bool Active)? p){var cats=new[]{"Housing","Food / Nutrition","Benefits / Insurance","Transportation","Employment / Education","Behavioral Health","Substance Use Treatment","Primary Care","Family / Child Services","Legal / Administrative Support","Emergency Assistance","Other"};return $"""<label>Name<input name='name' value='{H(p?.Name)}' required/></label><label>Category<select name='category'>{Opts(cats,p?.Category)}</select></label><label>Services<textarea name='services' rows='5' required>{H(p?.Services)}</textarea></label><label>Eligibility<textarea name='eligibility' rows='3'>{H(p?.Eligibility)}</textarea></label><label>Service area<input name='serviceArea' value='{H(p?.ServiceArea)}'/></label><label>Languages<input name='languages' value='{H(p?.Languages)}'/></label><label>Phone<input name='phone' value='{H(p?.Phone)}'/></label><label>Email<input type='email' name='email' value='{H(p?.Email)}'/></label><label>Website<input name='website' value='{H(p?.Website)}'/></label><label>Address<input name='address' value='{H(p?.Address)}'/></label><label>Referral process<textarea name='referralProcess' rows='3'>{H(p?.ReferralProcess)}</textarea></label><label>Cost / insurance notes<textarea name='costInsurance' rows='3'>{H(p?.CostInsurance)}</textarea></label><label>Hours<input name='hours' value='{H(p?.Hours)}'/></label><label>Availability status<select name='availabilityStatus'>{Opts(new[]{"Unknown","Available","Limited availability","Waitlist","Not accepting referrals","Emergency only"},p?.Availability)}</select></label><label>Navigation notes<textarea name='navigationNotes' rows='4'>{H(p?.NavigationNotes)}</textarea></label><label><input type='checkbox' name='active' value='true' {(p is null||p.Value.Active?"checked":"")}/> Active resource</label>""";}
    private static async Task<string> ProviderOptions(string p){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Id,Name,Category,AvailabilityStatus FROM SocialWorkProviders WHERE Active=1 ORDER BY Category,Name";var rows=new List<string>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync())rows.Add($"<option value='{H(r.GetString(0))}'>{H(r.GetString(2))} · {H(r.GetString(1))} · {H(N(r,3))}</option>");return string.Join("",rows);}
    private static async Task<(Guid Id,string Name,string Category,string Services,string? Eligibility,string? ServiceArea,string? Languages,string? Phone,string? Email,string? Website,string? Address,string? ReferralProcess,string? CostInsurance,string? Hours,string? Availability,string? NavigationNotes,bool Active)?> LoadProvider(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Id,Name,Category,Services,Eligibility,ServiceArea,Languages,Phone,Email,Website,Address,ReferralProcess,CostInsurance,Hours,AvailabilityStatus,NavigationNotes,Active FROM SocialWorkProviders WHERE Id=$id";c.Parameters.AddWithValue("$id",id.ToString());await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?(Guid.Parse(r.GetString(0)),r.GetString(1),r.GetString(2),r.GetString(3),N(r,4),N(r,5),N(r,6),N(r,7),N(r,8),N(r,9),N(r,10),N(r,11),N(r,12),N(r,13),N(r,14),N(r,15),r.GetInt64(16)==1):null;}
    private static async Task<(string Complaint,string Subject,string Incident,string ProbationOfficer,string ProbationStatus,string Conditions,string RequestedServices,string Priority,string Status)?> LoadAssignment(string p,Guid id,string user){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="""SELECT d.ComplaintNumber,d.SubjectName,d.IncidentNumber,COALESCE(pc.AssignedOfficer,''),pc.Status,pc.Conditions,a.RequestedServices,a.Priority,a.Status FROM SocialWorkAssignments a JOIN DeferredDispositionCases pc ON pc.Id=a.ProbationCaseId JOIN DaComplaints d ON d.Id=a.ComplaintId WHERE a.Id=$id AND lower(a.SocialWorkerUsername)=lower($u) AND a.Status<>'Revoked' AND (a.AccessEndDate IS NULL OR a.AccessEndDate='' OR date(a.AccessEndDate)>=date('now'))""";c.Parameters.AddWithValue("$id",id.ToString());c.Parameters.AddWithValue("$u",user);await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?(r.GetString(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5),r.GetString(6),r.GetString(7),r.GetString(8)):null;}
    private static async Task<string> ReferralHtml(string p,Guid id){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText="SELECT Provider,Category,Detail,Status,CreatedAt,ProviderId FROM SocialWorkReferrals WHERE AssignmentId=$id ORDER BY CreatedAt DESC";c.Parameters.AddWithValue("$id",id.ToString());var rows=new List<string>();await using var r=await c.ExecuteReaderAsync();while(await r.ReadAsync()){var provider=H(r.GetString(0));var link=!r.IsDBNull(5)&&Guid.TryParse(r.GetString(5),out var pid)?$"<a href='/providers/{pid}'><b>{provider}</b></a>":$"<b>{provider}</b>";rows.Add($"<article>{link}<span>{H(r.GetString(1))} · {H(r.GetString(3))}</span><p>{H(r.GetString(2))}</p><small>{H(r.GetString(4))}</small></article>");}return rows.Count==0?"<p class='muted'>No resource referrals.</p>":string.Join("",rows);}
    private static async Task Exec(string p,string sql,params(string Key,object? Value)[] ps){await using var cn=Open(p);await cn.OpenAsync();var c=cn.CreateCommand();c.CommandText=sql;foreach(var x in ps)c.Parameters.AddWithValue(x.Key,x.Value?.ToString()??"");await c.ExecuteNonQueryAsync();}
    private static void EnsureSchema(string p){Directory.CreateDirectory(Path.GetDirectoryName(p)!);using var cn=Open(p);cn.Open();using var c=cn.CreateCommand();c.CommandText="""CREATE TABLE IF NOT EXISTS SocialWorkAssignments(Id TEXT PRIMARY KEY,ProbationCaseId TEXT NOT NULL,ComplaintId TEXT NOT NULL,SocialWorkerUsername TEXT NOT NULL,Status TEXT NOT NULL,ReferralReason TEXT NOT NULL,RequestedServices TEXT NOT NULL,Priority TEXT NOT NULL,AssignedBy TEXT NOT NULL,AssignedAt TEXT NOT NULL,AccessEndDate TEXT NULL,RevokedBy TEXT NULL,RevokedAt TEXT NULL,RevocationReason TEXT NULL,CompletionSummary TEXT NULL,CompletedAt TEXT NULL,UpdatedAt TEXT NOT NULL);CREATE TABLE IF NOT EXISTS SocialWorkProviders(Id TEXT PRIMARY KEY,Name TEXT NOT NULL,Category TEXT NOT NULL,Services TEXT NOT NULL,Eligibility TEXT NULL,ServiceArea TEXT NULL,Languages TEXT NULL,Phone TEXT NULL,Email TEXT NULL,Website TEXT NULL,Address TEXT NULL,ReferralProcess TEXT NULL,CostInsurance TEXT NULL,Hours TEXT NULL,AvailabilityStatus TEXT NULL,NavigationNotes TEXT NULL,Active INTEGER NOT NULL,CreatedBy TEXT NOT NULL,CreatedAt TEXT NOT NULL,UpdatedBy TEXT NOT NULL,UpdatedAt TEXT NOT NULL);CREATE TABLE IF NOT EXISTS SocialWorkReferrals(Id TEXT PRIMARY KEY,AssignmentId TEXT NOT NULL,ProviderId TEXT NULL,Category TEXT NOT NULL,Provider TEXT NOT NULL,Detail TEXT NOT NULL,Status TEXT NOT NULL,CreatedBy TEXT NOT NULL,CreatedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL);CREATE INDEX IF NOT EXISTS IX_SocialAssignments_User ON SocialWorkAssignments(SocialWorkerUsername,Status);CREATE INDEX IF NOT EXISTS IX_SocialProviders_Category ON SocialWorkProviders(Category,Active);CREATE INDEX IF NOT EXISTS IX_SocialReferrals_Assignment ON SocialWorkReferrals(AssignmentId);""";c.ExecuteNonQuery();}
    private static SqliteConnection Open(string p)=>new($"Data Source={p}");private static string Now()=>DateTimeOffset.UtcNow.ToString("O");private static string? N(SqliteDataReader r,int i)=>r.IsDBNull(i)?null:r.GetString(i);private static bool IsSocialWorker(ClaimsPrincipal u)=>u.IsInRole("SocialWorker")||u.IsInRole("Administrator");private static string Opts(IEnumerable<string> xs,string? s)=>string.Join("",xs.Select(x=>$"<option value='{H(x)}' {(string.Equals(x,s,StringComparison.OrdinalIgnoreCase)?"selected":"")}>{H(x)}</option>"));private static string H(string? s)=>WebUtility.HtmlEncode(s??"");private static IResult Html(string s)=>Results.Content(s,"text/html; charset=utf-8");private static string Page(string t,string b)=>$"<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>{H(t)} · CMPD Partners</title><link rel='stylesheet' href='/app.css'></head><body><header class='top'><a href='/' class='brand'>CMPD <span>Partners</span></a><div>Department of Health</div></header>{b}</body></html>";
}
